import type { CefrLevel } from '../types.ts';
import { diversityCoachScenarios } from './coach-scenarios-diversity.ts';
import { additionalCoachScenarios } from './coach-scenarios-extra.ts';
import { nextCoachScenarios } from './coach-scenarios-next.ts';
import { supplementalCoachScenarios } from './coach-scenarios-supplement.ts';
import { transferCoachScenarios } from './coach-scenarios-transfer.ts';

export type CoachGuidedHint = {
  label: string;
  german: string;
  czech: string;
};

export type CoachScenario = {
  id: string;
  title: string;
  eyebrow: string;
  description: string;
  goal: string;
  level: CefrLevel;
  minutes: number;
  turns: number;
  opening: string;
  openingCs: string;
  focusWords: string[];
  contextCues: string[];
  starterPrompts: string[];
  guidedHints?: CoachGuidedHint[];
  learnerRole: string;
  coachRole: string;
  icon:
    | 'coffee'
    | 'train'
    | 'school'
    | 'shopping'
    | 'people'
    | 'food'
    | 'map'
    | 'hotel'
    | 'health'
    | 'calendar'
    | 'home'
    | 'work'
    | 'luggage'
    | 'presentation'
    | 'timer'
    | 'discussion'
    | 'debate'
    | 'interview';
  accent: 'coral' | 'sky' | 'mint' | 'butter';
};

export const coachScenarios: CoachScenario[] = [
  {
    id: 'cafe',
    title: 'Objednávka v kavárně',
    eyebrow: 'Roleplay · mluvení',
    description: 'Objednej pití, zeptej se na nabídku a na konci zaplať.',
    goal: 'Zvládnout tři přirozené repliky v kavárně.',
    level: 'A1',
    minutes: 5,
    turns: 3,
    opening: 'Guten Tag! Was darf es für Sie sein?',
    openingCs: 'Dobrý den! Co si dáte?',
    focusWords: ['Ich hätte gern', 'bitte', 'die Rechnung'],
    contextCues: ['Kaffee', 'Tee', 'Wasser', 'Kuchen', 'bestellen', 'trinken', 'zahlen', 'Euro'],
    starterPrompts: [
      'Ich hätte gern einen Tee, bitte.',
      'Was empfehlen Sie?',
      'Die Rechnung, bitte.',
    ],
    guidedHints: [
      {
        label: 'Objednávka',
        german: 'Ich hätte gern einen Tee, bitte.',
        czech: 'Dala bych si čaj, prosím.',
      },
      {
        label: 'Další přání',
        german: 'Ich nehme auch ein Stück Kuchen.',
        czech: 'Dám si také kousek dortu.',
      },
      { label: 'Placení', german: 'Die Rechnung, bitte.', czech: 'Účet, prosím.' },
    ],
    learnerRole: 'zákaznice',
    coachRole: 'obsluha kavárny',
    icon: 'coffee',
    accent: 'coral',
  },
  {
    id: 'train',
    title: 'Jízdenka na nádraží',
    eyebrow: 'Roleplay · cestování',
    description: 'Kup si jízdenku, ověř přestup a zjisti správné nástupiště.',
    goal: 'Domluvit cestu vlakem bez přepnutí do češtiny.',
    level: 'A2',
    minutes: 6,
    turns: 3,
    opening: 'Guten Tag. Wohin möchten Sie fahren?',
    openingCs: 'Dobrý den. Kam chcete jet?',
    focusWords: ['hin und zurück', 'umsteigen', 'das Gleis'],
    contextCues: [
      'Zug',
      'Bahnhof',
      'Fahrkarte',
      'Ticket',
      'fahren',
      'Abfahrt',
      'Ankunft',
      'Berlin',
    ],
    starterPrompts: [
      'Nach Berlin, bitte.',
      'Muss ich umsteigen?',
      'Von welchem Gleis fährt der Zug ab?',
    ],
    guidedHints: [
      {
        label: 'Cíl cesty',
        german: 'Ich möchte nach Berlin fahren.',
        czech: 'Chtěla bych jet do Berlína.',
      },
      { label: 'Přestup', german: 'Muss ich umsteigen?', czech: 'Musím přestupovat?' },
      {
        label: 'Nástupiště',
        german: 'Von welchem Gleis fährt der Zug ab?',
        czech: 'Ze kterého nástupiště vlak odjíždí?',
      },
    ],
    learnerRole: 'cestující',
    coachRole: 'pracovník přepážky',
    icon: 'train',
    accent: 'sky',
  },
  {
    id: 'school',
    title: 'Požádej o vysvětlení',
    eyebrow: 'Roleplay · škola',
    description: 'Řekni, čemu nerozumíš, a domluv si konkrétní další krok.',
    goal: 'Popsat problém a aktivně si říct o pomoc.',
    level: 'A2',
    minutes: 6,
    turns: 3,
    opening: 'Du wolltest etwas zur Hausaufgabe fragen. Worum geht es?',
    openingCs: 'Chtěla ses zeptat na domácí úkol. O co jde?',
    focusWords: ['die Aufgabe', 'erklären', 'nicht verstehen'],
    contextCues: ['Hausaufgabe', 'Frage', 'Übung', 'Test', 'lernen', 'fertig', 'Problem', 'Hilfe'],
    starterPrompts: [
      'Ich verstehe die Aufgabe nicht.',
      'Können Sie das bitte erklären?',
      'Ich mache die Aufgabe heute fertig.',
    ],
    guidedHints: [
      {
        label: 'Pojmenuj problém',
        german: 'Ich verstehe die zweite Aufgabe nicht.',
        czech: 'Nerozumím druhému úkolu.',
      },
      {
        label: 'Požádej o pomoc',
        german: 'Können Sie das bitte noch einmal erklären?',
        czech: 'Můžete to prosím vysvětlit ještě jednou?',
      },
      {
        label: 'Domluv krok',
        german: 'Ich mache die Aufgabe heute fertig.',
        czech: 'Dokončím úkol dnes.',
      },
    ],
    learnerRole: 'studentka',
    coachRole: 'učitel',
    icon: 'school',
    accent: 'mint',
  },
  {
    id: 'shopping',
    title: 'Nakupování oblečení',
    eyebrow: 'Roleplay · situace',
    description: 'Vyber velikost, řekni, jak oblečení sedí, a zvol platbu.',
    goal: 'Zvládnout praktický rozhovor v obchodě.',
    level: 'A2',
    minutes: 6,
    turns: 3,
    opening: 'Hallo! Kann ich Ihnen helfen?',
    openingCs: 'Dobrý den! Mohu vám pomoci?',
    focusWords: ['anprobieren', 'die Größe', 'mit Karte zahlen'],
    contextCues: ['Jacke', 'Hose', 'Kleid', 'Farbe', 'passen', 'kaufen', 'tragen', 'Geschäft'],
    starterPrompts: [
      'Kann ich diese Jacke anprobieren?',
      'Haben Sie Größe M?',
      'Kann ich kontaktlos mit Karte zahlen?',
    ],
    guidedHints: [
      {
        label: 'Vyzkoušení',
        german: 'Kann ich diese Jacke anprobieren?',
        czech: 'Mohu si tuto bundu vyzkoušet?',
      },
      {
        label: 'Velikost',
        german: 'Haben Sie die Jacke in Größe M?',
        czech: 'Máte tu bundu ve velikosti M?',
      },
      {
        label: 'Placení',
        german: 'Ich möchte mit Karte zahlen.',
        czech: 'Chtěla bych platit kartou.',
      },
    ],
    learnerRole: 'zákaznice',
    coachRole: 'prodavačka',
    icon: 'shopping',
    accent: 'butter',
  },
  {
    id: 'introductions',
    title: 'První seznámení',
    eyebrow: 'Roleplay · lidé',
    description: 'Představ se, řekni odkud jsi a najdi jeden společný zájem.',
    goal: 'Udržet krátké seznámení bez naučeného monologu.',
    level: 'A1',
    minutes: 5,
    turns: 3,
    opening: 'Hallo! Ich heiße Lena. Wie heißt du?',
    openingCs: 'Ahoj! Jmenuji se Lena. Jak se jmenuješ?',
    focusWords: ['Ich heiße', 'Ich komme aus', 'Ich mag'],
    contextCues: [
      'wohnen',
      'Tschechien',
      'Prag',
      'Hobby',
      'Freizeit',
      'Musik',
      'Bücher',
      'kennenlernen',
    ],
    starterPrompts: ['Ich heiße Anna.', 'Ich komme aus Tschechien.', 'Ich mag Musik und Bücher.'],
    guidedHints: [
      { label: 'Jméno', german: 'Ich heiße Anna. Und du?', czech: 'Jmenuji se Anna. A ty?' },
      { label: 'Odkud jsi', german: 'Ich komme aus Tschechien.', czech: 'Jsem z Česka.' },
      {
        label: 'Zájem',
        german: 'Ich mag Musik. Was magst du?',
        czech: 'Mám ráda hudbu. Co máš ráda ty?',
      },
    ],
    learnerRole: 'nová spolužačka',
    coachRole: 'spolužačka Lena',
    icon: 'people',
    accent: 'mint',
  },
  {
    id: 'bakery',
    title: 'Ráno v pekárně',
    eyebrow: 'Roleplay · jídlo',
    description: 'Řekni druh a množství pečiva, zeptej se na nabídku a objednávku uzavři.',
    goal: 'Nakoupit tři položky přesnými krátkými větami.',
    level: 'A1',
    minutes: 5,
    turns: 3,
    opening: 'Guten Morgen! Was möchten Sie?',
    openingCs: 'Dobré ráno! Co si přejete?',
    focusWords: ['Ich möchte', 'zwei Brötchen', 'Das ist alles'],
    contextCues: ['Brot', 'Kuchen', 'Stück', 'Bäckerei', 'Vollkorn', 'kaufen', 'kosten', 'Euro'],
    starterPrompts: [
      'Ich möchte zwei Brötchen, bitte.',
      'Haben Sie Vollkornbrot?',
      'Das ist alles, danke.',
    ],
    guidedHints: [
      {
        label: 'Množství',
        german: 'Ich möchte zwei Brötchen, bitte.',
        czech: 'Chtěla bych dvě housky, prosím.',
      },
      {
        label: 'Další položka',
        german: 'Haben Sie auch Vollkornbrot?',
        czech: 'Máte také celozrnný chléb?',
      },
      { label: 'Konec nákupu', german: 'Das ist alles, danke.', czech: 'To je všechno, děkuji.' },
    ],
    learnerRole: 'zákaznice',
    coachRole: 'pekařka',
    icon: 'food',
    accent: 'butter',
  },
  {
    id: 'directions',
    title: 'Cesta na nádraží',
    eyebrow: 'Roleplay · orientace',
    description: 'Zeptej se na cestu, ověř odbočku a poděkuj za pomoc.',
    goal: 'Porozumět třem základním pokynům ve městě.',
    level: 'A1',
    minutes: 5,
    turns: 3,
    opening: 'Entschuldigung, kann ich Ihnen helfen?',
    openingCs: 'Promiňte, mohu vám pomoci?',
    focusWords: ['Wo ist', 'links', 'geradeaus'],
    contextCues: ['Bahnhof', 'Weg', 'rechts', 'Ampel', 'gehen', 'Straße', 'abbiegen', 'danke'],
    starterPrompts: [
      'Wo ist der Bahnhof, bitte?',
      'Muss ich hier links gehen?',
      'Vielen Dank für Ihre Hilfe.',
    ],
    guidedHints: [
      { label: 'Místo', german: 'Wo ist der Bahnhof, bitte?', czech: 'Kde je nádraží, prosím?' },
      { label: 'Ověření', german: 'Muss ich hier links gehen?', czech: 'Musím tady jít doleva?' },
      {
        label: 'Poděkování',
        german: 'Vielen Dank für Ihre Hilfe.',
        czech: 'Moc děkuji za vaši pomoc.',
      },
    ],
    learnerRole: 'návštěvnice města',
    coachRole: 'místní obyvatel',
    icon: 'map',
    accent: 'sky',
  },
  {
    id: 'hotel-check-in',
    title: 'Příjezd do hotelu',
    eyebrow: 'Roleplay · cestování',
    description: 'Najdi rezervaci, zjisti čas snídaně a vyžádej si přístup k Wi-Fi.',
    goal: 'Vyřídit check-in a dvě praktické otázky.',
    level: 'A2',
    minutes: 6,
    turns: 3,
    opening: 'Guten Abend! Haben Sie eine Reservierung?',
    openingCs: 'Dobrý večer! Máte rezervaci?',
    focusWords: ['reserviert', 'das Frühstück', 'der WLAN-Code'],
    contextCues: ['Zimmer', 'Hotel', 'Name', 'Ausweis', 'Stock', 'Schlüssel', 'Rezeption', 'Gast'],
    starterPrompts: [
      'Ich habe ein Zimmer auf den Namen Novák reserviert.',
      'Ab wann gibt es Frühstück?',
      'Wie lautet der WLAN-Code?',
    ],
    guidedHints: [
      {
        label: 'Rezervace',
        german: 'Ich habe ein Zimmer auf den Namen Novák reserviert.',
        czech: 'Mám rezervovaný pokoj na jméno Novák.',
      },
      { label: 'Čas', german: 'Ab wann gibt es Frühstück?', czech: 'Od kolika je snídaně?' },
      { label: 'Přístup', german: 'Wie lautet der WLAN-Code?', czech: 'Jaký je kód k Wi-Fi?' },
    ],
    learnerRole: 'hotelový host',
    coachRole: 'recepční',
    icon: 'hotel',
    accent: 'sky',
  },
  {
    id: 'pharmacy',
    title: 'Rada v lékárně',
    eyebrow: 'Roleplay · zdraví',
    description: 'Popiš potíže, požádej o doporučení a ověř dávkování.',
    goal: 'Předat důležité informace bezpečně a srozumitelně.',
    level: 'A2',
    minutes: 6,
    turns: 3,
    opening: 'Guten Tag. Was fehlt Ihnen?',
    openingCs: 'Dobrý den. Co vám je?',
    focusWords: ['seit gestern', 'Halsschmerzen', 'Wie oft'],
    contextCues: [
      'Husten',
      'Fieber',
      'Tablette',
      'nehmen',
      'empfehlen',
      'Arzt',
      'Medikament',
      'krank',
    ],
    starterPrompts: [
      'Ich habe seit gestern Halsschmerzen.',
      'Was können Sie empfehlen?',
      'Wie oft soll ich das nehmen?',
    ],
    guidedHints: [
      {
        label: 'Potíž a čas',
        german: 'Ich habe seit gestern Halsschmerzen.',
        czech: 'Od včerejška mě bolí v krku.',
      },
      {
        label: 'Doporučení',
        german: 'Was können Sie mir empfehlen?',
        czech: 'Co mi můžete doporučit?',
      },
      {
        label: 'Dávkování',
        german: 'Wie oft soll ich das nehmen?',
        czech: 'Jak často to mám užívat?',
      },
    ],
    learnerRole: 'zákaznice',
    coachRole: 'lékárnice',
    icon: 'health',
    accent: 'coral',
  },
  {
    id: 'invitation',
    title: 'Pozvání na oslavu',
    eyebrow: 'Roleplay · volný čas',
    description: 'Přijmi pozvání, domluv čas a zeptej se, co máš přinést.',
    goal: 'Domluvit konkrétní plán bez nejasností.',
    level: 'A2',
    minutes: 5,
    turns: 3,
    opening: 'Ich feiere am Samstag meinen Geburtstag. Hast du Zeit?',
    openingCs: 'V sobotu slavím narozeniny. Máš čas?',
    focusWords: ['gern kommen', 'gegen sieben', 'mitbringen'],
    contextCues: ['Samstag', 'Geburtstag', 'Feier', 'Zeit', 'Uhr', 'trinken', 'essen', 'Einladung'],
    starterPrompts: [
      'Danke, ich komme gern.',
      'Ich komme gegen sieben Uhr.',
      'Soll ich etwas mitbringen?',
    ],
    guidedHints: [
      { label: 'Odpověď', german: 'Danke, ich komme gern.', czech: 'Děkuji, ráda přijdu.' },
      { label: 'Čas', german: 'Ich komme gegen sieben Uhr.', czech: 'Přijdu kolem sedmé.' },
      { label: 'Nabídka', german: 'Soll ich etwas mitbringen?', czech: 'Mám něco přinést?' },
    ],
    learnerRole: 'pozvaná kamarádka',
    coachRole: 'oslavenkyně',
    icon: 'calendar',
    accent: 'mint',
  },
  {
    id: 'apartment-repair',
    title: 'Porucha v bytě',
    eyebrow: 'Roleplay · bydlení',
    description: 'Popiš závadu pronajímateli, vysvětli její dopad a domluv termín opravy.',
    goal: 'Vyřešit praktický problém věcně a bez zbytečného konfliktu.',
    level: 'B1',
    minutes: 7,
    turns: 3,
    opening: 'Guten Tag, Sie wollten ein Problem in der Wohnung melden. Was ist passiert?',
    openingCs: 'Dobrý den, chtěla jste nahlásit problém v bytě. Co se stalo?',
    focusWords: ['funktioniert nicht', 'seit drei Tagen', 'einen Termin vereinbaren'],
    contextCues: [
      'Wohnung',
      'Heizung',
      'Wasser',
      'Strom',
      'kalt',
      'Reparatur',
      'Techniker',
      'Vermieter',
    ],
    starterPrompts: [
      'Die Heizung funktioniert seit drei Tagen nicht.',
      'In der Wohnung ist es sehr kalt.',
      'Können wir einen Reparaturtermin vereinbaren?',
    ],
    learnerRole: 'nájemnice',
    coachRole: 'pronajímatel',
    icon: 'home',
    accent: 'butter',
  },
  {
    id: 'job-interview',
    title: 'První pracovní pohovor',
    eyebrow: 'Roleplay · práce',
    description: 'Představ zkušenost, dolož jednu silnou stránku příkladem a polož vlastní otázku.',
    goal: 'Odpovědět konkrétně místo obecných frází.',
    level: 'B1',
    minutes: 7,
    turns: 3,
    opening: 'Erzählen Sie mir bitte kurz etwas über Ihre bisherigen Erfahrungen.',
    openingCs: 'Řekněte mi prosím stručně něco o svých dosavadních zkušenostech.',
    focusWords: ['Erfahrung mit', 'zuverlässig', 'im Team arbeiten'],
    contextCues: [
      'Arbeit',
      'Kunden',
      'Aufgabe',
      'Bewerbung',
      'Stelle',
      'Stärke',
      'Projekt',
      'Arbeitstag',
    ],
    starterPrompts: [
      'Ich habe ein Jahr im Kundenservice gearbeitet.',
      'Ich arbeite zuverlässig und gern im Team.',
      'Wie sieht ein typischer Arbeitstag aus?',
    ],
    learnerRole: 'uchazečka',
    coachRole: 'personalistka',
    icon: 'work',
    accent: 'sky',
  },
  {
    id: 'lost-luggage',
    title: 'Ztracené zavazadlo',
    eyebrow: 'Roleplay · problém na cestě',
    description: 'Nahlas nedoručený kufr, přesně ho popiš a ověř další postup.',
    goal: 'Získat potvrzení a konkrétní způsob doručení.',
    level: 'B1',
    minutes: 7,
    turns: 3,
    opening: 'Guten Tag. Wie kann ich Ihnen beim Gepäck helfen?',
    openingCs: 'Dobrý den. Jak vám mohu pomoci se zavazadlem?',
    focusWords: ['nicht angekommen', 'schwarzer Koffer', 'eine Bestätigung'],
    contextCues: [
      'Gepäck',
      'Flug',
      'beschreiben',
      'E-Mail',
      'liefern',
      'Unterkunft',
      'Flughafen',
      'verloren',
    ],
    starterPrompts: [
      'Mein Koffer ist leider nicht angekommen.',
      'Es ist ein mittelgroßer schwarzer Koffer.',
      'Bekomme ich eine schriftliche Bestätigung?',
    ],
    learnerRole: 'cestující',
    coachRole: 'pracovnice reklamací',
    icon: 'luggage',
    accent: 'coral',
  },
  {
    id: 'project-meeting',
    title: 'Rozhodnutí v projektovém týmu',
    eyebrow: 'Roleplay · spolupráce',
    description: 'Navrhni řešení, reaguj na námitku a uzavři jasné rozdělení úkolů.',
    goal: 'Prosadit návrh a současně udržet týmovou dohodu.',
    level: 'B2',
    minutes: 8,
    turns: 3,
    opening: 'Wir liegen hinter dem Zeitplan. Wie sollten wir die nächste Woche organisieren?',
    openingCs: 'Jsme ve skluzu. Jak bychom měli zorganizovat příští týden?',
    focusWords: ['Ich schlage vor', 'allerdings', 'Verantwortung übernehmen'],
    contextCues: [
      'Projekt',
      'Zeitplan',
      'Woche',
      'Aufgabe',
      'priorisieren',
      'Umfang',
      'verschieben',
      'Präsentation',
      'Daten',
    ],
    starterPrompts: [
      'Ich schlage vor, dass wir zuerst die wichtigsten Aufgaben priorisieren.',
      'Das stimmt, allerdings brauchen wir einen realistischen Umfang.',
      'Ich kann die Verantwortung für die Präsentation übernehmen.',
    ],
    learnerRole: 'členka týmu',
    coachRole: 'vedoucí projektu',
    icon: 'presentation',
    accent: 'mint',
  },
  {
    id: 'deadline-negotiation',
    title: 'Vyjednání termínu',
    eyebrow: 'Roleplay · pracovní dohoda',
    description: 'Vysvětli riziko nereálného termínu, nabídni varianty a potvrď měřitelné řešení.',
    goal: 'Vyjednat změnu bez odmítnutí odpovědnosti.',
    level: 'B2',
    minutes: 8,
    turns: 3,
    opening: 'Der Bericht muss eigentlich bis Freitag fertig sein. Schaffen Sie das?',
    openingCs: 'Zpráva má být hotová do pátku. Zvládnete to?',
    focusWords: ['unter der Voraussetzung', 'eine Alternative', 'verbindlich zusagen'],
    contextCues: [
      'Bericht',
      'Freitag',
      'Daten',
      'Termin',
      'schaffen',
      'Kurzfassung',
      'Montag',
      'Version',
      'liefern',
    ],
    starterPrompts: [
      'Unter der Voraussetzung, dass ich die Daten heute bekomme, ist Freitag möglich.',
      'Alternativ kann ich am Freitag eine Kurzfassung liefern.',
      'Die vollständige Version kann ich für Montag verbindlich zusagen.',
    ],
    learnerRole: 'odpovědná kolegyně',
    coachRole: 'vedoucí',
    icon: 'timer',
    accent: 'butter',
  },
  {
    id: 'difficult-feedback',
    title: 'Citlivá zpětná vazba',
    eyebrow: 'Roleplay · komunikace',
    description: 'Pojmenuj konkrétní chování, popiš dopad a společně navrhni změnu.',
    goal: 'Vést nepříjemný rozhovor bez obviňování a mlžení.',
    level: 'B2',
    minutes: 8,
    turns: 3,
    opening: 'Du wolltest mit mir über unsere Zusammenarbeit sprechen. Was beschäftigt dich?',
    openingCs: 'Chtěla jsi se mnou mluvit o naší spolupráci. Co tě trápí?',
    focusWords: ['Mir ist aufgefallen', 'dadurch', 'Wie können wir'],
    contextCues: [
      'Zusammenarbeit',
      'Absprache',
      'ändern',
      'Aufgabe',
      'planen',
      'früher',
      'abstimmen',
      'Team',
    ],
    starterPrompts: [
      'Mir ist aufgefallen, dass Absprachen mehrmals kurzfristig geändert wurden.',
      'Dadurch konnte ich meine Aufgaben nicht zuverlässig planen.',
      'Wie können wir Änderungen künftig früher abstimmen?',
    ],
    learnerRole: 'kolegyně',
    coachRole: 'člen týmu',
    icon: 'discussion',
    accent: 'coral',
  },
  {
    id: 'defend-position',
    title: 'Obhajoba stanoviska',
    eyebrow: 'Roleplay · argumentace',
    description: 'Vymez tezi, připusť oprávněnou námitku a ukaž, proč závěr přesto drží.',
    goal: 'Argumentovat přesně, s nuancí a bez falešných jistot.',
    level: 'C1',
    minutes: 8,
    turns: 3,
    opening: 'Ihre Position klingt plausibel, aber unterschätzt sie nicht die praktischen Kosten?',
    openingCs: 'Vaše stanovisko zní věrohodně, ale nepodceňuje praktické náklady?',
    focusWords: ['Zwar', 'entscheidend ist jedoch', 'unter diesen Umständen'],
    contextCues: [
      'Kosten',
      'Zeitraum',
      'Annahme',
      'Risiko',
      'Einführung',
      'Aufwand',
      'Position',
      'Einwand',
      'schrittweise',
    ],
    starterPrompts: [
      'Zwar entstehen zunächst höhere Kosten, langfristig sinkt jedoch der Aufwand.',
      'Der Einwand ist berechtigt; entscheidend ist jedoch der betrachtete Zeitraum.',
      'Unter diesen Umständen halte ich eine schrittweise Einführung für sinnvoll.',
    ],
    learnerRole: 'diskutující',
    coachRole: 'kritický oponent',
    icon: 'debate',
    accent: 'sky',
  },
  {
    id: 'media-interview',
    title: 'Rozhovor pro média',
    eyebrow: 'Roleplay · veřejné vystoupení',
    description:
      'Odpověz na kritickou otázku, odděl fakta od odhadu a vrať rozhovor k hlavnímu sdělení.',
    goal: 'Formulovat stručně i pod tlakem bez zavádějícího zjednodušení.',
    level: 'C1',
    minutes: 8,
    turns: 3,
    opening:
      'Kritiker behaupten, Ihr Vorschlag löse das eigentliche Problem gar nicht. Was entgegnen Sie?',
    openingCs: 'Kritici tvrdí, že váš návrh skutečný problém vůbec neřeší. Co odpovíte?',
    focusWords: ['Nach heutigem Stand', 'darauf hindeuten', 'entscheidend bleibt'],
    contextCues: [
      'Kritik',
      'Vorschlag',
      'Daten',
      'Ergebnis',
      'Wirkung',
      'transparent',
      'prüfen',
      'Problem',
      'Aussage',
    ],
    starterPrompts: [
      'Nach heutigem Stand zeigen die Daten ein differenzierteres Bild.',
      'Mehrere Ergebnisse deuten darauf hin, dass der Ansatz wirkt.',
      'Entscheidend bleibt, die Wirkung transparent zu überprüfen.',
    ],
    learnerRole: 'odborná hostka',
    coachRole: 'novinář',
    icon: 'interview',
    accent: 'mint',
  },
  ...additionalCoachScenarios,
  ...supplementalCoachScenarios,
  ...nextCoachScenarios,
  ...transferCoachScenarios,
  ...diversityCoachScenarios,
];

const coachScenariosById = new Map(coachScenarios.map((scenario) => [scenario.id, scenario]));

export function coachScenarioById(id: string): CoachScenario | undefined {
  return coachScenariosById.get(id);
}
