import type { CoachScenario } from './coach.ts';

export const diversityCoachScenarios: CoachScenario[] = [
  {
    id: 'market-shopping',
    title: 'Nákup na trhu',
    eyebrow: 'Roleplay · jídlo a množství',
    description: 'Vyber čerstvé potraviny, řekni množství a zkontroluj cenu nákupu.',
    goal: 'Dokončit nákup tří položek bez přepnutí do češtiny.',
    level: 'A1',
    minutes: 5,
    turns: 3,
    opening: 'Guten Morgen! Was darf ich Ihnen vom Marktstand geben?',
    openingCs: 'Dobré ráno! Co vám mohu dát ze stánku?',
    focusWords: ['ich nehme', 'ein Kilo', 'was kostet das'],
    contextCues: [
      'Wochenmarkt',
      'Tomate',
      'Gurke',
      'Kartoffel',
      'Apfel',
      'auswählen',
      'abwiegen',
      'dazulegen',
      'regional',
    ],
    starterPrompts: [
      'Ich nehme drei Tomaten und eine Gurke, bitte.',
      'Bitte wiegen Sie auch ein Kilo Kartoffeln ab.',
      'Was kostet das zusammen?',
    ],
    guidedHints: [
      {
        label: 'Výběr',
        german: 'Ich nehme drei Tomaten, bitte.',
        czech: 'Vezmu si tři rajčata, prosím.',
      },
      {
        label: 'Množství',
        german: 'Bitte wiegen Sie ein Kilo Kartoffeln ab.',
        czech: 'Odvažte prosím kilo brambor.',
      },
      {
        label: 'Cena',
        german: 'Was kostet das zusammen?',
        czech: 'Kolik to stojí dohromady?',
      },
    ],
    learnerRole: 'zákaznice na trhu',
    coachRole: 'prodavačka zeleniny',
    icon: 'food',
    accent: 'coral',
  },
  {
    id: 'hobby-meetup',
    title: 'První návštěva zájmové skupiny',
    eyebrow: 'Roleplay · volný čas',
    description: 'Zjisti, co skupina dělá, a domluv si první návštěvu nebo ukázkovou hodinu.',
    goal: 'Vybrat nový koníček a potvrdit konkrétní termín návštěvy.',
    level: 'A1',
    minutes: 5,
    turns: 3,
    opening: 'Hallo! Welches Hobby möchtest du bei uns ausprobieren?',
    openingCs: 'Ahoj! Který koníček si u nás chceš vyzkoušet?',
    focusWords: ['ausprobieren', 'wann trefft ihr euch', 'vorbeikommen'],
    contextCues: [
      'Freizeitgruppe',
      'Spieleabend',
      'Kletterhalle',
      'Schnupperkurs',
      'fotografieren',
      'mitspielen',
      'sich verabreden',
      'Freitag',
    ],
    starterPrompts: [
      'Ich möchte das Klettern ausprobieren.',
      'Wann trefft ihr euch in der Kletterhalle?',
      'Ich kann am Freitag vorbeikommen.',
    ],
    guidedHints: [
      {
        label: 'Zájem',
        german: 'Ich möchte das Klettern ausprobieren.',
        czech: 'Chci si vyzkoušet lezení.',
      },
      {
        label: 'Termín',
        german: 'Wann trefft ihr euch?',
        czech: 'Kdy se scházíte?',
      },
      {
        label: 'Potvrzení',
        german: 'Ich kann am Freitag vorbeikommen.',
        czech: 'Mohu se stavit v pátek.',
      },
    ],
    learnerRole: 'nová zájemkyně',
    coachRole: 'organizátor skupiny',
    icon: 'people',
    accent: 'butter',
  },
  {
    id: 'civic-office',
    title: 'Žádost na občanském úřadě',
    eyebrow: 'Roleplay · městské služby',
    description: 'Zjisti postup, předlož správné doklady a ověř, kdy bude žádost hotová.',
    goal: 'Podat úplnou žádost a porozumět dalšímu kroku.',
    level: 'A2',
    minutes: 6,
    turns: 3,
    opening: 'Guten Tag. Was möchten Sie heute beim Bürgeramt erledigen?',
    openingCs: 'Dobrý den. Co chcete dnes na občanském úřadě vyřídit?',
    focusWords: ['ich beantrage', 'welche Unterlagen', 'persönlich abholen'],
    contextCues: [
      'Bürgeramt',
      'Meldebescheinigung',
      'Wartemarke',
      'Wohnsitz',
      'Formular',
      'Pass',
      'vorlegen',
      'ausfüllen',
      'terminpflichtig',
    ],
    starterPrompts: [
      'Ich möchte eine Meldebescheinigung beantragen.',
      'Welche Unterlagen muss ich vorlegen?',
      'Kann ich das Dokument nächste Woche persönlich abholen?',
    ],
    guidedHints: [
      {
        label: 'Žádost',
        german: 'Ich möchte eine Meldebescheinigung beantragen.',
        czech: 'Chci požádat o potvrzení o bydlišti.',
      },
      {
        label: 'Doklady',
        german: 'Welche Unterlagen muss ich vorlegen?',
        czech: 'Které doklady musím předložit?',
      },
      {
        label: 'Převzetí',
        german: 'Wann kann ich das Dokument abholen?',
        czech: 'Kdy mohu dokument vyzvednout?',
      },
    ],
    learnerRole: 'žadatelka',
    coachRole: 'úředník',
    icon: 'school',
    accent: 'sky',
  },
  {
    id: 'cultural-evening',
    title: 'Naplánuj kulturní večer',
    eyebrow: 'Roleplay · kultura',
    description: 'Vyber představení, zajisti vstupenky a potvrď praktické detaily návštěvy.',
    goal: 'Domluvit kulturní program od rezervace po příchod do sálu.',
    level: 'A2',
    minutes: 6,
    turns: 3,
    opening: 'Welche Vorstellung sollen wir am Samstag besuchen?',
    openingCs: 'Které představení máme v sobotu navštívit?',
    focusWords: ['im Voraus', 'der Einlass', 'ausverkauft'],
    contextCues: [
      'Eintrittskarte',
      'Vorstellung',
      'Programmheft',
      'Einlass',
      'Garderobe',
      'aufführen',
      'stattfinden',
      'applaudieren',
      'Saal',
    ],
    starterPrompts: [
      'Ich möchte die frühe Vorstellung besuchen.',
      'Wir sollten die Eintrittskarten im Voraus kaufen.',
      'Wann beginnt der Einlass in den Saal?',
    ],
    guidedHints: [
      {
        label: 'Výběr',
        german: 'Ich möchte die frühe Vorstellung besuchen.',
        czech: 'Chci navštívit časnější představení.',
      },
      {
        label: 'Vstupenky',
        german: 'Wir kaufen die Eintrittskarten im Voraus.',
        czech: 'Vstupenky koupíme předem.',
      },
      {
        label: 'Příchod',
        german: 'Wann beginnt der Einlass?',
        czech: 'Kdy začíná vstup do sálu?',
      },
    ],
    learnerRole: 'návštěvnice divadla',
    coachRole: 'kamarád plánující program',
    icon: 'calendar',
    accent: 'coral',
  },
  {
    id: 'workplace-onboarding',
    title: 'Převzetí nové pracovní agendy',
    eyebrow: 'Roleplay · práce',
    description: 'Ujasni si kompetence, postup předání a okamžik samostatného převzetí úkolů.',
    goal: 'Domluvit realistický a kontrolovatelný plán zapracování.',
    level: 'B1',
    minutes: 7,
    turns: 3,
    opening: 'Welche Punkte deiner Einarbeitung sind noch unklar?',
    openingCs: 'Které body tvého zapracování jsou ještě nejasné?',
    focusWords: ['die Zuständigkeit klären', 'bei jemandem rückfragen', 'nach und nach'],
    contextCues: [
      'Einarbeitung',
      'Übergabe',
      'Ansprechpartner',
      'Übergabeprotokoll',
      'sich einarbeiten',
      'weiterleiten',
      'rückfragen',
      'ohne Aufsicht',
      'Aufgabe',
    ],
    starterPrompts: [
      'Ich möchte zuerst meine Zuständigkeiten klären.',
      'Bei Sonderfällen frage ich bei meiner Ansprechpartnerin rück.',
      'Danach übernehme ich die Aufgaben nach und nach ohne Aufsicht.',
    ],
    learnerRole: 'nová členka týmu',
    coachRole: 'vedoucí týmu',
    icon: 'work',
    accent: 'mint',
  },
  {
    id: 'media-literacy',
    title: 'Prověř problematickou zprávu',
    eyebrow: 'Roleplay · média',
    description: 'Dohledávej zdroje, odděl titulek od důkazů a vysvětli závěr kontroly.',
    goal: 'Posoudit tvrzení bez ukvapeného označení za pravdu nebo lež.',
    level: 'B1',
    minutes: 7,
    turns: 3,
    opening: 'Diese Überschrift verbreitet sich schnell. Wie gehst du bei der Prüfung vor?',
    openingCs: 'Tento nadpis se rychle šíří. Jak budeš při kontrole postupovat?',
    focusWords: ['zurückverfolgen', 'gegenprüfen', 'quellenbasiert einordnen'],
    contextCues: [
      'Überschrift',
      'Bildquelle',
      'Suchergebnis',
      'Primärquelle',
      'Gerücht',
      'gegenprüfen',
      'kontextualisieren',
      'verkürzt',
      'quellenbasiert',
    ],
    starterPrompts: [
      'Zuerst verfolge ich die Behauptung zur Primärquelle zurück.',
      'Danach prüfe ich die Zahl mit einer zweiten Quelle gegen.',
      'Die verkürzte Grafik braucht eine quellenbasierte Einordnung.',
    ],
    learnerRole: 'fact-checker',
    coachRole: 'editorka',
    icon: 'interview',
    accent: 'sky',
  },
  {
    id: 'project-risk',
    title: 'Prioritizace projektových rizik',
    eyebrow: 'Roleplay · projektové řízení',
    description: 'Porovnej pravděpodobnost a dopad a přiřaď hlavnímu riziku protiopatření.',
    goal: 'Obhájit pořadí rizik pomocí konkrétních kritérií.',
    level: 'B2',
    minutes: 8,
    turns: 3,
    opening: 'Welches Risiko sollten wir in der nächsten Projektphase zuerst behandeln?',
    openingCs: 'Které riziko bychom měli v další fázi projektu řešit jako první?',
    focusWords: ['hoch gewichten', 'das Schadensausmaß', 'eine Gegenmaßnahme'],
    contextCues: [
      'Risikomatrix',
      'Eintrittswahrscheinlichkeit',
      'Schadensausmaß',
      'Gegenmaßnahme',
      'Engpass',
      'gewichten',
      'abfedern',
      'eskalieren',
      'vorbeugend',
    ],
    starterPrompts: [
      'Wir sollten den personellen Engpass am höchsten gewichten.',
      'Die Wahrscheinlichkeit ist mittel, aber das Schadensausmaß wäre hoch.',
      'Als Gegenmaßnahme plane ich eine zusätzliche Testreserve ein.',
    ],
    learnerRole: 'riziková analytička',
    coachRole: 'projektová vedoucí',
    icon: 'presentation',
    accent: 'coral',
  },
  {
    id: 'accessible-city',
    title: 'Audit přístupnosti veřejného prostoru',
    eyebrow: 'Roleplay · město',
    description: 'Pojmenuj překážku, vysvětli její dopad a navrhni realizovatelnou nápravu.',
    goal: 'Převést obecný požadavek na přístupnost do konkrétních opatření.',
    level: 'B2',
    minutes: 8,
    turns: 3,
    opening: 'Welches Hindernis beeinträchtigt die Teilhabe an diesem Bahnhof am stärksten?',
    openingCs: 'Která překážka na tomto nádraží nejvíce omezuje zapojení lidí?',
    focusWords: ['stufenlos erreichbar', 'beeinträchtigen', 'umbauen'],
    contextCues: [
      'Barrierefreiheit',
      'Bordsteinabsenkung',
      'Leitsystem',
      'Aufzugsausfall',
      'Teilhabe',
      'umbauen',
      'kennzeichnen',
      'beeinträchtigen',
      'Ersatzweg',
    ],
    starterPrompts: [
      'Der Aufzugsausfall beeinträchtigt den einzigen stufenlosen Zugang.',
      'Ein gut gekennzeichneter Ersatzweg würde kurzfristig helfen.',
      'Langfristig muss der Seiteneingang barrierefrei umgebaut werden.',
    ],
    learnerRole: 'zástupkyně obyvatel',
    coachRole: 'městský plánovač',
    icon: 'map',
    accent: 'mint',
  },
  {
    id: 'science-communication',
    title: 'Vysvětli výzkum širokému publiku',
    eyebrow: 'Roleplay · věda',
    description: 'Formuluj hlavní sdělení, zachovej nejistotu a použij srozumitelný příklad.',
    goal: 'Zjednodušit odborný výsledek bez zkreslení jeho síly nebo limitů.',
    level: 'C1',
    minutes: 8,
    turns: 3,
    opening: 'Wie würden Sie Ihr Ergebnis einem Laienpublikum in einem Satz erklären?',
    openingCs: 'Jak byste svůj výsledek vysvětlila laickému publiku jednou větou?',
    focusWords: ['die Kernaussage', 'belastbar', 'der Unsicherheitsbereich'],
    contextCues: [
      'Fachpublikum',
      'Laienpublikum',
      'Kernaussage',
      'Unsicherheitsbereich',
      'Größenordnung',
      'veranschaulichen',
      'vereinfachen',
      'missverstehen',
      'allgemeinverständlich',
    ],
    starterPrompts: [
      'Die Kernaussage lautet, dass ein belastbarer Zusammenhang besteht.',
      'Die genaue Größenordnung liegt jedoch in einem breiten Unsicherheitsbereich.',
      'Ein Alltagsvergleich kann den Effekt allgemeinverständlich veranschaulichen.',
    ],
    learnerRole: 'vědkyně',
    coachRole: 'novinář pro veřejnost',
    icon: 'presentation',
    accent: 'sky',
  },
  {
    id: 'crisis-communication',
    title: 'Sjednoť krizové sdělení',
    eyebrow: 'Roleplay · krizové řízení',
    description: 'Odděl ověřené informace od nepotvrzených a vydej jednoznačný další pokyn.',
    goal: 'Připravit stručnou krizovou zprávu bez rozporů a předčasné jistoty.',
    level: 'C1',
    minutes: 8,
    turns: 3,
    opening: 'Welche Informationen können wir in der nächsten öffentlichen Mitteilung bestätigen?',
    openingCs: 'Které informace můžeme v příštím veřejném sdělení potvrdit?',
    focusWords: ['nach aktuellem Informationsstand', 'unbestätigt', 'aktualisieren'],
    contextCues: [
      'Lagebild',
      'Krisenstab',
      'Informationsstand',
      'Handlungsempfehlung',
      'Entwarnung',
      'abgleichen',
      'dementieren',
      'aktualisieren',
      'widerspruchsfrei',
    ],
    starterPrompts: [
      'Nach aktuellem Informationsstand besteht keine unmittelbare Gefahr.',
      'Die gemeldete Ursache ist jedoch weiterhin unbestätigt.',
      'Wir aktualisieren die Handlungsempfehlung um zwölf Uhr.',
    ],
    learnerRole: 'tisková mluvčí',
    coachRole: 'vedoucí krizového štábu',
    icon: 'discussion',
    accent: 'coral',
  },
];
