import type { CefrLevel } from '../types.ts';
import type { CoachScenario } from './coach.ts';

type ScenarioIcon = CoachScenario['icon'];

type TransferCoachSpec = {
  chapterId: string;
  id: string;
  title: string;
  description: string;
  goal: string;
  level: CefrLevel;
  opening: string;
  openingCs: string;
  focusWords: [string, string, string];
  cues: [string, string, string, string, string];
  prompts: [string, string, string];
  promptCs?: [string, string, string];
  learnerRole: string;
  coachRole: string;
  icon: ScenarioIcon;
};

function transferScenario(spec: TransferCoachSpec): CoachScenario {
  const guidedHints = spec.promptCs?.map((czech, index) => ({
    label: `Krok ${index + 1}`,
    german: spec.prompts[index],
    czech,
  }));
  const minutes = spec.level === 'A1' ? 5 : spec.level === 'A2' ? 6 : spec.level === 'B1' ? 7 : 8;
  const accent: CoachScenario['accent'] =
    spec.level === 'A1'
      ? 'mint'
      : spec.level === 'A2'
        ? 'butter'
        : spec.level === 'B1'
          ? 'sky'
          : spec.level === 'B2'
            ? 'coral'
            : 'mint';
  return {
    id: spec.id,
    title: spec.title,
    eyebrow: `Transfer · ${spec.level} mluvení`,
    description: spec.description,
    goal: spec.goal,
    level: spec.level,
    minutes,
    turns: 3,
    opening: spec.opening,
    openingCs: spec.openingCs,
    focusWords: spec.focusWords,
    contextCues: [...spec.cues, ...spec.focusWords],
    starterPrompts: spec.prompts,
    guidedHints,
    learnerRole: spec.learnerRole,
    coachRole: spec.coachRole,
    icon: spec.icon,
    accent,
  };
}

const transferCoachSpecs: TransferCoachSpec[] = [
  {
    chapterId: 'chapter-33-ask-for-repetition',
    id: 'transfer-ask-for-repetition',
    title: 'Zopakování bez rozpaků',
    description: 'Zastav nejasný výklad, vyžádej si pomalejší zopakování a ověř detail.',
    goal: 'Získat přesnou informaci místo předstírání, že je všechno jasné.',
    level: 'A1',
    opening: 'Entschuldigung, war die Aufgabe klar?',
    openingCs: 'Promiň, bylo zadání jasné?',
    focusWords: ['bitte wiederholen', 'langsamer sprechen', 'Meinen Sie'],
    cues: ['Aufgabe', 'Satz', 'Seite', 'verstehen', 'erklären'],
    prompts: [
      'Noch nicht. Können Sie den letzten Satz bitte wiederholen?',
      'Können Sie bitte etwas langsamer sprechen?',
      'Meinen Sie Seite zwölf?',
    ],
    promptCs: [
      'Ještě ne. Můžete prosím zopakovat poslední větu?',
      'Můžete prosím mluvit trochu pomaleji?',
      'Myslíte stranu dvanáct?',
    ],
    learnerRole: 'studentka, která potřebuje upřesnění',
    coachRole: 'učitel',
    icon: 'school',
  },
  {
    chapterId: 'chapter-35-price-and-payment',
    id: 'transfer-price-and-payment',
    title: 'Cena, platba a účtenka',
    description: 'Zjisti cenu, zvol způsob platby a dokonči nákup bez neurčitých gest.',
    goal: 'Vyřídit tři základní platební kroky přesnými krátkými větami.',
    level: 'A1',
    opening: 'Das macht sechs Euro achtzig. Möchten Sie bar oder mit Karte zahlen?',
    openingCs: 'Je to šest eur osmdesát. Chcete platit hotově, nebo kartou?',
    focusWords: ['Wie viel kostet', 'mit Karte zahlen', 'den Kassenbon'],
    cues: ['Preis', 'Euro', 'bar', 'Karte', 'kosten'],
    prompts: [
      'Wie viel kostet das Brötchen?',
      'Ich zahle mit Karte, bitte.',
      'Den Kassenbon nehme ich gern.',
    ],
    promptCs: ['Kolik stojí ta houska?', 'Zaplatím kartou, prosím.', 'Účtenku si ráda vezmu.'],
    learnerRole: 'zákaznice',
    coachRole: 'prodavač u pokladny',
    icon: 'shopping',
  },
  {
    chapterId: 'chapter-38-morning-time',
    id: 'transfer-morning-routine',
    title: 'Ranní rutina s časem',
    description: 'Seřaď ranní činnosti a přidej k nim konkrétní časové údaje.',
    goal: 'Popsat ráno ve třech navazujících větách se správně oddělenými slovesy.',
    level: 'A1',
    opening: 'Guten Morgen! Wann musst du heute aus dem Haus?',
    openingCs: 'Dobré ráno! Kdy dnes musíš vyjít z domu?',
    focusWords: ['um halb sieben', 'danach', 'zur Schule fahren'],
    cues: ['aufstehen', 'duschen', 'frühstücken', 'Uhr', 'Morgen'],
    prompts: [
      'Ich stehe um halb sieben auf.',
      'Danach dusche ich und frühstücke.',
      'Um Viertel vor acht fahre ich zur Schule.',
    ],
    promptCs: [
      'Vstávám v půl sedmé.',
      'Potom se osprchuji a nasnídám.',
      'Ve tři čtvrtě na osm jedu do školy.',
    ],
    learnerRole: 'studentka plánující ráno',
    coachRole: 'spolužačka',
    icon: 'timer',
  },
  {
    chapterId: 'chapter-40-whose-is-it',
    id: 'transfer-whose-is-it',
    title: 'Komu to patří',
    description: 'Rozliš vlastníky několika věcí a správně použij přivlastnění i dativ.',
    goal: 'Vrátit tři věci správným lidem bez ukazování nebo jednoslovných odpovědí.',
    level: 'A1',
    opening: 'Im Flur liegen mehrere Sachen. Welche gehören dir?',
    openingCs: 'Na chodbě leží několik věcí. Které patří tobě?',
    focusWords: ['gehört mir', 'Ist das dein', 'meiner Schwester'],
    cues: ['Tasche', 'Regenschirm', 'Schlüssel', 'gehören', 'Flur'],
    prompts: [
      'Die blaue Tasche gehört mir.',
      'Ist das dein Regenschirm?',
      'Nein, der Regenschirm gehört meiner Schwester.',
    ],
    promptCs: [
      'Ta modrá taška patří mně.',
      'Je to tvůj deštník?',
      'Ne, ten deštník patří mé sestře.',
    ],
    learnerRole: 'členka domácnosti',
    coachRole: 'soused, který našel věci',
    icon: 'home',
  },
  {
    chapterId: 'chapter-41-evening-together',
    id: 'transfer-evening-together',
    title: 'Společný večer doma',
    description: 'Navrhni činnost, domluv pořadí a uzavři večer konkrétním plánem.',
    goal: 'Naplánovat společný večer bez tří izolovaných návrhů.',
    level: 'A1',
    opening: 'Wir haben heute Abend beide Zeit. Was machen wir zusammen?',
    openingCs: 'Dnes večer máme oba čas. Co podnikneme společně?',
    focusWords: ['zusammen kochen', 'danach', 'um zehn Uhr'],
    cues: ['Abend', 'Film', 'Küche', 'aufräumen', 'Zeit'],
    prompts: [
      'Wir können zusammen kochen.',
      'Danach möchte ich einen Film sehen.',
      'Um zehn Uhr räumen wir die Küche auf.',
    ],
    promptCs: [
      'Můžeme společně vařit.',
      'Potom se chci podívat na film.',
      'V deset hodin uklidíme kuchyň.',
    ],
    learnerRole: 'členka domácnosti',
    coachRole: 'spolubydlící',
    icon: 'home',
  },
  {
    chapterId: 'chapter-44-transfer-in-town',
    id: 'transfer-city-connection',
    title: 'Přestup až do cíle',
    description: 'Ověř první linku, místo přestupu i konečnou zastávku.',
    goal: 'Sestavit celou cestu městskou dopravou ve správném pořadí.',
    level: 'A1',
    opening: 'Sie möchten zum Museum. Wo steigen Sie um?',
    openingCs: 'Chcete jet k muzeu. Kde přestoupíte?',
    focusWords: ['zuerst', 'steige ich um', 'muss ich aussteigen'],
    cues: ['Linie', 'Hauptbahnhof', 'Haltestelle', 'Museum', 'fahren'],
    prompts: [
      'Ich fahre zuerst mit der Linie drei.',
      'Am Hauptbahnhof steige ich in die Linie sieben um.',
      'An welcher Haltestelle muss ich aussteigen?',
    ],
    promptCs: [
      'Nejdřív jedu linkou tři.',
      'Na hlavním nádraží přestoupím na linku sedm.',
      'Na které zastávce musím vystoupit?',
    ],
    learnerRole: 'cestující',
    coachRole: 'pracovník dopravního podniku',
    icon: 'map',
  },
  {
    chapterId: 'chapter-47-room-problem',
    id: 'transfer-hotel-room-problem',
    title: 'Závada na hotelovém pokoji',
    description: 'Popiš konkrétní závadu, požádej o zásah a domluv záložní řešení.',
    goal: 'Získat proveditelnou nápravu bez obecného „pokoj není dobrý“.',
    level: 'A2',
    opening: 'Rezeption, guten Abend. Was stimmt in Ihrem Zimmer nicht?',
    openingCs: 'Recepce, dobrý večer. Co není v pořádku na vašem pokoji?',
    focusWords: ['funktioniert nicht', 'jemanden schicken', 'ein anderes Zimmer'],
    cues: ['Heizung', 'Zimmer', 'Rezeption', 'reparieren', 'heute'],
    prompts: [
      'Die Heizung in meinem Zimmer funktioniert nicht.',
      'Könnten Sie bitte jemanden schicken?',
      'Falls das heute nicht geht, brauche ich ein anderes Zimmer.',
    ],
    promptCs: [
      'Topení v mém pokoji nefunguje.',
      'Mohli byste prosím někoho poslat?',
      'Pokud to dnes nepůjde, potřebuji jiný pokoj.',
    ],
    learnerRole: 'hotelová hostka',
    coachRole: 'recepční',
    icon: 'hotel',
  },
  {
    chapterId: 'chapter-49-at-the-pharmacy',
    id: 'transfer-pharmacy-request',
    title: 'Přesný požadavek v lékárně',
    description: 'Popiš potíže, uveď důležité omezení a ověř způsob užívání.',
    goal: 'Získat srozumitelné informace o přípravku pomocí tří přesných otázek.',
    level: 'A2',
    opening: 'Guten Tag. Was brauchen Sie aus der Apotheke?',
    openingCs: 'Dobrý den. Co potřebujete z lékárny?',
    focusWords: ['gegen Penicillin allergisch', 'welche Tabletten geeignet', 'wie oft einnehmen'],
    cues: ['Halsschmerzen', 'Mittel', 'Apotheke', 'Tablette', 'Beschwerden'],
    prompts: [
      'Ich bin gegen Penicillin allergisch.',
      'Welche Tabletten sind für mich geeignet?',
      'Wie oft soll ich sie einnehmen?',
    ],
    promptCs: [
      'Jsem alergická na penicilin.',
      'Které tablety jsou pro mě vhodné?',
      'Jak často je mám užívat?',
    ],
    learnerRole: 'zákaznice v lékárně',
    coachRole: 'lékárník',
    icon: 'health',
  },
  {
    chapterId: 'chapter-51-when-to-see-doctor',
    id: 'transfer-doctor-next-step',
    title: 'Další krok při potížích',
    description: 'Shrň změnu stavu a domluv konkrétní kontakt s odbornou pomocí.',
    goal: 'Popsat zhoršení a potvrdit další krok bez jazykově neurčitého sdělení.',
    level: 'A2',
    opening: 'Ihre Beschwerden dauern schon mehrere Tage. Wie geht es Ihnen heute?',
    openingCs: 'Vaše potíže trvají už několik dní. Jak vám je dnes?',
    focusWords: ['seit gestern höher', 'außerdem', 'einen Arzttermin vereinbaren'],
    cues: ['Fieber', 'Husten', 'Beschwerden', 'Termin', 'Arzt'],
    prompts: [
      'Das Fieber ist seit gestern höher.',
      'Außerdem habe ich starken Husten.',
      'Dann vereinbare ich heute noch einen Arzttermin.',
    ],
    promptCs: [
      'Od včerejška je horečka vyšší.',
      'Navíc mám silný kašel.',
      'Domluvím si tedy ještě dnes termín u lékaře.',
    ],
    learnerRole: 'pacientka popisující stav',
    coachRole: 'zdravotnický pracovník',
    icon: 'health',
  },
  {
    chapterId: 'chapter-55-request-a-remedy',
    id: 'transfer-request-remedy',
    title: 'Náprava po vadném nákupu',
    description: 'Pojmenuj vadu, řekni preferované řešení a nabídni přijatelnou alternativu.',
    goal: 'Uzavřít reklamaci konkrétním výsledkem místo pouhého popisu problému.',
    level: 'A2',
    opening: 'Sie möchten den Artikel reklamieren. Was wünschen Sie?',
    openingCs: 'Chcete výrobek reklamovat. Jaké řešení si přejete?',
    focusWords: ['nach zwei Tagen kaputt', 'umtauschen', 'um eine Erstattung bitten'],
    cues: ['Reißverschluss', 'Jacke', 'Kassenbon', 'Reklamation', 'Lösung'],
    prompts: [
      'Der Reißverschluss ist nach zwei Tagen kaputt.',
      'Ich möchte die Jacke umtauschen.',
      'Falls das nicht möglich ist, bitte ich um eine Erstattung.',
    ],
    promptCs: [
      'Zip je po dvou dnech rozbitý.',
      'Chci bundu vyměnit.',
      'Pokud to není možné, žádám o vrácení peněz.',
    ],
    learnerRole: 'zákaznice s reklamací',
    coachRole: 'pracovník zákaznického servisu',
    icon: 'shopping',
  },
  {
    chapterId: 'chapter-57-neighbour-agreement',
    id: 'transfer-neighbour-agreement',
    title: 'Dohoda se sousedem',
    description: 'Uznat problém nestačí: domluv konkrétní pravidlo i způsob další komunikace.',
    goal: 'Uklidnit sousedský spor a uzavřít ověřitelnou dohodu.',
    level: 'A2',
    opening: 'Die Musik war gestern Abend sehr laut. Wie können wir das lösen?',
    openingCs: 'Hudba byla včera večer velmi hlasitá. Jak to můžeme vyřešit?',
    focusWords: ['Es tut mir leid', 'die Musik leiser stellen', 'direkt klingeln'],
    cues: ['Musik', 'Nachbar', 'laut', 'Abend', 'stören'],
    prompts: [
      'Es tut mir leid, dass die Musik so laut war.',
      'Ab zehn Uhr werde ich die Musik leiser stellen.',
      'Wenn es wieder stört, klingeln Sie bitte direkt bei mir.',
    ],
    promptCs: [
      'Mrzí mě, že byla hudba tak hlasitá.',
      'Od deseti hodin hudbu ztiším.',
      'Pokud to bude znovu rušit, zazvoňte prosím přímo u mě.',
    ],
    learnerRole: 'sousedka, která hledá dohodu',
    coachRole: 'nespokojený soused',
    icon: 'home',
  },
  {
    chapterId: 'chapter-58-house-rules',
    id: 'transfer-house-rules',
    title: 'Pravidla domu bez dohadů',
    description: 'Ověř časy, třídění odpadu a noční zamykání třemi konkrétními otázkami.',
    goal: 'Zjistit praktická pravidla domu a vlastními slovy jedno potvrdit.',
    level: 'A2',
    opening: 'Sie sind neu im Haus. Welche Regel möchten Sie zuerst klären?',
    openingCs: 'Jste v domě nová. Které pravidlo chcete nejdřív objasnit?',
    focusWords: ['Wann darf ich', 'Wo trennen wir', 'Könnten wir eine Ausnahme vereinbaren'],
    cues: ['Waschmaschine', 'Papier', 'Glas', 'Haustür', 'nachts'],
    prompts: [
      'Wann darf ich die Waschmaschine benutzen?',
      'Wo trennen wir Papier und Glas?',
      'Könnten wir für Samstag eine Ausnahme von der Ruhezeit vereinbaren?',
    ],
    promptCs: [
      'Kdy mohu používat pračku?',
      'Kde třídíme papír a sklo?',
      'Mohli bychom se na sobotu domluvit na výjimce z doby klidu?',
    ],
    learnerRole: 'nová nájemnice',
    coachRole: 'správce domu',
    icon: 'home',
  },
  {
    chapterId: 'chapter-59-measurable-study-goal',
    id: 'transfer-measurable-study-goal',
    title: 'Cíl, který lze ověřit',
    description: 'Proměň obecné „chci se zlepšit“ v konkrétní výkon, rytmus a závěrečnou kontrolu.',
    goal: 'Formulovat měřitelný studijní cíl se způsobem vyhodnocení.',
    level: 'B1',
    opening: 'Was möchtest du bis zum Ende des Monats im Deutschen erreichen?',
    openingCs: 'Čeho chceš v němčině dosáhnout do konce měsíce?',
    focusWords: ['frei sprechen können', 'an vier Tagen', 'am Monatsende vergleichen'],
    cues: ['Lernziel', 'Monat', 'Aufnahme', 'Fortschritt', 'üben'],
    prompts: [
      'Ich möchte zehn Minuten frei über meinen Alltag sprechen können.',
      'Dafür übe ich an vier Tagen pro Woche.',
      'Am Monatsende nehme ich eine kurze Antwort auf und vergleiche sie mit heute.',
    ],
    learnerRole: 'studentka stanovující cíl',
    coachRole: 'studijní mentor',
    icon: 'school',
  },
  {
    chapterId: 'chapter-60-weekly-study-plan',
    id: 'transfer-weekly-study-plan',
    title: 'Týdenní plán bez přeplnění',
    description: 'Rozděl omezený čas mezi slovní zásobu, gramatiku a aktivní mluvení.',
    goal: 'Sestavit proveditelný plán se třemi odlišnými druhy práce.',
    level: 'B1',
    opening: 'Du hast diese Woche nur vier freie Lernzeiten. Wie verteilst du sie?',
    openingCs: 'Tento týden máš jen čtyři volné časy na učení. Jak je rozdělíš?',
    focusWords: ['Wörter wiederholen', 'Grammatik üben', 'einen Sprechblock einplanen'],
    cues: ['Montag', 'Mittwoch', 'Wochenende', 'Lernzeit', 'Plan'],
    prompts: [
      'Am Montag wiederhole ich die neuen Wörter.',
      'Am Mittwoch übe ich die Grammatik mit kurzen Beispielen.',
      'Am Wochenende plane ich einen längeren Sprechblock ein.',
    ],
    learnerRole: 'studentka s omezeným časem',
    coachRole: 'studijní mentor',
    icon: 'calendar',
  },
  {
    chapterId: 'chapter-62-review-progress',
    id: 'transfer-review-progress',
    title: 'Poctivé vyhodnocení pokroku',
    description: 'Odděl to, co se zlepšilo, od přetrvávající slabiny a uprav další plán.',
    goal: 'Vyhodnotit čtyři týdny učení pomocí důkazu, ne dojmu.',
    level: 'B1',
    opening: 'Du lernst seit vier Wochen nach deinem neuen Plan. Was hat sich verändert?',
    openingCs: 'Učíš se čtyři týdny podle nového plánu. Co se změnilo?',
    focusWords: ['inzwischen', 'noch oft', 'deshalb reserviere ich'],
    cues: ['Lesen', 'Sprechen', 'Wörter', 'Fortschritt', 'Lernplan'],
    prompts: [
      'Beim Lesen verstehe ich inzwischen deutlich mehr.',
      'Beim Sprechen suche ich noch oft nach den richtigen Wörtern.',
      'Deshalb reserviere ich nächste Woche mehr Zeit für aktives Sprechen.',
    ],
    learnerRole: 'studentka hodnotící vlastní práci',
    coachRole: 'studijní mentor',
    icon: 'school',
  },
  {
    chapterId: 'chapter-63-practical-example',
    id: 'transfer-practical-example',
    title: 'Dolož tvrzení příkladem',
    description: 'Nahraď obecné sebehodnocení konkrétní situací, jednáním a výsledkem.',
    goal: 'Popsat pracovní zkušenost ve struktuře problém–akce–výsledek.',
    level: 'B1',
    opening: 'Sie sagen, Sie könnten gut unter Zeitdruck arbeiten. Können Sie ein Beispiel nennen?',
    openingCs: 'Říkáte, že umíte dobře pracovat pod časovým tlakem. Můžete uvést příklad?',
    focusWords: ['kurzfristig ausfallen', 'Aufgaben neu verteilen', 'den Termin einhalten'],
    cues: ['Projekt', 'Kollegin', 'Kunde', 'Zeitdruck', 'Ergebnis'],
    prompts: [
      'Bei meinem letzten Projekt fiel eine Kollegin kurzfristig aus.',
      'Ich habe die Aufgaben neu verteilt und den Kunden informiert.',
      'Dadurch konnten wir den Termin trotzdem einhalten.',
    ],
    learnerRole: 'uchazečka popisující zkušenost',
    coachRole: 'personalista',
    icon: 'work',
  },
  {
    chapterId: 'chapter-66-order-events',
    id: 'transfer-order-events',
    title: 'Události v přesném pořadí',
    description: 'Zrekonstruuj průběh incidentu bez skoků mezi příčinou a následkem.',
    goal: 'Popsat tři fáze události pomocí jasných časových spojek.',
    level: 'B1',
    opening: 'Sie haben den Vorfall beobachtet. Was geschah zuerst?',
    openingCs: 'Událost jste pozorovala. Co se stalo jako první?',
    focusWords: ['zuerst bemerkte ich', 'danach informierte ich', 'schließlich wurde'],
    cues: ['Vorfall', 'Anzeige', 'Betrieb', 'Person', 'unterbrechen'],
    prompts: [
      'Zuerst bemerkte ich, dass die Anzeige ausgefallen war.',
      'Danach informierte ich die zuständige Person.',
      'Schließlich wurde der Betrieb sicher unterbrochen.',
    ],
    learnerRole: 'svědkyně incidentu',
    coachRole: 'osoba pořizující záznam',
    icon: 'timer',
  },
  {
    chapterId: 'chapter-67-earlier-event',
    id: 'transfer-earlier-event',
    title: 'Co se stalo ještě předtím',
    description: 'Odliš předchozí událost od pozdějšího děje pomocí plusquamperfekta.',
    goal: 'Vysvětlit zpoždění tak, aby byly příčina i časová posloupnost jednoznačné.',
    level: 'B1',
    opening: 'Warum begann die Besprechung später als geplant?',
    openingCs: 'Proč porada začala později, než bylo plánováno?',
    focusWords: ['bevor', 'hatte geschickt', 'erst danach'],
    cues: ['Besprechung', 'Kunde', 'Daten', 'prüfen', 'Entscheidung'],
    prompts: [
      'Bevor die Besprechung begann, hatte der Kunde neue Daten geschickt.',
      'Wir hatten die Zahlen noch nicht geprüft.',
      'Erst danach konnten wir eine belastbare Entscheidung treffen.',
    ],
    learnerRole: 'účastnice porady',
    coachRole: 'vedoucí zjišťující příčinu',
    icon: 'work',
  },
  {
    chapterId: 'chapter-68-brief-report',
    id: 'transfer-brief-report',
    title: 'Stručný záznam incidentu',
    description: 'Shrň čas, příčinu a vyřešení incidentu bez vedlejších detailů.',
    goal: 'Vytvořit třívětý věcný report vhodný do protokolu.',
    level: 'B1',
    opening: 'Fassen Sie den Zwischenfall bitte für das Protokoll zusammen.',
    openingCs: 'Shrňte prosím událost pro protokol.',
    focusWords: ['es kam zu', 'die Ursache war', 'nachdem'],
    cues: ['Dienstag', 'Übergabe', 'Verzögerung', 'Datei', 'Prozess'],
    prompts: [
      'Am Dienstag kam es während der Übergabe zu einer Verzögerung.',
      'Die Ursache war eine unvollständige Datei.',
      'Nachdem wir die Datei ersetzt hatten, lief der Prozess wieder normal.',
    ],
    learnerRole: 'pracovnice podávající hlášení',
    coachRole: 'osoba vedoucí protokol',
    icon: 'work',
  },
  {
    chapterId: 'chapter-69-explain-a-process',
    id: 'transfer-explain-process',
    title: 'Proces krok za krokem',
    description: 'Vysvětli kontrolu, opravu a zveřejnění dokumentu pomocí procesního pasiva.',
    goal: 'Popsat firemní postup nezávisle na konkrétní vykonávající osobě.',
    level: 'B1',
    opening: 'Wie läuft die Freigabe eines neuen Dokuments ab?',
    openingCs: 'Jak probíhá schválení nového dokumentu?',
    focusWords: ['zuerst wird', 'danach werden', 'zum Schluss wird'],
    cues: ['Entwurf', 'Prüfung', 'Korrektur', 'Version', 'System'],
    prompts: [
      'Zuerst wird der Entwurf von zwei Personen geprüft.',
      'Danach werden offene Punkte dokumentiert und geklärt.',
      'Zum Schluss wird die freigegebene Version im System veröffentlicht.',
    ],
    learnerRole: 'pracovnice vysvětlující postup',
    coachRole: 'nový člen týmu',
    icon: 'work',
  },
  {
    chapterId: 'chapter-70-opinion-with-reason',
    id: 'transfer-opinion-with-reason',
    title: 'Názor, důvod a omezení',
    description: 'Vyjádři stanovisko, podlož ho důvodem a přidej relevantní podmínku.',
    goal: 'Obhájit názor bez absolutního tvrzení nebo pouhého „protože ano“.',
    level: 'B1',
    opening: 'Sollte die Schule einen späteren Unterrichtsbeginn testen?',
    openingCs: 'Měla by škola vyzkoušet pozdější začátek vyučování?',
    focusWords: ['Meiner Meinung nach', 'weil', 'allerdings'],
    cues: ['Unterricht', 'Morgen', 'Konzentration', 'Busfahrplan', 'testen'],
    prompts: [
      'Meiner Meinung nach wäre ein späterer Beginn sinnvoll.',
      'Das wäre hilfreich, weil sich viele Schülerinnen morgens besser konzentrieren könnten.',
      'Allerdings müsste der Busfahrplan berücksichtigt werden.',
    ],
    learnerRole: 'studentka v debatě',
    coachRole: 'člen školské rady',
    icon: 'discussion',
  },
  {
    chapterId: 'chapter-71-acknowledge-objection',
    id: 'transfer-acknowledge-objection',
    title: 'Uznat námitku a neztratit návrh',
    description: 'Přijmi oprávněné riziko a uprav návrh tak, aby zůstal proveditelný.',
    goal: 'Reagovat na námitku věcně místo jejího odmítnutí nebo úplného ústupu.',
    level: 'B1',
    opening: 'Der Vorschlag spart Zeit, könnte aber die Qualität verschlechtern.',
    openingCs: 'Návrh šetří čas, ale mohl by zhoršit kvalitu.',
    focusWords: ['Der Einwand ist berechtigt', 'zunächst begrenzen', 'ohne zu gefährden'],
    cues: ['Vorschlag', 'Qualität', 'Kontrolle', 'Team', 'Verfahren'],
    prompts: [
      'Der Einwand ist berechtigt, weil die Kontrolle nicht entfallen darf.',
      'Wir könnten den Test zunächst auf ein kleines Team begrenzen.',
      'So gewinnen wir Daten, ohne das ganze Verfahren zu gefährden.',
    ],
    learnerRole: 'autorka návrhu',
    coachRole: 'kritický člen týmu',
    icon: 'discussion',
  },
  {
    chapterId: 'chapter-72-propose-compromise',
    id: 'transfer-propose-compromise',
    title: 'Kompromis se dvěma termíny',
    description: 'Spoj rychlou dílčí dodávku s pozdějším úplným výsledkem.',
    goal: 'Navrhnout kompromis, který zachová potřeby obou stran.',
    level: 'B1',
    opening: 'Eine Seite will am Freitag liefern, die andere erst am Montag. Was schlagen Sie vor?',
    openingCs: 'Jedna strana chce dodat výsledek v pátek, druhá až v pondělí. Co navrhujete?',
    focusWords: ['Ich schlage vor', 'folgt am Montag', 'damit'],
    cues: ['Freitag', 'Kurzfassung', 'Version', 'Kunde', 'Prüfzeit'],
    prompts: [
      'Ich schlage vor, am Freitag eine geprüfte Kurzfassung zu liefern.',
      'Die vollständige Version folgt dann am Montag.',
      'Damit erhält der Kunde früh ein Ergebnis, und das Team behält genug Prüfzeit.',
    ],
    learnerRole: 'moderátorka dohody',
    coachRole: 'zástupce jedné strany',
    icon: 'discussion',
  },
  {
    chapterId: 'chapter-77-measurable-criteria',
    id: 'transfer-measurable-criteria',
    title: 'Kritéria před experimentem',
    description: 'Urči metriky, okamžik vyhodnocení i hranici úspěchu před zahájením pilotu.',
    goal: 'Zabránit tomu, aby se úspěch definoval až podle výsledku.',
    level: 'B2',
    opening: 'Woran erkennen wir nach sechs Wochen, ob der Pilot erfolgreich war?',
    openingCs: 'Podle čeho za šest týdnů poznáme, zda byl pilot úspěšný?',
    focusWords: ['wir sollten messen', 'vor Beginn festlegen', 'nur wenn'],
    cues: ['Bearbeitungszeit', 'Fehlerquote', 'Zufriedenheit', 'Kennzahl', 'Pilot'],
    prompts: [
      'Wir sollten Bearbeitungszeit, Fehlerquote und Zufriedenheit messen.',
      'Die Kriterien müssen vor Beginn verbindlich festgelegt werden.',
      'Ein Erfolg liegt nur vor, wenn sich mindestens zwei Kennzahlen verbessern.',
    ],
    learnerRole: 'vedoucí experimentu',
    coachRole: 'člen rozhodovacího týmu',
    icon: 'presentation',
  },
  {
    chapterId: 'chapter-79-evidence-based-decision',
    id: 'transfer-evidence-decision',
    title: 'Rozhodnutí ze smíšených výsledků',
    description: 'Odděl pozitivní signál od omezené jistoty a navrhni další ověřovací krok.',
    goal: 'Přijmout přiměřené rozhodnutí bez přehnaného závěru z malé skupiny.',
    level: 'B2',
    opening: 'Die Ergebnisse sind gemischt. Welche Entscheidung lässt sich trotzdem begründen?',
    openingCs: 'Výsledky jsou smíšené. Jaké rozhodnutí lze přesto odůvodnit?',
    focusWords: ['während', 'da die Stichprobe klein war', 'eine zweite Testphase'],
    cues: ['Bearbeitungszeit', 'Fehlerquote', 'Stichprobe', 'Ergebnis', 'ausweiten'],
    prompts: [
      'Die Bearbeitungszeit ist gesunken, während die Fehlerquote stabil blieb.',
      'Da die Stichprobe klein war, sollten wir den Piloten nicht sofort ausweiten.',
      'Ich empfehle eine zweite Testphase mit einer größeren Gruppe.',
    ],
    learnerRole: 'analytička výsledků',
    coachRole: 'rozhodující manažer',
    icon: 'presentation',
  },
  {
    chapterId: 'chapter-82-proportionate-responsibility',
    id: 'transfer-proportionate-responsibility',
    title: 'Odpovědnost bez hledání viníka',
    description: 'Rozděl odpovědnost mezi chybu procesu, reakci týmu a povinnost vedení.',
    goal: 'Popsat přiměřenou odpovědnost bez zjednodušení na jedinou osobu.',
    level: 'B2',
    opening: 'Wer trägt Verantwortung für die Verzögerung?',
    openingCs: 'Kdo nese odpovědnost za zpoždění?',
    focusWords: ['lässt sich nicht zuschreiben', 'hätte ansprechen müssen', 'sollte sicherstellen'],
    cues: ['Fehler', 'Übergabe', 'Zuständigkeit', 'Leitung', 'Prozess'],
    prompts: [
      'Der Fehler entstand an zwei Übergabepunkten und lässt sich nicht einer Person zuschreiben.',
      'Das Team hätte die unklare Zuständigkeit früher ansprechen müssen.',
      'Die Leitung sollte jedoch sicherstellen, dass der Prozess künftig eindeutig dokumentiert ist.',
    ],
    learnerRole: 'nezávislá hodnotitelka',
    coachRole: 'vedoucí hledající nápravu',
    icon: 'discussion',
  },
  {
    chapterId: 'chapter-84-describe-a-trend',
    id: 'transfer-describe-trend',
    title: 'Trend bez přehánění',
    description: 'Popiš počáteční růst, maximum i následnou stabilizaci jedním souvislým výkladem.',
    goal: 'Převést časovou řadu do přesného slovního popisu bez kauzální domněnky.',
    level: 'B2',
    opening: 'Was zeigen die Nutzungszahlen der letzten zwölf Monate?',
    openingCs: 'Co ukazují údaje o využití za posledních dvanáct měsíců?',
    focusWords: ['zunächst langsam', 'der höchste Wert', 'stabilisiert sich'],
    cues: ['Nutzung', 'Quartal', 'Anstieg', 'Rückgang', 'Niveau'],
    prompts: [
      'Die Nutzung stieg zunächst langsam und nahm ab Mai deutlich zu.',
      'Im dritten Quartal wurde der höchste Wert erreicht.',
      'Seit Oktober stabilisiert sich die Zahl auf einem leicht niedrigeren Niveau.',
    ],
    learnerRole: 'prezentující analytička',
    coachRole: 'člen publika',
    icon: 'presentation',
  },
  {
    chapterId: 'chapter-85-correlation-not-cause',
    id: 'transfer-correlation-caution',
    title: 'Korelace ještě není příčina',
    description:
      'Pojmenuj vztah v datech, nabídni alternativní vysvětlení a stanov podmínku důkazu.',
    goal: 'Zabránit kauzálnímu závěru, který dostupná data nepodporují.',
    level: 'B2',
    opening: 'Teams mit mehr Homeoffice melden höhere Zufriedenheit. Ist das schon ein Beweis?',
    openingCs: 'Týmy s větším podílem home office uvádějí vyšší spokojenost. Je to už důkaz?',
    focusWords: ['einen Zusammenhang zeigen', 'möglicherweise', 'kontrolliert werden'],
    cues: ['Homeoffice', 'Zufriedenheit', 'Ursache', 'Führung', 'Aufgabenstruktur'],
    prompts: [
      'Die Daten zeigen einen Zusammenhang, aber noch keinen kausalen Effekt.',
      'Möglicherweise unterscheiden sich die Teams auch in Führung oder Aufgabenstruktur.',
      'Für eine belastbare Aussage müssten diese Faktoren kontrolliert werden.',
    ],
    learnerRole: 'datová analytička',
    coachRole: 'kritický zadavatel',
    icon: 'presentation',
  },
  {
    chapterId: 'chapter-86-limited-recommendation',
    id: 'transfer-limited-recommendation',
    title: 'Doporučení s jasnou hranicí',
    description: 'Doporuč omezený krok, přidej kontrolní termín a podmínku trvalého zavedení.',
    goal: 'Formulovat použitelné doporučení i při neúplných datech.',
    level: 'B2',
    opening: 'Welche Empfehlung können Sie trotz der unsicheren Daten geben?',
    openingCs: 'Jaké doporučení můžete dát navzdory nejistým datům?',
    focusWords: ['auf Grundlage', 'sollte überprüft werden', 'erst bei'],
    cues: ['Daten', 'Pilotversuch', 'Kriterien', 'Einführung', 'Ergebnis'],
    prompts: [
      'Auf Grundlage der bisherigen Daten empfehle ich einen begrenzten Pilotversuch.',
      'Die Maßnahme sollte nach drei Monaten anhand fester Kriterien überprüft werden.',
      'Eine dauerhafte Einführung wäre erst bei stabilen Ergebnissen vertretbar.',
    ],
    learnerRole: 'odborná poradkyně',
    coachRole: 'rozhodující komise',
    icon: 'presentation',
  },
  {
    chapterId: 'chapter-90-source-and-comment',
    id: 'transfer-source-and-comment',
    title: 'Zdroj oddělený od komentáře',
    description: 'Připiš tvrzení autorům, popiš skutečná data a teprve potom je interpretuj.',
    goal: 'Zabránit tomu, aby cizí hodnocení působilo jako ověřený fakt redakce.',
    level: 'C1',
    opening:
      'Die Studie behauptet, die Reform sei eindeutig erfolgreich. Wie berichten Sie darüber?',
    openingCs: 'Studie tvrdí, že reforma byla jednoznačně úspěšná. Jak o tom budete informovat?',
    focusWords: ['nach Angaben der Autoren', 'zeigen tatsächlich', 'nicht gleichzusetzen'],
    cues: ['Studie', 'Reform', 'Teilnahme', 'Einflussfaktor', 'Kausalnachweis'],
    prompts: [
      'Nach Angaben der Autoren habe die Reform die Teilnahme erhöht.',
      'Die veröffentlichten Daten zeigen tatsächlich einen Anstieg, lassen aber mehrere Einflussfaktoren offen.',
      'Die positive Bewertung stammt daher von den Autoren; sie ist nicht mit einem gesicherten Kausalnachweis gleichzusetzen.',
    ],
    learnerRole: 'redaktorka vědecké zprávy',
    coachRole: 'vedoucí redakce',
    icon: 'interview',
  },
  {
    chapterId: 'chapter-92-compare-media-claims',
    id: 'transfer-compare-media-claims',
    title: 'Dva titulky, jedna datová řada',
    description: 'Ukaž, jak rozdílný výběr období vede ke dvěma zdánlivě opačným titulkům.',
    goal: 'Porovnat mediální výroky bez falešného prohlášení, že jeden nutně lže.',
    level: 'C1',
    opening:
      'Zwei Medien ziehen aus derselben Studie gegensätzliche Schlüsse. Wie ordnen Sie das ein?',
    openingCs: 'Dvě média vyvozují ze stejné studie opačné závěry. Jak to zařadíte?',
    focusWords: ['während', 'unterschiedliche Zeiträume', 'eine faire Zusammenfassung'],
    cues: ['Medium', 'Studie', 'Anstieg', 'Rückgang', 'Unsicherheit'],
    prompts: [
      'Das erste Medium hebt den kurzfristigen Anstieg hervor, während das zweite auf den späteren Rückgang verweist.',
      'Beide Aussagen beziehen sich auf reale Daten, wählen jedoch unterschiedliche Zeiträume.',
      'Eine faire Zusammenfassung muss deshalb den gesamten Verlauf und die Unsicherheit nennen.',
    ],
    learnerRole: 'mediální analytička',
    coachRole: 'moderátor diskuse',
    icon: 'interview',
  },
  {
    chapterId: 'chapter-94-cut-clumsy-text',
    id: 'transfer-concise-editing',
    title: 'Redakční řez bez ztráty významu',
    description: 'Nahraď těžkopádné nominalizace slovesem a zachovej podmínku, výsledek i limit.',
    goal: 'Zkrátit odborný odstavec, aniž zmizí jeho logická struktura.',
    level: 'C1',
    opening: 'Dieser Absatz ist korrekt, aber unnötig schwerfällig. Wie würden Sie ihn straffen?',
    openingCs: 'Tento odstavec je správný, ale zbytečně těžkopádný. Jak byste ho zkrátila?',
    focusWords: ['stattdessen schreibe ich', 'lässt sich bündeln', 'behält bei'],
    cues: ['Absatz', 'Nominalisierung', 'Satz', 'Voraussetzung', 'Einschränkung'],
    prompts: [
      'Statt „eine Durchführung der Überprüfung vornehmen“ schreibe ich „die Ergebnisse prüfen“.',
      'Die drei Vorbemerkungen lassen sich zu einem präzisen Satz bündeln.',
      'Die gekürzte Fassung behält Voraussetzung, Ergebnis und Einschränkung bei.',
    ],
    learnerRole: 'redaktorka odborného textu',
    coachRole: 'autor původního návrhu',
    icon: 'work',
  },
  {
    chapterId: 'chapter-96-false-agreement',
    id: 'transfer-false-agreement',
    title: 'Stejné slovo není stejná dohoda',
    description: 'Rozbal zdánlivou shodu a ukaž rozdílná kritéria ukrytá pod stejným výrazem.',
    goal: 'Odhalit falešný konsenzus dřív, než se z něj stane neproveditelná dohoda.',
    level: 'C1',
    opening: 'Beide Seiten sagen, sie wollten eine „faire Lösung“. Besteht damit schon Einigkeit?',
    openingCs: 'Obě strany říkají, že chtějí „spravedlivé řešení“. Znamená to už shodu?',
    focusWords: ['verdeckt unterschiedliche', 'die eine Seite', 'nicht aber'],
    cues: ['Fairness', 'Anteil', 'Aufwand', 'Kriterium', 'Einigung'],
    prompts: [
      'Die gleiche Formulierung verdeckt unterschiedliche Vorstellungen von Fairness.',
      'Die eine Seite fordert gleiche Anteile, die andere gewichtet den bisherigen Aufwand.',
      'Es besteht also Einigkeit über das Zielwort, nicht aber über das Entscheidungskriterium.',
    ],
    learnerRole: 'mediátorka',
    coachRole: 'člen vyjednávacího týmu',
    icon: 'discussion',
  },
  {
    chapterId: 'chapter-98-synthesise-inputs',
    id: 'transfer-synthesise-inputs',
    title: 'Syntéza dvou rozdílných posudků',
    description: 'Spoj společný základ, odlišné důkazy a otevřená rizika do jednoho přehledu.',
    goal: 'Vytvořit syntézu, která nesmaže rozpor ani neopakuje dva izolované souhrny.',
    level: 'C1',
    opening:
      'Zwei Gutachten bewerten dieselbe Maßnahme unterschiedlich. Wie fassen Sie beide zusammen?',
    openingCs: 'Dva posudky hodnotí stejné opatření rozdílně. Jak oba shrnete?',
    focusWords: ['beide erkennen', 'stützt sich auf', 'getrennt ausweisen'],
    cues: ['Gutachten', 'Maßnahme', 'Kostendaten', 'Beschäftigte', 'Risiko'],
    prompts: [
      'Beide Gutachten erkennen kurzfristige Vorteile, gewichten die langfristigen Risiken jedoch verschieden.',
      'Das erste stützt sich vor allem auf Kostendaten, das zweite auf Folgen für die Beschäftigten.',
      'Eine belastbare Synthese muss daher Nutzen, Datenbasis und offene Risiken getrennt ausweisen.',
    ],
    learnerRole: 'autorka podkladového materiálu',
    coachRole: 'člen rozhodovací komise',
    icon: 'presentation',
  },
  {
    chapterId: 'chapter-100-decision-recommendation',
    id: 'transfer-decision-recommendation',
    title: 'Doporučení s pojistkou',
    description: 'Vyber variantu, připoj rozhodující podmínku a stanov okamžik přezkoumání.',
    goal: 'Dodat vedení akční doporučení, které nezamlčí limity ani cestu zpět.',
    level: 'C1',
    opening: 'Die Leitung braucht heute eine Entscheidung. Welche Empfehlung ist tragfähig?',
    openingCs: 'Vedení dnes potřebuje rozhodnutí. Jaké doporučení je udržitelné?',
    focusWords: ['sofern', 'ohne zu ignorieren', 'sollte überprüft werden'],
    cues: ['Option', 'Finanzierung', 'Testphase', 'Risiko', 'Zwischenziel'],
    prompts: [
      'Ich empfehle Option B, sofern die Finanzierung für die zweijährige Testphase gesichert ist.',
      'Sie erfüllt das wichtigste Kriterium, ohne die derzeit bekannten Risiken zu ignorieren.',
      'Sollten die Zwischenziele verfehlt werden, muss die Entscheidung nach zwölf Monaten überprüft werden.',
    ],
    learnerRole: 'strategická poradkyně',
    coachRole: 'člen vedení',
    icon: 'debate',
  },
];

export const transferCoachScenarios: CoachScenario[] = transferCoachSpecs.map(transferScenario);

export const transferCoachScenarioIdByChapterId: Readonly<Record<string, string>> =
  Object.fromEntries(transferCoachSpecs.map((spec) => [spec.chapterId, spec.id]));
