import type { CoachScenario } from './coach.ts';

export const supplementalCoachScenarios: CoachScenario[] = [
  {
    id: 'bakery-preorder',
    title: 'Vyzvednutí objednávky v pekárně',
    eyebrow: 'Roleplay · každodenní nákup',
    description: 'Najdi objednávku podle jména, zkontroluj obsah a požádej o zabalení.',
    goal: 'Vyzvednout předem objednané pečivo ve třech jasných krocích.',
    level: 'A1',
    minutes: 5,
    turns: 3,
    opening: 'Guten Morgen! Sie möchten eine Bestellung abholen. Auf welchen Namen?',
    openingCs: 'Dobré ráno! Chcete si vyzvednout objednávku. Na jaké jméno?',
    focusWords: ['auf den Namen', 'bestellt', 'bitte einpacken'],
    contextCues: [
      'Bestellung',
      'Bäckerei',
      'Brezel',
      'Zimtschnecke',
      'abholen',
      'bestellen',
      'einpacken',
      'mitnehmen',
    ],
    starterPrompts: [
      'Die Bestellung ist auf den Namen Novák.',
      'Ich habe zwei Brezeln und eine Zimtschnecke bestellt.',
      'Können Sie bitte alles einpacken?',
    ],
    guidedHints: [
      {
        label: 'Jméno',
        german: 'Die Bestellung ist auf den Namen Novák.',
        czech: 'Objednávka je na jméno Novák.',
      },
      {
        label: 'Kontrola',
        german: 'Ich habe zwei Brezeln und eine Zimtschnecke bestellt.',
        czech: 'Objednala jsem dvě preclíky a jednoho skořicového šneka.',
      },
      {
        label: 'Zabalení',
        german: 'Können Sie bitte alles einpacken?',
        czech: 'Můžete prosím všechno zabalit?',
      },
    ],
    learnerRole: 'zákaznice s předobjednávkou',
    coachRole: 'obsluha pekárny',
    icon: 'food',
    accent: 'butter',
  },
  {
    id: 'medical-examination',
    title: 'Vyšetření u lékaře',
    eyebrow: 'Roleplay · zdraví',
    description: 'Popiš délku potíží, upřesni příznak a ověř další postup.',
    goal: 'Předat lékaři tři konkrétní informace bez neurčitého „je mi špatně“.',
    level: 'A2',
    minutes: 6,
    turns: 3,
    opening: 'Guten Tag. Was fehlt Ihnen und seit wann haben Sie die Beschwerden?',
    openingCs: 'Dobrý den. Co vám je a jak dlouho máte potíže?',
    focusWords: ['seit drei Tagen', 'tut besonders weh', 'zur Untersuchung'],
    contextCues: [
      'Arztpraxis',
      'Untersuchung',
      'Halsschmerzen',
      'Fieber',
      'Husten',
      'untersuchen',
      'verschreiben',
      'nüchtern',
    ],
    starterPrompts: [
      'Seit drei Tagen habe ich Halsschmerzen und leichtes Fieber.',
      'Beim Schlucken tut mir der Hals besonders weh.',
      'Muss ich für die Untersuchung morgen nüchtern kommen?',
    ],
    guidedHints: [
      {
        label: 'Délka potíží',
        german: 'Seit drei Tagen habe ich Halsschmerzen.',
        czech: 'Tři dny mě bolí v krku.',
      },
      {
        label: 'Upřesnění',
        german: 'Beim Schlucken tut mir der Hals besonders weh.',
        czech: 'Při polykání mě krk bolí obzvlášť.',
      },
      {
        label: 'Další krok',
        german: 'Muss ich zur Untersuchung nüchtern kommen?',
        czech: 'Musím přijít na vyšetření nalačno?',
      },
    ],
    learnerRole: 'pacientka',
    coachRole: 'praktický lékař',
    icon: 'health',
    accent: 'mint',
  },
  {
    id: 'study-planning',
    title: 'Plán přípravy na zkoušku',
    eyebrow: 'Roleplay · studijní strategie',
    description: 'Urči slabé místo, rozvrhni etapy a stanov způsob kontroly pokroku.',
    goal: 'Proměnit obecné „musím se učit“ v proveditelný plán s měřitelnou kontrolou.',
    level: 'B1',
    minutes: 7,
    turns: 3,
    opening: 'Die Prüfung ist in vier Wochen. Was möchtest du zuerst verbessern?',
    openingCs: 'Zkouška je za čtyři týdny. Co chceš zlepšit jako první?',
    focusWords: ['mein Schwerpunkt', 'in Etappen einteilen', 'Fortschritt überprüfen'],
    contextCues: [
      'Prüfung',
      'Zeitplan',
      'Lernmethode',
      'Etappe',
      'Fortschritt',
      'wiederholen',
      'anwenden',
      'überprüfen',
    ],
    starterPrompts: [
      'Mein Schwerpunkt ist das freie Sprechen, weil mir dort Wörter fehlen.',
      'Ich teile die vier Wochen in Wortschatz, Grammatik und Prüfungstraining ein.',
      'Jeden Freitag überprüfe ich meinen Fortschritt mit einer Probeaufgabe.',
    ],
    learnerRole: 'studentka před zkouškou',
    coachRole: 'studijní poradce',
    icon: 'school',
    accent: 'sky',
  },
  {
    id: 'hybrid-team-coordination',
    title: 'Koordinace hybridního týmu',
    eyebrow: 'Roleplay · spolupráce',
    description: 'Vyřeš překryv časových pásem, nastav předávání práce a omez zbytečné porady.',
    goal: 'Dohodnout udržitelný pracovní postup pro distribuovaný tým.',
    level: 'B2',
    minutes: 8,
    turns: 3,
    opening:
      'Unsere Videokonferenzen passen nie für alle Zeitzonen. Wie könnten wir den Ablauf ändern?',
    openingCs:
      'Naše videokonference nikdy nevyhovují všem časovým pásmům. Jak bychom mohli změnit postup?',
    focusWords: ['feste Übergabe', 'asynchron dokumentieren', 'wöchentlich abstimmen'],
    contextCues: [
      'Videokonferenz',
      'Zeitzone',
      'Arbeitsablauf',
      'Kernzeit',
      'Übergabe',
      'abstimmen',
      'dokumentieren',
      'koordinieren',
    ],
    starterPrompts: [
      'Wir sollten nur einen wöchentlichen Termin in der gemeinsamen Kernzeit behalten.',
      'Die übrigen Entscheidungen können wir asynchron dokumentieren.',
      'Für jede Zeitzone würde ich eine feste Übergabe mit klarer Zuständigkeit einführen.',
    ],
    learnerRole: 'koordinátorka distribuovaného týmu',
    coachRole: 'vedoucí projektu',
    icon: 'work',
    accent: 'coral',
  },
  {
    id: 'fact-checking-briefing',
    title: 'Redakční ověření tvrzení',
    eyebrow: 'Roleplay · média a zdroje',
    description: 'Posuď původ tvrzení, pojmenuj chybějící důkaz a navrhni bezpečnou formulaci.',
    goal: 'Rozhodnout o zveřejnění bez zaměnění dosahu zprávy za její důvěryhodnost.',
    level: 'C1',
    minutes: 8,
    turns: 3,
    opening:
      'Die Meldung verbreitet sich schnell, aber bisher beruft sie sich nur auf ein anonymes Konto. Können wir sie veröffentlichen?',
    openingCs:
      'Zpráva se rychle šíří, ale zatím se odvolává jen na anonymní účet. Můžeme ji zveřejnit?',
    focusWords: ['Quelle nachprüfen', 'nicht unabhängig bestätigt', 'laut eigenen Angaben'],
    contextCues: [
      'Quelle',
      'Falschmeldung',
      'Schlagzeile',
      'Reichweite',
      'Bestätigung',
      'nachprüfen',
      'verzerren',
      'glaubwürdig',
    ],
    starterPrompts: [
      'Die hohe Reichweite sagt nichts darüber aus, ob die Quelle glaubwürdig ist.',
      'Wir sollten Ort, Zeitpunkt und Urheber des Bildes unabhängig nachprüfen.',
      'Bis dahin können wir nur schreiben, das anonyme Konto behaupte, über entsprechende Informationen zu verfügen.',
    ],
    learnerRole: 'fact-checkerka',
    coachRole: 'vedoucí vydání',
    icon: 'interview',
    accent: 'mint',
  },
];
