import type { CoachScenario } from './coach.ts';

export const additionalCoachScenarios: CoachScenario[] = [
  {
    id: 'supermarket-checkout',
    title: 'U pokladny v supermarketu',
    eyebrow: 'Roleplay · každodenní nákup',
    description: 'Požádej o tašku, vyber způsob platby a nezapomeň na účtenku.',
    goal: 'Dokončit nákup třemi krátkými a jistými replikami.',
    level: 'A1',
    minutes: 5,
    turns: 3,
    opening: 'Guten Tag! Haben Sie alles gefunden? Brauchen Sie eine Tüte?',
    openingCs: 'Dobrý den! Našla jste všechno? Potřebujete tašku?',
    focusWords: ['eine Tüte', 'mit Karte', 'der Kassenbon'],
    contextCues: ['Supermarkt', 'Kasse', 'Einkauf', 'Tüte', 'Karte', 'bar', 'zahlen', 'Kassenbon'],
    starterPrompts: [
      'Ja, ich brauche eine Tüte, bitte.',
      'Ich möchte mit Karte zahlen.',
      'Den Kassenbon, bitte.',
    ],
    guidedHints: [
      {
        label: 'Taška',
        german: 'Ja, ich brauche eine Tüte, bitte.',
        czech: 'Ano, potřebuji tašku, prosím.',
      },
      {
        label: 'Platba',
        german: 'Ich möchte mit Karte zahlen.',
        czech: 'Chtěla bych platit kartou.',
      },
      {
        label: 'Účtenka',
        german: 'Den Kassenbon, bitte.',
        czech: 'Účtenku, prosím.',
      },
    ],
    learnerRole: 'zákaznice',
    coachRole: 'pokladní',
    icon: 'shopping',
    accent: 'mint',
  },
  {
    id: 'city-bus',
    title: 'Jízda městským autobusem',
    eyebrow: 'Roleplay · doprava po městě',
    description: 'Kup správnou jízdenku, ověř linku a zjisti, kde vystoupit.',
    goal: 'Dostat se autobusem do centra bez tápaní.',
    level: 'A1',
    minutes: 5,
    turns: 3,
    opening: 'Guten Tag. Wohin möchten Sie mit dem Bus fahren?',
    openingCs: 'Dobrý den. Kam chcete jet autobusem?',
    focusWords: ['eine Fahrkarte', 'die Linie', 'aussteigen'],
    contextCues: [
      'Bus',
      'Haltestelle',
      'Stadtzentrum',
      'Museum',
      'Fahrkarte',
      'Linie',
      'fahren',
      'aussteigen',
    ],
    starterPrompts: [
      'Eine Fahrkarte ins Stadtzentrum, bitte.',
      'Ist das die richtige Linie zum Museum?',
      'Wo muss ich aussteigen?',
    ],
    guidedHints: [
      {
        label: 'Jízdenka',
        german: 'Eine Fahrkarte ins Stadtzentrum, bitte.',
        czech: 'Jednu jízdenku do centra, prosím.',
      },
      {
        label: 'Linka',
        german: 'Ist das die richtige Linie zum Museum?',
        czech: 'Je to správná linka k muzeu?',
      },
      {
        label: 'Výstup',
        german: 'Wo muss ich aussteigen?',
        czech: 'Kde musím vystoupit?',
      },
    ],
    learnerRole: 'cestující',
    coachRole: 'řidička autobusu',
    icon: 'train',
    accent: 'sky',
  },
  {
    id: 'new-neighbor',
    title: 'Seznámení se sousedem',
    eyebrow: 'Roleplay · nové bydlení',
    description: 'Představ se, zeptej se na dům a udělej malé přátelské gesto.',
    goal: 'Navázat první jednoduchý kontakt se sousedem.',
    level: 'A1',
    minutes: 5,
    turns: 3,
    opening: 'Hallo, ich bin Tom aus der Wohnung nebenan. Sind Sie neu hier?',
    openingCs: 'Dobrý den, jsem Tom z vedlejšího bytu. Jste tu nová?',
    focusWords: ['Ich wohne', 'Wo ist', 'Möchten Sie'],
    contextCues: ['Nachbar', 'Wohnung', 'Haus', 'Müllraum', 'Kaffee', 'neu', 'wohnen', 'nebenan'],
    starterPrompts: [
      'Ja, ich wohne seit Montag hier.',
      'Wo ist der Müllraum?',
      'Möchten Sie einen Kaffee?',
    ],
    guidedHints: [
      {
        label: 'Představení',
        german: 'Ja, ich wohne seit Montag hier.',
        czech: 'Ano, bydlím tu od pondělí.',
      },
      { label: 'Otázka', german: 'Wo ist der Müllraum?', czech: 'Kde je místnost na odpadky?' },
      {
        label: 'Pozvání',
        german: 'Möchten Sie einen Kaffee?',
        czech: 'Dáte si kávu?',
      },
    ],
    learnerRole: 'nová sousedka',
    coachRole: 'soused Tom',
    icon: 'people',
    accent: 'coral',
  },
  {
    id: 'doctor-appointment',
    title: 'Objednání k lékaři',
    eyebrow: 'Roleplay · telefonát',
    description: 'Požádej o termín, nabídni vhodný čas a potvrď domluvenou hodinu.',
    goal: 'Domluvit návštěvu ordinace bez složitého vysvětlování.',
    level: 'A1',
    minutes: 5,
    turns: 3,
    opening: 'Praxis Dr. Berger, guten Tag. Was kann ich für Sie tun?',
    openingCs: 'Ordinace doktora Bergera, dobrý den. Co pro vás mohu udělat?',
    focusWords: ['einen Termin', 'am Dienstag', 'passt gut'],
    contextCues: [
      'Praxis',
      'Arzt',
      'Termin',
      'Dienstag',
      'Vormittag',
      'Uhr',
      'Zeit',
      'vereinbaren',
    ],
    starterPrompts: [
      'Ich möchte einen Termin vereinbaren.',
      'Am Dienstagvormittag habe ich Zeit.',
      'Ja, zehn Uhr passt gut.',
    ],
    guidedHints: [
      {
        label: 'Důvod hovoru',
        german: 'Ich möchte einen Termin vereinbaren.',
        czech: 'Chtěla bych si domluvit termín.',
      },
      {
        label: 'Možný čas',
        german: 'Am Dienstagvormittag habe ich Zeit.',
        czech: 'V úterý dopoledne mám čas.',
      },
      {
        label: 'Potvrzení',
        german: 'Ja, zehn Uhr passt gut.',
        czech: 'Ano, deset hodin mi vyhovuje.',
      },
    ],
    learnerRole: 'pacientka po telefonu',
    coachRole: 'recepční ordinace',
    icon: 'calendar',
    accent: 'butter',
  },
  {
    id: 'restaurant-reservation',
    title: 'Rezervace v restauraci',
    eyebrow: 'Roleplay · večer venku',
    description: 'Rezervuj stůl, ověř vegetariánskou nabídku a potvrď jméno.',
    goal: 'Zařídit večeři se všemi důležitými detaily.',
    level: 'A2',
    minutes: 6,
    turns: 3,
    opening: 'Restaurant Lindenhof, guten Abend. Wie kann ich Ihnen helfen?',
    openingCs: 'Restaurace Lindenhof, dobrý večer. Jak vám mohu pomoci?',
    focusWords: ['einen Tisch reservieren', 'vegetarische Gerichte', 'auf den Namen'],
    contextCues: [
      'Restaurant',
      'Tisch',
      'Freitag',
      'Personen',
      'Abend',
      'vegetarisch',
      'reservieren',
      'Name',
    ],
    starterPrompts: [
      'Ich möchte für Freitagabend einen Tisch für zwei Personen reservieren.',
      'Haben Sie auch vegetarische Gerichte?',
      'Die Reservierung ist auf den Namen Novák.',
    ],
    guidedHints: [
      {
        label: 'Rezervace',
        german: 'Ich möchte für Freitag einen Tisch für zwei reservieren.',
        czech: 'Chtěla bych na pátek rezervovat stůl pro dva.',
      },
      {
        label: 'Nabídka',
        german: 'Haben Sie auch vegetarische Gerichte?',
        czech: 'Máte také vegetariánská jídla?',
      },
      {
        label: 'Jméno',
        german: 'Die Reservierung ist auf den Namen Novák.',
        czech: 'Rezervace je na jméno Novák.',
      },
    ],
    learnerRole: 'hostka po telefonu',
    coachRole: 'obsluha restaurace',
    icon: 'food',
    accent: 'coral',
  },
  {
    id: 'return-purchase',
    title: 'Vrácení vadného zboží',
    eyebrow: 'Roleplay · reklamace',
    description: 'Popiš závadu, dolož nákup a vyber si výměnu nebo vrácení peněz.',
    goal: 'Vyřídit reklamaci zdvořile a konkrétně.',
    level: 'A2',
    minutes: 6,
    turns: 3,
    opening: 'Guten Tag. Was stimmt mit dem Artikel nicht?',
    openingCs: 'Dobrý den. Co je se zbožím v nepořádku?',
    focusWords: ['funktioniert nicht', 'der Kassenbon', 'Geld zurück'],
    contextCues: [
      'Artikel',
      'Kopfhörer',
      'kaputt',
      'Kassenbon',
      'gestern',
      'umtauschen',
      'zurückgeben',
      'erstatten',
    ],
    starterPrompts: [
      'Diese Kopfhörer funktionieren leider nicht.',
      'Ja, hier ist der Kassenbon von gestern.',
      'Ich möchte lieber mein Geld zurück.',
    ],
    guidedHints: [
      {
        label: 'Závada',
        german: 'Diese Kopfhörer funktionieren leider nicht.',
        czech: 'Tato sluchátka bohužel nefungují.',
      },
      {
        label: 'Doklad',
        german: 'Hier ist der Kassenbon von gestern.',
        czech: 'Tady je včerejší účtenka.',
      },
      {
        label: 'Řešení',
        german: 'Ich möchte lieber mein Geld zurück.',
        czech: 'Raději bych chtěla vrátit peníze.',
      },
    ],
    learnerRole: 'zákaznice',
    coachRole: 'pracovník reklamací',
    icon: 'shopping',
    accent: 'butter',
  },
  {
    id: 'post-office',
    title: 'Balík na poště',
    eyebrow: 'Roleplay · vyřizování',
    description: 'Pošli balík do zahraničí, vyber rychlost a vyžádej si sledovací číslo.',
    goal: 'Odeslat zásilku a vědět, jak ji sledovat.',
    level: 'A2',
    minutes: 6,
    turns: 3,
    opening: 'Guten Tag. Was möchten Sie verschicken?',
    openingCs: 'Dobrý den. Co chcete poslat?',
    focusWords: ['ein Paket', 'Expressversand', 'die Sendungsnummer'],
    contextCues: [
      'Post',
      'Paket',
      'Österreich',
      'Adresse',
      'wiegen',
      'schicken',
      'Express',
      'Sendungsnummer',
    ],
    starterPrompts: [
      'Ich möchte dieses Paket nach Österreich schicken.',
      'Wie viel kostet der Expressversand?',
      'Bekomme ich eine Sendungsnummer?',
    ],
    guidedHints: [
      {
        label: 'Cíl zásilky',
        german: 'Ich möchte dieses Paket nach Österreich schicken.',
        czech: 'Chtěla bych tento balík poslat do Rakouska.',
      },
      {
        label: 'Rychlost',
        german: 'Wie viel kostet der Expressversand?',
        czech: 'Kolik stojí expresní doručení?',
      },
      {
        label: 'Sledování',
        german: 'Bekomme ich eine Sendungsnummer?',
        czech: 'Dostanu sledovací číslo?',
      },
    ],
    learnerRole: 'odesílatelka',
    coachRole: 'pracovnice pošty',
    icon: 'luggage',
    accent: 'sky',
  },
  {
    id: 'bike-rental',
    title: 'Půjčení kola',
    eyebrow: 'Roleplay · aktivní výlet',
    description: 'Vyber dobu půjčení, ověř vybavení a zjisti čas vrácení.',
    goal: 'Půjčit si kolo včetně praktických podmínek.',
    level: 'A2',
    minutes: 6,
    turns: 3,
    opening: 'Hallo! Für wie lange möchten Sie ein Fahrrad mieten?',
    openingCs: 'Dobrý den! Na jak dlouho si chcete půjčit kolo?',
    focusWords: ['für einen Tag', 'ein Fahrradhelm', 'zurückbringen'],
    contextCues: ['Fahrrad', 'mieten', 'Tag', 'Helm', 'Schloss', 'Preis', 'Uhr', 'zurückbringen'],
    starterPrompts: [
      'Ich möchte das Fahrrad für einen Tag mieten.',
      'Ist ein Fahrradhelm im Preis dabei?',
      'Wann muss ich das Fahrrad zurückbringen?',
    ],
    guidedHints: [
      {
        label: 'Doba',
        german: 'Ich möchte das Fahrrad für einen Tag mieten.',
        czech: 'Chtěla bych si kolo půjčit na jeden den.',
      },
      {
        label: 'Vybavení',
        german: 'Ist ein Fahrradhelm im Preis dabei?',
        czech: 'Je v ceně cyklistická helma?',
      },
      {
        label: 'Vrácení',
        german: 'Wann muss ich das Fahrrad zurückbringen?',
        czech: 'Kdy musím kolo vrátit?',
      },
    ],
    learnerRole: 'turistka',
    coachRole: 'pracovník půjčovny',
    icon: 'map',
    accent: 'mint',
  },
  {
    id: 'apartment-viewing',
    title: 'Prohlídka nového bytu',
    eyebrow: 'Roleplay · bydlení',
    description: 'Zjisti celkové náklady, ptej se na okolí a domluv další krok.',
    goal: 'Ověřit si před rozhodnutím tři důležité podmínky nájmu.',
    level: 'B1',
    minutes: 7,
    turns: 3,
    opening: 'Willkommen zur Besichtigung. Was möchten Sie zuerst über die Wohnung wissen?',
    openingCs: 'Vítejte na prohlídce. Co byste chtěla o bytě vědět jako první?',
    focusWords: ['in der Miete enthalten', 'die Umgebung', 'ab wann verfügbar'],
    contextCues: [
      'Besichtigung',
      'Wohnung',
      'Miete',
      'Nebenkosten',
      'Verkehr',
      'Nachbarschaft',
      'verfügbar',
      'Mietvertrag',
    ],
    starterPrompts: [
      'Sind die Nebenkosten in der Miete enthalten?',
      'Wie ist die Verkehrsanbindung in dieser Umgebung?',
      'Ab wann wäre die Wohnung verfügbar?',
    ],
    learnerRole: 'zájemkyně o byt',
    coachRole: 'makléřka',
    icon: 'home',
    accent: 'sky',
  },
  {
    id: 'call-in-sick',
    title: 'Omluva z práce',
    eyebrow: 'Roleplay · pracovní telefonát',
    description: 'Oznam absenci, předej naléhavý úkol a nastav realistické očekávání návratu.',
    goal: 'Vyřešit nepříjemný telefonát zodpovědně a bez zbytečných detailů.',
    level: 'B1',
    minutes: 7,
    turns: 3,
    opening: 'Guten Morgen. Du klingst nicht gut — kannst du heute arbeiten?',
    openingCs: 'Dobré ráno. Nezníš dobře — můžeš dnes pracovat?',
    focusWords: ['mich krankmelden', 'übernehmen', 'voraussichtlich'],
    contextCues: [
      'krank',
      'Arbeit',
      'fehlen',
      'Aufgabe',
      'Kollegin',
      'übergeben',
      'morgen',
      'informieren',
    ],
    starterPrompts: [
      'Ich muss mich für heute krankmelden.',
      'Kann Lea bitte den Kundentermin übernehmen?',
      'Voraussichtlich melde ich mich morgen früh wieder.',
    ],
    learnerRole: 'nemocná kolegyně',
    coachRole: 'vedoucí týmu',
    icon: 'health',
    accent: 'coral',
  },
  {
    id: 'phone-contract',
    title: 'Nejasnost na vyúčtování',
    eyebrow: 'Roleplay · zákaznická linka',
    description: 'Upozorni na vyšší částku, zjisti příčinu a vyjednej vhodnější tarif.',
    goal: 'Proměnit nejasnou stížnost v konkrétní řešení.',
    level: 'B1',
    minutes: 7,
    turns: 3,
    opening: 'Kundenservice, guten Tag. Worum geht es bei Ihrer Rechnung?',
    openingCs: 'Zákaznický servis, dobrý den. Čeho se týká vaše vyúčtování?',
    focusWords: ['höher als sonst', 'woran liegt das', 'den Tarif wechseln'],
    contextCues: [
      'Rechnung',
      'Vertrag',
      'Tarif',
      'Datenvolumen',
      'Gebühr',
      'Monat',
      'wechseln',
      'Kundenservice',
    ],
    starterPrompts: [
      'Meine Rechnung ist diesen Monat viel höher als sonst.',
      'Woran liegt diese zusätzliche Gebühr?',
      'Dann möchte ich in einen passenden Tarif wechseln.',
    ],
    learnerRole: 'zákaznice operátora',
    coachRole: 'pracovník podpory',
    icon: 'discussion',
    accent: 'butter',
  },
  {
    id: 'weekend-planning',
    title: 'Plán na deštivý víkend',
    eyebrow: 'Roleplay · domluva s přáteli',
    description: 'Reaguj na změnu počasí, navrhni alternativu a domluv rozdělení příprav.',
    goal: 'Najít společný plán místo pouhého odmítání návrhů.',
    level: 'B1',
    minutes: 7,
    turns: 3,
    opening: 'Für Samstag ist starker Regen angekündigt. Sollen wir die Wanderung absagen?',
    openingCs: 'Na sobotu hlásí silný déšť. Máme túru zrušit?',
    focusWords: ['stattdessen', 'wenn das Wetter', 'ich kümmere mich um'],
    contextCues: [
      'Wochenende',
      'Regen',
      'Wanderung',
      'Museum',
      'Ausflug',
      'Wetter',
      'planen',
      'Tickets',
    ],
    starterPrompts: [
      'Wir könnten stattdessen das neue Technikmuseum besuchen.',
      'Wenn das Wetter besser wird, machen wir am Sonntag einen kurzen Ausflug.',
      'Ich kümmere mich um die Tickets fürs Museum.',
    ],
    learnerRole: 'kamarádka v plánovací skupině',
    coachRole: 'kamarád',
    icon: 'calendar',
    accent: 'mint',
  },
  {
    id: 'customer-complaint',
    title: 'Uklidnění nespokojeného zákazníka',
    eyebrow: 'Roleplay · řešení konfliktu',
    description: 'Uznej frustraci, ověř fakta a nabídni konkrétní nápravu.',
    goal: 'Převést emotivní stížnost k řešení bez prázdných omluv.',
    level: 'B2',
    minutes: 8,
    turns: 3,
    opening: 'Seit zwei Wochen warte ich auf meine Bestellung. Langsam reicht es mir!',
    openingCs: 'Už dva týdny čekám na objednávku. Už toho mám opravdu dost!',
    focusWords: ['Ich verstehe Ihren Ärger', 'sofort prüfen', 'als Ausgleich'],
    contextCues: [
      'Bestellung',
      'Lieferung',
      'Verspätung',
      'Kundennummer',
      'prüfen',
      'erstatten',
      'Gutschein',
      'Lösung',
    ],
    starterPrompts: [
      'Ich verstehe Ihren Ärger und möchte das sofort für Sie prüfen.',
      'Könnten Sie mir bitte Ihre Bestellnummer nennen?',
      'Als Ausgleich erstatten wir die Versandkosten und liefern morgen.',
    ],
    learnerRole: 'specialistka zákaznické péče',
    coachRole: 'rozzlobený zákazník',
    icon: 'discussion',
    accent: 'coral',
  },
  {
    id: 'remote-work',
    title: 'Návrh práce na dálku',
    eyebrow: 'Roleplay · interní vyjednávání',
    description: 'Předlož přínos, ošetři obavu vedení a navrhni měřitelný pilot.',
    goal: 'Prosadit změnu pomocí argumentů a bezpečného experimentu.',
    level: 'B2',
    minutes: 8,
    turns: 3,
    opening: 'Sie möchten mehr im Homeoffice arbeiten. Wie würde das unserem Team helfen?',
    openingCs: 'Chcete více pracovat z domova. Jak by to našemu týmu pomohlo?',
    focusWords: ['meiner Erfahrung nach', 'die Erreichbarkeit sicherstellen', 'testweise'],
    contextCues: [
      'Homeoffice',
      'Team',
      'Produktivität',
      'Erreichbarkeit',
      'Büro',
      'Zusammenarbeit',
      'Pilotphase',
      'auswerten',
    ],
    starterPrompts: [
      'Meiner Erfahrung nach kann ich zu Hause konzentrierter arbeiten.',
      'Die Erreichbarkeit würde ich durch feste Kernzeiten sicherstellen.',
      'Wir könnten das Modell sechs Wochen lang testweise einführen und danach auswerten.',
    ],
    learnerRole: 'zaměstnankyně s návrhem',
    coachRole: 'vedoucí oddělení',
    icon: 'home',
    accent: 'sky',
  },
  {
    id: 'salary-conversation',
    title: 'Rozhovor o zvýšení mzdy',
    eyebrow: 'Roleplay · kariéra',
    description: 'Dolož přínos výsledky, reaguj na rozpočtovou námitku a domluv další krok.',
    goal: 'Vyjednávat sebevědomě, věcně a bez ultimáta.',
    level: 'B2',
    minutes: 8,
    turns: 3,
    opening:
      'Sie möchten über Ihr Gehalt sprechen. Was hat sich seit unserem letzten Gespräch verändert?',
    openingCs: 'Chcete mluvit o své mzdě. Co se od našeho posledního rozhovoru změnilo?',
    focusWords: ['zusätzliche Verantwortung', 'nachvollziehbar', 'konkrete Kriterien'],
    contextCues: [
      'Gehalt',
      'Verantwortung',
      'Ergebnis',
      'Projekt',
      'Budget',
      'Leistung',
      'Anpassung',
      'Gespräch',
    ],
    starterPrompts: [
      'Ich habe zusätzliche Verantwortung für zwei wichtige Projekte übernommen.',
      'Die Budgetlage ist nachvollziehbar, meine Ergebnisse möchte ich trotzdem berücksichtigt wissen.',
      'Können wir konkrete Kriterien und einen Termin für die Anpassung festhalten?',
    ],
    learnerRole: 'zaměstnankyně',
    coachRole: 'nadřízená',
    icon: 'work',
    accent: 'butter',
  },
  {
    id: 'academic-seminar',
    title: 'Oponentura v semináři',
    eyebrow: 'Roleplay · akademická diskuse',
    description: 'Zpochybni závěr, přesně vymez limit dat a navrhni způsob ověření.',
    goal: 'Nesouhlasit odborně, nuancovaně a konstruktivně.',
    level: 'C1',
    minutes: 8,
    turns: 3,
    opening:
      'Die Studie belegt doch eindeutig, dass die Maßnahme erfolgreich war. Sehen Sie das anders?',
    openingCs: 'Studie přece jednoznačně dokládá, že opatření bylo úspěšné. Vidíte to jinak?',
    focusWords: ['Diese Schlussfolgerung greift zu kurz', 'insofern als', 'überprüfen ließe sich'],
    contextCues: [
      'Studie',
      'Stichprobe',
      'Daten',
      'Schlussfolgerung',
      'Kausalität',
      'Methode',
      'Vergleichsgruppe',
      'überprüfen',
    ],
    starterPrompts: [
      'Diese Schlussfolgerung greift zu kurz, weil die Stichprobe sehr klein war.',
      'Die Daten sind insofern aussagekräftig, als sie einen Trend zeigen, nicht aber Kausalität.',
      'Überprüfen ließe sich die Annahme mit einer größeren Vergleichsgruppe.',
    ],
    learnerRole: 'účastnice odborného semináře',
    coachRole: 'autor studie',
    icon: 'school',
    accent: 'mint',
  },
  {
    id: 'town-hall',
    title: 'Veřejná debata o dopravě',
    eyebrow: 'Roleplay · občanská argumentace',
    description: 'Obhaj omezení aut v centru, uznej legitimní obavu a nabídni pojistku.',
    goal: 'Spojit přesvědčivý postoj s férovou reakcí na protistranu.',
    level: 'C1',
    minutes: 8,
    turns: 3,
    opening:
      'Ein autofreies Zentrum klingt gut, aber schadet es nicht vor allem kleinen Geschäften?',
    openingCs: 'Centrum bez aut zní dobře, ale neuškodí hlavně malým obchodům?',
    focusWords: ['Es wäre verkürzt', 'dem Einwand Rechnung tragen', 'unter der Bedingung'],
    contextCues: [
      'Innenstadt',
      'Verkehr',
      'Geschäfte',
      'Lieferverkehr',
      'Fußgänger',
      'Umsatz',
      'Übergangsphase',
      'Ausnahme',
    ],
    starterPrompts: [
      'Es wäre verkürzt, weniger Autoverkehr automatisch mit weniger Umsatz gleichzusetzen.',
      'Dem Einwand können wir mit festen Zeiten für den Lieferverkehr Rechnung tragen.',
      'Ich unterstütze den Vorschlag unter der Bedingung einer ausgewerteten Übergangsphase.',
    ],
    learnerRole: 'zástupkyně občanské iniciativy',
    coachRole: 'skeptický majitel obchodu',
    icon: 'debate',
    accent: 'coral',
  },
  {
    id: 'team-mediation',
    title: 'Mediace sporu v týmu',
    eyebrow: 'Roleplay · vedení lidí',
    description: 'Odděl pozice od potřeb, shrň shodu a navrhni pravidlo pro další spolupráci.',
    goal: 'Moderovat napětí bez hledání viníka a bez falešného kompromisu.',
    level: 'C1',
    minutes: 8,
    turns: 3,
    opening: 'Wir drehen uns im Kreis: Beide Seiten behaupten, die andere blockiere das Projekt.',
    openingCs: 'Točíme se v kruhu: obě strany tvrdí, že ta druhá blokuje projekt.',
    focusWords: [
      'Wenn ich Sie richtig verstehe',
      'worin Einigkeit besteht',
      'als verbindliche Regel',
    ],
    contextCues: [
      'Konflikt',
      'Team',
      'Priorität',
      'Ressourcen',
      'Entscheidung',
      'Zuständigkeit',
      'Vereinbarung',
      'Zusammenarbeit',
    ],
    starterPrompts: [
      'Wenn ich Sie richtig verstehe, geht es beiden Seiten vor allem um verlässliche Prioritäten.',
      'Einigkeit besteht darin, dass Entscheidungen früher dokumentiert werden müssen.',
      'Lassen Sie uns eine wöchentliche Abstimmung als verbindliche Regel festhalten.',
    ],
    learnerRole: 'moderátorka schůzky',
    coachRole: 'frustrovaný člen týmu',
    icon: 'people',
    accent: 'sky',
  },
];
