import type { CoachScenario } from './coach.ts';

export const nextCoachScenarios: CoachScenario[] = [
  {
    id: 'weather-outfit',
    title: 'Oblečení podle počasí',
    eyebrow: 'Roleplay · počasí a oblečení',
    description: 'Zjisti předpověď, vyber vhodné oblečení a rozhodni, co si vezmeš s sebou.',
    goal: 'Připravit se na deštivý den třemi jednoduchými větami.',
    level: 'A1',
    minutes: 5,
    turns: 3,
    opening: 'Heute ist das Wetter wechselhaft. Was möchtest du draußen machen?',
    openingCs: 'Dnes je proměnlivé počasí. Co chceš dělat venku?',
    focusWords: ['es regnet', 'eine Regenjacke', 'mitnehmen'],
    contextCues: [
      'Wetter',
      'Regen',
      'Sonne',
      'Wind',
      'Jacke',
      'Regenschirm',
      'anziehen',
      'mitnehmen',
      'Spaziergang',
    ],
    starterPrompts: [
      'Ich möchte im Park spazieren gehen.',
      'Wenn es regnet, ziehe ich eine Regenjacke an.',
      'Ich nehme auch einen Regenschirm mit.',
    ],
    guidedHints: [
      {
        label: 'Plán',
        german: 'Ich möchte im Park spazieren gehen.',
        czech: 'Chci se projít v parku.',
      },
      {
        label: 'Oblečení',
        german: 'Ich ziehe eine Regenjacke an.',
        czech: 'Vezmu si nepromokavou bundu.',
      },
      {
        label: 'S sebou',
        german: 'Ich nehme einen Regenschirm mit.',
        czech: 'Vezmu si s sebou deštník.',
      },
    ],
    learnerRole: 'člověk plánující procházku',
    coachRole: 'kamarád sledující předpověď',
    icon: 'luggage',
    accent: 'sky',
  },
  {
    id: 'library-card',
    title: 'První návštěva knihovny',
    eyebrow: 'Roleplay · městské služby',
    description: 'Požádej o průkaz, zjisti výpůjční dobu a najdi správné oddělení.',
    goal: 'Založit si čtenářský průkaz a vypůjčit si první knihu.',
    level: 'A1',
    minutes: 5,
    turns: 3,
    opening: 'Guten Tag! Sind Sie zum ersten Mal in unserer Bibliothek?',
    openingCs: 'Dobrý den! Jste v naší knihovně poprvé?',
    focusWords: ['einen Ausweis beantragen', 'ausleihen', 'wo finde ich'],
    contextCues: [
      'Bibliothek',
      'Bibliotheksausweis',
      'Buch',
      'Adresse',
      'beantragen',
      'ausleihen',
      'zurückgeben',
      'Abteilung',
      'Wochen',
    ],
    starterPrompts: [
      'Ja, ich möchte einen Bibliotheksausweis beantragen.',
      'Wie lange kann ich ein Buch ausleihen?',
      'Wo finde ich die deutschen Kinderbücher?',
    ],
    guidedHints: [
      {
        label: 'Průkaz',
        german: 'Ich möchte einen Bibliotheksausweis beantragen.',
        czech: 'Chci požádat o čtenářský průkaz.',
      },
      {
        label: 'Doba',
        german: 'Wie lange kann ich das Buch ausleihen?',
        czech: 'Na jak dlouho si mohu knihu půjčit?',
      },
      {
        label: 'Oddělení',
        german: 'Wo finde ich die Kinderbücher?',
        czech: 'Kde najdu dětské knihy?',
      },
    ],
    learnerRole: 'nová čtenářka',
    coachRole: 'pracovník knihovny',
    icon: 'school',
    accent: 'butter',
  },
  {
    id: 'dietary-request',
    title: 'Dietní požadavek v restauraci',
    eyebrow: 'Roleplay · jídlo a zdraví',
    description: 'Vysvětli omezení, ověř složení jídla a požádej o vhodnou úpravu.',
    goal: 'Objednat bezpečné jídlo bez neurčitého nebo omluvného vysvětlování.',
    level: 'A2',
    minutes: 6,
    turns: 3,
    opening: 'Guten Abend! Haben Sie schon ein Gericht ausgewählt?',
    openingCs: 'Dobrý večer! Už jste si vybrala jídlo?',
    focusWords: ['ich vertrage kein', 'enthält das', 'ohne zubereiten'],
    contextCues: [
      'Restaurant',
      'Gericht',
      'Zutat',
      'Allergie',
      'Milch',
      'Nüsse',
      'vertragen',
      'enthalten',
      'zubereiten',
    ],
    starterPrompts: [
      'Ich vertrage keine Nüsse und brauche ein Gericht ohne Nüsse.',
      'Enthält die Gemüsesuppe Milch oder Sahne?',
      'Können Sie den Salat bitte ohne Käse zubereiten?',
    ],
    guidedHints: [
      {
        label: 'Omezení',
        german: 'Ich vertrage keine Nüsse.',
        czech: 'Nesnáším ořechy.',
      },
      {
        label: 'Složení',
        german: 'Enthält die Suppe Milch?',
        czech: 'Obsahuje polévka mléko?',
      },
      {
        label: 'Úprava',
        german: 'Können Sie das ohne Käse zubereiten?',
        czech: 'Můžete to připravit bez sýra?',
      },
    ],
    learnerRole: 'hostka s dietním omezením',
    coachRole: 'obsluha restaurace',
    icon: 'food',
    accent: 'mint',
  },
  {
    id: 'missed-connection',
    title: 'Zmeškaný vlakový přípoj',
    eyebrow: 'Roleplay · problém na cestě',
    description: 'Popiš zpoždění, zjisti další spoj a ověř platnost původní jízdenky.',
    goal: 'Najít proveditelnou náhradní cestu po zmeškaném přestupu.',
    level: 'A2',
    minutes: 6,
    turns: 3,
    opening: 'Guten Tag. Wie kann ich Ihnen bei Ihrer Verbindung helfen?',
    openingCs: 'Dobrý den. Jak vám mohu pomoci s vaším spojením?',
    focusWords: ['den Anschluss verpasst', 'nächste Verbindung', 'Fahrkarte gültig'],
    contextCues: [
      'Bahnhof',
      'Anschluss',
      'Verspätung',
      'Verbindung',
      'Fahrkarte',
      'verpassen',
      'umsteigen',
      'gültig',
      'Gleis',
    ],
    starterPrompts: [
      'Mein Zug hatte Verspätung und ich habe den Anschluss verpasst.',
      'Wann fährt die nächste Verbindung nach Leipzig?',
      'Ist meine Fahrkarte auch für diesen Zug gültig?',
    ],
    guidedHints: [
      {
        label: 'Problém',
        german: 'Ich habe den Anschluss verpasst.',
        czech: 'Zmeškala jsem přípoj.',
      },
      {
        label: 'Další spoj',
        german: 'Wann fährt die nächste Verbindung?',
        czech: 'Kdy jede další spoj?',
      },
      {
        label: 'Jízdenka',
        german: 'Ist meine Fahrkarte noch gültig?',
        czech: 'Platí ještě moje jízdenka?',
      },
    ],
    learnerRole: 'cestující po zmeškaném přestupu',
    coachRole: 'informační pracovník',
    icon: 'train',
    accent: 'coral',
  },
  {
    id: 'volunteer-event',
    title: 'Organizace dobrovolnické akce',
    eyebrow: 'Roleplay · komunita',
    description: 'Upřesni potřeby akce, rozděl úkoly a domluv záložní plán.',
    goal: 'Proměnit nápad na sousedskou akci v konkrétní rozdělení práce.',
    level: 'B1',
    minutes: 7,
    turns: 3,
    opening:
      'Für die Aufräumaktion am Samstag fehlen uns noch ein klarer Plan und Helfer. Womit beginnen wir?',
    openingCs: 'Pro sobotní úklidovou akci nám stále chybí jasný plán a pomocníci. Čím začneme?',
    focusWords: ['Aufgaben verteilen', 'sich kümmern um', 'falls es regnet'],
    contextCues: [
      'Aufräumaktion',
      'Freiwillige',
      'Handschuhe',
      'Müllsäcke',
      'Treffpunkt',
      'verteilen',
      'organisieren',
      'Regen',
      'Gemeindezentrum',
    ],
    starterPrompts: [
      'Zuerst sollten wir die Aufgaben unter den Freiwilligen verteilen.',
      'Ich kümmere mich um Handschuhe, Müllsäcke und den Treffpunkt.',
      'Falls es stark regnet, verschieben wir die Aktion auf Sonntag.',
    ],
    learnerRole: 'koordinátorka dobrovolníků',
    coachRole: 'člen organizačního týmu',
    icon: 'people',
    accent: 'mint',
  },
  {
    id: 'study-project-presentation',
    title: 'Příprava týmové prezentace',
    eyebrow: 'Roleplay · studijní projekt',
    description: 'Vymez hlavní otázku, navrhni strukturu a domluv společnou zkoušku.',
    goal: 'Sestavit s týmem srozumitelnou prezentaci s termínem nácviku.',
    level: 'B1',
    minutes: 7,
    turns: 3,
    opening: 'Unsere Präsentation ist nächste Woche. Welche Leitfrage soll im Mittelpunkt stehen?',
    openingCs: 'Naše prezentace je příští týden. Která hlavní otázka má stát v centru pozornosti?',
    focusWords: ['im Mittelpunkt stehen', 'in drei Teile gliedern', 'gemeinsam proben'],
    contextCues: [
      'Präsentation',
      'Leitfrage',
      'Gliederung',
      'Beispiel',
      'Folie',
      'Quelle',
      'gliedern',
      'proben',
      'Feedback',
    ],
    starterPrompts: [
      'Im Mittelpunkt soll die Frage nach den Folgen für Studierende stehen.',
      'Wir können die Präsentation in Ursachen, Beispiele und Lösungen gliedern.',
      'Am Montag sollten wir gemeinsam proben und uns Feedback geben.',
    ],
    learnerRole: 'členka studijního týmu',
    coachRole: 'spolužák',
    icon: 'presentation',
    accent: 'sky',
  },
  {
    id: 'energy-saving-proposal',
    title: 'Návrh na úsporu energie',
    eyebrow: 'Roleplay · udržitelnost',
    description: 'Stanov prioritu, dolož očekávaný přínos a reaguj na obavu z nákladů.',
    goal: 'Obhájit realistické energetické opatření před správou budovy.',
    level: 'B2',
    minutes: 8,
    turns: 3,
    opening:
      'Sie schlagen Investitionen in die Energieeffizienz vor. Welche Maßnahme hätte für Sie Priorität?',
    openingCs:
      'Navrhujete investice do energetické účinnosti. Které opatření by pro vás mělo prioritu?',
    focusWords: ['Vorrang haben', 'dadurch ließe sich', 'amortisieren'],
    contextCues: [
      'Energieverbrauch',
      'Dämmung',
      'Heizung',
      'Beleuchtung',
      'Investition',
      'Einsparung',
      'Kosten',
      'amortisieren',
      'Verbrauchsdaten',
    ],
    starterPrompts: [
      'Eine bessere Dämmung sollte Vorrang haben, weil dort die größten Verluste entstehen.',
      'Dadurch ließe sich der jährliche Energieverbrauch deutlich senken.',
      'Die Investition ist hoch, dürfte sich aber innerhalb von sechs Jahren amortisieren.',
    ],
    learnerRole: 'autorka energetického návrhu',
    coachRole: 'správce budovy',
    icon: 'home',
    accent: 'butter',
  },
  {
    id: 'privacy-incident-response',
    title: 'Reakce na incident s daty',
    eyebrow: 'Roleplay · digitální soukromí',
    description:
      'Odděl ověřená fakta, navrhni okamžitou ochranu a stanov transparentní komunikaci.',
    goal: 'Koordinovat první reakci na možné neoprávněné zpřístupnění údajů.',
    level: 'B2',
    minutes: 8,
    turns: 3,
    opening:
      'Wir haben ungewöhnliche Zugriffe auf Kundendaten entdeckt. Was wissen wir bereits sicher?',
    openingCs: 'Zjistili jsme neobvyklé přístupy k zákaznickým údajům. Co už víme jistě?',
    focusWords: ['nach aktuellem Stand', 'Zugriff sperren', 'Betroffene informieren'],
    contextCues: [
      'Kundendaten',
      'Zugriff',
      'Konto',
      'Protokoll',
      'Passwort',
      'sperren',
      'untersuchen',
      'informieren',
      'Betroffene',
    ],
    starterPrompts: [
      'Nach aktuellem Stand wurde auf zwölf Konten ungewöhnlich oft zugegriffen.',
      'Wir sollten die betroffenen Zugänge sperren und die Protokolle sichern.',
      'Sobald der Umfang bestätigt ist, müssen wir die Betroffenen transparent informieren.',
    ],
    learnerRole: 'členka incidentního týmu',
    coachRole: 'vedoucí ochrany dat',
    icon: 'work',
    accent: 'coral',
  },
  {
    id: 'research-ethics-review',
    title: 'Etické posouzení výzkumu',
    eyebrow: 'Roleplay · výzkumná etika',
    description: 'Zvaž přínos a riziko studie, zpochybni souhlas a navrhni ochranné podmínky.',
    goal: 'Formulovat podmíněné etické stanovisko bez předstírání jednoduché odpovědi.',
    level: 'C1',
    minutes: 8,
    turns: 3,
    opening:
      'Der wissenschaftliche Nutzen ist plausibel. Wie beurteilen Sie die Risiken für die Teilnehmenden?',
    openingCs: 'Vědecký přínos je věrohodný. Jak hodnotíte rizika pro účastníky?',
    focusWords: ['nicht außer Acht lassen', 'informierte Einwilligung', 'unter der Bedingung'],
    contextCues: [
      'Studie',
      'Teilnehmende',
      'Risiko',
      'Nutzen',
      'Einwilligung',
      'Datenschutz',
      'Belastung',
      'abwägen',
      'Ethikkommission',
    ],
    starterPrompts: [
      'Wir dürfen die psychische Belastung der Teilnehmenden nicht außer Acht lassen.',
      'Die informierte Einwilligung ist nur glaubwürdig, wenn ein Rückzug jederzeit folgenlos bleibt.',
      'Ich würde die Studie unter der Bedingung einer unabhängigen Ansprechstelle genehmigen.',
    ],
    learnerRole: 'členka etické komise',
    coachRole: 'vedoucí výzkumného projektu',
    icon: 'discussion',
    accent: 'mint',
  },
  {
    id: 'policy-consultation',
    title: 'Veřejná konzultace návrhu',
    eyebrow: 'Roleplay · veřejná politika',
    description: 'Vymez problém návrhu, zvaž protichůdné zájmy a formuluj ověřitelný kompromis.',
    goal: 'Přetavit obecnou námitku do konkrétní podmínky pro rozhodnutí.',
    level: 'C1',
    minutes: 8,
    turns: 3,
    opening:
      'Der Entwurf soll den Verkehr reduzieren, stößt aber bei Gewerbetreibenden auf Widerstand. Wo liegt der Kernkonflikt?',
    openingCs:
      'Návrh má omezit dopravu, ale naráží na odpor podnikatelů. Kde leží jádro konfliktu?',
    focusWords: ['Zielkonflikt', 'berechtigte Einwände', 'anhand von Kriterien'],
    contextCues: [
      'Entwurf',
      'Verkehr',
      'Gewerbe',
      'Anwohner',
      'Lieferzeiten',
      'Ausnahme',
      'Kriterium',
      'Übergangsphase',
      'auswerten',
    ],
    starterPrompts: [
      'Der Zielkonflikt liegt zwischen weniger Verkehr und verlässlichen Liefermöglichkeiten.',
      'Die Einwände des Gewerbes sind berechtigt, rechtfertigen aber keine unbegrenzte Ausnahme.',
      'Nach einer sechsmonatigen Übergangsphase sollten wir die Wirkung anhand klarer Kriterien auswerten.',
    ],
    learnerRole: 'účastnice veřejné konzultace',
    coachRole: 'moderátor odborného slyšení',
    icon: 'debate',
    accent: 'sky',
  },
];
