import type { Article, CefrLevel, LexemeKind, VerbForms } from '../types.ts';
import type { CourseWord } from './path.ts';

export type CourseChapterContentSupplement = {
  words: CourseWord[];
  grammarLessonIds: string[];
  coachScenarioIds: string[];
};

function noun(
  german: string,
  czech: string,
  article: Article,
  plural: string,
  cefr: CefrLevel,
  exampleDe: string,
  exampleCs: string,
  collocation: string,
  acceptedCzech: string[] = [],
): CourseWord {
  return {
    german,
    czech,
    kind: 'noun',
    article,
    plural,
    cefr,
    exampleDe,
    exampleCs,
    contexts: [exampleDe],
    collocations: [collocation],
    acceptedCzech,
  };
}

function verb(
  german: string,
  czech: string,
  cefr: CefrLevel,
  forms: [string, string, string, VerbForms['auxiliary']],
  exampleDe: string,
  exampleCs: string,
  collocation: string,
  acceptedCzech: string[] = [],
): CourseWord {
  return {
    german,
    czech,
    kind: 'verb',
    cefr,
    verbForms: {
      thirdPerson: forms[0],
      preterite: forms[1],
      participle: forms[2],
      auxiliary: forms[3],
    },
    exampleDe,
    exampleCs,
    contexts: [exampleDe],
    collocations: [collocation],
    acceptedCzech,
  };
}

function term(
  german: string,
  czech: string,
  kind: Exclude<LexemeKind, 'noun' | 'verb'>,
  cefr: CefrLevel,
  exampleDe: string,
  exampleCs: string,
  collocation: string,
  acceptedCzech: string[] = [],
): CourseWord {
  return {
    german,
    czech,
    kind,
    cefr,
    exampleDe,
    exampleCs,
    contexts: [exampleDe],
    collocations: [collocation],
    acceptedCzech,
  };
}

export const courseChapterContentSupplements: Record<string, CourseChapterContentSupplement> = {
  'chapter-12-cafe-bakery': {
    grammarLessonIds: ['compound-noun-gender'],
    coachScenarioIds: ['bakery-preorder'],
    words: [
      noun(
        'Bäckerei',
        'pekárna',
        'die',
        'Bäckereien',
        'A1',
        'Die Bäckerei öffnet um sechs Uhr.',
        'Pekárna otevírá v šest hodin.',
        'in der Bäckerei einkaufen',
      ),
      noun(
        'Brotsorte',
        'druh chleba',
        'die',
        'Brotsorten',
        'A1',
        'Welche Brotsorte ist heute frisch?',
        'Který druh chleba je dnes čerstvý?',
        'eine dunkle Brotsorte',
      ),
      noun(
        'Croissant',
        'croissant',
        'das',
        'Croissants',
        'A1',
        'Ich nehme ein Croissant zum Frühstück.',
        'Dám si k snídani croissant.',
        'ein Croissant nehmen',
      ),
      noun(
        'Brezel',
        'preclík',
        'die',
        'Brezeln',
        'A1',
        'Die Brezel kostet zwei Euro.',
        'Preclík stojí dvě eura.',
        'eine Brezel mitnehmen',
      ),
      noun(
        'Zimtschnecke',
        'skořicový šnek',
        'die',
        'Zimtschnecken',
        'A1',
        'Die Zimtschnecke ist noch warm.',
        'Skořicový šnek je ještě teplý.',
        'eine warme Zimtschnecke',
      ),
      verb(
        'mitnehmen',
        'vzít s sebou',
        'A1',
        ['nimmt mit', 'nahm mit', 'mitgenommen', 'haben'],
        'Ich nehme das Brot mit.',
        'Vezmu si chléb s sebou.',
        'etwas zum Mitnehmen',
      ),
      verb(
        'empfehlen',
        'doporučit',
        'A1',
        ['empfiehlt', 'empfahl', 'empfohlen', 'haben'],
        'Welche Brotsorte empfehlen Sie?',
        'Který druh chleba doporučujete?',
        'jemandem etwas empfehlen',
      ),
      verb(
        'einpacken',
        'zabalit',
        'A1',
        ['packt ein', 'packte ein', 'eingepackt', 'haben'],
        'Können Sie die Brezel bitte einpacken?',
        'Můžete prosím preclík zabalit?',
        'ein Gebäck einpacken',
      ),
      term(
        'frisch',
        'čerstvý',
        'adjective',
        'A1',
        'Das Brot ist ganz frisch.',
        'Chléb je úplně čerstvý.',
        'frisch gebacken',
      ),
      term(
        'süß',
        'sladký',
        'adjective',
        'A1',
        'Das Croissant ist nicht zu süß.',
        'Croissant není příliš sladký.',
        'etwas Süßes',
      ),
    ],
  },
  'chapter-16-health': {
    grammarLessonIds: ['seit-versus-vor'],
    coachScenarioIds: ['medical-examination'],
    words: [
      noun(
        'Arztpraxis',
        'lékařská ordinace',
        'die',
        'Arztpraxen',
        'A2',
        'Die Arztpraxis ist im zweiten Stock.',
        'Lékařská ordinace je ve druhém patře.',
        'eine Arztpraxis anrufen',
      ),
      noun(
        'Rezept',
        'recept',
        'das',
        'Rezepte',
        'A2',
        'Die Ärztin schreibt mir ein Rezept.',
        'Lékařka mi píše recept.',
        'ein Rezept ausstellen',
      ),
      noun(
        'Untersuchung',
        'vyšetření',
        'die',
        'Untersuchungen',
        'A2',
        'Die Untersuchung dauert nur zehn Minuten.',
        'Vyšetření trvá jen deset minut.',
        'eine Untersuchung machen',
      ),
      noun(
        'Apotheke',
        'lékárna',
        'die',
        'Apotheken',
        'A2',
        'Das Medikament bekomme ich in der Apotheke.',
        'Lék dostanu v lékárně.',
        'in die Apotheke gehen',
      ),
      noun(
        'Sprechstunde',
        'ordinační hodina',
        'die',
        'Sprechstunden',
        'A2',
        'Die Sprechstunde beginnt um neun Uhr.',
        'Ordinační hodina začíná v devět.',
        'in die Sprechstunde kommen',
      ),
      verb(
        'untersuchen',
        'vyšetřit',
        'A2',
        ['untersucht', 'untersuchte', 'untersucht', 'haben'],
        'Die Ärztin untersucht meinen Hals.',
        'Lékařka mi vyšetřuje krk.',
        'einen Patienten untersuchen',
      ),
      verb(
        'verschreiben',
        'předepsat',
        'A2',
        ['verschreibt', 'verschrieb', 'verschrieben', 'haben'],
        'Der Arzt verschreibt mir Tabletten.',
        'Lékař mi předepisuje tablety.',
        'jemandem ein Medikament verschreiben',
      ),
      verb(
        'behandeln',
        'léčit',
        'A2',
        ['behandelt', 'behandelte', 'behandelt', 'haben'],
        'Diese Salbe behandelt die Entzündung.',
        'Tato mast léčí zánět.',
        'eine Krankheit behandeln',
      ),
      term(
        'gesund',
        'zdravý',
        'adjective',
        'A2',
        'Nach einer Woche bin ich wieder gesund.',
        'Po týdnu jsem zase zdravá.',
        'gesund werden',
      ),
      term(
        'nüchtern',
        'nalačno',
        'adjective',
        'A2',
        'Zur Untersuchung muss ich nüchtern kommen.',
        'Na vyšetření musím přijít nalačno.',
        'nüchtern zur Untersuchung kommen',
      ),
    ],
  },
  'chapter-19-study-goals': {
    grammarLessonIds: ['ohne-anstatt-zu'],
    coachScenarioIds: ['study-planning'],
    words: [
      noun(
        'Prüfung',
        'zkouška',
        'die',
        'Prüfungen',
        'B1',
        'Die Prüfung findet Ende Mai statt.',
        'Zkouška se koná na konci května.',
        'eine Prüfung bestehen',
      ),
      noun(
        'Zeitplan',
        'časový plán',
        'der',
        'Zeitpläne',
        'B1',
        'Mein Zeitplan enthält drei Lernphasen.',
        'Můj časový plán obsahuje tři fáze učení.',
        'einen Zeitplan erstellen',
      ),
      noun(
        'Lernmethode',
        'metoda učení',
        'die',
        'Lernmethoden',
        'B1',
        'Diese Lernmethode passt gut zu meinem Ziel.',
        'Tato metoda učení se dobře hodí k mému cíli.',
        'eine Lernmethode ausprobieren',
      ),
      noun(
        'Notiz',
        'poznámka',
        'die',
        'Notizen',
        'B1',
        'Ich schreibe zu jedem Fehler eine kurze Notiz.',
        'Ke každé chybě si píšu krátkou poznámku.',
        'Notizen machen',
      ),
      noun(
        'Etappe',
        'dílčí etapa',
        'die',
        'Etappen',
        'B1',
        'Nach jeder Etappe überprüfe ich meinen Fortschritt.',
        'Po každé etapě kontroluji svůj pokrok.',
        'ein Ziel in Etappen teilen',
      ),
      verb(
        'anwenden',
        'použít',
        'B1',
        ['wendet an', 'wandte an', 'angewandt', 'haben'],
        'Ich wende die neue Regel in eigenen Sätzen an.',
        'Nové pravidlo používám ve vlastních větách.',
        'eine Methode anwenden',
      ),
      verb(
        'überprüfen',
        'zkontrolovat',
        'B1',
        ['überprüft', 'überprüfte', 'überprüft', 'haben'],
        'Am Freitag überprüfe ich meinen Zeitplan.',
        'V pátek kontroluji svůj časový plán.',
        'den Fortschritt überprüfen',
      ),
      verb(
        'einteilen',
        'rozvrhnout',
        'B1',
        ['teilt ein', 'teilte ein', 'eingeteilt', 'haben'],
        'Ich teile den Lernstoff in kleine Etappen ein.',
        'Rozvrhuji si učivo do malých etap.',
        'die Zeit sinnvoll einteilen',
      ),
      term(
        'regelmäßig',
        'pravidelně',
        'other',
        'B1',
        'Ich wiederhole die neuen Wörter regelmäßig.',
        'Nová slova si pravidelně opakuji.',
        'regelmäßig üben',
      ),
      term(
        'langfristig',
        'dlouhodobě',
        'other',
        'B1',
        'Langfristig möchte ich sicherer sprechen.',
        'Dlouhodobě chci mluvit jistěji.',
        'langfristig planen',
      ),
    ],
  },
  'chapter-24-remote-work': {
    grammarLessonIds: ['man-versus-passive'],
    coachScenarioIds: ['hybrid-team-coordination'],
    words: [
      noun(
        'Videokonferenz',
        'videokonference',
        'die',
        'Videokonferenzen',
        'B2',
        'Die Videokonferenz beginnt wegen der Zeitzone später.',
        'Videokonference začíná kvůli časovému pásmu později.',
        'an einer Videokonferenz teilnehmen',
      ),
      noun(
        'Arbeitsablauf',
        'pracovní postup',
        'der',
        'Arbeitsabläufe',
        'B2',
        'Der neue Arbeitsablauf reduziert unnötige Meetings.',
        'Nový pracovní postup omezuje zbytečné schůzky.',
        'einen Arbeitsablauf verbessern',
      ),
      noun(
        'Zeitzone',
        'časové pásmo',
        'die',
        'Zeitzonen',
        'B2',
        'Unser Team arbeitet in drei Zeitzonen.',
        'Náš tým pracuje ve třech časových pásmech.',
        'über mehrere Zeitzonen hinweg',
      ),
      noun(
        'Ausstattung',
        'vybavení',
        'die',
        'Ausstattungen',
        'B2',
        'Eine gute technische Ausstattung ist im Homeoffice entscheidend.',
        'Dobré technické vybavení je při práci z domova zásadní.',
        'technische Ausstattung bereitstellen',
      ),
      noun(
        'Richtlinie',
        'směrnice',
        'die',
        'Richtlinien',
        'B2',
        'Die Richtlinie regelt unsere Erreichbarkeit.',
        'Směrnice upravuje naši dostupnost.',
        'eine Richtlinie einführen',
      ),
      verb(
        'abstimmen',
        'sladit',
        'B2',
        ['stimmt ab', 'stimmte ab', 'abgestimmt', 'haben'],
        'Wir stimmen die Kernzeiten im Team ab.',
        'V týmu slaďujeme společnou pracovní dobu.',
        'Termine miteinander abstimmen',
      ),
      verb(
        'dokumentieren',
        'zdokumentovat',
        'B2',
        ['dokumentiert', 'dokumentierte', 'dokumentiert', 'haben'],
        'Alle Entscheidungen werden schriftlich dokumentiert.',
        'Všechna rozhodnutí se písemně dokumentují.',
        'eine Entscheidung dokumentieren',
      ),
      verb(
        'koordinieren',
        'koordinovat',
        'B2',
        ['koordiniert', 'koordinierte', 'koordiniert', 'haben'],
        'Eine Person koordiniert die Übergabe zwischen den Zeitzonen.',
        'Jedna osoba koordinuje předávání práce mezi časovými pásmy.',
        'ein verteiltes Team koordinieren',
      ),
      term(
        'hybrid',
        'hybridní',
        'adjective',
        'B2',
        'Das Team arbeitet an zwei Tagen hybrid.',
        'Tým pracuje dva dny hybridně.',
        'hybrid arbeiten',
      ),
      term(
        'effizient',
        'efektivní',
        'adjective',
        'B2',
        'Asynchrone Updates machen die Zusammenarbeit effizienter.',
        'Asynchronní aktualizace zefektivňují spolupráci.',
        'effizient zusammenarbeiten',
      ),
    ],
  },
  'chapter-28-media-indirect-speech': {
    grammarLessonIds: ['source-attribution-phrases'],
    coachScenarioIds: ['fact-checking-briefing'],
    words: [
      noun(
        'Quelle',
        'zdroj',
        'die',
        'Quellen',
        'C1',
        'Die Quelle wird im Artikel nicht genannt.',
        'Zdroj není v článku uveden.',
        'eine Quelle überprüfen',
      ),
      noun(
        'Schlagzeile',
        'titulek',
        'die',
        'Schlagzeilen',
        'C1',
        'Die Schlagzeile verkürzt die eigentliche Aussage.',
        'Titulek zjednodušuje původní sdělení.',
        'eine irreführende Schlagzeile',
      ),
      noun(
        'Reichweite',
        'dosah',
        'die',
        'Reichweiten',
        'C1',
        'Die Falschmeldung erreichte eine enorme Reichweite.',
        'Nepravdivá zpráva dosáhla obrovského dosahu.',
        'eine hohe Reichweite erzielen',
      ),
      noun(
        'Falschmeldung',
        'nepravdivá zpráva',
        'die',
        'Falschmeldungen',
        'C1',
        'Die Redaktion korrigierte die Falschmeldung sofort.',
        'Redakce nepravdivou zprávu ihned opravila.',
        'eine Falschmeldung korrigieren',
      ),
      noun(
        'Pressekonferenz',
        'tisková konference',
        'die',
        'Pressekonferenzen',
        'C1',
        'Auf der Pressekonferenz blieben zwei Fragen offen.',
        'Na tiskové konferenci zůstaly dvě otázky nezodpovězené.',
        'auf einer Pressekonferenz erklären',
      ),
      verb(
        'nachprüfen',
        'ověřit',
        'C1',
        ['prüft nach', 'prüfte nach', 'nachgeprüft', 'haben'],
        'Die Zahlen lassen sich anhand der Quelle nachprüfen.',
        'Čísla lze ověřit podle zdroje.',
        'eine Behauptung nachprüfen',
      ),
      verb(
        'verzerren',
        'zkreslit',
        'C1',
        ['verzerrt', 'verzerrte', 'verzerrt', 'haben'],
        'Der fehlende Kontext verzerrt die Aussage.',
        'Chybějící kontext zkresluje sdělení.',
        'ein Zitat verzerren',
      ),
      verb(
        'verbreiten',
        'šířit',
        'C1',
        ['verbreitet', 'verbreitete', 'verbreitet', 'haben'],
        'Mehrere Konten verbreiteten dieselbe Falschmeldung.',
        'Několik účtů šířilo stejnou nepravdivou zprávu.',
        'Informationen verbreiten',
      ),
      term(
        'glaubwürdig',
        'důvěryhodný',
        'adjective',
        'C1',
        'Die Erklärung wirkt nur mit überprüfbaren Daten glaubwürdig.',
        'Vysvětlení působí důvěryhodně jen s ověřitelnými daty.',
        'glaubwürdig erscheinen',
      ),
      term(
        'irreführend',
        'zavádějící',
        'adjective',
        'C1',
        'Die Grafik ist ohne Skalenangabe irreführend.',
        'Graf je bez uvedení měřítka zavádějící.',
        'eine irreführende Darstellung',
      ),
    ],
  },
};

export const supplementalCourseWords = Object.values(courseChapterContentSupplements).flatMap(
  (supplement) => supplement.words,
);
