import { noun, term, verb, type FoundationWord } from './course-foundation-words.ts';

/** Frequent words needed to make the existing A1 situations usable independently. */
export const everydayFoundations: Record<string, FoundationWord[]> = {
  'chapter-31-first-introduction': [
    verb(
      'sprechen',
      'mluvit',
      'to speak',
      ['spricht', 'sprach', 'gesprochen', 'haben'],
      'Ich spreche ein bisschen Deutsch.',
      'Mluvím trochu německy.',
    ),
    noun(
      'Deutsch',
      'němčina',
      'German',
      'das',
      '—',
      'Ich lerne Deutsch in der Schule.',
      'Ve škole se učím němčinu.',
    ),
    noun(
      'Land',
      'země',
      'country',
      'das',
      'Länder',
      'Aus welchem Land kommst du?',
      'Ze které země pocházíš?',
    ),
  ],
  'chapter-32-find-the-right-page': [
    verb(
      'schreiben',
      'psát',
      'to write',
      ['schreibt', 'schrieb', 'geschrieben', 'haben'],
      'Schreib bitte deinen Namen auf das Blatt.',
      'Napiš prosím na list své jméno.',
    ),
    noun(
      'Stift',
      'psací potřeba; tužka; pero',
      'pen; pencil',
      'der',
      'Stifte',
      'Hast du einen Stift für mich?',
      'Máš pro mě tužku?',
    ),
    term(
      'null',
      'nula',
      'zero',
      'Die Telefonnummer beginnt mit null.',
      'Telefonní číslo začíná nulou.',
    ),
  ],
  'chapter-33-ask-for-repetition': [
    verb(
      'verstehen',
      'rozumět; pochopit',
      'to understand',
      ['versteht', 'verstand', 'verstanden', 'haben'],
      'Ich verstehe die Frage nicht.',
      'Nerozumím otázce.',
    ),
    verb(
      'fragen',
      'ptát se; zeptat se',
      'to ask',
      ['fragt', 'fragte', 'gefragt', 'haben'],
      'Darf ich noch etwas fragen?',
      'Můžu se ještě na něco zeptat?',
    ),
    noun(
      'Antwort',
      'odpověď',
      'answer',
      'die',
      'Antworten',
      'Kannst du die Antwort bitte wiederholen?',
      'Můžeš prosím zopakovat odpověď?',
    ),
  ],
  'chapter-34-simple-order': [
    verb(
      'trinken',
      'pít',
      'to drink',
      ['trinkt', 'trank', 'getrunken', 'haben'],
      'Was möchtest du trinken?',
      'Co bys chtěla pít?',
    ),
    noun(
      'Kaffee',
      'káva',
      'coffee',
      'der',
      'Kaffees',
      'Ich nehme einen Kaffee mit Milch.',
      'Dám si kávu s mlékem.',
    ),
    noun(
      'Saft',
      'šťáva; džus',
      'juice',
      'der',
      'Säfte',
      'Ein Glas Saft, bitte.',
      'Jednu sklenici džusu, prosím.',
    ),
  ],
  'chapter-35-price-and-payment': [
    term('elf', 'jedenáct', 'eleven', 'Die Rechnung macht elf Euro.', 'Účet je na jedenáct eur.'),
    term(
      'zwölf',
      'dvanáct',
      'twelve',
      'Zusammen kostet das zwölf Euro.',
      'Dohromady to stojí dvanáct eur.',
    ),
    noun('Geld', 'peníze', 'money', 'das', '—', 'Ich habe das Geld dabei.', 'Mám peníze u sebe.'),
  ],
  'chapter-36-takeaway-order': [
    noun(
      'Hunger',
      'hlad',
      'hunger',
      'der',
      '—',
      'Ich habe Hunger und nehme ein Brötchen.',
      'Mám hlad a vezmu si housku.',
    ),
    { ...term('hungrig', 'hladový', 'hungry', 'Ich bin hungrig.', 'Mám hlad.'), kind: 'adjective' },
    noun(
      'Banane',
      'banán',
      'banana',
      'die',
      'Bananen',
      'Ich nehme noch eine Banane mit.',
      'Vezmu si s sebou ještě banán.',
    ),
  ],
  'chapter-37-repair-the-order': [
    {
      ...term(
        'richtig',
        'správný; správně',
        'correct; right',
        'Ist meine Bestellung richtig?',
        'Je moje objednávka správně?',
      ),
      kind: 'adjective',
    },
    {
      ...term(
        'falsch',
        'chybný; špatný; špatně',
        'wrong; incorrect',
        'Das ist leider die falsche Bestellung.',
        'To je bohužel špatná objednávka.',
      ),
      kind: 'adjective',
    },
    term(
      'noch',
      'ještě',
      'still; another',
      'Ich möchte noch einen Tee.',
      'Chtěla bych ještě jeden čaj.',
    ),
  ],
  'chapter-38-morning-time': [
    verb(
      'schlafen',
      'spát',
      'to sleep',
      ['schläft', 'schlief', 'geschlafen', 'haben'],
      'Am Sonntag schlafe ich länger.',
      'V neděli spím déle.',
    ),
    term('früh', 'brzy', 'early', 'Ich stehe morgen früh auf.', 'Zítra vstávám brzy.'),
    term(
      'spät',
      'pozdě',
      'late',
      'Heute komme ich spät zur Schule.',
      'Dnes přijdu do školy pozdě.',
    ),
  ],
  'chapter-39-who-lives-here': [
    noun(
      'Kind',
      'dítě',
      'child',
      'das',
      'Kinder',
      'In der Familie leben zwei Kinder.',
      'V rodině žijí dvě děti.',
    ),
    noun(
      'Tochter',
      'dcera',
      'daughter',
      'die',
      'Töchter',
      'Ihre Tochter wohnt in Prag.',
      'Její dcera bydlí v Praze.',
    ),
    noun(
      'Sohn',
      'syn',
      'son',
      'der',
      'Söhne',
      'Unser Sohn geht schon zur Schule.',
      'Náš syn už chodí do školy.',
    ),
  ],
  'chapter-40-whose-is-it': [
    noun(
      'Tisch',
      'stůl',
      'table',
      'der',
      'Tische',
      'Der Schlüssel liegt auf dem Tisch.',
      'Klíč leží na stole.',
    ),
    noun(
      'Stuhl',
      'židle',
      'chair',
      'der',
      'Stühle',
      'Ist dieser Stuhl frei?',
      'Je tato židle volná?',
    ),
    noun(
      'Bett',
      'postel',
      'bed',
      'das',
      'Betten',
      'Das Bett gehört meiner Schwester.',
      'Postel patří mé sestře.',
    ),
  ],
  'chapter-41-evening-together': [
    verb(
      'kochen',
      'vařit',
      'to cook',
      ['kocht', 'kochte', 'gekocht', 'haben'],
      'Heute kochen wir gemeinsam.',
      'Dnes vaříme společně.',
    ),
    verb(
      'sehen',
      'vidět; sledovat',
      'to see; to watch',
      ['sieht', 'sah', 'gesehen', 'haben'],
      'Wir sehen am Abend einen Film.',
      'Večer se díváme na film.',
    ),
    verb(
      'hören',
      'slyšet; poslouchat',
      'to hear; to listen to',
      ['hört', 'hörte', 'gehört', 'haben'],
      'Ich höre gern Musik.',
      'Ráda poslouchám hudbu.',
    ),
  ],
  'chapter-42-route-to-destination': [
    verb(
      'gehen',
      'jít',
      'to go; to walk',
      ['geht', 'ging', 'gegangen', 'sein'],
      'Gehen Sie hier nach links.',
      'Tady jděte doleva.',
    ),
    verb(
      'suchen',
      'hledat',
      'to look for',
      ['sucht', 'suchte', 'gesucht', 'haben'],
      'Ich suche den Bahnhof.',
      'Hledám nádraží.',
    ),
    verb(
      'finden',
      'najít',
      'to find',
      ['findet', 'fand', 'gefunden', 'haben'],
      'Wo finde ich die Haltestelle?',
      'Kde najdu zastávku?',
    ),
  ],
  'chapter-43-right-stop': [
    verb(
      'warten',
      'čekat',
      'to wait',
      ['wartet', 'wartete', 'gewartet', 'haben'],
      'Ich warte an der Haltestelle.',
      'Čekám na zastávce.',
    ),
    verb(
      'fahren',
      'jet; jezdit',
      'to go by vehicle; to travel',
      ['fährt', 'fuhr', 'gefahren', 'sein'],
      'Der Bus fährt zum Bahnhof.',
      'Autobus jede na nádraží.',
    ),
    noun(
      'Minute',
      'minuta',
      'minute',
      'die',
      'Minuten',
      'Der Bus kommt in fünf Minuten.',
      'Autobus přijede za pět minut.',
    ),
  ],
  'chapter-44-transfer-in-town': [
    noun(
      'Woche',
      'týden',
      'week',
      'die',
      'Wochen',
      'Diese Woche fahre ich mit dem Bus.',
      'Tento týden jezdím autobusem.',
    ),
    noun(
      'Wochenende',
      'víkend',
      'weekend',
      'das',
      'Wochenenden',
      'Am Wochenende fährt der Bus seltener.',
      'O víkendu jezdí autobus méně často.',
    ),
    term(
      'um',
      'v; ve',
      'at (a specific time)',
      'Der Anschluss fährt um neun Uhr.',
      'Navazující spoj jede v devět hodin.',
    ),
  ],
  'chapter-103-weather-and-clothing': [
    noun(
      'Hose',
      'kalhoty',
      'trousers; pants',
      'die',
      'Hosen',
      'Meine Hose ist noch nass.',
      'Moje kalhoty jsou ještě mokré.',
    ),
    noun(
      'Schuh',
      'bota',
      'shoe',
      'der',
      'Schuhe',
      'Diese Schuhe sind wasserdicht.',
      'Tyto boty jsou nepromokavé.',
    ),
    noun(
      'Regen',
      'déšť',
      'rain',
      'der',
      '—',
      'Bei Regen nehme ich eine Jacke mit.',
      'Když prší, beru si s sebou bundu.',
    ),
  ],
  'chapter-104-library-services': [
    verb(
      'helfen',
      'pomoci; pomáhat',
      'to help',
      ['hilft', 'half', 'geholfen', 'haben'],
      'Können Sie mir bitte helfen?',
      'Můžete mi prosím pomoci?',
    ),
    {
      ...term(
        'langsam',
        'pomalý; pomalu',
        'slow; slowly',
        'Sprechen Sie bitte langsam.',
        'Mluvte prosím pomalu.',
      ),
      kind: 'adjective',
    },
    {
      ...term(
        'schnell',
        'rychlý; rychle',
        'fast; quickly',
        'Ich finde das Buch schnell.',
        'Knihu najdu rychle.',
      ),
      kind: 'adjective',
    },
  ],
};
