export type TransferChapterThread = {
  wordLemmas: readonly [string, string, string, string, ...string[]];
  grammarLessonId: string;
  grammarIdea: string;
  grammarPattern: string;
  coachScenarioId: string;
  sentenceStarter: string;
  promptDe: string;
  promptCs: string;
  responseDe: string;
  responseCs: string;
};

/**
 * Editorial spine for every focused transfer chapter. The chapter generator
 * must not rotate unrelated source material: vocabulary, grammar, dialogue,
 * model answer, and coach mission all resolve through this one contract.
 */
export const transferChapterThreads: Readonly<Record<string, TransferChapterThread>> = {
  'chapter-31-first-introduction': {
    wordLemmas: ['Schule', 'Stunde', 'Heft', 'Mitschüler', 'lernen'],
    grammarLessonId: 'verb-second-position',
    grammarIdea: 'sloveso na druhé pozici při krátkém představení',
    grammarPattern: 'Ich heiße ... und heute lerne ich ...',
    coachScenarioId: 'introductions',
    sentenceStarter: 'Ich heiße ...',
    promptDe: 'Hallo, ich bin Leo. Wie heißt du und was lernst du heute?',
    promptCs: 'Ahoj, já jsem Leo. Jak se jmenuješ a co se dnes učíš?',
    responseDe: 'Ich heiße Anna und heute lerne ich in der Schule Deutsch.',
    responseCs: 'Jmenuji se Anna a dnes se ve škole učím německy.',
  },
  'chapter-32-find-the-right-page': {
    wordLemmas: ['Anweisung', 'Arbeitsblatt', 'Seite', 'aufschlagen', 'markieren'],
    grammarLessonId: 'modal-verbs',
    grammarIdea: 'shrnutí pokynu pomocí sollen a infinitivu na konci',
    grammarPattern: 'Ich soll ... aufschlagen und ... markieren.',
    coachScenarioId: 'school',
    sentenceStarter: 'Ich soll ...',
    promptDe: 'Schlagen Sie das Arbeitsblatt auf Seite zwölf auf und markieren Sie Aufgabe drei.',
    promptCs: 'Otevřete pracovní list na straně dvanáct a označte úkol tři.',
    responseDe: 'Ich soll Seite zwölf aufschlagen und Aufgabe drei markieren.',
    responseCs: 'Mám otevřít stranu dvanáct a označit úkol tři.',
  },
  'chapter-33-ask-for-repetition': {
    wordLemmas: ['Anweisung', 'wiederholen', 'buchstabieren', 'noch einmal', 'langsamer'],
    grammarLessonId: 'questions',
    grammarIdea: 'zdvořilá otázka se slovesem před podmětem',
    grammarPattern: 'Können Sie ... bitte noch einmal ...?',
    coachScenarioId: 'transfer-ask-for-repetition',
    sentenceStarter: 'Können Sie ...',
    promptDe: 'War die Anweisung verständlich?',
    promptCs: 'Byl pokyn srozumitelný?',
    responseDe: 'Können Sie die Anweisung bitte noch einmal langsamer wiederholen?',
    responseCs: 'Můžete prosím ten pokyn ještě jednou pomaleji zopakovat?',
  },
  'chapter-34-simple-order': {
    wordLemmas: ['Bestellung', 'Brötchen', 'Tasse', 'bestellen', 'möchten'],
    grammarLessonId: 'accusative',
    grammarIdea: 'akuzativ po möchten při zdvořilé objednávce',
    grammarPattern: 'Ich möchte + Akkusativ + bitte.',
    coachScenarioId: 'cafe',
    sentenceStarter: 'Ich möchte ...',
    promptDe: 'Guten Morgen. Was möchten Sie bestellen?',
    promptCs: 'Dobré ráno. Co si přejete objednat?',
    responseDe: 'Ich möchte ein Brötchen und eine Tasse Tee, bitte.',
    responseCs: 'Chtěla bych housku a šálek čaje, prosím.',
  },
  'chapter-35-price-and-payment': {
    wordLemmas: ['kosten', 'bezahlen', 'bar', 'Rechnung', 'zusammen'],
    grammarLessonId: 'numbers-and-prices',
    grammarIdea: 'otázka na celkovou cenu a přesné vyjádření platby',
    grammarPattern: 'Was kostet das zusammen? Ich bezahle ...',
    coachScenarioId: 'transfer-price-and-payment',
    sentenceStarter: 'Was kostet ...',
    promptDe: 'Möchten Sie bar oder mit Karte bezahlen?',
    promptCs: 'Chcete zaplatit hotově, nebo kartou?',
    responseDe: 'Was kostet das zusammen? Ich bezahle die Rechnung mit Karte.',
    responseCs: 'Kolik to stojí dohromady? Účet zaplatím kartou.',
  },
  'chapter-36-takeaway-order': {
    wordLemmas: ['Brötchen', 'Brezel', 'mitnehmen', 'einpacken', 'sonst noch'],
    grammarLessonId: 'separable-imperative',
    grammarIdea: 'odlučitelná slovesa mitnehmen a einpacken v objednávce',
    grammarPattern: 'Ich nehme ... mit. Packen Sie ... bitte ein.',
    coachScenarioId: 'bakery-preorder',
    sentenceStarter: 'Ich nehme ... mit.',
    promptDe: 'Was darf ich Ihnen zum Mitnehmen einpacken?',
    promptCs: 'Co vám mohu zabalit s sebou?',
    responseDe: 'Ich nehme zwei Brezeln mit. Packen Sie sie bitte ein.',
    responseCs: 'Vezmu si s sebou dva preclíky. Zabalte je prosím.',
  },
  'chapter-37-repair-the-order': {
    wordLemmas: ['Bestellung', 'Brotsorte', 'Croissant', 'Brezel', 'Zimtschnecke'],
    grammarLessonId: 'coordinating-connectors',
    grammarIdea: 'oprava nedorozumění pomocí nicht, sondern',
    grammarPattern: 'Ich habe nicht ... bestellt, sondern ...',
    coachScenarioId: 'bakery-preorder',
    sentenceStarter: 'Ich habe nicht ...',
    promptDe: 'Hier sind ein Croissant und eine Brezel. Stimmt Ihre Bestellung so?',
    promptCs: 'Tady je croissant a preclík. Je vaše objednávka takto správně?',
    responseDe:
      'Ich habe kein Croissant bestellt, sondern zwei Brezeln. Das ist meine ganze Bestellung.',
    responseCs: 'Neobjednala jsem si croissant, ale dva preclíky. To je celá moje objednávka.',
  },
  'chapter-38-morning-time': {
    wordLemmas: ['morgens', 'aufstehen', 'Frühstück', 'brauchen', 'pünktlich'],
    grammarLessonId: 'present-endings',
    grammarIdea: 'přítomný čas a druhá pozice slovesa po časovém údaji',
    grammarPattern: 'Um ... stehe ich auf, um ... frühstücke ich und um ... bin ich ...',
    coachScenarioId: 'transfer-morning-routine',
    sentenceStarter: 'Um sieben Uhr ...',
    promptDe: 'Wann stehst du auf, damit du pünktlich bist?',
    promptCs: 'Kdy vstáváš, abys přišla včas?',
    responseDe:
      'Um sieben Uhr stehe ich auf, um Viertel nach sieben frühstücke ich und um acht Uhr bin ich pünktlich in der Schule.',
    responseCs: 'V sedm hodin vstávám, ve čtvrt na osm snídám a v osm jsem včas ve škole.',
  },
  'chapter-39-who-lives-here': {
    wordLemmas: ['Haushalt', 'Schwester', 'Bruder', 'Großmutter', 'wohnen'],
    grammarLessonId: 'possessive-articles',
    grammarIdea: 'přivlastňovací člen před členem domácnosti',
    grammarPattern: 'Meine ... wohnt mit unserer ...',
    coachScenarioId: 'new-neighbor',
    sentenceStarter: 'In unserem Haushalt ...',
    promptDe: 'Wer gehört zu eurem Haushalt?',
    promptCs: 'Kdo patří do vaší domácnosti?',
    responseDe: 'Meine Schwester wohnt mit unserer Großmutter, mein Bruder wohnt allein.',
    responseCs: 'Moje sestra bydlí s naší babičkou, můj bratr bydlí sám.',
  },
  'chapter-40-whose-is-it': {
    wordLemmas: ['Schlüssel', 'gehören', 'teilen', 'unser', 'ihr'],
    grammarLessonId: 'dative-pronouns',
    grammarIdea: 'osobní zájmeno v dativu po slovese gehören',
    grammarPattern: 'Der ... gehört mir, aber ... gehört ihr.',
    coachScenarioId: 'transfer-whose-is-it',
    sentenceStarter: 'Der Schlüssel gehört ...',
    promptDe: 'Wem gehören der Schlüssel und die blaue Tasche?',
    promptCs: 'Komu patří klíč a modrá taška?',
    responseDe: 'Der Schlüssel gehört mir, aber die blaue Tasche gehört ihr.',
    responseCs: 'Klíč patří mně, ale modrá taška patří jí.',
  },
  'chapter-41-evening-together': {
    wordLemmas: ['Wohnzimmer', 'teilen', 'gemeinsam', 'allein', 'unser'],
    grammarLessonId: 'coordinating-connectors',
    grammarIdea: 'spojení dvou večerních činností pomocí und a danach',
    grammarPattern: 'Wir ... gemeinsam und danach ...',
    coachScenarioId: 'transfer-evening-together',
    sentenceStarter: 'Wir können gemeinsam ...',
    promptDe: 'Was machen wir heute Abend gemeinsam?',
    promptCs: 'Co budeme dnes večer dělat společně?',
    responseDe: 'Um sieben Uhr kochen wir gemeinsam und danach räumen wir unser Wohnzimmer auf.',
    responseCs: 'V sedm budeme společně vařit a potom uklidíme náš obývací pokoj.',
  },
  'chapter-42-route-to-destination': {
    wordLemmas: ['Kreuzung', 'Rathaus', 'Brücke', 'abbiegen', 'geradeaus'],
    grammarLessonId: 'imperative-basics',
    grammarIdea: 'zdvořilý rozkazovací způsob při popisu cesty',
    grammarPattern: 'Gehen Sie ... und biegen Sie ... ab.',
    coachScenarioId: 'directions',
    sentenceStarter: 'Gehen Sie ...',
    promptDe: 'Wie komme ich von hier zum Rathaus?',
    promptCs: 'Jak se odsud dostanu k radnici?',
    responseDe: 'Gehen Sie bis zur Kreuzung geradeaus und biegen Sie vor der Brücke links ab.',
    responseCs: 'Jděte rovně až ke křižovatce a před mostem odbočte doleva.',
  },
  'chapter-43-right-stop': {
    wordLemmas: ['Haltestelle', 'Fahrplan', 'Rathaus', 'einsteigen', 'aussteigen'],
    grammarLessonId: 'questions',
    grammarIdea: 'ano/ne otázka a W-otázka při ověření spoje',
    grammarPattern: 'Fährt ...? An welcher Haltestelle ...?',
    coachScenarioId: 'city-bus',
    sentenceStarter: 'Fährt dieser Bus ...',
    promptDe: 'Kann ich Ihnen mit der Verbindung helfen?',
    promptCs: 'Mohu vám pomoci se spojením?',
    responseDe: 'Fährt dieser Bus zum Rathaus? An welcher Haltestelle muss ich aussteigen?',
    responseCs: 'Jede tento autobus k radnici? Na které zastávce musím vystoupit?',
  },
  'chapter-44-transfer-in-town': {
    wordLemmas: ['Haltestelle', 'Fahrplan', 'Rathaus', 'einsteigen', 'aussteigen'],
    grammarLessonId: 'separable-verbs',
    grammarIdea: 'odlučitelná slovesa při popisu přestupu',
    grammarPattern: 'An ... steige ich aus und an ... wieder ein.',
    coachScenarioId: 'transfer-city-connection',
    sentenceStarter: 'Am Rathaus steige ich ...',
    promptDe: 'Wie wechseln Sie am Rathaus in die nächste Linie?',
    promptCs: 'Jak u radnice přestoupíte na další linku?',
    responseDe: 'Am Rathaus steige ich aus und an der nächsten Haltestelle wieder ein.',
    responseCs: 'U radnice vystoupím a na další zastávce znovu nastoupím.',
  },
  'chapter-45-ticket-and-departure': {
    wordLemmas: ['Fahrkarte', 'Gleis', 'umsteigen', 'Abfahrt', 'hin und zurück'],
    grammarLessonId: 'separable-verbs',
    grammarIdea: 'odlučitelná slovesa abfahren a umsteigen v cestovním dotazu',
    grammarPattern: 'Wann fährt ... ab, und wo steige ich um?',
    coachScenarioId: 'train',
    sentenceStarter: 'Ich brauche eine Fahrkarte ...',
    promptDe: 'Wohin möchten Sie fahren?',
    promptCs: 'Kam chcete jet?',
    responseDe:
      'Ich brauche eine Fahrkarte nach Leipzig hin und zurück. Wann fährt der Zug ab, und von welchem Gleis?',
    responseCs: 'Potřebuji zpáteční jízdenku do Lipska. Kdy vlak odjíždí a z kterého nástupiště?',
  },
  'chapter-46-confirm-reservation': {
    wordLemmas: ['Reservierung', 'Rezeption', 'Doppelzimmer', 'Ausweis', 'einchecken'],
    grammarLessonId: 'perfect-haben',
    grammarIdea: 'perfektum pro předem dokončenou rezervaci',
    grammarPattern: 'Ich habe ... reserviert und möchte jetzt ...',
    coachScenarioId: 'hotel-check-in',
    sentenceStarter: 'Ich habe ... reserviert.',
    promptDe: 'Guten Abend. Haben Sie eine Reservierung?',
    promptCs: 'Dobrý večer. Máte rezervaci?',
    responseDe:
      'Ich habe vom 12. bis 14. Mai ein Doppelzimmer auf meinen Namen reserviert und möchte jetzt einchecken.',
    responseCs:
      'Od 12. do 14. května jsem si rezervovala dvoulůžkový pokoj na své jméno a teď se chci ubytovat.',
  },
  'chapter-47-room-problem': {
    wordLemmas: ['Rezeption', 'Doppelzimmer', 'Handtuch', 'fehlen', 'funktionieren'],
    grammarLessonId: 'indirect-questions',
    grammarIdea: 'zdvořilá nepřímá otázka s ob a slovesem na konci',
    grammarPattern: 'Können Sie mir sagen, ob/wann ...?',
    coachScenarioId: 'transfer-hotel-room-problem',
    sentenceStarter: 'In meinem Zimmer ...',
    promptDe: 'Rezeption, guten Abend. Was stimmt in Ihrem Doppelzimmer nicht?',
    promptCs: 'Recepce, dobrý večer. Co není v pořádku ve vašem dvoulůžkovém pokoji?',
    responseDe:
      'Im Bad fehlt ein Handtuch. Können Sie mir sagen, wann die Heizung wieder funktioniert?',
    responseCs: 'V koupelně chybí ručník. Můžete mi říct, kdy bude topení znovu fungovat?',
  },
  'chapter-48-describe-symptoms': {
    wordLemmas: ['Beschwerde', 'Halsschmerz', 'Husten', 'Fieber', 'seit gestern'],
    grammarLessonId: 'seit-versus-vor',
    grammarIdea: 'seit pro potíže, které začaly dříve a stále trvají',
    grammarPattern: 'Seit ... habe ich ...',
    coachScenarioId: 'doctor-appointment',
    sentenceStarter: 'Seit gestern ...',
    promptDe: 'Welche Beschwerden haben Sie und seit wann?',
    promptCs: 'Jaké máte potíže a odkdy?',
    responseDe: 'Seit gestern habe ich starke Halsschmerzen, Husten und leichtes Fieber.',
    responseCs: 'Od včerejška mě silně bolí v krku, kašlu a mám mírnou horečku.',
  },
  'chapter-49-at-the-pharmacy': {
    wordLemmas: ['Tablette', 'Nebenwirkung', 'einnehmen', 'allergisch', 'Apotheke'],
    grammarLessonId: 'adjective-prepositions',
    grammarIdea: 'pevná předložková vazba allergisch gegen a otázka na užívání léku',
    grammarPattern: 'Ich bin gegen ... allergisch. Wie oft soll ich ... einnehmen?',
    coachScenarioId: 'transfer-pharmacy-request',
    sentenceStarter: 'Ich bin gegen ... allergisch.',
    promptDe: 'Was muss ich wissen, bevor ich Ihnen diese Tabletten empfehle?',
    promptCs: 'Co musím vědět, než vám tyto tablety doporučím?',
    responseDe:
      'Ich bin gegen Penicillin allergisch. Welche Tabletten sind für mich geeignet, und wie oft soll ich sie einnehmen?',
    responseCs:
      'Jsem alergická na penicilin. Které tablety jsou pro mě vhodné a jak často je mám užívat?',
  },
  'chapter-50-safe-dosage': {
    wordLemmas: ['Tablette', 'Nebenwirkung', 'einnehmen', 'zweimal täglich', 'rezeptfrei'],
    grammarLessonId: 'quantity-words',
    grammarIdea: 'přesné množství a četnost při dávkování',
    grammarPattern: 'Soll ich ... zweimal täglich ... einnehmen?',
    coachScenarioId: 'pharmacy',
    sentenceStarter: 'Soll ich diese Tablette ...',
    promptDe: 'Haben Sie noch eine Frage zur Einnahme?',
    promptCs: 'Máte ještě otázku k užívání?',
    responseDe:
      'Soll ich eine rezeptfreie Tablette zweimal täglich nach dem Essen einnehmen, und welche Nebenwirkungen sind möglich?',
    responseCs:
      'Mám užívat jednu volně prodejnou tabletu dvakrát denně po jídle a jaké vedlejší účinky se mohou objevit?',
  },
  'chapter-51-when-to-see-doctor': {
    wordLemmas: ['Husten', 'Fieber', 'Arztpraxis', 'Sprechstunde', 'Untersuchung'],
    grammarLessonId: 'connector-adverbs',
    grammarIdea: 'důsledek po deshalb se slovesem před podmětem',
    grammarPattern: 'Das ... wird stärker; deshalb rufe ich ... an.',
    coachScenarioId: 'transfer-doctor-next-step',
    sentenceStarter: 'Das Fieber ...',
    promptDe: 'Wie hat sich Ihr Zustand verändert?',
    promptCs: 'Jak se váš stav změnil?',
    responseDe:
      'Das Fieber und der Husten werden stärker; deshalb rufe ich die Arztpraxis an und frage nach der Sprechstunde.',
    responseCs: 'Horečka a kašel sílí, proto zavolám do ordinace a zeptám se na ordinační hodiny.',
  },
  'chapter-52-suggest-a-time': {
    wordLemmas: ['Verabredung', 'verschieben', 'deshalb', 'zusagen', 'leider'],
    grammarLessonId: 'weil-dass',
    grammarIdea: 'důvod se spojkou weil a slovesem na konci vedlejší věty',
    grammarPattern: 'Ich muss ... verschieben, weil ... Passt ...?',
    coachScenarioId: 'invitation',
    sentenceStarter: 'Ich muss unsere Verabredung ...',
    promptDe: 'Kannst du unserer Verabredung am Freitag zusagen?',
    promptCs: 'Můžeš potvrdit naši schůzku v pátek?',
    responseDe:
      'Leider muss ich unsere Verabredung verschieben, weil ich am Freitag arbeite. Passt Samstag?',
    responseCs: 'Bohužel musím naši schůzku přesunout, protože v pátek pracuji. Hodí se sobota?',
  },
  'chapter-53-compare-two-options': {
    wordLemmas: ['Größe', 'Auswahl', 'passen', 'vergleichen', 'günstiger'],
    grammarLessonId: 'comparison',
    grammarIdea: 'komparativ při srovnání ceny a vhodnosti',
    grammarPattern: 'Dieses Modell ist ..., aber das andere ist ... und passt ... besser.',
    coachScenarioId: 'shopping',
    sentenceStarter: 'Dieses Modell ist ...',
    promptDe: 'Welches der beiden Modelle passt besser zu Ihnen?',
    promptCs: 'Který z těchto dvou modelů vám vyhovuje lépe?',
    responseDe:
      'Dieses Modell ist günstiger, aber das andere ist besser verarbeitet und passt mir in Größe M besser.',
    responseCs:
      'Tento model je levnější, ale ten druhý je lépe zpracovaný a ve velikosti M mi sedí lépe.',
  },
  'chapter-54-describe-a-defect': {
    wordLemmas: ['Kassenbon', 'Mangel', 'Größe', 'beschädigt', 'zurückgeben'],
    grammarLessonId: 'adjective-endings-after-ein',
    grammarIdea: 'koncovka přídavného jména po neurčitém členu v popisu vady',
    grammarPattern: 'Nach ... hatte ... einen sichtbaren Mangel.',
    coachScenarioId: 'return-purchase',
    sentenceStarter: 'Nach dem ersten Tragen ...',
    promptDe: 'Was ist mit dem Artikel passiert?',
    promptCs: 'Co se s výrobkem stalo?',
    responseDe:
      'Nach dem ersten Tragen hatte die Jacke einen sichtbaren Mangel und war am Ärmel beschädigt.',
    responseCs: 'Po prvním nošení měla bunda viditelnou vadu a byla poškozená na rukávu.',
  },
  'chapter-55-request-a-remedy': {
    wordLemmas: ['Umtausch', 'Kassenbon', 'Erstattung', 'umtauschen', 'gegen Vorlage'],
    grammarLessonId: 'indirect-questions',
    grammarIdea: 'zdvořilá nepřímá otázka na podmínky nápravy',
    grammarPattern: 'Können Sie mir sagen, ob ...?',
    coachScenarioId: 'transfer-request-remedy',
    sentenceStarter: 'Können Sie mir sagen, ob ...',
    promptDe: 'Welche Lösung wünschen Sie für die beschädigte Jacke?',
    promptCs: 'Jaké řešení si přejete pro poškozenou bundu?',
    responseDe:
      'Können Sie mir sagen, ob ich die Jacke umtauschen oder gegen Vorlage des Kassenbons eine Erstattung bekommen kann?',
    responseCs:
      'Můžete mi říct, zda mohu bundu vyměnit, nebo po předložení účtenky dostat peníze zpět?',
  },
  'chapter-56-flat-viewing': {
    wordLemmas: ['Mietvertrag', 'Kaution', 'Nebenkosten', 'Innenhof', 'Keller'],
    grammarLessonId: 'indirect-questions',
    grammarIdea: 'nepřímá otázka s ob při ověřování podmínek bydlení',
    grammarPattern: 'Können Sie mir sagen, ob ...?',
    coachScenarioId: 'apartment-viewing',
    sentenceStarter: 'Können Sie mir sagen, ob ...',
    promptDe: 'Was möchten Sie über die Wohnung wissen?',
    promptCs: 'Co chcete o bytě vědět?',
    responseDe:
      'Können Sie mir sagen, ob die Wohnung zum Innenhof liegt, der Keller nutzbar ist und Nebenkosten sowie Kaution im Mietvertrag stehen?',
    responseCs:
      'Můžete mi říct, zda byt směřuje do vnitrobloku, zda lze používat sklep a zda jsou vedlejší náklady i kauce uvedené v nájemní smlouvě?',
  },
  'chapter-57-neighbour-agreement': {
    wordLemmas: ['Mietvertrag', 'Hausordnung', 'einziehen', 'hellhörig', 'Rücksicht nehmen'],
    grammarLessonId: 'connector-adverbs',
    grammarIdea: 'důsledek po deshalb při formulaci sousedského pravidla',
    grammarPattern: 'Das Haus ist ...; deshalb ...',
    coachScenarioId: 'transfer-neighbour-agreement',
    sentenceStarter: 'Das Haus ist hellhörig, deshalb ...',
    promptDe: 'Die Musik war gestern sehr laut. Wie vermeiden wir das künftig?',
    promptCs: 'Hudba byla včera velmi hlasitá. Jak tomu příště předejdeme?',
    responseDe:
      'Das Haus ist hellhörig; deshalb nehme ich laut Hausordnung ab zehn Uhr besonders Rücksicht.',
    responseCs:
      'Dům má tenké stěny, proto budu podle domovního řádu od deseti hodin obzvlášť ohleduplná.',
  },
  'chapter-58-house-rules': {
    wordLemmas: ['Mietvertrag', 'Keller', 'Hausordnung', 'hellhörig', 'Rücksicht nehmen'],
    grammarLessonId: 'relative-clauses-basic',
    grammarIdea: 'vztažná věta, která přesně určí dokument s pravidly',
    grammarPattern: 'Die Hausordnung, die ..., nennt ...',
    coachScenarioId: 'transfer-house-rules',
    sentenceStarter: 'Die Hausordnung, die ...',
    promptDe: 'Wo finde ich die verbindlichen Ruhezeiten?',
    promptCs: 'Kde najdu závazné doby klidu?',
    responseDe:
      'Die Hausordnung, die Teil des Mietvertrags ist, nennt die Ruhezeiten für das hellhörige Haus. Können wir für Samstag eine Ausnahme vereinbaren?',
    responseCs:
      'Domovní řád, který je součástí nájemní smlouvy, uvádí doby klidu pro dům s tenkými stěnami. Můžeme se na sobotu domluvit na výjimce?',
  },
  'chapter-59-measurable-study-goal': {
    wordLemmas: ['Lernziel', 'Fortschritt', 'Schwerpunkt', 'festlegen', 'regelmäßig'],
    grammarLessonId: 'zu-infinitives',
    grammarIdea: 'infinitivní doplnění po cíli a účel pomocí um ... zu',
    grammarPattern: 'Mein Lernziel ist es, bis ... zu ...',
    coachScenarioId: 'transfer-measurable-study-goal',
    sentenceStarter: 'Mein Lernziel ist es, ...',
    promptDe: 'Welchen konkreten Fortschritt möchtest du bis Monatsende erreichen?',
    promptCs: 'Jakého konkrétního pokroku chceš dosáhnout do konce měsíce?',
    responseDe: 'Mein Lernziel ist es, bis Monatsende regelmäßig zehn Minuten frei zu sprechen.',
    responseCs: 'Mým studijním cílem je do konce měsíce pravidelně deset minut volně mluvit.',
  },
  'chapter-60-weekly-study-plan': {
    wordLemmas: ['Lernstoff', 'Gewohnheit', 'realistisch', 'Zeitplan', 'einteilen'],
    grammarLessonId: 'infinitive-complements',
    grammarIdea: 'infinitiv s zu po versuchen při plánování',
    grammarPattern: 'Ich versuche, ... in ... einzuteilen.',
    coachScenarioId: 'transfer-weekly-study-plan',
    sentenceStarter: 'Ich versuche, den Lernstoff ...',
    promptDe: 'Wie verteilst du den Lernstoff auf deine vier freien Termine?',
    promptCs: 'Jak rozdělíš učivo mezi své čtyři volné termíny?',
    responseDe:
      'Ich versuche, den Lernstoff im Zeitplan in vier realistische Einheiten einzuteilen.',
    responseCs: 'Snažím se rozdělit učivo v rozvrhu do čtyř realistických bloků.',
  },
  'chapter-61-learning-obstacle': {
    wordLemmas: ['sich konzentrieren', 'schrittweise', 'realistisch', 'Prüfung', 'Lernmethode'],
    grammarLessonId: 'purpose-clauses',
    grammarIdea: 'účelová konstrukce um ... zu pro konkrétní nápravu',
    grammarPattern: 'Weil ich mich ..., übe ich ..., um mich ... vorzubereiten.',
    coachScenarioId: 'study-planning',
    sentenceStarter: 'Um mich besser ...',
    promptDe: 'Was hindert dich gerade am Lernen, und was änderst du?',
    promptCs: 'Co ti právě brání v učení a co změníš?',
    responseDe:
      'Weil ich mich abends schlecht konzentriere, übe ich schrittweise in kurzen Einheiten, um mich gezielt auf die Prüfung vorzubereiten.',
    responseCs:
      'Protože se večer špatně soustředím, učím se postupně v krátkých blocích, abych se na zkoušku připravila cíleně.',
  },
  'chapter-62-review-progress': {
    wordLemmas: ['Fortschritt', 'Zeitplan', 'Lernmethode', 'anwenden', 'überprüfen'],
    grammarLessonId: 'indirect-questions',
    grammarIdea: 'vložená otázka s ob při vyhodnocení výsledku',
    grammarPattern: 'Ich überprüfe, ob ...',
    coachScenarioId: 'transfer-review-progress',
    sentenceStarter: 'Ich überprüfe, ob ...',
    promptDe: 'Woran erkennst du, ob dein Plan funktioniert?',
    promptCs: 'Podle čeho poznáš, zda tvůj plán funguje?',
    responseDe:
      'Von vier geplanten Einheiten habe ich drei geschafft; ich überprüfe, ob meine Lernmethode Fortschritt bringt, und passe den Zeitplan an.',
    responseCs:
      'Ze čtyř naplánovaných bloků jsem zvládla tři; ověřím, zda moje studijní metoda přináší pokrok, a upravím rozvrh.',
  },
  'chapter-63-practical-example': {
    wordLemmas: ['Berufserfahrung', 'Verantwortung', 'Tätigkeit', 'betreuen', 'übernehmen'],
    grammarLessonId: 'praeteritum-core',
    grammarIdea: 'préteritum pro stručný popis minulé odpovědnosti',
    grammarPattern: 'In meinem letzten Projekt übernahm ich ...',
    coachScenarioId: 'transfer-practical-example',
    sentenceStarter: 'In meinem letzten Projekt ...',
    promptDe: 'Können Sie Ihre Berufserfahrung an einem konkreten Beispiel zeigen?',
    promptCs: 'Můžete svou pracovní zkušenost ukázat na konkrétním příkladu?',
    responseDe:
      'In meinem letzten Projekt übernahm ich die Verantwortung und betreute fünf Kundinnen, sodass alle Anfragen pünktlich beantwortet wurden.',
    responseCs:
      'Ve svém posledním projektu jsem převzala odpovědnost a starala se o pět zákaznic, takže všechny dotazy dostaly odpověď včas.',
  },
  'chapter-64-report-an-absence': {
    wordLemmas: ['Vertretung', 'Krankmeldung', 'sich krankmelden', 'zuständig', 'kurzfristig'],
    grammarLessonId: 'weil-dass',
    grammarIdea: 'důvod absence ve vedlejší větě s weil',
    grammarPattern: 'Ich muss mich ... krankmelden, weil ...',
    coachScenarioId: 'call-in-sick',
    sentenceStarter: 'Ich muss mich leider ...',
    promptDe: 'Warum können Sie heute nicht arbeiten, und wer übernimmt Ihre Aufgaben?',
    promptCs: 'Proč dnes nemůžete pracovat a kdo převezme vaše úkoly?',
    responseDe:
      'Ich muss mich kurzfristig krankmelden, weil ich Fieber habe; meine Vertretung ist für die bereits vereinbarten Kundentermine zuständig.',
    responseCs:
      'Musím se narychlo omluvit z práce, protože mám horečku; zastupující kolegyně odpovídá za už domluvené schůzky se zákazníky.',
  },
  'chapter-65-home-service-case': {
    wordLemmas: ['Vermieter', 'Heizung', 'reparieren', 'zuverlässig'],
    grammarLessonId: 'relative-clauses',
    grammarIdea: 'vztažná věta pro přesný popis závady a osoby, která ji řeší',
    grammarPattern: 'Die Heizung, die ..., wird von ... repariert.',
    coachScenarioId: 'apartment-repair',
    sentenceStarter: 'Die Heizung, die ...',
    promptDe: 'Was genau ist kaputt, und wann kann jemand kommen?',
    promptCs: 'Co přesně je rozbité a kdy může někdo přijít?',
    responseDe:
      'Die Heizung, die seit gestern nicht funktioniert, wird morgen von einem zuverlässigen Techniker repariert.',
    responseCs: 'Topení, které od včerejška nefunguje, zítra opraví spolehlivý technik.',
  },
  'chapter-66-order-events': {
    wordLemmas: ['Vorfall', 'Ablauf', 'Zeugin', 'zunächst', 'anschließend'],
    grammarLessonId: 'praeteritum-lexical-verbs',
    grammarIdea: 'préteritum a časové konektory pro jasnou chronologii',
    grammarPattern: 'Zunächst ..., anschließend ...',
    coachScenarioId: 'transfer-order-events',
    sentenceStarter: 'Zunächst ...',
    promptDe: 'Wie lief der Vorfall aus Sicht der Zeugin ab?',
    promptCs: 'Jak událost proběhla z pohledu svědkyně?',
    responseDe:
      'Zunächst bemerkte die Zeugin den Vorfall, anschließend schilderte sie der Polizei den Ablauf und schließlich bestätigte sie das Protokoll.',
    responseCs:
      'Nejdřív si svědkyně všimla události, následně popsala její průběh policii a nakonec potvrdila protokol.',
  },
  'chapter-67-earlier-event': {
    wordLemmas: ['Gepäckstück', 'bemerken', 'zurücklassen', 'melden', 'bereits'],
    grammarLessonId: 'before-after-clauses',
    grammarIdea: 'plusquamperfekt pro děj, který nastal před pozdějším zjištěním',
    grammarPattern: 'Bevor ich ... bemerkte, hatte ich bereits ...',
    coachScenarioId: 'transfer-earlier-event',
    sentenceStarter: 'Bevor ich ...',
    promptDe: 'Was war geschehen, bevor Sie den Verlust meldeten?',
    promptCs: 'Co se stalo předtím, než jste ztrátu nahlásila?',
    responseDe:
      'Bevor ich den Verlust bemerkte, hatte ich das Gepäckstück bereits im Zug zurückgelassen.',
    responseCs: 'Než jsem si ztráty všimla, už jsem zavazadlo nechala ve vlaku.',
  },
  'chapter-68-brief-report': {
    wordLemmas: ['Vorfall', 'Ablauf', 'zunächst', 'anschließend', 'unerwartet'],
    grammarLessonId: 'connector-adverbs',
    grammarIdea: 'časová spojovací příslovce se slovesem na druhé pozici',
    grammarPattern: 'Zunächst ..., anschließend ...',
    coachScenarioId: 'transfer-brief-report',
    sentenceStarter: 'Zunächst ...',
    promptDe: 'Fassen Sie den Vorfall bitte in zwei klaren Schritten zusammen.',
    promptCs: 'Shrňte prosím událost ve dvou jasných krocích.',
    responseDe:
      'Zunächst stockte der Ablauf unerwartet, anschließend wurde der Vorfall der Leitung gemeldet.',
    responseCs: 'Nejdřív se průběh nečekaně zadrhl, následně byla událost nahlášena vedení.',
  },
  'chapter-69-explain-a-process': {
    wordLemmas: ['Aufgabe', 'Erfahrung', 'übernehmen', 'Ergebnis', 'selbstständig'],
    grammarLessonId: 'process-passive',
    grammarIdea: 'procesní pasivum, když je důležitější krok než vykonavatel',
    grammarPattern: 'Zuerst wird ..., dann wird ..., am Ende wird ...',
    coachScenarioId: 'transfer-explain-process',
    sentenceStarter: 'Zuerst wird ...',
    promptDe: 'Wie wird die Aufgabe vom Anfang bis zum Ergebnis bearbeitet?',
    promptCs: 'Jak se úkol zpracuje od začátku až k výsledku?',
    responseDe:
      'Zuerst wird die Aufgabe verteilt, dann wird die Verantwortung übernommen und am Ende wird das Ergebnis geprüft.',
    responseCs:
      'Nejdřív se rozdělí úkol, potom se převezme odpovědnost a nakonec se zkontroluje výsledek.',
  },
  'chapter-70-opinion-with-reason': {
    wordLemmas: ['Standpunkt', 'Priorität', 'Vorteil', 'abwägen', 'dennoch'],
    grammarLessonId: 'weil-dass',
    grammarIdea: 'vedlejší věta s weil pro konkrétní zdůvodnění názoru',
    grammarPattern: 'Meiner Meinung nach ..., weil ...',
    coachScenarioId: 'transfer-opinion-with-reason',
    sentenceStarter: 'Meiner Meinung nach ...',
    promptDe: 'Welche Option bevorzugen Sie und warum?',
    promptCs: 'Které možnosti dáváte přednost a proč?',
    responseDe:
      'Meiner Meinung nach hat der Vorschlag einen Vorteil, weil er unsere wichtigste Priorität schützt.',
    responseCs:
      'Podle mého názoru má návrh jednu výhodu, protože chrání naši nejdůležitější prioritu.',
  },
  'chapter-71-acknowledge-objection': {
    wordLemmas: ['Einwand', 'zustimmen', 'einwenden', 'abwägen', 'entgegenkommen'],
    grammarLessonId: 'concession-patterns',
    grammarIdea: 'ústupková věta s obwohl pro uznání platné námitky',
    grammarPattern: 'Obwohl der Einwand ..., stimme ich ...',
    coachScenarioId: 'transfer-acknowledge-objection',
    sentenceStarter: 'Obwohl der Einwand ...',
    promptDe: 'Der Vorschlag spart Zeit, könnte aber die Qualität senken. Wie reagieren Sie?',
    promptCs: 'Návrh šetří čas, ale mohl by snížit kvalitu. Jak zareagujete?',
    responseDe:
      'Obwohl der Einwand berechtigt ist, stimme ich dem Ziel zu und komme Ihnen beim Umfang entgegen.',
    responseCs: 'Přestože je námitka oprávněná, souhlasím s cílem a ustoupím vám v rozsahu.',
  },
  'chapter-72-propose-compromise': {
    wordLemmas: ['Kompromiss', 'Spielraum', 'einerseits', 'andererseits', 'unter der Bedingung'],
    grammarLessonId: 'paired-connectors-basic',
    grammarIdea: 'dvoudílný konektor einerseits ... andererseits pro vyvážený kompromis',
    grammarPattern: 'Einerseits ..., andererseits ... unter der Bedingung, dass ...',
    coachScenarioId: 'transfer-propose-compromise',
    sentenceStarter: 'Einerseits ...',
    promptDe: 'Wie verbinden Sie den frühen Termin mit ausreichender Prüfzeit?',
    promptCs: 'Jak spojíte brzký termín s dostatečným časem na kontrolu?',
    responseDe:
      'Einerseits liefern wir am Freitag eine Kurzfassung, andererseits folgt die Vollversion am Montag unter der Bedingung, dass genügend Prüfzeit bleibt.',
    responseCs:
      'Na jedné straně dodáme v pátek zkrácenou verzi, na druhé straně bude plná verze následovat v pondělí, ovšem jen za podmínky, že zbude dost času na kontrolu.',
  },
  'chapter-73-compare-project-options': {
    wordLemmas: ['Vorschlag', 'Auswirkung', 'abwägen', 'obwohl', 'Entscheidung'],
    grammarLessonId: 'complex-connectors',
    grammarIdea: 'spojka obwohl pro kontrast mezi výhodou a dopadem varianty',
    grammarPattern: 'Obwohl Variante A ..., hat Variante B ...',
    coachScenarioId: 'project-meeting',
    sentenceStarter: 'Obwohl Variante A ...',
    promptDe: 'Welche Auswirkungen haben die beiden Vorschläge auf das Team?',
    promptCs: 'Jaké dopady mají oba návrhy na tým?',
    responseDe:
      'Obwohl Vorschlag A günstiger ist, hat Vorschlag B positivere Auswirkungen auf das Team.',
    responseCs: 'Přestože je návrh A levnější, má návrh B příznivější dopady na tým.',
  },
  'chapter-74-specific-feedback': {
    wordLemmas: ['Rückmeldung', 'Missverständnis', 'Beobachtung', 'Wirkung', 'Erwartung'],
    grammarLessonId: 'complex-connectors',
    grammarIdea: 'oddělení pozorování a účinku pomocí jasné důsledkové vazby',
    grammarPattern: 'Meine Beobachtung ist, dass ...; dadurch ...',
    coachScenarioId: 'difficult-feedback',
    sentenceStarter: 'Meine Beobachtung ist, dass ...',
    promptDe: 'Welche konkrete Beobachtung möchten Sie ansprechen?',
    promptCs: 'Jaké konkrétní pozorování chcete zmínit?',
    responseDe:
      'Meine Beobachtung ist, dass zwei Übergaben fehlten; dadurch entstand ein Missverständnis über den Bearbeitungsstand. Das ist noch keine Bewertung der Teamleistung.',
    responseCs:
      'Pozoruji, že chyběla dvě předání; proto vzniklo nedorozumění ohledně stavu zpracování. To ještě není hodnocení výkonu týmu.',
  },
  'chapter-75-calm-the-conflict': {
    wordLemmas: ['Missverständnis', 'ansprechen', 'wahrnehmen', 'nachvollziehen', 'vereinbaren'],
    grammarLessonId: 'hedging-and-distance',
    grammarIdea: 'zmírnění osobního hodnocení pomocí wahrnehmen a nachvollziehen',
    grammarPattern: 'Ich kann nachvollziehen, dass Sie ... wahrgenommen haben; ...',
    coachScenarioId: 'team-mediation',
    sentenceStarter: 'Ich kann nachvollziehen, dass ...',
    promptDe: 'Wie können wir das Missverständnis ansprechen, ohne den Konflikt zu verschärfen?',
    promptCs: 'Jak můžeme nedorozumění otevřít, aniž konflikt vyostříme?',
    responseDe:
      'Ich kann nachvollziehen, dass Sie den Ton anders wahrgenommen haben; lassen Sie uns einen nächsten Schritt vereinbaren.',
    responseCs: 'Chápu, že jste tón vnímala jinak; domluvme si další krok.',
  },
  'chapter-76-remote-work-pilot': {
    wordLemmas: ['Pilotphase', 'Erreichbarkeit', 'Kernzeit', 'Arbeitsort', 'Messgröße'],
    grammarLessonId: 'conditional-without-wenn',
    grammarIdea: 'podmínková věta bez wenn pro vymezení pilotu',
    grammarPattern: 'Sollte die Pilotphase starten, gelten ...',
    coachScenarioId: 'remote-work',
    sentenceStarter: 'Sollte die Pilotphase starten, ...',
    promptDe: 'Welchen Umfang soll der Homeoffice-Pilot haben?',
    promptCs: 'Jaký rozsah má mít pilot práce z domova?',
    responseDe:
      'Sollte die Pilotphase starten, gelten zwei mobile Arbeitstage und eine verbindliche Kernzeit.',
    responseCs:
      'Pokud pilotní fáze začne, budou platit dva mobilní pracovní dny a závazná hlavní pracovní doba.',
  },
  'chapter-77-measurable-criteria': {
    wordLemmas: ['Messgröße', 'Zwischenbilanz', 'ausweiten', 'erfassen', 'evaluieren'],
    grammarLessonId: 'future-with-werden',
    grammarIdea: 'budoucí vyhodnocení a podmínka rozšíření experimentu',
    grammarPattern: 'Wir werden ... erfassen; nur dann wird ... ausgeweitet.',
    coachScenarioId: 'transfer-measurable-criteria',
    sentenceStarter: 'Wir werden ... erfassen.',
    promptDe: 'Welche Messgrößen entscheiden nach sechs Wochen über den Pilot?',
    promptCs: 'Které metriky po šesti týdnech rozhodnou o pilotu?',
    responseDe:
      'Wir werden Bearbeitungszeit und Fehlerquote erfassen; nur bei einer positiven Zwischenbilanz wird der Pilot ausgeweitet.',
    responseCs:
      'Budeme měřit dobu zpracování a chybovost; pilot se rozšíří jen při pozitivním průběžném hodnocení.',
  },
  'chapter-78-experiment-conditions': {
    wordLemmas: [
      'ortsunabhängig',
      'verbindlich',
      'unter Vorbehalt',
      'vorausgesetzt',
      'Videokonferenz',
    ],
    grammarLessonId: 'conditional-without-wenn',
    grammarIdea: 'formální podmínka s vorausgesetzt pro pravidla experimentu',
    grammarPattern: 'Vorausgesetzt, ..., kann ...',
    coachScenarioId: 'hybrid-team-coordination',
    sentenceStarter: 'Vorausgesetzt, ...',
    promptDe: 'Unter welchen Bedingungen kann das Team ortsunabhängig arbeiten?',
    promptCs: 'Za jakých podmínek může tým pracovat nezávisle na místě?',
    responseDe:
      'Vorausgesetzt, die Kernzeit und die Videokonferenz bleiben verbindlich, kann das Team ortsunabhängig arbeiten.',
    responseCs:
      'Za předpokladu, že hlavní pracovní doba a videokonference zůstanou závazné, může tým pracovat nezávisle na místě.',
  },
  'chapter-79-evidence-based-decision': {
    wordLemmas: ['Arbeitsablauf', 'Messgröße', 'Zwischenbilanz', 'erfassen', 'evaluieren'],
    grammarLessonId: 'past-sequence',
    grammarIdea: 'předčasnost výsledku vyjádřená časovou návazností po vyhodnocení',
    grammarPattern: 'Nachdem wir ... evaluiert haben, ...',
    coachScenarioId: 'transfer-evidence-decision',
    sentenceStarter: 'Nachdem wir ...',
    promptDe: 'Welche Entscheidung erlauben die bisherigen Messgrößen?',
    promptCs: 'Jaké rozhodnutí dovolují dosavadní metriky?',
    responseDe:
      'Nachdem wir den Arbeitsablauf sechs Wochen evaluiert haben, spricht die Zwischenbilanz für eine zweite Testphase.',
    responseCs:
      'Po šesti týdnech vyhodnocování pracovního postupu průběžná bilance podporuje druhou testovací fázi.',
  },
  'chapter-80-set-conditions': {
    wordLemmas: ['Frist', 'Kompromiss', 'einräumen', 'unter der Voraussetzung', 'Einwand'],
    grammarLessonId: 'concession-patterns',
    grammarIdea: 'ústup a podmínka v jedné vyjednávací reakci',
    grammarPattern: 'Ich räume ein, dass ...; unter der Voraussetzung, dass ...',
    coachScenarioId: 'deadline-negotiation',
    sentenceStarter: 'Ich räume ein, dass ...',
    promptDe: 'Unter welcher Voraussetzung können Sie eine längere Frist akzeptieren?',
    promptCs: 'Za jaké podmínky můžete přijmout delší lhůtu?',
    responseDe:
      'Ich räume ein, dass die Frist knapp ist; unter der Voraussetzung, dass wir den Umfang verkleinern, finden wir einen Kompromiss.',
    responseCs:
      'Připouštím, že je lhůta krátká; kompromis najdeme za podmínky, že zmenšíme rozsah.',
  },
  'chapter-81-core-of-complaint': {
    wordLemmas: ['Beanstandung', 'Entschuldigung', 'Abhilfe', 'Bearbeitungszeit', 'prüfen'],
    grammarLessonId: 'passive-agent-and-tense',
    grammarIdea: 'pasivum pro věcné shrnutí stavu reklamace',
    grammarPattern: 'Die Beanstandung wird ... geprüft; anschließend ...',
    coachScenarioId: 'customer-complaint',
    sentenceStarter: 'Die Beanstandung wird ...',
    promptDe: 'Fassen Sie bitte zusammen, was mit meiner Beschwerde geschieht.',
    promptCs: 'Shrňte prosím, co se bude dít s mou stížností.',
    responseDe:
      'Die Beanstandung wird heute geprüft; anschließend nennen wir die Ursache, die Bearbeitungszeit und konkrete Abhilfe.',
    responseCs:
      'Reklamace bude dnes prověřena; následně uvedeme příčinu, dobu zpracování a konkrétní nápravu.',
  },
  'chapter-82-proportionate-responsibility': {
    wordLemmas: ['Beanstandung', 'Abhilfe', 'Zuordnung', 'verursachen', 'prüfen'],
    grammarLessonId: 'passive-agent-and-tense',
    grammarIdea: 'pasivum s původcem pro oddělení příčiny a odpovědnosti',
    grammarPattern: 'Der Fehler wurde durch ... verursacht, aber ...',
    coachScenarioId: 'transfer-proportionate-responsibility',
    sentenceStarter: 'Der Fehler wurde durch ...',
    promptDe: 'Wer trägt welchen Anteil an der Verantwortung?',
    promptCs: 'Kdo nese jaký podíl odpovědnosti?',
    responseDe:
      'Der Fehler wurde durch eine falsche Zuordnung verursacht, aber die Verantwortung muss im gesamten Prozess geprüft werden.',
    responseCs:
      'Chybu způsobilo nesprávné přiřazení, ale odpovědnost je nutné prověřit v celém procesu.',
  },
  'chapter-83-remedy-with-deadline': {
    wordLemmas: ['Abhilfe', 'Gutschrift', 'Bearbeitungszeit', 'nachliefern', 'unverzüglich'],
    grammarLessonId: 'passive-with-modals',
    grammarIdea: 'pasivum s termínem pro konkrétní a ověřitelnou nápravu',
    grammarPattern: '... muss bis ... nachgeliefert werden, und ... soll ... werden.',
    coachScenarioId: 'customer-complaint',
    sentenceStarter: 'Das fehlende Teil wird ...',
    promptDe: 'Welche Abhilfe bieten Sie an, und bis wann ist sie abgeschlossen?',
    promptCs: 'Jakou nápravu nabízíte a dokdy bude dokončena?',
    responseDe:
      'Das fehlende Teil muss bis Freitag nachgeliefert werden, und die Gutschrift soll unverzüglich ausgestellt werden.',
    responseCs: 'Chybějící díl musí být dodán do pátku a dobropis má být vystaven neprodleně.',
  },
  'chapter-84-describe-a-trend': {
    wordLemmas: ['Datensatz', 'Anteil', 'Schwankung', 'ansteigen', 'zurückgehen'],
    grammarLessonId: 'praeteritum-lexical-verbs',
    grammarIdea: 'préteritum silných sloves při přesném popisu změny v čase',
    grammarPattern: 'Der Anteil stieg ..., ging danach ... zurück; ...',
    coachScenarioId: 'transfer-describe-trend',
    sentenceStarter: 'Der Anteil stieg ...',
    promptDe: 'Wie entwickelte sich der Anteil im Datensatz über das Jahr?',
    promptCs: 'Jak se podíl v datovém souboru během roku vyvíjel?',
    responseDe:
      'Der Anteil stieg bis Juli deutlich an und ging danach leicht zurück; die Schwankung blieb gering.',
    responseCs: 'Podíl do července výrazně rostl a potom mírně klesl; kolísání zůstalo malé.',
  },
  'chapter-85-correlation-not-cause': {
    wordLemmas: ['Zusammenhang', 'Stichprobe', 'Abweichung', 'hindeuten', 'belegen'],
    grammarLessonId: 'focus-constructions',
    grammarIdea: 'vymezení toho, co data ukazují a co už nedokazují',
    grammarPattern: 'Was ... betrifft, deuten ... hin, belegen aber nicht ...',
    coachScenarioId: 'transfer-correlation-caution',
    sentenceStarter: 'Was den Zusammenhang betrifft, ...',
    promptDe: 'Belegen die Daten bereits eine Ursache?',
    promptCs: 'Dokazují data už příčinu?',
    responseDe:
      'Was den Zusammenhang betrifft, deuten die Daten darauf hin; wegen der kleinen Stichprobe belegen sie jedoch keine Ursache.',
    responseCs:
      'Pokud jde o souvislost, data na ni ukazují, ale kvůli malému vzorku nedokazují příčinu.',
  },
  'chapter-86-limited-recommendation': {
    wordLemmas: [
      'Datensatz',
      'Stichprobe',
      'annähernd',
      'aussagekräftig',
      'unter Berücksichtigung',
    ],
    grammarLessonId: 'right-field-structure',
    grammarIdea: 'odsunutí těžkého omezení za hlavní doporučení',
    grammarPattern: 'Unter Berücksichtigung ... ist ... noch nicht ... genug, um ...',
    coachScenarioId: 'transfer-limited-recommendation',
    sentenceStarter: 'Unter Berücksichtigung ...',
    promptDe: 'Welche Empfehlung ist trotz der kleinen Stichprobe vertretbar?',
    promptCs: 'Jaké doporučení je obhajitelné navzdory malému vzorku?',
    responseDe:
      'Unter Berücksichtigung der kleinen Stichprobe ist der Datensatz noch nicht aussagekräftig genug, um eine dauerhafte Einführung zu empfehlen.',
    responseCs:
      'S ohledem na malý vzorek není datový soubor ještě dostatečně vypovídající pro doporučení trvalého zavedení.',
  },
  'chapter-87-strength-of-evidence': {
    wordLemmas: ['Befund', 'Annahme', 'Evidenz', 'Gegenargument', 'vorläufig'],
    grammarLessonId: 'epistemic-modals',
    grammarIdea: 'epistemické modální sloveso pro kalibraci síly závěru',
    grammarPattern: 'Der Befund dürfte ..., die Evidenz reicht jedoch nur ...',
    coachScenarioId: 'academic-seminar',
    sentenceStarter: 'Der Befund dürfte ...',
    promptDe: 'Wie stark stützt dieser Befund die Annahme?',
    promptCs: 'Jak silně tento nález podporuje předpoklad?',
    responseDe:
      'Der Befund dürfte die Annahme stützen, die Evidenz reicht jedoch nur für einen vorläufigen Schluss.',
    responseCs:
      'Nález pravděpodobně podporuje předpoklad, důkazy však stačí jen k předběžnému závěru.',
  },
  'chapter-88-transparent-limitation': {
    wordLemmas: ['Vorbehalt', 'untermauern', 'widerlegen', 'einordnen', 'nahelegen'],
    grammarLessonId: 'hedging-and-distance',
    grammarIdea: 'jazykový odstup, který přizná omezení bez znehodnocení výsledku',
    grammarPattern: 'Unter diesem Vorbehalt lässt sich ..., ohne ... zu ...',
    coachScenarioId: 'defend-position',
    sentenceStarter: 'Unter diesem Vorbehalt ...',
    promptDe: 'Wie nennen Sie die methodische Grenze, ohne den Befund zu verwerfen?',
    promptCs: 'Jak pojmenujete metodické omezení, aniž nález zavrhnete?',
    responseDe:
      'Unter diesem Vorbehalt lässt sich der Befund einordnen, ohne die gesamte Schlussfolgerung zu widerlegen.',
    responseCs: 'S touto výhradou lze nález zasadit do kontextu, aniž by byl vyvrácen celý závěr.',
  },
  'chapter-89-report-a-claim': {
    wordLemmas: ['Berichterstattung', 'Stellungnahme', 'Wortlaut', 'Zuschreibung', 'Dementi'],
    grammarLessonId: 'indirect-speech',
    grammarIdea: 'konjunktiv I pro přesnou reprodukci cizího tvrzení',
    grammarPattern: 'In der Stellungnahme hieß es, ... sei ...',
    coachScenarioId: 'media-interview',
    sentenceStarter: 'In der Stellungnahme hieß es, ...',
    promptDe: 'Wie geben Sie den Wortlaut der Stellungnahme mit klarer Zuschreibung wieder?',
    promptCs: 'Jak reprodukujete znění stanoviska s jasným připsáním zdroji?',
    responseDe:
      'In der Stellungnahme hieß es, der Wortlaut sei in der Berichterstattung verkürzt wiedergegeben worden.',
    responseCs: 'Ve stanovisku stálo, že znění bylo ve zpravodajství reprodukováno zkráceně.',
  },
  'chapter-90-source-and-comment': {
    wordLemmas: ['Quelle', 'zitieren', 'laut Angaben', 'wörtlich', 'sinngemäß'],
    grammarLessonId: 'source-attribution-phrases',
    grammarIdea: 'atribuce pomocí laut Angaben před odděleným redakčním komentářem',
    grammarPattern: 'Laut Angaben der Quelle ...; die Redaktion kommentiert ...',
    coachScenarioId: 'transfer-source-and-comment',
    sentenceStarter: 'Laut Angaben der Quelle ...',
    promptDe: 'Was meldet die Quelle, und was ist Ihre eigene Einordnung?',
    promptCs: 'Co uvádí zdroj a co je vaše vlastní interpretace?',
    responseDe:
      'Laut Angaben der Quelle stieg die Teilnahme; die Redaktion kommentiert, dass dies noch keine Ursache belegt.',
    responseCs:
      'Podle údajů zdroje účast vzrostla; redakce dodává, že to ještě nedokazuje příčinu.',
  },
  'chapter-91-calibrate-uncertainty': {
    wordLemmas: ['Quelle', 'laut Angaben', 'angeblich', 'nachprüfen', 'glaubwürdig'],
    grammarLessonId: 'evidential-sollen-wollen',
    grammarIdea: 'evidenční sollen pro nepotvrzenou informaci převzatou ze zdroje',
    grammarPattern: 'Laut Angaben ... soll ...; ... muss das nachprüfen.',
    coachScenarioId: 'fact-checking-briefing',
    sentenceStarter: 'Laut Angaben der Quelle ...',
    promptDe: 'Wie formulieren Sie die Meldung, solange die Angabe noch nicht bestätigt ist?',
    promptCs: 'Jak zprávu formulujete, dokud údaj není potvrzený?',
    responseDe:
      'Laut Angaben der Quelle soll die Zahl gesunken sein; die Redaktion muss das noch nachprüfen.',
    responseCs: 'Podle údajů zdroje měl počet klesnout; redakce to ještě musí ověřit.',
  },
  'chapter-92-compare-media-claims': {
    wordLemmas: ['Quelle', 'Schlagzeile', 'Reichweite', 'Falschmeldung', 'nachprüfen'],
    grammarLessonId: 'negation-scope',
    grammarIdea: 'přesný rozsah záporu ve větě nicht jede',
    grammarPattern: 'Nicht jede ... ist ...; entscheidend sind ...',
    coachScenarioId: 'transfer-compare-media-claims',
    sentenceStarter: 'Nicht jede Schlagzeile ...',
    promptDe: 'Ist eine zugespitzte Schlagzeile automatisch eine Falschmeldung?',
    promptCs: 'Je vyhrocený titulek automaticky falešnou zprávou?',
    responseDe:
      'Nicht jede zugespitzte Schlagzeile ist eine Falschmeldung; entscheidend sind Quelle, Zeitraum und nachprüfbare Daten.',
    responseCs:
      'Ne každý vyhrocený titulek je falešná zpráva; rozhodující jsou zdroj, období a ověřitelná data.',
  },
  'chapter-93-answer-counterargument': {
    wordLemmas: ['Behauptung', 'Standpunkt', 'widerlegen', 'demnach', 'Einordnung'],
    grammarLessonId: 'indirect-speech',
    grammarIdea: 'nepřímá řeč pro férové shrnutí protiargumentu před odpovědí',
    grammarPattern: 'Der Einwand lautet, ... sei ...; demnach ...',
    coachScenarioId: 'defend-position',
    sentenceStarter: 'Der Einwand lautet, ...',
    promptDe: 'Wie lautet das stärkste Gegenargument, und was folgt daraus für Ihren Standpunkt?',
    promptCs: 'Jak zní nejsilnější protiargument a co z něj plyne pro vaše stanovisko?',
    responseDe:
      'Der Einwand lautet, die Behauptung sei nicht belegt; demnach muss ich meinen Standpunkt genauer einordnen.',
    responseCs:
      'Námitka zní, že tvrzení není doložené; podle toho musím své stanovisko přesněji zasadit.',
  },
  'chapter-94-cut-clumsy-text': {
    wordLemmas: ['Formulierung', 'präzisieren', 'Voraussetzung', 'hinsichtlich', 'überarbeiten'],
    grammarLessonId: 'nominal-and-verbal-style',
    grammarIdea: 'nahrazení těžké nominalizace přesným slovesem',
    grammarPattern: 'Statt „eine ... vornehmen“ schreibe ich „...“.',
    coachScenarioId: 'transfer-concise-editing',
    sentenceStarter: 'Statt ... schreibe ich ...',
    promptDe:
      'Wie überarbeiten Sie die schwerfällige Formulierung, ohne die Voraussetzung zu verlieren?',
    promptCs: 'Jak přepracujete těžkopádnou formulaci, aniž ztratíte podmínku?',
    responseDe:
      'Statt „eine Überarbeitung vornehmen“ schreibe ich „den Absatz überarbeiten“ und präzisiere die Voraussetzung.',
    responseCs: 'Místo „provést přepracování“ napíšu „přepracovat odstavec“ a upřesním podmínku.',
  },
  'chapter-95-neutral-summary': {
    wordLemmas: ['Übereinstimmung', 'Differenz', 'Kernanliegen', 'Gesprächsrahmen', 'Einigung'],
    grammarLessonId: 'hedging-and-distance',
    grammarIdea: 'neutrální rozsah shody bez hodnotícího zesílení',
    grammarPattern: 'Beide Seiten teilen im Wesentlichen ..., die Differenz betrifft ...',
    coachScenarioId: 'team-mediation',
    sentenceStarter: 'Beide Seiten teilen ...',
    promptDe: 'Wo besteht Übereinstimmung, und worin liegt die Differenz?',
    promptCs: 'V čem panuje shoda a v čem spočívá rozdíl?',
    responseDe:
      'Beide Seiten teilen im Wesentlichen das Kernanliegen; die Differenz betrifft den Weg zu einer Einigung.',
    responseCs: 'Obě strany se v zásadě shodují na hlavním zájmu; rozdíl se týká cesty k dohodě.',
  },
  'chapter-96-false-agreement': {
    wordLemmas: [
      'Übereinstimmung',
      'Differenz',
      'paraphrasieren',
      'auseinanderhalten',
      'festhalten',
    ],
    grammarLessonId: 'nuanced-connectors',
    grammarIdea: 'ústupková spojka obwohl pro rozlišení stejného slova a jiných kritérií',
    grammarPattern: 'Obwohl beide ..., muss ich ... auseinanderhalten.',
    coachScenarioId: 'transfer-false-agreement',
    sentenceStarter: 'Obwohl beide ...',
    promptDe: 'Beide Seiten sagen „fair“. Ist das bereits echte Übereinstimmung?',
    promptCs: 'Obě strany říkají „spravedlivé“. Je to už skutečná shoda?',
    responseDe:
      'Obwohl beide von Fairness sprechen, muss ich die Differenz zwischen ihren Kriterien festhalten und die Begriffe auseinanderhalten.',
    responseCs:
      'Přestože obě strany mluví o spravedlnosti, musím zaznamenat rozdíl mezi jejich kritérii a rozlišit používané pojmy.',
  },
  'chapter-97-procedural-next-step': {
    wordLemmas: ['Verfahrensschritt', 'vermitteln', 'festhalten', 'keinesfalls', 'unter Wahrung'],
    grammarLessonId: 'noun-verb-collocations',
    grammarIdea: 'funkční vazba einen Schritt festhalten bez předstírání dohody',
    grammarPattern: 'Als nächsten Verfahrensschritt halten wir ... fest, ohne ...',
    coachScenarioId: 'team-mediation',
    sentenceStarter: 'Als nächsten Verfahrensschritt ...',
    promptDe: 'Welcher nächste Schritt ist möglich, obwohl noch keine Einigung besteht?',
    promptCs: 'Jaký další krok je možný, přestože ještě neexistuje dohoda?',
    responseDe:
      'Als nächsten Verfahrensschritt halten wir die offenen Punkte fest, ohne eine Einigung vorzutäuschen.',
    responseCs:
      'Jako další procesní krok zaznamenáme otevřené body, aniž bychom předstírali dohodu.',
  },
  'chapter-98-synthesise-inputs': {
    wordLemmas: ['Handlungsoption', 'Abwägung', 'Leitkriterium', 'Umsetzbarkeit', 'Folgewirkung'],
    grammarLessonId: 'c1-editing-checkpoint',
    grammarIdea: 'paralelní syntéza společného základu a rozdílného hodnocení',
    grammarPattern: 'Beide ... nennen ..., gewichten ... jedoch unterschiedlich.',
    coachScenarioId: 'transfer-synthesise-inputs',
    sentenceStarter: 'Beide Gutachten ...',
    promptDe: 'Was haben die beiden Gutachten gemeinsam, und worin unterscheiden sie sich?',
    promptCs: 'Co mají oba posudky společné a v čem se liší?',
    responseDe:
      'Beide Gutachten nennen dieselben Handlungsoptionen, gewichten Umsetzbarkeit und Folgewirkung jedoch unterschiedlich.',
    responseCs:
      'Oba posudky uvádějí stejné možnosti postupu, ale rozdílně váží proveditelnost a následné dopady.',
  },
  'chapter-99-state-the-limits': {
    wordLemmas: [
      'Entscheidungsgrundlage',
      'synthetisieren',
      'priorisieren',
      'offenlegen',
      'ableiten',
    ],
    grammarLessonId: 'hedging-and-distance',
    grammarIdea: 'omezená platnost toho, co lze z dostupných podkladů odvodit',
    grammarPattern: 'Aus der vorläufigen ... lässt sich nur ... ableiten.',
    coachScenarioId: 'policy-consultation',
    sentenceStarter: 'Aus der vorläufigen Entscheidungsgrundlage ...',
    promptDe: 'Welche Grenzen der Entscheidungsgrundlage müssen Sie offenlegen?',
    promptCs: 'Které meze rozhodovacího podkladu musíte otevřeně uvést?',
    responseDe:
      'Aus der vorläufigen Entscheidungsgrundlage lässt sich nur nach Offenlegung der Risiken eine begrenzte Empfehlung ableiten.',
    responseCs:
      'Z předběžného rozhodovacího podkladu lze odvodit omezené doporučení jen tehdy, když otevřeně uvedeme rizika.',
  },
  'chapter-100-decision-recommendation': {
    wordLemmas: [
      'Handlungsoption',
      'Umsetzbarkeit',
      'vorbehaltlich',
      'maßgeblich',
      'unter Abwägung',
    ],
    grammarLessonId: 'c1-editing-checkpoint',
    grammarIdea: 'stručné doporučení, kritérium a podmínka pozdější revize',
    grammarPattern: 'Unter Abwägung ... empfehle ich ..., vorbehaltlich ...',
    coachScenarioId: 'transfer-decision-recommendation',
    sentenceStarter: 'Unter Abwägung aller Kriterien ...',
    promptDe:
      'Welche Handlungsoption empfehlen Sie, und welche Sicherung braucht die Entscheidung?',
    promptCs: 'Kterou možnost postupu doporučujete a jakou pojistku rozhodnutí potřebuje?',
    responseDe:
      'Unter Abwägung aller Kriterien empfehle ich Handlungsoption B, vorbehaltlich einer Überprüfung nach zwölf Monaten.',
    responseCs:
      'Po zvážení všech kritérií doporučuji možnost B s výhradou kontroly po dvanácti měsících.',
  },
};

export const TRANSFER_CHAPTER_THREAD_COUNT = Object.keys(transferChapterThreads).length;
