import type { Article, CefrLevel, LexemeKind, VerbForms } from '../types.ts';
import type { FutureChapterVocabularyPack } from './future-chapter-vocabulary.ts';
import type { CourseWord } from './path.ts';

type WordDraftBase = {
  german: string;
  czech: string;
  exampleDe: string;
  exampleCs: string;
  collocation: string;
};

type NounDraft = {
  kind: 'noun';
  article: Article;
  plural: string;
} & WordDraftBase;

type VerbDraft = {
  kind: 'verb';
  forms: [string, string, string, VerbForms['auxiliary']];
} & WordDraftBase;

type TermDraft = {
  kind: Exclude<LexemeKind, 'noun' | 'verb'>;
} & WordDraftBase;

type WordDraft = NounDraft | VerbDraft | TermDraft;

function noun(
  german: string,
  czech: string,
  article: Article,
  plural: string,
  exampleDe: string,
  exampleCs: string,
  collocation: string,
): NounDraft {
  return { kind: 'noun', german, czech, article, plural, exampleDe, exampleCs, collocation };
}

function verb(
  german: string,
  czech: string,
  forms: VerbDraft['forms'],
  exampleDe: string,
  exampleCs: string,
  collocation: string,
): VerbDraft {
  return { kind: 'verb', german, czech, forms, exampleDe, exampleCs, collocation };
}

function term(
  german: string,
  czech: string,
  kind: TermDraft['kind'],
  exampleDe: string,
  exampleCs: string,
  collocation: string,
): TermDraft {
  return { kind, german, czech, exampleDe, exampleCs, collocation };
}

function vocabularyPack(
  definition: Omit<FutureChapterVocabularyPack, 'words'> & { words: WordDraft[] },
): FutureChapterVocabularyPack {
  const cefr = definition.level.slice(0, 2) as CefrLevel;
  return {
    ...definition,
    words: definition.words.map((draft): CourseWord => {
      const common = {
        german: draft.german,
        czech: draft.czech,
        kind: draft.kind,
        cefr,
        role: 'target' as const,
        exampleDe: draft.exampleDe,
        exampleCs: draft.exampleCs,
        contexts: [draft.exampleDe],
        collocations: [draft.collocation],
        acceptedCzech: [],
      };
      if (draft.kind === 'noun') {
        return { ...common, article: draft.article, plural: draft.plural };
      }
      if (draft.kind === 'verb') {
        return {
          ...common,
          verbForms: {
            thirdPerson: draft.forms[0],
            preterite: draft.forms[1],
            participle: draft.forms[2],
            auxiliary: draft.forms[3],
          },
        };
      }
      return common;
    }),
  };
}

export const diversityVocabularyPacks: FutureChapterVocabularyPack[] = [
  vocabularyPack({
    id: 'market-groceries',
    level: 'A1.1',
    title: 'Nákup na trhu',
    situation: 'Výběr čerstvých potravin, určení množství a kontrola výsledné ceny.',
    grammarLessonIds: ['numbers-and-prices', 'quantity-words'],
    coachScenarioIds: ['market-shopping'],
    words: [
      noun(
        'Wochenmarkt',
        'týdenní trh',
        'der',
        'Wochenmärkte',
        'Der Wochenmarkt ist jeden Samstag geöffnet.',
        'Týdenní trh je otevřený každou sobotu.',
        'auf dem Wochenmarkt einkaufen',
      ),
      noun(
        'Einkaufszettel',
        'nákupní seznam',
        'der',
        'Einkaufszettel',
        'Auf meinem Einkaufszettel stehen fünf Dinge.',
        'Na mém nákupním seznamu je pět věcí.',
        'einen Einkaufszettel schreiben',
      ),
      noun(
        'Tomate',
        'rajče',
        'die',
        'Tomaten',
        'Die Tomate ist rot und reif.',
        'Rajče je červené a zralé.',
        'reife Tomaten kaufen',
      ),
      noun(
        'Gurke',
        'okurka',
        'die',
        'Gurken',
        'Ich nehme eine Gurke für den Salat.',
        'Vezmu jednu okurku do salátu.',
        'eine frische Gurke',
      ),
      noun(
        'Stoffbeutel',
        'látková taška',
        'der',
        'Stoffbeutel',
        'Das Gemüse kommt in meinen Stoffbeutel.',
        'Zelenina přijde do mé látkové tašky.',
        'einen Stoffbeutel mitbringen',
      ),
      verb(
        'auswählen',
        'vybrat',
        ['wählt aus', 'wählte aus', 'ausgewählt', 'haben'],
        'Ich wähle drei reife Tomaten aus.',
        'Vyberu tři zralá rajčata.',
        'Obst sorgfältig auswählen',
      ),
      verb(
        'abwiegen',
        'odvážit',
        ['wiegt ab', 'wog ab', 'abgewogen', 'haben'],
        'Die Verkäuferin wiegt ein Kilo Kartoffeln ab.',
        'Prodavačka odváží kilo brambor.',
        'ein Kilo Gemüse abwiegen',
      ),
      verb(
        'dazulegen',
        'přidat k nákupu',
        ['legt dazu', 'legte dazu', 'dazugelegt', 'haben'],
        'Bitte legen Sie noch zwei Äpfel dazu.',
        'Přidejte prosím ještě dvě jablka.',
        'noch ein Stück dazulegen',
      ),
      term(
        'regional',
        'místní',
        'adjective',
        'Diese Kartoffeln sind regional.',
        'Tyto brambory jsou místní.',
        'regionale Produkte',
      ),
      term(
        'kiloweise',
        'po kilech',
        'other',
        'Die Äpfel werden kiloweise verkauft.',
        'Jablka se prodávají po kilech.',
        'Obst kiloweise verkaufen',
      ),
    ],
  }),
  vocabularyPack({
    id: 'hobby-meetup',
    level: 'A1.1',
    title: 'Volný čas a společný koníček',
    situation: 'Výběr volnočasové aktivity, domluva místa a první návštěva skupiny.',
    grammarLessonIds: ['present-endings', 'coordinating-connectors'],
    coachScenarioIds: ['hobby-meetup'],
    words: [
      noun(
        'Freizeitgruppe',
        'volnočasová skupina',
        'die',
        'Freizeitgruppen',
        'Unsere Freizeitgruppe trifft sich am Freitag.',
        'Naše volnočasová skupina se schází v pátek.',
        'eine Freizeitgruppe finden',
      ),
      noun(
        'Spieleabend',
        'večer deskových her',
        'der',
        'Spieleabende',
        'Der Spieleabend beginnt um sechs Uhr.',
        'Večer deskových her začíná v šest hodin.',
        'zu einem Spieleabend kommen',
      ),
      noun(
        'Zeichenblock',
        'skicák',
        'der',
        'Zeichenblöcke',
        'Mein Zeichenblock liegt schon auf dem Tisch.',
        'Můj skicák už leží na stole.',
        'einen Zeichenblock mitbringen',
      ),
      noun(
        'Kletterhalle',
        'lezecká hala',
        'die',
        'Kletterhallen',
        'Die Kletterhalle ist neben dem Bahnhof.',
        'Lezecká hala je vedle nádraží.',
        'in der Kletterhalle trainieren',
      ),
      noun(
        'Schnupperkurs',
        'ukázkový kurz',
        'der',
        'Schnupperkurse',
        'Der Schnupperkurs kostet nichts.',
        'Ukázkový kurz nic nestojí.',
        'einen Schnupperkurs besuchen',
      ),
      verb(
        'sich verabreden',
        'domluvit si setkání',
        ['verabredet sich', 'verabredete sich', 'sich verabredet', 'haben'],
        'Wir verabreden uns für Samstag.',
        'Domluvíme se na sobotu.',
        'sich für das Wochenende verabreden',
      ),
      verb(
        'vorbeikommen',
        'stavit se',
        ['kommt vorbei', 'kam vorbei', 'vorbeigekommen', 'sein'],
        'Kannst du am Freitag vorbeikommen?',
        'Můžeš se v pátek stavit?',
        'am Abend vorbeikommen',
      ),
      verb(
        'mitspielen',
        'hrát s ostatními',
        ['spielt mit', 'spielte mit', 'mitgespielt', 'haben'],
        'Heute spielt eine neue Person mit.',
        'Dnes hraje s námi nový člověk.',
        'bei einer Runde mitspielen',
      ),
      verb(
        'fotografieren',
        'fotografovat',
        ['fotografiert', 'fotografierte', 'fotografiert', 'haben'],
        'Im Park fotografieren wir alte Bäume.',
        'V parku fotografujeme staré stromy.',
        'gemeinsam fotografieren',
      ),
      verb(
        'ausprobieren',
        'vyzkoušet',
        ['probiert aus', 'probierte aus', 'ausprobiert', 'haben'],
        'Ich möchte das Klettern ausprobieren.',
        'Chci si vyzkoušet lezení.',
        'ein neues Hobby ausprobieren',
      ),
    ],
  }),
  vocabularyPack({
    id: 'civic-services',
    level: 'A2.1',
    title: 'Vyřízení na úřadě',
    situation: 'Příprava dokladů, získání pořadového čísla a podání jednoduché žádosti.',
    grammarLessonIds: ['dative', 'indirect-questions'],
    coachScenarioIds: ['civic-office'],
    words: [
      noun(
        'Bürgeramt',
        'občanský úřad',
        'das',
        'Bürgerämter',
        'Das Bürgeramt öffnet heute um acht Uhr.',
        'Občanský úřad dnes otevírá v osm hodin.',
        'einen Termin beim Bürgeramt buchen',
      ),
      noun(
        'Meldebescheinigung',
        'potvrzení o bydlišti',
        'die',
        'Meldebescheinigungen',
        'Für den Vertrag brauche ich eine Meldebescheinigung.',
        'Ke smlouvě potřebuji potvrzení o bydlišti.',
        'eine Meldebescheinigung beantragen',
      ),
      noun(
        'Wartemarke',
        'pořadový lístek',
        'die',
        'Wartemarken',
        'Am Eingang ziehe ich eine Wartemarke.',
        'U vchodu si vezmu pořadový lístek.',
        'eine Wartemarke ziehen',
      ),
      noun(
        'Öffnungszeit',
        'otevírací doba',
        'die',
        'Öffnungszeiten',
        'Die Öffnungszeit steht auf der Internetseite.',
        'Otevírací doba je uvedená na webu.',
        'die Öffnungszeiten prüfen',
      ),
      noun(
        'Wohnsitz',
        'bydliště',
        'der',
        'Wohnsitze',
        'Mein neuer Wohnsitz ist in Leipzig.',
        'Moje nové bydliště je v Lipsku.',
        'den Wohnsitz anmelden',
      ),
      verb(
        'beantragen',
        'požádat o vydání',
        ['beantragt', 'beantragte', 'beantragt', 'haben'],
        'Ich beantrage einen neuen Ausweis.',
        'Žádám o nový průkaz.',
        'ein Dokument beantragen',
      ),
      verb(
        'vorlegen',
        'předložit',
        ['legt vor', 'legte vor', 'vorgelegt', 'haben'],
        'Bitte legen Sie Ihren Pass vor.',
        'Předložte prosím svůj pas.',
        'einen gültigen Pass vorlegen',
      ),
      verb(
        'ausfüllen',
        'vyplnit',
        ['füllt aus', 'füllte aus', 'ausgefüllt', 'haben'],
        'Ich fülle das Formular zu Hause aus.',
        'Formulář vyplním doma.',
        'ein Formular vollständig ausfüllen',
      ),
      term(
        'terminpflichtig',
        'vyžadující objednání',
        'adjective',
        'Diese Dienstleistung ist terminpflichtig.',
        'Tato služba vyžaduje předchozí objednání.',
        'ein terminpflichtiger Behördengang',
      ),
      term(
        'persönlich',
        'osobně',
        'other',
        'Den Antrag muss ich persönlich abgeben.',
        'Žádost musím odevzdat osobně.',
        'persönlich erscheinen',
      ),
    ],
  }),
  vocabularyPack({
    id: 'cultural-evening',
    level: 'A2.2',
    title: 'Kulturní večer',
    situation: 'Výběr představení, zajištění vstupenek a orientace v divadle.',
    grammarLessonIds: ['time-manner-place', 'weil-dass'],
    coachScenarioIds: ['cultural-evening'],
    words: [
      noun(
        'Eintrittskarte',
        'vstupenka',
        'die',
        'Eintrittskarten',
        'Unsere Eintrittskarten liegen an der Kasse bereit.',
        'Naše vstupenky jsou připravené u pokladny.',
        'zwei Eintrittskarten reservieren',
      ),
      noun(
        'Vorstellung',
        'představení',
        'die',
        'Vorstellungen',
        'Die Vorstellung dauert neunzig Minuten.',
        'Představení trvá devadesát minut.',
        'eine Vorstellung besuchen',
      ),
      noun(
        'Programmheft',
        'program',
        'das',
        'Programmhefte',
        'Im Programmheft stehen alle Namen.',
        'V programu jsou uvedena všechna jména.',
        'im Programmheft nachlesen',
      ),
      noun(
        'Einlass',
        'vstup do sálu',
        'der',
        '—',
        'Der Einlass beginnt eine halbe Stunde vorher.',
        'Vstup do sálu začíná o půl hodiny dříve.',
        'auf den Einlass warten',
      ),
      noun(
        'Garderobe',
        'šatna',
        'die',
        'Garderoben',
        'Unsere Jacken bleiben an der Garderobe.',
        'Naše bundy zůstanou v šatně.',
        'eine Jacke an der Garderobe abgeben',
      ),
      verb(
        'aufführen',
        'uvést na scéně',
        ['führt auf', 'führte auf', 'aufgeführt', 'haben'],
        'Das Ensemble führt ein modernes Stück auf.',
        'Soubor uvádí moderní hru.',
        'ein Theaterstück aufführen',
      ),
      verb(
        'stattfinden',
        'konat se',
        ['findet statt', 'fand statt', 'stattgefunden', 'haben'],
        'Das Konzert findet im großen Saal statt.',
        'Koncert se koná ve velkém sále.',
        'am Abend stattfinden',
      ),
      verb(
        'applaudieren',
        'tleskat',
        ['applaudiert', 'applaudierte', 'applaudiert', 'haben'],
        'Am Ende applaudiert das Publikum lange.',
        'Na konci publikum dlouho tleská.',
        'den Künstlern applaudieren',
      ),
      term(
        'ausverkauft',
        'vyprodaný',
        'adjective',
        'Die spätere Vorstellung ist bereits ausverkauft.',
        'Pozdější představení je už vyprodané.',
        'vollständig ausverkauft sein',
      ),
      term(
        'im Voraus',
        'předem',
        'phrase',
        'Wir kaufen die Karten im Voraus.',
        'Vstupenky kupujeme předem.',
        'rechtzeitig im Voraus buchen',
      ),
    ],
  }),
  vocabularyPack({
    id: 'workplace-onboarding',
    level: 'B1.1',
    title: 'První týden v nové práci',
    situation: 'Převzetí agendy, hledání správných kontaktů a ověření pracovního postupu.',
    grammarLessonIds: ['relative-clauses', 'verb-preposition-basics'],
    coachScenarioIds: ['workplace-onboarding'],
    words: [
      noun(
        'Einarbeitung',
        'zapracování',
        'die',
        'Einarbeitungen',
        'Die Einarbeitung dauert zwei Wochen.',
        'Zapracování trvá dva týdny.',
        'eine strukturierte Einarbeitung',
      ),
      noun(
        'Zuständigkeit',
        'kompetence',
        'die',
        'Zuständigkeiten',
        'Die Zuständigkeiten stehen im Teamhandbuch.',
        'Kompetence jsou uvedené v týmové příručce.',
        'eine Zuständigkeit klären',
      ),
      noun(
        'Übergabe',
        'předání agendy',
        'die',
        'Übergaben',
        'Für die Übergabe planen wir eine Stunde ein.',
        'Na předání agendy plánujeme jednu hodinu.',
        'eine vollständige Übergabe vorbereiten',
      ),
      noun(
        'Ansprechpartner',
        'kontaktní osoba',
        'der',
        'Ansprechpartner',
        'Mein Ansprechpartner arbeitet im Supportteam.',
        'Moje kontaktní osoba pracuje v týmu podpory.',
        'den richtigen Ansprechpartner finden',
      ),
      noun(
        'Übergabeprotokoll',
        'předávací protokol',
        'der',
        'Übergabeprotokolle',
        'Das Übergabeprotokoll nennt alle offenen Aufgaben.',
        'Předávací protokol uvádí všechny otevřené úkoly.',
        'ein Übergabeprotokoll prüfen',
      ),
      verb(
        'sich einarbeiten',
        'zapracovat se',
        ['arbeitet sich ein', 'arbeitete sich ein', 'sich eingearbeitet', 'haben'],
        'Ich arbeite mich gerade in das System ein.',
        'Právě se zapracovávám do systému.',
        'sich in ein Thema einarbeiten',
      ),
      verb(
        'weiterleiten',
        'přeposlat',
        ['leitet weiter', 'leitete weiter', 'weitergeleitet', 'haben'],
        'Bitte leite die Anfrage an mich weiter.',
        'Přepošli mi prosím ten dotaz.',
        'eine Nachricht intern weiterleiten',
      ),
      verb(
        'rückfragen',
        'doptat se',
        ['fragt rück', 'fragte rück', 'rückgefragt', 'haben'],
        'Bei Unklarheiten frage ich bei meiner Kollegin rück.',
        'Při nejasnostech se doptám kolegyně.',
        'bei der Teamleitung rückfragen',
      ),
      term(
        'nach und nach',
        'postupně',
        'other',
        'Ich übernehme die Aufgaben nach und nach.',
        'Úkoly přebírám postupně.',
        'nach und nach Verantwortung übernehmen',
      ),
      term(
        'ohne Aufsicht',
        'bez dohledu',
        'phrase',
        'Ab Montag bearbeite ich die Fälle ohne Aufsicht.',
        'Od pondělí zpracovávám případy bez dohledu.',
        'eine Aufgabe ohne Aufsicht erledigen',
      ),
    ],
  }),
  vocabularyPack({
    id: 'media-literacy',
    level: 'B1.2',
    title: 'Ověřování zpráv',
    situation: 'Kontrola titulku, dohledání původního zdroje a vysvětlení míry důvěryhodnosti.',
    grammarLessonIds: ['da-wo-compounds', 'adjective-prepositions'],
    coachScenarioIds: ['media-literacy'],
    words: [
      noun(
        'Überschrift',
        'nadpis',
        'die',
        'Überschriften',
        'Die Überschrift klingt dramatischer als der Artikel.',
        'Nadpis zní dramatičtěji než článek.',
        'eine zugespitzte Überschrift',
      ),
      noun(
        'Bildquelle',
        'zdroj obrázku',
        'die',
        'Bildquellen',
        'Unter dem Foto fehlt die Bildquelle.',
        'Pod fotografií chybí zdroj obrázku.',
        'eine Bildquelle angeben',
      ),
      noun(
        'Suchergebnis',
        'výsledek vyhledávání',
        'das',
        'Suchergebnisse',
        'Das erste Suchergebnis ist eine Werbeanzeige.',
        'První výsledek vyhledávání je reklama.',
        'Suchergebnisse vergleichen',
      ),
      noun(
        'Primärquelle',
        'primární zdroj',
        'die',
        'Primärquellen',
        'Die Primärquelle enthält die vollständigen Zahlen.',
        'Primární zdroj obsahuje úplná čísla.',
        'zur Primärquelle zurückgehen',
      ),
      noun(
        'Gerücht',
        'fáma',
        'die',
        'Gerüchte',
        'Das angebliche Zitat verbreitet sich als Gerücht.',
        'Údajný citát se šíří jako fáma.',
        'ein Gerücht widerlegen',
      ),
      verb(
        'gegenprüfen',
        'ověřit z druhého zdroje',
        ['prüft gegen', 'prüfte gegen', 'gegengeprüft', 'haben'],
        'Ich prüfe die Zahl mit einer zweiten Quelle gegen.',
        'Číslo ověřuji pomocí druhého zdroje.',
        'eine Behauptung gegenprüfen',
      ),
      verb(
        'kontextualisieren',
        'zasadit do souvislostí',
        ['kontextualisiert', 'kontextualisierte', 'kontextualisiert', 'haben'],
        'Eine Expertin kontextualisiert das Ergebnis.',
        'Odbornice zasazuje výsledek do souvislostí.',
        'eine Nachricht sachlich kontextualisieren',
      ),
      verb(
        'zurückverfolgen',
        'dohledat původ',
        ['verfolgt zurück', 'verfolgte zurück', 'zurückverfolgt', 'haben'],
        'Wir verfolgen das Foto bis zur Originalseite zurück.',
        'Dohledáme fotografii až k původní stránce.',
        'ein Zitat zum Ursprung zurückverfolgen',
      ),
      term(
        'verkürzt',
        'příliš zjednodušený',
        'adjective',
        'Die Grafik stellt den langen Verlauf verkürzt dar.',
        'Graf zobrazuje dlouhý vývoj příliš zjednodušeně.',
        'eine verkürzte Darstellung',
      ),
      term(
        'quellenbasiert',
        'založený na zdrojích',
        'adjective',
        'Die Erklärung ist transparent und quellenbasiert.',
        'Vysvětlení je transparentní a založené na zdrojích.',
        'eine quellenbasierte Einordnung',
      ),
    ],
  }),
  vocabularyPack({
    id: 'project-risk',
    level: 'B2.1',
    title: 'Rizika projektu',
    situation: 'Porovnání pravděpodobnosti a dopadu rizik s návrhem konkrétních opatření.',
    grammarLessonIds: ['complex-connectors', 'conditional-without-wenn'],
    coachScenarioIds: ['project-risk'],
    words: [
      noun(
        'Risikomatrix',
        'matice rizik',
        'die',
        'Risikomatrizen',
        'Die Risikomatrix zeigt drei kritische Punkte.',
        'Matice rizik ukazuje tři kritické body.',
        'eine Risikomatrix erstellen',
      ),
      noun(
        'Eintrittswahrscheinlichkeit',
        'pravděpodobnost výskytu',
        'die',
        'Eintrittswahrscheinlichkeiten',
        'Die Eintrittswahrscheinlichkeit ist gering.',
        'Pravděpodobnost výskytu je nízká.',
        'die Eintrittswahrscheinlichkeit bewerten',
      ),
      noun(
        'Schadensausmaß',
        'rozsah škody',
        'das',
        'Schadensausmaße',
        'Das mögliche Schadensausmaß bleibt hoch.',
        'Možný rozsah škody zůstává vysoký.',
        'das Schadensausmaß begrenzen',
      ),
      noun(
        'Gegenmaßnahme',
        'protiopatření',
        'die',
        'Gegenmaßnahmen',
        'Für jedes Hauptrisiko gibt es eine Gegenmaßnahme.',
        'Pro každé hlavní riziko existuje protiopatření.',
        'eine Gegenmaßnahme festlegen',
      ),
      noun(
        'Engpass',
        'úzké místo',
        'der',
        'Engpässe',
        'Der größte Engpass ist die fehlende Testzeit.',
        'Největším úzkým místem je chybějící čas na testování.',
        'einen personellen Engpass erkennen',
      ),
      verb(
        'gewichten',
        'přiřadit váhu',
        ['gewichtet', 'gewichtete', 'gewichtet', 'haben'],
        'Wir gewichten Risiken nach Wahrscheinlichkeit und Schadensausmaß.',
        'Rizikům přiřadujeme váhu podle pravděpodobnosti a rozsahu škody.',
        'Risiken nach Wirkung gewichten',
      ),
      verb(
        'abfedern',
        'zmírnit dopad',
        ['federt ab', 'federte ab', 'abgefedert', 'haben'],
        'Eine Reserve kann die Verzögerung abfedern.',
        'Rezerva může zmírnit zpoždění.',
        'finanzielle Folgen abfedern',
      ),
      verb(
        'eskalieren',
        'eskalovat',
        ['eskaliert', 'eskalierte', 'eskaliert', 'haben'],
        'Das Team eskaliert den Engpass frühzeitig.',
        'Tým eskaluje úzké místo včas.',
        'ein kritisches Problem eskalieren',
      ),
      term(
        'vorbeugend',
        'preventivní',
        'adjective',
        'Wir treffen eine vorbeugende Maßnahme.',
        'Přijímáme preventivní opatření.',
        'vorbeugende Kontrollen',
      ),
      term(
        'vertretbar',
        'přijatelný',
        'adjective',
        'Das verbleibende Risiko ist vertretbar.',
        'Zbývající riziko je přijatelné.',
        'ein vertretbares Restrisiko',
      ),
    ],
  }),
  vocabularyPack({
    id: 'accessible-city',
    level: 'B2.2',
    title: 'Přístupné město',
    situation: 'Posouzení překážek ve veřejném prostoru a návrh konkrétního zlepšení přístupnosti.',
    grammarLessonIds: ['prepositional-relative-clauses', 'passive-with-modals'],
    coachScenarioIds: ['accessible-city'],
    words: [
      noun(
        'Barrierefreiheit',
        'bezbariérovost',
        'die',
        '—',
        'Barrierefreiheit gehört zur Planung des Bahnhofs.',
        'Bezbariérovost patří k plánování nádraží.',
        'digitale und bauliche Barrierefreiheit',
      ),
      noun(
        'Bordsteinabsenkung',
        'snížený obrubník',
        'die',
        'Bordsteinabsenkungen',
        'An der Kreuzung fehlt eine Bordsteinabsenkung.',
        'Na křižovatce chybí snížený obrubník.',
        'eine Bordsteinabsenkung bauen',
      ),
      noun(
        'Leitsystem',
        'orientační systém',
        'das',
        'Leitsysteme',
        'Das taktile Leitsystem endet vor der Treppe.',
        'Hmatový orientační systém končí před schody.',
        'ein taktiles Leitsystem ergänzen',
      ),
      noun(
        'Aufzugsausfall',
        'výpadek výtahu',
        'der',
        'Aufzugsausfälle',
        'Der Aufzugsausfall wird am Eingang angezeigt.',
        'Výpadek výtahu je oznámený u vchodu.',
        'über einen Aufzugsausfall informieren',
      ),
      noun(
        'Teilhabe',
        'zapojení do společnosti',
        'die',
        '—',
        'Gute Zugänge ermöglichen gesellschaftliche Teilhabe.',
        'Dobré přístupy umožňují zapojení do společnosti.',
        'gleichberechtigte Teilhabe ermöglichen',
      ),
      verb(
        'umbauen',
        'stavebně upravit',
        ['baut um', 'baute um', 'umgebaut', 'haben'],
        'Die Stadt baut den Eingang stufenlos um.',
        'Město stavebně upravuje vchod na bezbariérový.',
        'einen Zugang barrierefrei umbauen',
      ),
      verb(
        'kennzeichnen',
        'označit',
        ['kennzeichnet', 'kennzeichnete', 'gekennzeichnet', 'haben'],
        'Alle Umwege werden deutlich gekennzeichnet.',
        'Všechny objížďky budou jasně označené.',
        'einen Ersatzweg kennzeichnen',
      ),
      verb(
        'beeinträchtigen',
        'omezit funkčnost',
        ['beeinträchtigt', 'beeinträchtigte', 'beeinträchtigt', 'haben'],
        'Die Baustelle beeinträchtigt den Zugang zum Bahnsteig.',
        'Staveniště omezuje přístup k nástupišti.',
        'die Mobilität beeinträchtigen',
      ),
      term(
        'stufenlos',
        'bez schodů',
        'adjective',
        'Der Seiteneingang ist stufenlos erreichbar.',
        'Boční vchod je dostupný bez schodů.',
        'ein stufenloser Zugang',
      ),
      term(
        'gut erreichbar',
        'dobře dostupný',
        'phrase',
        'Die Ersatzhaltestelle muss gut erreichbar sein.',
        'Náhradní zastávka musí být dobře dostupná.',
        'mit öffentlichen Verkehrsmitteln erreichbar',
      ),
    ],
  }),
  vocabularyPack({
    id: 'science-communication',
    level: 'C1.1',
    title: 'Srozumitelná věda',
    situation: 'Převod odborného výsledku pro širší publikum bez ztráty nejistoty a přesnosti.',
    grammarLessonIds: ['source-attribution-phrases', 'hedging-and-distance'],
    coachScenarioIds: ['science-communication'],
    words: [
      noun(
        'Fachpublikum',
        'odborné publikum',
        'das',
        'Fachpublika',
        'Das Fachpublikum kennt die verwendete Methode.',
        'Odborné publikum zná použitou metodu.',
        'vor einem Fachpublikum sprechen',
      ),
      noun(
        'Laienpublikum',
        'laické publikum',
        'das',
        'Laienpublika',
        'Für ein Laienpublikum erklären wir den Begriff zuerst.',
        'Pro laické publikum nejprve vysvětlíme pojem.',
        'ein Laienpublikum erreichen',
      ),
      noun(
        'Kernaussage',
        'hlavní sdělení',
        'die',
        'Kernaussagen',
        'Die Kernaussage passt in einen klaren Satz.',
        'Hlavní sdělení se vejde do jedné jasné věty.',
        'eine Kernaussage formulieren',
      ),
      noun(
        'Unsicherheitsbereich',
        'rozmezí nejistoty',
        'der',
        'Unsicherheitsbereiche',
        'Der Unsicherheitsbereich bleibt in der Grafik sichtbar.',
        'Rozmezí nejistoty zůstává v grafu viditelné.',
        'einen Unsicherheitsbereich ausweisen',
      ),
      noun(
        'Größenordnung',
        'řádová velikost',
        'die',
        'Größenordnungen',
        'Ein Vergleich macht die Größenordnung verständlich.',
        'Srovnání činí řádovou velikost srozumitelnou.',
        'die Größenordnung verdeutlichen',
      ),
      verb(
        'veranschaulichen',
        'názorně ukázat',
        ['veranschaulicht', 'veranschaulichte', 'veranschaulicht', 'haben'],
        'Ein Alltagsvergleich veranschaulicht das Ergebnis.',
        'Přirovnání z běžného života názorně ukazuje výsledek.',
        'einen Zusammenhang veranschaulichen',
      ),
      verb(
        'vereinfachen',
        'zjednodušit',
        ['vereinfacht', 'vereinfachte', 'vereinfacht', 'haben'],
        'Wir vereinfachen die Formulierung ohne falsche Sicherheit.',
        'Zjednodušíme formulaci bez vytváření falešné jistoty.',
        'eine Erklärung sinnvoll vereinfachen',
      ),
      verb(
        'missverstehen',
        'nesprávně pochopit',
        ['missversteht', 'missverstand', 'missverstanden', 'haben'],
        'Ohne Kontext könnte man die Zahl missverstehen.',
        'Bez kontextu by bylo možné číslo nesprávně pochopit.',
        'eine Aussage leicht missverstehen',
      ),
      term(
        'belastbar',
        'spolehlivě podložený',
        'adjective',
        'Nur dieser Teil des Ergebnisses ist belastbar.',
        'Jen tato část výsledku je spolehlivě podložená.',
        'eine belastbare Schlussfolgerung',
      ),
      term(
        'allgemeinverständlich',
        'obecně srozumitelný',
        'adjective',
        'Die Zusammenfassung ist kurz und allgemeinverständlich.',
        'Shrnutí je krátké a obecně srozumitelné.',
        'allgemeinverständlich formulieren',
      ),
    ],
  }),
  vocabularyPack({
    id: 'crisis-communication',
    level: 'C1.2',
    title: 'Komunikace v krizové situaci',
    situation:
      'Sjednocení aktuálních informací, označení nejistoty a vydání jasného dalšího pokynu.',
    grammarLessonIds: ['noun-verb-collocations', 'nuanced-connectors'],
    coachScenarioIds: ['crisis-communication'],
    words: [
      noun(
        'Lagebild',
        'situační přehled',
        'das',
        'Lagebilder',
        'Das Lagebild wird jede Stunde aktualisiert.',
        'Situační přehled se aktualizuje každou hodinu.',
        'ein gemeinsames Lagebild erstellen',
      ),
      noun(
        'Krisenstab',
        'krizový štáb',
        'der',
        'Krisenstäbe',
        'Der Krisenstab tritt um neun Uhr zusammen.',
        'Krizový štáb se schází v devět hodin.',
        'einen Krisenstab einberufen',
      ),
      noun(
        'Informationsstand',
        'stav informací',
        'der',
        'Informationsstände',
        'Nach aktuellem Informationsstand besteht keine akute Gefahr.',
        'Podle aktuálního stavu informací nehrozí bezprostřední nebezpečí.',
        'nach aktuellem Informationsstand',
      ),
      noun(
        'Handlungsempfehlung',
        'doporučený postup',
        'die',
        'Handlungsempfehlungen',
        'Die Handlungsempfehlung nennt drei konkrete Schritte.',
        'Doporučený postup uvádí tři konkrétní kroky.',
        'eine Handlungsempfehlung veröffentlichen',
      ),
      noun(
        'Entwarnung',
        'odvolání poplachu',
        'die',
        'Entwarnungen',
        'Für eine Entwarnung ist es noch zu früh.',
        'Na odvolání poplachu je ještě příliš brzy.',
        'offiziell Entwarnung geben',
      ),
      verb(
        'abgleichen',
        'vzájemně porovnat',
        ['gleicht ab', 'glich ab', 'abgeglichen', 'haben'],
        'Die Behörden gleichen ihre Informationsstände miteinander ab.',
        'Úřady navzájem porovnávají stav svých informací.',
        'Informationen intern abgleichen',
      ),
      verb(
        'dementieren',
        'oficiálně popřít',
        ['dementiert', 'dementierte', 'dementiert', 'haben'],
        'Die Einsatzleitung dementiert das falsche Gerücht.',
        'Vedení zásahu oficiálně popírá nepravdivou fámu.',
        'eine Falschmeldung dementieren',
      ),
      verb(
        'aktualisieren',
        'aktualizovat',
        ['aktualisiert', 'aktualisierte', 'aktualisiert', 'haben'],
        'Wir aktualisieren die Hinweise um zwölf Uhr.',
        'Pokyny aktualizujeme ve dvanáct hodin.',
        'Informationen fortlaufend aktualisieren',
      ),
      term(
        'unbestätigt',
        'nepotvrzený',
        'adjective',
        'Die gemeldete Ursache ist bislang unbestätigt.',
        'Nahlášená příčina je zatím nepotvrzená.',
        'eine unbestätigte Meldung',
      ),
      term(
        'widerspruchsfrei',
        'bezrozporný',
        'adjective',
        'Die öffentliche Mitteilung muss widerspruchsfrei sein.',
        'Veřejné sdělení musí být bezrozporné.',
        'widerspruchsfrei kommunizieren',
      ),
    ],
  }),
];

export const diversityVocabulary = diversityVocabularyPacks.flatMap((pack) => pack.words);
