import type { Article, CefrLevel, DetailedCefrLevel, LexemeKind, VerbForms } from '../types.ts';
import { diversityVocabularyPacks } from './course-vocabulary-diversity.ts';
import type { CourseWord } from './path.ts';

export type FutureChapterVocabularyPack = {
  id: string;
  level: DetailedCefrLevel;
  title: string;
  situation: string;
  grammarLessonIds: string[];
  coachScenarioIds: string[];
  words: CourseWord[];
};

type WordDraftBase = {
  german: string;
  czech: string;
  exampleDe: string;
  exampleCs: string;
  collocation: string;
};

type NounDraft = {
  kind: 'noun';
  article: Article;
  plural: string;
} & WordDraftBase;

type VerbDraft = {
  kind: 'verb';
  forms: [string, string, string, VerbForms['auxiliary']];
} & WordDraftBase;

type TermDraft = {
  kind: Exclude<LexemeKind, 'noun' | 'verb'>;
} & WordDraftBase;

type WordDraft = NounDraft | VerbDraft | TermDraft;

function n(
  german: string,
  czech: string,
  article: Article,
  plural: string,
  exampleDe: string,
  exampleCs: string,
  collocation: string,
): NounDraft {
  return { kind: 'noun', german, czech, article, plural, exampleDe, exampleCs, collocation };
}

function v(
  german: string,
  czech: string,
  forms: VerbDraft['forms'],
  exampleDe: string,
  exampleCs: string,
  collocation: string,
): VerbDraft {
  return { kind: 'verb', german, czech, forms, exampleDe, exampleCs, collocation };
}

function t(
  german: string,
  czech: string,
  kind: TermDraft['kind'],
  exampleDe: string,
  exampleCs: string,
  collocation: string,
): TermDraft {
  return { kind, german, czech, exampleDe, exampleCs, collocation };
}

function pack(definition: Omit<FutureChapterVocabularyPack, 'words'> & { words: WordDraft[] }) {
  const cefr = definition.level.slice(0, 2) as CefrLevel;
  return {
    ...definition,
    words: definition.words.map((draft): CourseWord => {
      const common = {
        german: draft.german,
        czech: draft.czech,
        kind: draft.kind,
        cefr,
        role: 'target' as const,
        exampleDe: draft.exampleDe,
        exampleCs: draft.exampleCs,
        contexts: [draft.exampleDe],
        collocations: [draft.collocation],
        acceptedCzech: [],
      };
      if (draft.kind === 'noun') {
        return { ...common, article: draft.article, plural: draft.plural };
      }
      if (draft.kind === 'verb') {
        return {
          ...common,
          verbForms: {
            thirdPerson: draft.forms[0],
            preterite: draft.forms[1],
            participle: draft.forms[2],
            auxiliary: draft.forms[3],
          },
        };
      }
      return common;
    }),
  } satisfies FutureChapterVocabularyPack;
}

export const futureChapterVocabularyPacks: FutureChapterVocabularyPack[] = [
  pack({
    id: 'weather-and-clothing',
    level: 'A1.2',
    title: 'Počasí a vhodné oblečení',
    situation: 'Rozhodování, co si obléct a vzít ven podle krátké předpovědi.',
    grammarLessonIds: ['separable-imperative', 'schon-noch-erst'],
    coachScenarioIds: ['weather-outfit'],
    words: [
      n(
        'Regenschauer',
        'dešťová přeháňka',
        'der',
        'Regenschauer',
        'Am Nachmittag kommt ein kurzer Regenschauer.',
        'Odpoledne přijde krátká dešťová přeháňka.',
        'mit Regenschauern rechnen',
      ),
      n(
        'Gummistiefel',
        'holínka',
        'der',
        'Gummistiefel',
        'Im nassen Garten trage ich Gummistiefel.',
        'Na mokré zahradě nosím holínky.',
        'wasserdichte Gummistiefel',
      ),
      n(
        'Kapuze',
        'kapuce',
        'die',
        'Kapuzen',
        'Zieh bei starkem Wind die Kapuze auf.',
        'Při silném větru si nasaď kapuci.',
        'die Kapuze aufziehen',
      ),
      n(
        'Sonnencreme',
        'opalovací krém',
        'die',
        'Sonnencremes',
        'Im Sommer brauche ich Sonnencreme.',
        'V létě potřebuji opalovací krém.',
        'Sonnencreme auftragen',
      ),
      t(
        'wechselhaft',
        'proměnlivý',
        'adjective',
        'Das Wetter bleibt heute wechselhaft.',
        'Počasí dnes zůstane proměnlivé.',
        'wechselhaftes Wetter',
      ),
      t(
        'wasserdicht',
        'nepromokavý',
        'adjective',
        'Diese Jacke ist wirklich wasserdicht.',
        'Tato bunda je opravdu nepromokavá.',
        'eine wasserdichte Jacke',
      ),
      v(
        'frieren',
        'být komu zima',
        ['friert', 'fror', 'gefroren', 'haben'],
        'Ohne Schal friere ich schnell.',
        'Bez šály mi je rychle zima.',
        'an den Händen frieren',
      ),
      v(
        'trocknen',
        'schnout',
        ['trocknet', 'trocknete', 'getrocknet', 'haben'],
        'Die nassen Schuhe trocknen im Flur.',
        'Mokré boty schnou na chodbě.',
        'Kleidung trocknen',
      ),
      v(
        'sich umziehen',
        'převléct se',
        ['zieht sich um', 'zog sich um', 'sich umgezogen', 'haben'],
        'Nach dem Regen ziehe ich mich um.',
        'Po dešti se převléknu.',
        'sich schnell umziehen',
      ),
      t(
        'vorsichtshalber',
        'pro jistotu',
        'other',
        'Ich nehme vorsichtshalber einen Schirm mit.',
        'Pro jistotu si vezmu deštník.',
        'vorsichtshalber mitnehmen',
      ),
    ],
  }),
  pack({
    id: 'library-services',
    level: 'A1.2',
    title: 'Knihovna a výpůjčka',
    situation: 'Založení průkazu, orientace mezi regály a vrácení knihy.',
    grammarLessonIds: ['es-gibt-accusative', 'wer-wen-wem'],
    coachScenarioIds: ['library-card'],
    words: [
      n(
        'Bibliotheksausweis',
        'čtenářský průkaz',
        'der',
        'Bibliotheksausweise',
        'Für die Ausleihe brauche ich einen Bibliotheksausweis.',
        'K výpůjčce potřebuji čtenářský průkaz.',
        'einen Bibliotheksausweis beantragen',
      ),
      n(
        'Leihfrist',
        'výpůjční lhůta',
        'die',
        'Leihfristen',
        'Die Leihfrist beträgt vier Wochen.',
        'Výpůjční lhůta je čtyři týdny.',
        'die Leihfrist beachten',
      ),
      n(
        'Rückgabe',
        'vrácení',
        'die',
        'Rückgaben',
        'Die Rückgabe ist auch am Automaten möglich.',
        'Vrácení je možné i v automatu.',
        'Rückgabe am Schalter',
      ),
      n(
        'Lesesaal',
        'studovna',
        'der',
        'Lesesäle',
        'Im Lesesaal muss das Handy leise sein.',
        'Ve studovně musí být telefon ztlumený.',
        'im Lesesaal arbeiten',
      ),
      n(
        'Signatur',
        'signatura knihy',
        'die',
        'Signaturen',
        'Die Signatur zeigt das richtige Regal.',
        'Signatura ukazuje správný regál.',
        'nach der Signatur suchen',
      ),
      v(
        'vormerken',
        'rezervovat předem',
        ['merkt vor', 'merkte vor', 'vorgemerkt', 'haben'],
        'Ich lasse das ausgeliehene Buch vormerken.',
        'Nechám si rezervovat vypůjčenou knihu.',
        'ein Buch vormerken',
      ),
      v(
        'verlängern',
        'prodloužit',
        ['verlängert', 'verlängerte', 'verlängert', 'haben'],
        'Kann ich die Leihfrist online verlängern?',
        'Mohu prodloužit výpůjční lhůtu online?',
        'eine Frist verlängern',
      ),
      v(
        'einsortieren',
        'zařadit do regálu',
        ['sortiert ein', 'sortierte ein', 'einsortiert', 'haben'],
        'Die Mitarbeiterin sortiert die Bücher wieder ein.',
        'Pracovnice zařazuje knihy zpět do regálů.',
        'Bücher alphabetisch einsortieren',
      ),
      t(
        'ausleihbar',
        'dostupný k vypůjčení',
        'adjective',
        'Der Roman ist ab Montag wieder ausleihbar.',
        'Román bude od pondělí znovu k vypůjčení.',
        'online ausleihbar',
      ),
      t(
        'gebührenfrei',
        'bez poplatku',
        'adjective',
        'Die erste Verlängerung ist gebührenfrei.',
        'První prodloužení je bez poplatku.',
        'gebührenfrei verlängern',
      ),
    ],
  }),
  pack({
    id: 'dietary-needs',
    level: 'A2.1',
    title: 'Dietní potřeby v restauraci',
    situation: 'Ověření surovin, pojmenování nesnášenlivosti a změna přílohy.',
    grammarLessonIds: ['schon-noch-erst', 'werden-change'],
    coachScenarioIds: ['dietary-request'],
    words: [
      n(
        'Unverträglichkeit',
        'potravinová nesnášenlivost',
        'die',
        'Unverträglichkeiten',
        'Ich habe eine Unverträglichkeit gegenüber Laktose.',
        'Mám nesnášenlivost laktózy.',
        'eine Unverträglichkeit angeben',
      ),
      n(
        'Milchprodukt',
        'mléčný výrobek',
        'das',
        'Milchprodukte',
        'Dieses Gericht enthält keine Milchprodukte.',
        'Toto jídlo neobsahuje mléčné výrobky.',
        'auf Milchprodukte verzichten',
      ),
      n(
        'Erdnuss',
        'arašíd',
        'die',
        'Erdnüsse',
        'Schon eine Erdnuss kann eine Reaktion auslösen.',
        'Už jeden arašíd může vyvolat reakci.',
        'Spuren von Erdnüssen',
      ),
      n(
        'Speiseöl',
        'jedlý olej',
        'das',
        'Speiseöle',
        'Welches Speiseöl verwenden Sie in der Küche?',
        'Jaký jedlý olej používáte v kuchyni?',
        'in Speiseöl braten',
      ),
      n(
        'Beilage',
        'příloha k jídlu',
        'die',
        'Beilagen',
        'Als Beilage nehme ich gedünstetes Gemüse.',
        'Jako přílohu si dám dušenou zeleninu.',
        'eine Beilage wählen',
      ),
      v(
        'enthalten',
        'obsahovat',
        ['enthält', 'enthielt', 'enthalten', 'haben'],
        'Enthält die Soße Butter?',
        'Obsahuje omáčka máslo?',
        'eine Zutat enthalten',
      ),
      v(
        'vertragen',
        'snášet',
        ['verträgt', 'vertrug', 'vertragen', 'haben'],
        'Ich vertrage scharfes Essen nicht gut.',
        'Nesnáším dobře pálivé jídlo.',
        'etwas gut vertragen',
      ),
      v(
        'ersetzen',
        'nahradit',
        ['ersetzt', 'ersetzte', 'ersetzt', 'haben'],
        'Können Sie den Käse durch Tofu ersetzen?',
        'Můžete nahradit sýr tofu?',
        'etwas durch etwas ersetzen',
      ),
      t(
        'glutenfrei',
        'bezlepkový',
        'adjective',
        'Gibt es auch glutenfreies Brot?',
        'Máte také bezlepkový chléb?',
        'glutenfreie Speisen',
      ),
      t(
        'separat',
        'zvlášť',
        'adjective',
        'Bitte servieren Sie das Dressing separat.',
        'Podávejte prosím dresink zvlášť.',
        'separat zubereiten',
      ),
    ],
  }),
  pack({
    id: 'travel-disruptions',
    level: 'A2.2',
    title: 'Komplikace na cestě',
    situation: 'Zmeškaný přípoj, náhradní spoj a ověření podmínek jízdenky.',
    grammarLessonIds: ['hin-her-direction', 'schon-noch-erst'],
    coachScenarioIds: ['missed-connection'],
    words: [
      n(
        'Anschlusszug',
        'navazující vlak',
        'der',
        'Anschlusszüge',
        'Der Anschlusszug wartet heute nicht.',
        'Navazující vlak dnes nečeká.',
        'einen Anschlusszug erreichen',
      ),
      n(
        'Ersatzverbindung',
        'náhradní spojení',
        'die',
        'Ersatzverbindungen',
        'Die App zeigt eine schnellere Ersatzverbindung.',
        'Aplikace ukazuje rychlejší náhradní spojení.',
        'eine Ersatzverbindung suchen',
      ),
      n(
        'Zugbindung',
        'vázanost jízdenky na vlak',
        'die',
        'Zugbindungen',
        'Bei großer Verspätung kann die Zugbindung entfallen.',
        'Při velkém zpoždění může vázanost na vlak zaniknout.',
        'die Zugbindung aufheben',
      ),
      n(
        'Reisezentrum',
        'zákaznické centrum na nádraží',
        'das',
        'Reisezentren',
        'Im Reisezentrum bekomme ich eine neue Verbindung.',
        'V zákaznickém centru dostanu nové spojení.',
        'im Reisezentrum nachfragen',
      ),
      n(
        'Fahrgastrecht',
        'právo cestujícího',
        'das',
        'Fahrgastrechte',
        'Die Broschüre erklärt jedes wichtige Fahrgastrecht.',
        'Brožura vysvětluje každé důležité právo cestujícího.',
        'Fahrgastrechte geltend machen',
      ),
      v(
        'verpassen',
        'zmeškat',
        ['verpasst', 'verpasste', 'verpasst', 'haben'],
        'Wegen der Verspätung habe ich den Anschluss verpasst.',
        'Kvůli zpoždění jsem zmeškala přípoj.',
        'einen Anschluss verpassen',
      ),
      v(
        'ausfallen',
        'být zrušen',
        ['fällt aus', 'fiel aus', 'ausgefallen', 'sein'],
        'Der letzte Zug fällt heute aus.',
        'Poslední vlak je dnes zrušen.',
        'kurzfristig ausfallen',
      ),
      v(
        'umbuchen',
        'přebookovat',
        ['bucht um', 'buchte um', 'umgebucht', 'haben'],
        'Die Mitarbeiterin bucht mich kostenlos um.',
        'Pracovnice mě bezplatně přebookuje.',
        'eine Reise umbuchen',
      ),
      t(
        'uneingeschränkt gültig',
        'platný bez omezení',
        'phrase',
        'Das Ticket bleibt uneingeschränkt gültig.',
        'Jízdenka zůstává platná bez omezení.',
        'weiterhin gültig',
      ),
      t(
        'voraussichtlich',
        'podle předpokladu',
        'other',
        'Wir kommen voraussichtlich um achtzehn Uhr an.',
        'Podle předpokladu přijedeme v osmnáct hodin.',
        'voraussichtlich ankommen',
      ),
    ],
  }),
  pack({
    id: 'community-volunteering',
    level: 'B1.1',
    title: 'Dobrovolnická akce',
    situation: 'Rozdělení vybavení, lidí a záložního termínu komunitní akce.',
    grammarLessonIds: ['waehrend-clause', 'reciprocal-einander'],
    coachScenarioIds: ['volunteer-event'],
    words: [
      n(
        'Aufräumaktion',
        'úklidová akce',
        'die',
        'Aufräumaktionen',
        'Die Aufräumaktion beginnt am Flussufer.',
        'Úklidová akce začíná na břehu řeky.',
        'eine Aufräumaktion organisieren',
      ),
      n(
        'Freiwilliger',
        'dobrovolník',
        'der',
        'Freiwillige',
        'Jeder Freiwillige erhält Handschuhe.',
        'Každý dobrovolník dostane rukavice.',
        'Freiwillige gewinnen',
      ),
      n(
        'Müllsack',
        'pytel na odpadky',
        'der',
        'Müllsäcke',
        'Wir brauchen zwanzig stabile Müllsäcke.',
        'Potřebujeme dvacet pevných pytlů na odpadky.',
        'einen Müllsack füllen',
      ),
      n(
        'Arbeitshandschuh',
        'pracovní rukavice',
        'der',
        'Arbeitshandschuhe',
        'Die Arbeitshandschuhe schützen vor scharfen Kanten.',
        'Pracovní rukavice chrání před ostrými hranami.',
        'Arbeitshandschuhe tragen',
      ),
      n(
        'Sammelstelle',
        'sběrné místo',
        'die',
        'Sammelstellen',
        'Volle Säcke kommen zur Sammelstelle.',
        'Plné pytle patří na sběrné místo.',
        'eine Sammelstelle einrichten',
      ),
      v(
        'sich beteiligen',
        'zapojit se',
        ['beteiligt sich', 'beteiligte sich', 'sich beteiligt', 'haben'],
        'Mehr als dreißig Menschen beteiligen sich an der Aktion.',
        'Do akce se zapojí více než třicet lidí.',
        'sich an einer Aktion beteiligen',
      ),
      v(
        'verteilen',
        'rozdělit',
        ['verteilt', 'verteilte', 'verteilt', 'haben'],
        'Wir verteilen die Aufgaben in kleinen Teams.',
        'Rozdělíme úkoly do malých týmů.',
        'Aufgaben gerecht verteilen',
      ),
      v(
        'einsammeln',
        'sesbírat',
        ['sammelt ein', 'sammelte ein', 'eingesammelt', 'haben'],
        'Am Ende sammeln wir alle Werkzeuge ein.',
        'Nakonec sesbíráme všechny nástroje.',
        'Material einsammeln',
      ),
      t(
        'gemeinnützig',
        'veřejně prospěšný',
        'adjective',
        'Der Verein arbeitet gemeinnützig.',
        'Spolek pracuje veřejně prospěšně.',
        'ein gemeinnütziger Verein',
      ),
      t(
        'ehrenamtlich',
        'dobrovolnicky',
        'adjective',
        'Sie engagiert sich ehrenamtlich im Stadtteil.',
        'Dobrovolnicky se angažuje ve čtvrti.',
        'ehrenamtlich tätig sein',
      ),
    ],
  }),
  pack({
    id: 'academic-presentation',
    level: 'B1.2',
    title: 'Studijní prezentace',
    situation: 'Od hlavní otázky přes zdroje až ke společnému nácviku.',
    grammarLessonIds: ['nouns-with-prepositions', 'waehrend-clause'],
    coachScenarioIds: ['study-project-presentation'],
    words: [
      n(
        'Leitfrage',
        'hlavní výzkumná otázka',
        'die',
        'Leitfragen',
        'Unsere Leitfrage steht auf der ersten Folie.',
        'Naše hlavní otázka je na prvním snímku.',
        'eine Leitfrage formulieren',
      ),
      n(
        'Gliederung',
        'osnova',
        'die',
        'Gliederungen',
        'Die Gliederung besteht aus drei Teilen.',
        'Osnova se skládá ze tří částí.',
        'eine Gliederung erstellen',
      ),
      n(
        'Quellenangabe',
        'uvedení zdroje',
        'die',
        'Quellenangaben',
        'Unter der Grafik fehlt noch die Quellenangabe.',
        'Pod grafikou ještě chybí uvedení zdroje.',
        'eine Quellenangabe ergänzen',
      ),
      n(
        'Handout',
        'podkladový list',
        'das',
        'Handouts',
        'Das Handout fasst die wichtigsten Ergebnisse zusammen.',
        'Podkladový list shrnuje nejdůležitější výsledky.',
        'ein Handout verteilen',
      ),
      n(
        'Probelauf',
        'zkouška nanečisto',
        'der',
        'Probeläufe',
        'Beim Probelauf überschreiten wir die vorgesehene Zeit.',
        'Při zkoušce nanečisto překročíme vyhrazený čas.',
        'einen Probelauf machen',
      ),
      v(
        'gliedern',
        'členit',
        ['gliedert', 'gliederte', 'gegliedert', 'haben'],
        'Wir gliedern den Vortrag nach Themen.',
        'Členíme přednášku podle témat.',
        'einen Text klar gliedern',
      ),
      v(
        'nachweisen',
        'prokázat',
        ['weist nach', 'wies nach', 'nachgewiesen', 'haben'],
        'Die Statistik weist einen deutlichen Rückgang nach.',
        'Statistika prokazuje výrazný pokles.',
        'einen Zusammenhang nachweisen',
      ),
      v(
        'visualisieren',
        'znázornit',
        ['visualisiert', 'visualisierte', 'visualisiert', 'haben'],
        'Ein Diagramm visualisiert die Entwicklung.',
        'Graf znázorňuje vývoj.',
        'Ergebnisse visualisieren',
      ),
      t(
        'anschaulich',
        'názorný',
        'adjective',
        'Die Grafik erklärt das Ergebnis anschaulich.',
        'Grafika vysvětluje výsledek názorně.',
        'etwas anschaulich darstellen',
      ),
      t(
        'fristgerecht',
        've stanovené lhůtě',
        'adjective',
        'Alle Folien müssen fristgerecht fertig sein.',
        'Všechny snímky musí být hotové ve stanovené lhůtě.',
        'fristgerecht abgeben',
      ),
    ],
  }),
  pack({
    id: 'energy-efficiency',
    level: 'B2.1',
    title: 'Energetická účinnost',
    situation: 'Porovnání investice, měřitelné úspory a doby návratnosti.',
    grammarLessonIds: ['indem-dadurch-dass', 'haben-sein-zu-infinitive'],
    coachScenarioIds: ['energy-saving-proposal'],
    words: [
      n(
        'Energieverbrauch',
        'spotřeba energie',
        'der',
        'Energieverbräuche',
        'Der Energieverbrauch ist im Winter besonders hoch.',
        'Spotřeba energie je v zimě obzvlášť vysoká.',
        'den Energieverbrauch senken',
      ),
      n(
        'Wärmedämmung',
        'tepelná izolace',
        'die',
        'Wärmedämmungen',
        'Eine gute Wärmedämmung reduziert Wärmeverluste.',
        'Dobrá tepelná izolace snižuje tepelné ztráty.',
        'die Wärmedämmung verbessern',
      ),
      n(
        'Heizungsanlage',
        'topný systém',
        'die',
        'Heizungsanlagen',
        'Die alte Heizungsanlage arbeitet ineffizient.',
        'Starý topný systém pracuje neefektivně.',
        'eine Heizungsanlage modernisieren',
      ),
      n(
        'Verbrauchswert',
        'hodnota spotřeby',
        'der',
        'Verbrauchswerte',
        'Wir vergleichen die Verbrauchswerte vor und nach dem Umbau.',
        'Porovnáváme hodnoty spotřeby před a po rekonstrukci.',
        'Verbrauchswerte erfassen',
      ),
      n(
        'Amortisationszeit',
        'doba návratnosti',
        'die',
        'Amortisationszeiten',
        'Die Amortisationszeit beträgt ungefähr sechs Jahre.',
        'Doba návratnosti je přibližně šest let.',
        'die Amortisationszeit berechnen',
      ),
      v(
        'dämmen',
        'izolovat',
        ['dämmt', 'dämmte', 'gedämmt', 'haben'],
        'Wir dämmen zuerst das Dach.',
        'Nejprve izolujeme střechu.',
        'ein Gebäude dämmen',
      ),
      v(
        'nachrüsten',
        'dodatečně vybavit',
        ['rüstet nach', 'rüstete nach', 'nachgerüstet', 'haben'],
        'Die Sensoren lassen sich später nachrüsten.',
        'Senzory lze doplnit později.',
        'Technik nachrüsten',
      ),
      v(
        'einsparen',
        'ušetřit',
        ['spart ein', 'sparte ein', 'eingespart', 'haben'],
        'Neue Leuchten sparen jährlich Strom ein.',
        'Nová svítidla každoročně ušetří elektřinu.',
        'Kosten einsparen',
      ),
      t(
        'energieeffizient',
        'energeticky účinný',
        'adjective',
        'Das neue Gerät ist deutlich energieeffizienter.',
        'Nový přístroj je výrazně energeticky účinnější.',
        'energieeffizient heizen',
      ),
      t(
        'rentabel',
        'ekonomicky výhodný',
        'adjective',
        'Die Maßnahme wird nach einigen Jahren rentabel.',
        'Opatření se po několika letech ekonomicky vyplatí.',
        'wirtschaftlich rentabel',
      ),
    ],
  }),
  pack({
    id: 'digital-privacy',
    level: 'B2.2',
    title: 'Digitální soukromí',
    situation: 'Vyhodnocení přístupu k datům a první bezpečnostní opatření.',
    grammarLessonIds: ['genitive-relative-pronouns', 'haben-sein-zu-infinitive'],
    coachScenarioIds: ['privacy-incident-response'],
    words: [
      n(
        'Zugriffsrecht',
        'přístupové oprávnění',
        'das',
        'Zugriffsrechte',
        'Nicht jede Person braucht dieses Zugriffsrecht.',
        'Ne každý potřebuje toto přístupové oprávnění.',
        'Zugriffsrechte beschränken',
      ),
      n(
        'Datenleck',
        'únik dat',
        'das',
        'Datenlecks',
        'Das Team untersucht ein mögliches Datenleck.',
        'Tým vyšetřuje možný únik dat.',
        'ein Datenleck entdecken',
      ),
      n(
        'Sicherheitsprotokoll',
        'bezpečnostní protokol',
        'das',
        'Sicherheitsprotokolle',
        'Das Sicherheitsprotokoll dokumentiert jeden Anmeldeversuch.',
        'Bezpečnostní protokol dokumentuje každý pokus o přihlášení.',
        'ein Sicherheitsprotokoll auswerten',
      ),
      n(
        'Zwei-Faktor-Authentifizierung',
        'dvoufaktorové ověření',
        'die',
        'Zwei-Faktor-Authentifizierungen',
        'Die Zwei-Faktor-Authentifizierung schützt wichtige Konten.',
        'Dvoufaktorové ověření chrání důležité účty.',
        'Zwei-Faktor-Authentifizierung aktivieren',
      ),
      n(
        'Meldepflicht',
        'oznamovací povinnost',
        'die',
        'Meldepflichten',
        'Bei schweren Vorfällen gilt eine gesetzliche Meldepflicht.',
        'U závažných incidentů platí zákonná oznamovací povinnost.',
        'eine Meldepflicht erfüllen',
      ),
      v(
        'verschlüsseln',
        'šifrovat',
        ['verschlüsselt', 'verschlüsselte', 'verschlüsselt', 'haben'],
        'Wir verschlüsseln alle gespeicherten Kundendaten.',
        'Šifrujeme všechny uložené zákaznické údaje.',
        'Daten Ende-zu-Ende verschlüsseln',
      ),
      v(
        'widerrufen',
        'zrušit',
        ['widerruft', 'widerrief', 'widerrufen', 'haben'],
        'Die Administratorin widerruft den alten Zugang.',
        'Administrátorka ruší starý přístup.',
        'eine Berechtigung widerrufen',
      ),
      v(
        'protokollieren',
        'zaznamenávat do protokolu',
        ['protokolliert', 'protokollierte', 'protokolliert', 'haben'],
        'Das System protokolliert ungewöhnliche Zugriffe.',
        'Systém zaznamenává neobvyklé přístupy.',
        'einen Zugriff protokollieren',
      ),
      t(
        'unbefugt',
        'neoprávněný',
        'adjective',
        'Unbefugte Personen dürfen die Datei nicht öffnen.',
        'Neoprávněné osoby nesmějí soubor otevřít.',
        'unbefugter Zugriff',
      ),
      t(
        'manipulationssicher',
        'odolný proti manipulaci',
        'adjective',
        'Die Protokolle müssen manipulationssicher gespeichert werden.',
        'Protokoly musí být uloženy tak, aby nešly zmanipulovat.',
        'manipulationssicher archivieren',
      ),
    ],
  }),
  pack({
    id: 'research-ethics',
    level: 'C1.1',
    title: 'Výzkumná etika',
    situation: 'Posouzení souhlasu, rizik a podmínek pro schválení studie.',
    grammarLessonIds: ['evidential-sollen-wollen', 'apposition-case-punctuation'],
    coachScenarioIds: ['research-ethics-review'],
    words: [
      n(
        'Einwilligungserklärung',
        'formulář informovaného souhlasu',
        'die',
        'Einwilligungserklärungen',
        'Die Einwilligungserklärung muss verständlich formuliert sein.',
        'Formulář informovaného souhlasu musí být formulován srozumitelně.',
        'eine Einwilligungserklärung unterschreiben',
      ),
      n(
        'Risikobewertung',
        'posouzení rizik',
        'die',
        'Risikobewertungen',
        'Die Kommission verlangt eine unabhängige Risikobewertung.',
        'Komise požaduje nezávislé posouzení rizik.',
        'eine Risikobewertung vornehmen',
      ),
      n(
        'Versuchsperson',
        'účastník experimentu',
        'die',
        'Versuchspersonen',
        'Jede Versuchsperson darf die Teilnahme abbrechen.',
        'Každý účastník experimentu smí účast ukončit.',
        'Versuchspersonen aufklären',
      ),
      n(
        'Interessenkonflikt',
        'střet zájmů',
        'der',
        'Interessenkonflikte',
        'Der finanzielle Interessenkonflikt wird offengelegt.',
        'Finanční střet zájmů je zveřejněn.',
        'einen Interessenkonflikt offenlegen',
      ),
      n(
        'Abbruchkriterium',
        'kritérium pro ukončení',
        'das',
        'Abbruchkriterien',
        'Das Protokoll nennt klare Abbruchkriterien.',
        'Protokol uvádí jasná kritéria pro ukončení.',
        'Abbruchkriterien festlegen',
      ),
      v(
        'minimieren',
        'minimalizovat',
        ['minimiert', 'minimierte', 'minimiert', 'haben'],
        'Zusätzliche Pausen minimieren die Belastung.',
        'Dodatečné přestávky minimalizují zátěž.',
        'ein Risiko minimieren',
      ),
      v(
        'anonymisieren',
        'anonymizovat',
        ['anonymisiert', 'anonymisierte', 'anonymisiert', 'haben'],
        'Vor der Auswertung werden die Datensätze anonymisiert.',
        'Před vyhodnocením se datové soubory anonymizují.',
        'personenbezogene Daten anonymisieren',
      ),
      v(
        'genehmigen',
        'schválit',
        ['genehmigt', 'genehmigte', 'genehmigt', 'haben'],
        'Die Ethikkommission genehmigt die Studie unter Auflagen.',
        'Etická komise schvaluje studii s podmínkami.',
        'unter Auflagen genehmigen',
      ),
      t(
        'freiwillig',
        'dobrovolný',
        'adjective',
        'Die Teilnahme muss jederzeit freiwillig bleiben.',
        'Účast musí zůstat vždy dobrovolná.',
        'freiwillige Teilnahme',
      ),
      t(
        'ethisch vertretbar',
        'eticky obhajitelný',
        'phrase',
        'Unter diesen Bedingungen ist die Studie ethisch vertretbar.',
        'Za těchto podmínek je studie eticky obhajitelná.',
        'nur bedingt vertretbar',
      ),
    ],
  }),
  pack({
    id: 'public-policy',
    level: 'C1.2',
    title: 'Veřejná politika a konzultace',
    situation: 'Připomínkování návrhu, výjimky a měřitelné vyhodnocení dopadů.',
    grammarLessonIds: ['evidential-sollen-wollen', 'ellipsis-parallelism'],
    coachScenarioIds: ['policy-consultation'],
    words: [
      n(
        'Gesetzentwurf',
        'návrh zákona',
        'der',
        'Gesetzentwürfe',
        'Der Gesetzentwurf geht nun in die öffentliche Beratung.',
        'Návrh zákona nyní míří do veřejné konzultace.',
        'einen Gesetzentwurf überarbeiten',
      ),
      n(
        'Folgenabschätzung',
        'posouzení dopadů',
        'die',
        'Folgenabschätzungen',
        'Eine Folgenabschätzung untersucht soziale und finanzielle Auswirkungen.',
        'Posouzení dopadů zkoumá sociální a finanční účinky.',
        'eine Folgenabschätzung durchführen',
      ),
      n(
        'Härtefall',
        'případ zvláštní tvrdosti',
        'der',
        'Härtefälle',
        'Für begründete Härtefälle ist eine Ausnahme vorgesehen.',
        'Pro odůvodněné případy zvláštní tvrdosti se počítá s výjimkou.',
        'einen Härtefall anerkennen',
      ),
      n(
        'Übergangsregelung',
        'přechodné ustanovení',
        'die',
        'Übergangsregelungen',
        'Die Übergangsregelung gilt für sechs Monate.',
        'Přechodné ustanovení platí šest měsíců.',
        'eine Übergangsregelung schaffen',
      ),
      n(
        'Anhörung',
        'veřejné či odborné slyšení',
        'die',
        'Anhörungen',
        'Bei der Anhörung kommen mehrere Interessengruppen zu Wort.',
        'Při slyšení dostane slovo několik zájmových skupin.',
        'an einer Anhörung teilnehmen',
      ),
      v(
        'nachbessern',
        'dodatečně upravit',
        ['bessert nach', 'besserte nach', 'nachgebessert', 'haben'],
        'Das Ministerium muss bei den Ausnahmen nachbessern.',
        'Ministerstvo musí dodatečně upravit výjimky.',
        'einen Entwurf nachbessern',
      ),
      v(
        'befristen',
        'časově omezit',
        ['befristet', 'befristete', 'befristet', 'haben'],
        'Wir befristen die Sonderregelung auf ein Jahr.',
        'Zvláštní úpravu omezíme na jeden rok.',
        'eine Ausnahme befristen',
      ),
      v(
        'nachsteuern',
        'provést následnou korekci',
        ['steuert nach', 'steuerte nach', 'nachgesteuert', 'haben'],
        'Wenn die Belastung steigt, muss die Stadt nachsteuern.',
        'Pokud zátěž vzroste, město musí provést korekci.',
        'bei Problemen nachsteuern',
      ),
      t(
        'verhältnismäßig',
        'přiměřený',
        'adjective',
        'Der Eingriff muss geeignet und verhältnismäßig sein.',
        'Zásah musí být vhodný a přiměřený.',
        'eine verhältnismäßige Maßnahme',
      ),
      t(
        'praktisch umsetzbar',
        'prakticky proveditelný',
        'phrase',
        'Der Kompromiss ist rechtlich sauber und praktisch umsetzbar.',
        'Kompromis je právně čistý a prakticky proveditelný.',
        'unter realen Bedingungen umsetzbar',
      ),
    ],
  }),
  ...diversityVocabularyPacks,
];

export const futureChapterVocabulary = futureChapterVocabularyPacks.flatMap(
  (chapterPack) => chapterPack.words,
);
