import type {
  GrammarChoiceQuestion,
  GrammarFillQuestion,
  GrammarLesson,
  GrammarOrderQuestion,
  GrammarQuestion,
} from './grammar.ts';

type QuestionDraft =
  | Omit<GrammarChoiceQuestion, 'id'>
  | Omit<GrammarFillQuestion, 'id'>
  | Omit<GrammarOrderQuestion, 'id'>;

function choice(
  prompt: string,
  options: string[],
  answer: string,
  explanation: string,
  skill: string,
): QuestionDraft {
  return {
    kind: 'choice',
    prompt,
    instruction: 'Vyber správnou možnost.',
    options,
    answer,
    explanation,
    skill,
  };
}

function fill(
  prompt: string,
  before: string,
  after: string,
  answers: string[],
  hint: string,
  explanation: string,
  skill: string,
): QuestionDraft {
  return {
    kind: 'fill',
    prompt,
    instruction: 'Doplň chybějící část.',
    before,
    after,
    answers,
    hint,
    explanation,
    skill,
  };
}

function order(
  prompt: string,
  tokens: string[],
  answer: string[],
  translation: string,
  explanation: string,
  skill: string,
): QuestionDraft {
  return {
    kind: 'order',
    prompt,
    instruction: 'Poskládej větu ve správném pořadí.',
    tokens,
    answer,
    translation,
    explanation,
    skill,
  };
}

function lesson(
  definition: Omit<GrammarLesson, 'questions'> & { questions: QuestionDraft[] },
): GrammarLesson {
  const { questions, ...metadata } = definition;
  return {
    ...metadata,
    questions: questions.map(
      (question, index) =>
        ({ ...question, id: `${definition.id}-${index + 1}` }) as GrammarQuestion,
    ),
  };
}

export const nextGrammarLessons: GrammarLesson[] = [
  lesson({
    id: 'es-gibt-accusative',
    categoryId: 'daily-foundations',
    unit: 111,
    title: 'Es gibt: co někde je',
    shortTitle: 'Es gibt + akuzativ',
    subtitle: 'Popiš, co je v okolí, aniž bys hledala podmět pro každou novou věc.',
    cefr: 'A1',
    minutes: 5,
    completionXp: 20,
    concept:
      'Vazba es gibt znamená „je, jsou, existuje“ a výraz za ní stojí vždy v akuzativu. Proto říkáme einen Park, eine Apotheke a ein Café bez ohledu na českou stavbu.',
    formula: 'es gibt + akuzativ · einen / eine / ein / keine',
    examples: [
      { de: 'Hier gibt es einen Park.', cs: 'Tady je park.' },
      { de: 'Gibt es in der Nähe eine Apotheke?', cs: 'Je poblíž lékárna?' },
    ],
    questions: [
      choice(
        'In unserem Viertel gibt es ___ kleinen Markt.',
        ['einen', 'ein', 'einem', 'einer'],
        'einen',
        'Mužský rod stojí po „es gibt“ v akuzativu, proto má neurčitý člen tvar „einen“.',
        'mužský akuzativ po es gibt',
      ),
      fill(
        'Zeptej se, zda je poblíž bankomat.',
        'Gibt es hier ',
        ' Geldautomaten?',
        ['einen'],
        'Geldautomat je mužského rodu.',
        'Otázka zachovává vazbu „es gibt“ a mužský předmět má v akuzativu člen „einen“.',
        'otázka s es gibt',
      ),
      choice(
        'Která věta správně znamená „Dnes nejsou žádné volné pokoje“?',
        [
          'Heute gibt es keine freien Zimmer.',
          'Heute geben keine freien Zimmer.',
          'Heute gibt es keinen freie Zimmer.',
          'Heute ist es keine freien Zimmer.',
        ],
        'Heute gibt es keine freien Zimmer.',
        'Množné číslo v akuzativu používá „keine“ a přídavné jméno po něm koncovku -en.',
        'zápor množného čísla po es gibt',
      ),
      order(
        'Na rohu je malá pekárna.',
        ['eine kleine Bäckerei.', 'An der Ecke', 'es', 'gibt'],
        ['An der Ecke', 'gibt', 'es', 'eine kleine Bäckerei.'],
        'Na rohu je malá pekárna.',
        'Místní údaj je první, časované „gibt“ druhé a formální podmět „es“ stojí hned za ním.',
        'slovosled vazby es gibt',
      ),
      choice(
        'Was ___ es heute zum Mittagessen?',
        ['gibt', 'ist', 'hat', 'gebt'],
        'gibt',
        'Ustálená otázka zní „Was gibt es …?“; sloveso je ve třetí osobě jednotného čísla.',
        'časování vazby es gibt',
      ),
    ],
  }),
  lesson({
    id: 'wer-wen-wem',
    categoryId: 'cases',
    unit: 112,
    title: 'Wer, wen, wem?',
    shortTitle: 'Kdo, koho, komu',
    subtitle: 'Tvar otázky prozradí, jakou roli hledaná osoba ve větě má.',
    cefr: 'A1',
    minutes: 6,
    completionXp: 20,
    concept:
      'Wer se ptá na podmět, wen na osobu v akuzativu a wem na osobu v dativu. Správný tvar lze najít podle slovesa: sehen řídí akuzativ, helfen dativ.',
    formula: 'wer = nominativ · wen = akuzativ · wem = dativ',
    examples: [
      { de: 'Wer kommt heute?', cs: 'Kdo dnes přijde?' },
      { de: 'Wem hilfst du?', cs: 'Komu pomáháš?' },
    ],
    questions: [
      choice(
        '___ wartet vor der Tür?',
        ['Wer', 'Wen', 'Wem', 'Wessen'],
        'Wer',
        'Hledaná osoba sama čeká, je tedy podmětem v nominativu a otázka začíná „wer“.',
        'otázka na podmět',
      ),
      choice(
        '___ besuchst du am Wochenende?',
        ['Wen', 'Wer', 'Wem', 'Was für'],
        'Wen',
        'Sloveso „besuchen“ má přímý předmět v akuzativu, proto se na osobu ptáme „wen“.',
        'otázka na akuzativní osobu',
      ),
      fill(
        'Zeptej se na příjemce pomoci.',
        '',
        ' hilft die Nachbarin?',
        ['Wem'],
        'Helfen se pojí s dativem.',
        'Příjemce děje po slovese „helfen“ je v dativu, a proto použijeme tázací zájmeno „wem“.',
        'otázka na dativní osobu',
      ),
      order(
        'Koho dnes vyzvedneš na nádraží?',
        ['heute', 'am Bahnhof', 'holst', 'Wen', 'du', 'ab?'],
        ['Wen', 'holst', 'du', 'heute', 'am Bahnhof', 'ab?'],
        'Koho dnes vyzvedneš na nádraží?',
        'Tázací „wen“ je první, určité sloveso „holst“ druhé a odlučitelná předpona „ab“ uzavírá větu.',
        'wen v otázce s odlučitelným slovesem',
      ),
      choice(
        'Která dvojice otázky a odpovědi se shoduje v pádu?',
        [
          'Wem dankst du? – Meiner Kollegin.',
          'Wen dankst du? – Meiner Kollegin.',
          'Wer dankst du? – Meine Kollegin.',
          'Wem dankst du? – Meine Kollegin.',
        ],
        'Wem dankst du? – Meiner Kollegin.',
        '„Danken“ vyžaduje dativ; tomu odpovídá „wem“ i odpověď „meiner Kollegin“.',
        'shoda otázky a odpovědi v dativu',
      ),
    ],
  }),
  lesson({
    id: 'separable-imperative',
    categoryId: 'verb-lab',
    unit: 113,
    title: 'Pokyn s odlučitelným slovesem',
    shortTitle: 'Mach auf!',
    subtitle: 'Jádro pokynu stojí vpředu, předpona čeká až na konci.',
    cefr: 'A1',
    minutes: 6,
    completionXp: 20,
    concept:
      'V rozkazu s odlučitelným slovesem stojí slovesný kmen na začátku a předpona na konci: Ruf mich an! Zdvořilý tvar zachovává Sie: Rufen Sie an!',
    formula: 'kmen + doplnění + předpona! · infinitiv + Sie + doplnění + předpona!',
    examples: [
      { de: 'Mach bitte das Fenster auf!', cs: 'Otevři prosím okno!' },
      { de: 'Steigen Sie hier aus!', cs: 'Vystupte tady!' },
    ],
    questions: [
      order(
        'Zavolej mi prosím zítra.',
        ['bitte', 'morgen', 'an!', 'Ruf', 'mich'],
        ['Ruf', 'mich', 'bitte', 'morgen', 'an!'],
        'Zavolej mi prosím zítra.',
        'Rozkazovací tvar „ruf“ stojí první a předpona „an“ se odděluje až na konec pokynu.',
        'rozkaz s anrufen',
      ),
      choice(
        'Který zdvořilý pokyn je správně?',
        [
          'Füllen Sie bitte das Formular aus!',
          'Ausfüllen Sie bitte das Formular!',
          'Sie füllen bitte das Formular aus!',
          'Füllst Sie bitte das Formular aus!',
        ],
        'Füllen Sie bitte das Formular aus!',
        'Zdvořilý imperativ tvoří infinitivní tvar, zájmeno „Sie“ a oddělená předpona na konci.',
        'zdvořilý imperativ odlučitelného slovesa',
      ),
      fill(
        'Vyzvi kamaráda, aby vstal.',
        '',
        ' bitte auf!',
        ['Steh'],
        'Imperativ od stehen je steh.',
        'U „aufstehen“ použijeme rozkazovací tvar „steh“ a předponu „auf“ necháme na konci.',
        'nepravidelný imperativ aufstehen',
      ),
      choice(
        '___ bitte leise herein!',
        ['Komm', 'Kommst', 'Kommen du', 'Hereinkomm'],
        'Komm',
        'Pro osobu „du“ se zájmeno vypouští; kmen „komm“ stojí na začátku a „herein“ na konci.',
        'imperativ pro du',
      ),
      order(
        'Vezměte si prosím účtenku s sebou.',
        ['bitte', 'Sie', 'mit!', 'Nehmen', 'den Beleg'],
        ['Nehmen', 'Sie', 'bitte', 'den Beleg', 'mit!'],
        'Vezměte si prosím účtenku s sebou.',
        'Zdvořilé „nehmen Sie“ otevírá pokyn a odlučitelná část „mit“ uzavírá větu.',
        'zdvořilý pokyn s mitnehmen',
      ),
    ],
  }),
  lesson({
    id: 'hin-her-direction',
    categoryId: 'everyday-phrases',
    unit: 114,
    title: 'Hin, nebo her?',
    shortTitle: 'Směr od a k mluvčímu',
    subtitle: 'Jedno krátké slovo ukáže, z čí perspektivy se pohyb odehrává.',
    cefr: 'A2',
    minutes: 6,
    completionXp: 22,
    concept:
      'Hin označuje pohyb pryč od mluvčího, her pohyb směrem k němu. Stejný rozdíl je ve dvojicích hinaus–heraus, hinein–herein a v otázkách wohin–woher.',
    formula: 'hin = tam ode mě · her = sem ke mně · wohin? / woher?',
    examples: [
      { de: 'Geh bitte hinaus.', cs: 'Jdi prosím ven.' },
      { de: 'Komm bitte herein.', cs: 'Pojď prosím dovnitř.' },
    ],
    questions: [
      choice(
        'Du stehst draußen. Ich öffne die Tür und sage: „Komm bitte ___.“',
        ['herein', 'hinein', 'hinaus', 'dorthin'],
        'herein',
        'Osoba se pohybuje dovnitř směrem k mluvčímu, proto použijeme „herein“.',
        'směr k mluvčímu',
      ),
      fill(
        'Zeptej se na cíl cesty.',
        '',
        ' fährst du morgen?',
        ['Wohin'],
        'Ptáme se kam, ne odkud.',
        '„Wohin“ se ptá na cíl pohybu; „woher“ by se ptalo na výchozí místo.',
        'otázka na cíl pohybu',
      ),
      choice(
        '___ kommt dieser Zug?',
        ['Woher', 'Wohin', 'Worin', 'Wobei'],
        'Woher',
        'Ptáme se, odkud vlak přijíždí, tedy na původ pohybu pomocí „woher“.',
        'otázka na původ pohybu',
      ),
      order(
        'Polož tu krabici tamhle.',
        ['dorthin.', 'die Kiste', 'Stell', 'bitte'],
        ['Stell', 'die Kiste', 'bitte', 'dorthin.'],
        'Polož tu krabici tamhle.',
        '„Dorthin“ vyjadřuje směr k místu vzdálenému od mluvčího a stojí přirozeně na konci.',
        'směrové příslovce dorthin',
      ),
      choice(
        'Mluvčí je venku a volá dítě z domu k sobě. Co řekne?',
        ['Komm heraus!', 'Geh hinaus!', 'Komm hinein!', 'Geh herein!'],
        'Komm heraus!',
        'Dítě jde z domu ven směrem k mluvčímu, proto spojujeme „kommen“ s „heraus“.',
        'perspektiva v heraus',
      ),
    ],
  }),
  lesson({
    id: 'schon-noch-erst',
    categoryId: 'everyday-phrases',
    unit: 115,
    title: 'Schon, noch a erst',
    shortTitle: 'Už, ještě, teprve',
    subtitle: 'Vyjádři očekávání v čase, ne jen holý údaj z hodin.',
    cefr: 'A2',
    minutes: 6,
    completionXp: 22,
    concept:
      'Schon znamená „už“, noch „ještě“ a erst „teprve“ nebo „až“. Tato příslovce porovnávají skutečnost s očekáváním, takže změna jediného slova mění pohled mluvčího.',
    formula: 'schon = dříve, než čekám · noch = stále · erst = později/méně, než čekám',
    examples: [
      { de: 'Der Bus ist schon da.', cs: 'Autobus už je tady.' },
      { de: 'Das Geschäft öffnet erst um zehn.', cs: 'Obchod otevírá až v deset.' },
    ],
    questions: [
      choice(
        'Es ist erst acht Uhr. Der Laden ist ___ geschlossen.',
        ['noch', 'schon', 'erstens', 'wieder'],
        'noch',
        'Obchod zůstává v nezměněném stavu, proto „noch geschlossen“ znamená „ještě zavřený“.',
        'trvající stav s noch',
      ),
      fill(
        'Vyjádři překvapení, že host dorazil dříve.',
        'Du bist ',
        ' da!',
        ['schon'],
        'Host je tu už nyní.',
        '„Schon“ signalizuje, že očekávaná událost nastala dříve nebo je už dokončena.',
        'dřívější naplnění očekávání',
      ),
      choice(
        'Ich wohne ___ seit zwei Wochen hier, deshalb kenne ich die Stadt kaum.',
        ['erst', 'schon', 'noch immer', 'wieder'],
        'erst',
        'Dva týdny mluvčí hodnotí jako krátkou dobu; „erst“ odpovídá českému „teprve“.',
        'omezená doba s erst',
      ),
      order(
        'Zpráva ještě není hotová.',
        ['noch', 'Der Bericht', 'nicht', 'ist', 'fertig.'],
        ['Der Bericht', 'ist', 'noch', 'nicht', 'fertig.'],
        'Zpráva ještě není hotová.',
        'Spojení „noch nicht“ vyjadřuje, že očekávaný stav zatím nenastal, ale později nastat může.',
        'zápor noch nicht',
      ),
      choice(
        'Která věta znamená, že vlak odjede až za hodinu?',
        [
          'Der Zug fährt erst in einer Stunde ab.',
          'Der Zug fährt schon in einer Stunde ab.',
          'Der Zug fährt noch vor einer Stunde ab.',
          'Der Zug fährt wieder einer Stunde ab.',
        ],
        'Der Zug fährt erst in einer Stunde ab.',
        '„Erst“ posouvá očekávaný okamžik na později a přesně odpovídá českému „až“.',
        'pozdější okamžik s erst',
      ),
    ],
  }),
  lesson({
    id: 'werden-change',
    categoryId: 'narration-and-time',
    unit: 116,
    title: 'Werden jako změna stavu',
    shortTitle: 'Stávat se',
    subtitle: 'Ne každé werden je budoucnost nebo pasivum.',
    cefr: 'A2',
    minutes: 6,
    completionXp: 22,
    concept:
      'Samostatné sloveso werden znamená „stávat se“ a spojuje podmět s novou vlastností, povoláním nebo stavem. V perfektu má tvar ist geworden, nikoli worden.',
    formula: 'podmět + werden + nový stav · ist/sind geworden',
    examples: [
      { de: 'Es wird langsam dunkel.', cs: 'Pomalu se stmívá.' },
      { de: 'Sie ist Ärztin geworden.', cs: 'Stala se lékařkou.' },
    ],
    questions: [
      choice(
        'Die Tage ___ im Frühling länger.',
        ['werden', 'wurden worden', 'sind', 'haben'],
        'werden',
        'Podmět je v množném čísle a popisujeme změnu vlastnosti, proto použijeme „werden“.',
        'werden se změnou vlastnosti',
      ),
      fill(
        'Doplň perfektum slovesa werden ve významu stát se.',
        'Mein Bruder ist Vater ',
        '.',
        ['geworden'],
        'Samostatné werden má příčestí geworden.',
        'Při změně stavu tvoří perfektum pomocné „sein“ a příčestí „geworden“.',
        'perfektum ist geworden',
      ),
      choice(
        'Která věta popisuje změnu, nikoli budoucnost?',
        [
          'Das Wasser wird kalt.',
          'Ich werde morgen anrufen.',
          'Der Brief wird verschickt.',
          'Wir werden später kommen.',
        ],
        'Das Wasser wird kalt.',
        'Přídavné jméno „kalt“ označuje nový stav vody; není zde další infinitiv ani příčestí pasiva.',
        'rozpoznání plnovýznamového werden',
      ),
      order(
        'Po rozhovoru byl problém jasnější.',
        ['klarer', 'Nach dem Gespräch', 'das Problem', 'geworden.', 'ist'],
        ['Nach dem Gespräch', 'ist', 'das Problem', 'klarer', 'geworden.'],
        'Po rozhovoru byl problém jasnější.',
        'Pomocné „ist“ stojí po úvodním údaji a příčestí „geworden“ uzavírá větnou závorku.',
        'slovosled perfektu s geworden',
      ),
      choice(
        'Er möchte ___ werden.',
        ['Ingenieur', 'einen Ingenieur', 'dem Ingenieur', 'des Ingenieurs'],
        'Ingenieur',
        'Povolání po slovese „werden“ se bez dalšího určení běžně používá bez členu.',
        'povolání po werden bez členu',
      ),
    ],
  }),
  lesson({
    id: 'nouns-with-prepositions',
    categoryId: 'reference-and-quantity',
    unit: 117,
    title: 'Podstatná jména s předložkou',
    shortTitle: 'Interesse an, Grund für',
    subtitle: 'Vazba nekončí u slovesa: i podstatné jméno si vybírá svou předložku.',
    cefr: 'B1',
    minutes: 7,
    completionXp: 24,
    concept:
      'Řada německých podstatných jmen tvoří pevnou vazbu s předložkou a pádem: Interesse an s dativem, Grund für s akuzativem nebo Angst vor s dativem.',
    formula: 'Interesse an + D · Teilnahme an + D · Grund für + A · Angst vor + D',
    examples: [
      { de: 'Sie hat großes Interesse an dem Kurs.', cs: 'Má velký zájem o ten kurz.' },
      { de: 'Was ist der Grund für die Änderung?', cs: 'Jaký je důvod té změny?' },
    ],
    questions: [
      choice(
        'Sein Interesse ___ erneuerbaren Energien ist groß.',
        ['an', 'für', 'über', 'auf'],
        'an',
        'Podstatné jméno „Interesse“ tvoří ustálenou vazbu „Interesse an“ s dativem.',
        'vazba Interesse an',
      ),
      fill(
        'Doplň předložku v otázce na příčinu.',
        'Was ist der Grund ',
        ' diese Entscheidung?',
        ['für'],
        'Vazba zní Grund für.',
        'Po podstatném jménu „Grund“ se důvod vztahuje k věci pomocí „für“ a akuzativu.',
        'vazba Grund für',
      ),
      choice(
        'Die Teilnahme ___ der Umfrage ist freiwillig.',
        ['an', 'in', 'zu', 'gegen'],
        'an',
        '„Teilnahme an“ se pojí s dativem; stažený tvar by zněl například „am Kurs“.',
        'vazba Teilnahme an',
      ),
      order(
        'Mnoho lidí má strach z rostoucích nákladů.',
        ['vor', 'Viele Menschen', 'steigenden Kosten.', 'haben', 'Angst'],
        ['Viele Menschen', 'haben', 'Angst', 'vor', 'steigenden Kosten.'],
        'Mnoho lidí má strach z rostoucích nákladů.',
        'Pevná vazba je „Angst vor“ a množné číslo po dativní předložce má přídavné jméno na -en.',
        'vazba Angst vor s dativem',
      ),
      choice(
        'Která vazba je správně?',
        [
          'die Hoffnung auf eine Lösung',
          'die Hoffnung für einer Lösung',
          'die Hoffnung an eine Lösung',
          'die Hoffnung über eine Lösung',
        ],
        'die Hoffnung auf eine Lösung',
        'Očekávaný cíl se po „Hoffnung“ vyjadřuje vazbou „auf“ s akuzativem.',
        'vazba Hoffnung auf',
      ),
    ],
  }),
  lesson({
    id: 'waehrend-clause',
    categoryId: 'narration-and-time',
    unit: 118,
    title: 'Während jako spojka',
    shortTitle: 'Dva souběžné děje',
    subtitle: 'Nepleť si vedlejší větu s předložkou před podstatným jménem.',
    cefr: 'B1',
    minutes: 7,
    completionXp: 24,
    concept:
      'Spojka während uvádí vedlejší větu se slovesem na konci a vyjadřuje souběh nebo kontrast. Před podstatným jménem je während předložka, obvykle s genitivem.',
    formula: 'während + podmět + … + sloveso, hlavní věta · während + genitiv',
    examples: [
      { de: 'Während ich koche, deckt er den Tisch.', cs: 'Zatímco vařím, prostírá stůl.' },
      {
        de: 'Während des Gesprächs machte sie Notizen.',
        cs: 'Během rozhovoru si dělala poznámky.',
      },
    ],
    questions: [
      order(
        'Zatímco tým sbírá data, připravuji prezentaci.',
        ['sammelt,', 'bereite', 'Während das Team', 'ich', 'die Präsentation', 'Daten', 'vor.'],
        ['Während das Team', 'Daten', 'sammelt,', 'bereite', 'ich', 'die Präsentation', 'vor.'],
        'Zatímco tým sbírá data, připravuji prezentaci.',
        'Ve vedlejší větě stojí „sammelt“ na konci; po ní začíná hlavní věta určitým „bereite“.',
        'slovosled vedlejší věty s während',
      ),
      choice(
        '___ des Seminars waren Handys ausgeschaltet.',
        ['Während', 'Während dass', 'Indem', 'Seitdem'],
        'Während',
        'Před jmennou skupinou „des Seminars“ funguje „während“ jako předložka s genitivem.',
        'während jako předložka',
      ),
      fill(
        'Doplň přítomný tvar slovesa warten na konec vedlejší věty.',
        'Während ich auf den Bus ',
        ', lese ich Nachrichten.',
        ['warte'],
        'Po während jde sloveso vedlejší věty na konec.',
        'Spojka „während“ odsouvá časované sloveso „warte“ na konec své vedlejší věty.',
        'koncová pozice slovesa',
      ),
      choice(
        'Která věta vyjadřuje kontrast dvou současných postojů?',
        [
          'Während Lea zustimmt, bleibt Tom skeptisch.',
          'Während Leas Zustimmung bleibt Tom skeptisch.',
          'Lea stimmt zu während, Tom bleibt skeptisch.',
          'Während stimmt Lea zu, Tom skeptisch bleibt.',
        ],
        'Während Lea zustimmt, bleibt Tom skeptisch.',
        'Spojka může vedle souběhu zvýraznit i protiklad; obě části mají správný slovosled.',
        'kontrastní význam während',
      ),
      choice(
        'Ve které větě je während spojka?',
        [
          'Während wir warten, prüfen wir die Tickets.',
          'Während der Wartezeit prüfen wir die Tickets.',
          'Während des Fluges schlief er.',
          'Während einer Pause telefonierte sie.',
        ],
        'Während wir warten, prüfen wir die Tickets.',
        'Za spojkou následuje celý podmět „wir“ a sloveso „warten“; ostatní příklady obsahují jmennou skupinu.',
        'rozlišení spojky a předložky',
      ),
    ],
  }),
  lesson({
    id: 'reciprocal-einander',
    categoryId: 'connected-thoughts',
    unit: 119,
    title: 'Sich, nebo einander?',
    shortTitle: 'Vzájemnost',
    subtitle: 'Ukaž, že dvě osoby dělají totéž jedna druhé, ne každá sama sobě.',
    cefr: 'B1',
    minutes: 7,
    completionXp: 24,
    concept:
      'Vzájemný děj lze často vyjádřit zvratným zájmenem sich, ale einander odstraní nejasnost mezi „sebe“ a „navzájem“. S předložkou vzniká miteinander nebo voneinander.',
    formula: 'množný podmět + einander · mit + einander = miteinander',
    examples: [
      { de: 'Die Nachbarn helfen einander.', cs: 'Sousedé si navzájem pomáhají.' },
      { de: 'Wir lernen voneinander.', cs: 'Učíme se jeden od druhého.' },
    ],
    questions: [
      choice(
        'Die beiden Teams tauschen ___ regelmäßig aus.',
        ['sich', 'einander sich', 'ihnen', 'euch'],
        'sich',
        'U slovesa „sich austauschen“ množný podmět přirozeně označuje vzájemnou výměnu.',
        'vzájemné sich',
      ),
      fill(
        'Zdůrazni, že kolegové pomáhají jeden druhému.',
        'Die Kollegen helfen ',
        '.',
        ['einander'],
        'Použij jednoznačné zájmeno pro navzájem.',
        '„Einander“ jednoznačně vyjadřuje vzájemnost a po slovese „helfen“ nepotřebuje další koncovku.',
        'jednoznačná vzájemnost s einander',
      ),
      choice(
        'Wir sprechen offen ___ unsere Erwartungen.',
        ['miteinander über', 'einander mit über', 'uns mit von', 'voneinander mit'],
        'miteinander über',
        'Předložka „mit“ se spojí s „einander“ v příslovce „miteinander“; téma uvádí „über“.',
        'předložkové příslovce miteinander',
      ),
      order(
        'Ve skupině se učíme jeden od druhého.',
        ['voneinander.', 'In der Gruppe', 'wir', 'lernen'],
        ['In der Gruppe', 'lernen', 'wir', 'voneinander.'],
        'Ve skupině se učíme jeden od druhého.',
        '„Voneinander“ spojuje předložku „von“ se vzájemným zájmenem a hlavní věta zachovává sloveso druhé.',
        'voneinander ve větě',
      ),
      choice(
        'Která věta může být bez kontextu nejednoznačná?',
        [
          'Sie fotografieren sich.',
          'Sie helfen einander.',
          'Sie reden miteinander.',
          'Sie lernen voneinander.',
        ],
        'Sie fotografieren sich.',
        '„Sich“ může znamenat, že každý fotografuje sebe, nebo že fotografují jeden druhého; „einander“ by význam zpřesnilo.',
        'rozpoznání nejasného sich',
      ),
    ],
  }),
  lesson({
    id: 'genitive-relative-pronouns',
    categoryId: 'case-system-plus',
    unit: 120,
    title: 'Dessen a deren',
    shortTitle: 'Čí ve vztažné větě',
    subtitle: 'Propoj osobu nebo věc s tím, co jí patří, bez opakování jména.',
    cefr: 'B2',
    minutes: 7,
    completionXp: 26,
    concept:
      'Genitivní vztažné zájmeno dessen odkazuje k mužskému a střednímu rodu, deren k ženskému rodu a množnému číslu. Tvar určuje předchozí jméno, ne následující věc.',
    formula: 'der/das → dessen · die/jednotné i množné → deren + jméno bez členu',
    examples: [
      { de: 'Das ist der Autor, dessen Buch wir lesen.', cs: 'To je autor, jehož knihu čteme.' },
      {
        de: 'Die Firma, deren Daten fehlen, antwortet später.',
        cs: 'Firma, jejíž data chybějí, odpoví později.',
      },
    ],
    questions: [
      choice(
        'Der Forscher, ___ Studie zitiert wurde, hält heute einen Vortrag.',
        ['dessen', 'deren', 'dem', 'denen'],
        'dessen',
        'Vztažné zájmeno odkazuje k mužskému „der Forscher“, proto má genitivní tvar „dessen“.',
        'dessen po mužském rodu',
      ),
      fill(
        'Doplň zájmeno odkazující k ženskému rodu.',
        'Die Expertin, ',
        ' Bericht wir geprüft haben, kommt morgen.',
        ['deren'],
        'Odkazujeme k die Expertin.',
        'Ženský antecedent „die Expertin“ vyžaduje „deren“, i když následující „Bericht“ je mužského rodu.',
        'deren po ženském rodu',
      ),
      choice(
        'Die Familien, ___ Häuser beschädigt wurden, erhalten Hilfe.',
        ['deren', 'dessen', 'denen', 'derer'],
        'deren',
        'Při odkazu k množnému číslu „die Familien“ používáme genitivní vztažné zájmeno „deren“.',
        'deren po množném čísle',
      ),
      order(
        'Mluvíme s organizací, jejíž návrh byl přijat.',
        ['angenommen', 'Wir sprechen', 'deren Vorschlag', 'mit der Organisation,', 'wurde.'],
        ['Wir sprechen', 'mit der Organisation,', 'deren Vorschlag', 'angenommen', 'wurde.'],
        'Mluvíme s organizací, jejíž návrh byl přijat.',
        'Pád „mit der Organisation“ neovlivní tvar „deren“; pasivní sloveso stojí na konci vztažné věty.',
        'deren ve vztažné větě',
      ),
      choice(
        'Která věta správně odkazuje na střední „Museum“ pomocí „dessen“?',
        [
          'Das Museum, dessen Eingang renoviert wird, bleibt geöffnet.',
          'Das Museum, deren Eingang renoviert wird, bleibt geöffnet.',
          'Das Museum, dessen der Eingang renoviert wird, bleibt geöffnet.',
          'Das Museum, dem Eingang renoviert wird, bleibt geöffnet.',
        ],
        'Das Museum, dessen Eingang renoviert wird, bleibt geöffnet.',
        'Střední rod „das Museum“ odkazuje pomocí „dessen“ a následující jméno „Eingang“ už člen nemá.',
        'dessen po středním rodu',
      ),
    ],
  }),
  lesson({
    id: 'indem-dadurch-dass',
    categoryId: 'sentence-architecture',
    unit: 121,
    title: 'Indem a dadurch, dass',
    shortTitle: 'Jak vzniká výsledek',
    subtitle: 'Pojmenuj prostředek nebo mechanismus, ne pouze obecnou příčinu.',
    cefr: 'B2',
    minutes: 7,
    completionXp: 26,
    concept:
      'Indem uvádí způsob nebo prostředek, kterým vzniká výsledek. Konstrukce dadurch, dass vyjadřuje stejný mechanismus důrazněji a hodí se i tehdy, když mají části různé podměty.',
    formula: 'výsledek, indem + … + sloveso · dadurch, dass + … + sloveso, výsledek',
    examples: [
      {
        de: 'Wir sparen Energie, indem wir Geräte ausschalten.',
        cs: 'Šetříme energii tím, že vypínáme přístroje.',
      },
      {
        de: 'Dadurch, dass alle mitplanen, steigt die Akzeptanz.',
        cs: 'Tím, že všichni plánují společně, roste přijetí.',
      },
    ],
    questions: [
      fill(
        'Doplň spojku vyjadřující prostředek.',
        'Wir schützen die Daten, ',
        ' wir Zugriffe verschlüsseln.',
        ['indem'],
        'Šifrování je způsob ochrany.',
        '„Indem“ propojuje výsledek s konkrétním prostředkem a posílá sloveso „verschlüsseln“ na konec.',
        'prostředek s indem',
      ),
      order(
        'Tím, že zveřejníme kritéria, bude rozhodnutí srozumitelné.',
        [
          'wird',
          'Dadurch, dass',
          'wir die Kriterien',
          'nachvollziehbar.',
          'veröffentlichen,',
          'die Entscheidung',
        ],
        [
          'Dadurch, dass',
          'wir die Kriterien',
          'veröffentlichen,',
          'wird',
          'die Entscheidung',
          'nachvollziehbar.',
        ],
        'Tím, že zveřejníme kritéria, bude rozhodnutí srozumitelné.',
        'Vedlejší věta po „dass“ končí slovesem a hlavní věta po čárce začíná určitým „wird“.',
        'slovosled s dadurch dass',
      ),
      choice(
        'Která věta odpovídá otázce „Jak toho dosáhneme?“',
        [
          'Wir erreichen das Ziel, indem wir regelmäßig messen.',
          'Wir erreichen das Ziel, obwohl wir regelmäßig messen.',
          'Wir erreichen das Ziel, seitdem wir regelmäßig messen.',
          'Wir erreichen das Ziel, falls wir regelmäßig messen.',
        ],
        'Wir erreichen das Ziel, indem wir regelmäßig messen.',
        'Měření je prostředek k dosažení cíle, což přesně vyjadřuje spojka „indem“.',
        'významový výběr indem',
      ),
      choice(
        'Která varianta přirozeně připouští různé podměty?',
        [
          'Dadurch, dass die Stadt mehr Busse einsetzt, sparen Pendler Zeit.',
          'Die Pendler sparen Zeit, indem die Stadt mehr Busse einsetzt.',
          'Die Stadt spart Pendler Zeit indem mehr Busse.',
          'Dadurch die Stadt mehr Busse einsetzt, sparen Pendler Zeit.',
        ],
        'Dadurch, dass die Stadt mehr Busse einsetzt, sparen Pendler Zeit.',
        'Rozvinutá konstrukce „dadurch, dass“ jasně odděluje jednání města od výsledku u dojíždějících.',
        'různé podměty s dadurch dass',
      ),
      fill(
        'Doplň přítomný tvar slovesa laden na konec vedlejší věty.',
        'Die App wird schneller, indem sie weniger Daten ',
        '.',
        ['lädt'],
        'Časované sloveso patří na konec.',
        'Po „indem“ stojí podmět „sie“, předmět a nakonec určité sloveso „lädt“.',
        'koncové sloveso po indem',
      ),
    ],
  }),
  lesson({
    id: 'haben-sein-zu-infinitive',
    categoryId: 'voice-and-modality',
    unit: 122,
    title: 'Haben a sein + zu',
    shortTitle: 'Povinnost a možnost',
    subtitle: 'Formální alternativa k müssen, können a pasivu v jediném vzorci.',
    cefr: 'B2',
    minutes: 8,
    completionXp: 26,
    concept:
      'Haben + zu + infinitiv vyjadřuje aktivní povinnost konkrétního nositele. Sein + zu + infinitiv má pasivní význam a podle kontextu označuje nutnost nebo možnost.',
    formula: 'osoba + haben + předmět + zu + infinitiv · věc + sein + zu + infinitiv',
    examples: [
      { de: 'Wir haben die Frist einzuhalten.', cs: 'Musíme dodržet lhůtu.' },
      { de: 'Der Fehler ist leicht zu beheben.', cs: 'Chybu lze snadno odstranit.' },
    ],
    questions: [
      choice(
        'Přeformuluj „Wir müssen die Daten prüfen.“ formálněji.',
        [
          'Wir haben die Daten zu prüfen.',
          'Wir sind die Daten zu prüfen.',
          'Wir haben zu den Daten prüfen.',
          'Die Daten haben uns prüfen.',
        ],
        'Wir haben die Daten zu prüfen.',
        'Aktivní povinnost konkrétního podmětu se vyjadřuje konstrukcí „haben + zu + infinitiv“.',
        'aktivní povinnost s haben zu',
      ),
      fill(
        'Vyjádři, že dokument lze snadno najít.',
        'Das Dokument ist leicht ',
        '.',
        ['zu finden'],
        'Použij sein + zu + infinitiv.',
        '„Ist leicht zu finden“ má pasivní význam „lze jej snadno najít“ a hodnotí možnost.',
        'možnost se sein zu',
      ),
      order(
        'Všechny žádosti musí být podány do pátku.',
        ['einzureichen.', 'bis Freitag', 'Alle Anträge', 'sind'],
        ['Alle Anträge', 'sind', 'bis Freitag', 'einzureichen.'],
        'Všechny žádosti musí být podány do pátku.',
        'Podmět věci se pojí s „sein“ a infinitivem s vloženým „zu“: einreichen → einzureichen.',
        'povinnost se sein zu',
      ),
      choice(
        'Která věta znamená „Tento rozdíl nelze přehlédnout“?',
        [
          'Dieser Unterschied ist nicht zu übersehen.',
          'Dieser Unterschied hat nicht zu übersehen.',
          'Dieser Unterschied ist nicht überzusehen.',
          'Dieser Unterschied wird nicht zu übersehen.',
        ],
        'Dieser Unterschied ist nicht zu übersehen.',
        'Zápor konstrukce „sein + zu“ vyjadřuje nemožnost; u „übersehen“ stojí „zu“ před infinitivem.',
        'nemožnost se sein zu',
      ),
      choice(
        'Kdo je nositelem povinnosti ve větě „Die Behörde hat den Antrag zu bearbeiten“?',
        ['die Behörde', 'der Antrag', 'není vyjádřen', 'žadatel'],
        'die Behörde',
        'U konstrukce s „haben“ je gramatický podmět zároveň tím, kdo má úkol vykonat.',
        'rozpoznání nositele povinnosti',
      ),
    ],
  }),
  lesson({
    id: 'evidential-sollen-wollen',
    categoryId: 'precision-and-style',
    unit: 123,
    title: 'Sollen a wollen jako cizí tvrzení',
    shortTitle: 'Údajně a podle vlastních slov',
    subtitle: 'Uveď informaci, ale nepřebírej automaticky odpovědnost za její pravdivost.',
    cefr: 'C1',
    minutes: 8,
    completionXp: 28,
    concept:
      'Evidenciální sollen značí neověřenou informaci z cizího zdroje, zatímco wollen uvádí tvrzení samotného podmětu o sobě. Minulost často tvoří infinitiv perfekta.',
    formula: 'podmět + soll + … + infinitiv/perfektum · podmět + will + … + infinitiv/perfektum',
    examples: [
      { de: 'Die Methode soll sehr zuverlässig sein.', cs: 'Metoda je údajně velmi spolehlivá.' },
      { de: 'Der Zeuge will nichts bemerkt haben.', cs: 'Svědek tvrdí, že si ničeho nevšiml.' },
    ],
    questions: [
      choice(
        'Der Bericht ___ mehrere Fehler enthalten.',
        ['soll', 'will', 'muss', 'darf'],
        'soll',
        'Neživý podmět nemůže tvrdit sám o sobě; „soll“ označuje informaci převzatou z jiného zdroje.',
        'neověřená zpráva se sollen',
      ),
      fill(
        'Vyjádři tvrzení svědka o vlastní minulosti.',
        'Der Zeuge will den Raum nicht betreten ',
        '.',
        ['haben'],
        'Použij infinitiv perfekta betreten haben.',
        '„Will … betreten haben“ nevyjadřuje vůli, nýbrž svědkovo vlastní tvrzení o minulém ději.',
        'evidenciální wollen s perfektem',
      ),
      choice(
        'Která věta zachovává největší odstup od neověřené zprávy?',
        [
          'Das Unternehmen soll die Zahlen korrigiert haben.',
          'Das Unternehmen hat die Zahlen sicher korrigiert.',
          'Das Unternehmen korrigierte zweifellos die Zahlen.',
          'Natürlich hat das Unternehmen die Zahlen korrigiert.',
        ],
        'Das Unternehmen soll die Zahlen korrigiert haben.',
        '„Soll … korrigiert haben“ připisuje minulou informaci cizímu zdroji bez potvrzení autora.',
        'epistemický odstup se sollen',
      ),
      order(
        'Autorka tvrdí, že rukopis dokončila sama.',
        ['beendet', 'Die Autorin', 'das Manuskript', 'will', 'allein', 'haben.'],
        ['Die Autorin', 'will', 'das Manuskript', 'allein', 'beendet', 'haben.'],
        'Autorka tvrdí, že rukopis dokončila sama.',
        'Evidenciální „will“ stojí určité na druhé pozici a infinitiv perfekta „beendet haben“ uzavírá větu.',
        'slovosled evidenciálního wollen',
      ),
      choice(
        'Co znamená „Die Insel soll unbewohnt sein“?',
        [
          'Ostrov je podle dostupných zpráv neobydlený.',
          'Ostrov má povinnost být neobydlený.',
          'Obyvatelé chtějí ostrov opustit.',
          'Ostrov bude určitě neobydlený.',
        ],
        'Ostrov je podle dostupných zpráv neobydlený.',
        'U neživého podmětu a vlastnosti vyjadřuje „soll“ zprostředkovanou, nikoli potvrzenou informaci.',
        'interpretace evidenciálního sollen',
      ),
    ],
  }),
  lesson({
    id: 'apposition-case-punctuation',
    categoryId: 'academic-precision',
    unit: 124,
    title: 'Přístavek: pád a čárky',
    shortTitle: 'Naše vedoucí, Frau Klein',
    subtitle: 'Doplň vysvětlující pojmenování tak, aby seděl význam, pád i interpunkce.',
    cefr: 'C1',
    minutes: 8,
    completionXp: 28,
    concept:
      'Volný přístavek doplňuje stejné označení jinými slovy, odděluje se čárkami a zpravidla přebírá pád řídící jmenné skupiny. Bez čárek může jít o těsné pojmenování.',
    formula: 'jméno v pádu, přístavek ve stejném pádu, pokračování věty',
    examples: [
      {
        de: 'Mit Frau Neumann, unserer Leiterin, sprechen wir morgen.',
        cs: 'S paní Neumannovou, naší vedoucí, mluvíme zítra.',
      },
      {
        de: 'Prag, die Hauptstadt Tschechiens, liegt an der Moldau.',
        cs: 'Praha, hlavní město Česka, leží na Vltavě.',
      },
    ],
    questions: [
      choice(
        'Wir danken Herrn Vogt, ___ erfahrenen Berater.',
        ['unserem', 'unseren', 'unserer', 'unseres'],
        'unserem',
        'Sloveso „danken“ vyžaduje dativ a volný přístavek přebírá mužský dativ „unserem Berater“.',
        'pádová shoda přístavku',
      ),
      fill(
        'Doplň druhou čárku uzavírající přístavek.',
        'Die Studie, eine Langzeituntersuchung',
        ' umfasst zehn Jahre.',
        [','],
        'Volný přístavek musí být oddělen z obou stran.',
        'Přístavek „eine Langzeituntersuchung“ je vložená informace, a proto jej uzavírá druhá čárka.',
        'interpunkce volného přístavku',
      ),
      choice(
        'Která věta má správný pád i čárky?',
        [
          'Mit Lara, meiner ältesten Kollegin, bespreche ich den Entwurf.',
          'Mit Lara, meine älteste Kollegin, bespreche ich den Entwurf.',
          'Mit Lara meiner ältesten Kollegin bespreche ich den Entwurf.',
          'Mit Lara, meine ältesten Kollegin bespreche ich den Entwurf.',
        ],
        'Mit Lara, meiner ältesten Kollegin, bespreche ich den Entwurf.',
        'Předložka „mit“ řídí dativ; přístavek je také v dativu a z obou stran stojí čárka.',
        'pád a interpunkce přístavku',
      ),
      order(
        'Návrh, důležitý první krok, byl jednomyslně přijat.',
        ['einstimmig', 'ein wichtiger erster Schritt,', 'Der Vorschlag,', 'angenommen.', 'wurde'],
        ['Der Vorschlag,', 'ein wichtiger erster Schritt,', 'wurde', 'einstimmig', 'angenommen.'],
        'Návrh, důležitý první krok, byl jednomyslně přijat.',
        'Přístavek v nominativu leží mezi dvěma čárkami a pasivní přísudek vytváří závorku „wurde … angenommen“.',
        'přístavek v pasivní větě',
      ),
      choice(
        'Ve které větě je doplnění nezbytné k určení osoby a běžně se nepíše mezi dvě čárky?',
        [
          'Meine Kollegin Anna leitet das Treffen.',
          'Anna, meine Kollegin, leitet das Treffen.',
          'Herr Vogt, unser Berater, kommt später.',
          'Die Elbe, ein großer Fluss, mündet in die Nordsee.',
        ],
        'Meine Kollegin Anna leitet das Treffen.',
        'Jméno „Anna“ těsně určuje, která kolegyně je míněna; ostatní přístavky jen přidávají vysvětlení.',
        'těsný a volný přístavek',
      ),
    ],
  }),
  lesson({
    id: 'ellipsis-parallelism',
    categoryId: 'text-cohesion',
    unit: 125,
    title: 'Elipsa a paralelní stavba',
    shortTitle: 'Úsporné věty bez ztráty',
    subtitle: 'Vypusť opakování pouze tam, kde čtenář chybějící část bezpečně doplní.',
    cefr: 'C1',
    minutes: 8,
    completionXp: 28,
    concept:
      'Elipsa vypouští opakovaný člen, který lze jednoznačně obnovit z paralelní části. Dobrá paralelní stavba zachovává stejný gramatický vzorec a brání nejasnému nebo falešnému spojení.',
    formula: 'A + přísudek + X, B + [stejný přísudek] + Y',
    examples: [
      {
        de: 'Die erste Gruppe prüfte die Daten, die zweite die Quellen.',
        cs: 'První skupina kontrolovala data, druhá zdroje.',
      },
      {
        de: 'Je klarer das Ziel, desto einfacher die Planung.',
        cs: 'Čím jasnější cíl, tím snazší plánování.',
      },
    ],
    questions: [
      choice(
        'Která věta používá jednoznačnou elipsu?',
        [
          'Lena analysiert die Kosten, Tom die Risiken.',
          'Lena analysiert die Kosten, weil Tom die Risiken.',
          'Lena analysiert, Tom wegen der Risiken.',
          'Lena die Kosten, obwohl Tom analysiert.',
        ],
        'Lena analysiert die Kosten, Tom die Risiken.',
        'Ve druhé paralelní části lze bez pochyb doplnit stejné sloveso „analysiert“.',
        'rozpoznání větné elipsy',
      ),
      fill(
        'Doplň „konečnou verzi“ německy (die Endfassung); sloveso se neopakuje.',
        'Das Team prüft heute den Entwurf, morgen ',
        '.',
        ['die Endfassung'],
        'Přísudek „prüft“ platí pro obě části.',
        'Paralelní časové členění dovoluje ve druhé části vypustit „prüft das Team“ a ponechat nový předmět.',
        'obnova vypuštěného přísudku',
      ),
      order(
        'Jedni chtějí rychlé řešení, druzí trvalé.',
        ['eine schnelle Lösung,', 'die anderen', 'Die einen', 'eine dauerhafte.', 'wollen'],
        ['Die einen', 'wollen', 'eine schnelle Lösung,', 'die anderen', 'eine dauerhafte.'],
        'Jedni chtějí rychlé řešení, druzí trvalé.',
        'Dvojice „die einen – die anderen“ vytváří paralelu; ve druhé části se přísudek „wollen“ bezpečně vypouští.',
        'paralelní konstrukce die einen die anderen',
      ),
      choice(
        'Která úprava vytvoří gramaticky paralelní výčet?',
        [
          'Ziel ist, Kosten zu senken, Abläufe zu vereinfachen und Qualität zu sichern.',
          'Ziel ist, Kosten zu senken, vereinfachte Abläufe und dass Qualität gesichert wird.',
          'Ziel ist die Kostensenkung, Abläufe zu vereinfachen und sichere Qualität.',
          'Ziel ist, Kosten senken, die Abläufe vereinfacht und Qualität zu sichern.',
        ],
        'Ziel ist, Kosten zu senken, Abläufe zu vereinfachen und Qualität zu sichern.',
        'Všechny tři členy mají stejnou stavbu „předmět + zu + infinitiv“, takže výčet zůstává čitelný.',
        'gramatický paralelismus ve výčtu',
      ),
      choice(
        'Proč je věta „Mara versprach Lea zu helfen und eine schnelle Antwort“ problematická?',
        [
          'Spojuje infinitivní skupinu s jmennou skupinou bez společné stavby.',
          'Po versprach nikdy nesmí stát infinitiv s zu.',
          'Jméno Lea musí být vždy v genitivu.',
          'Spojka und vyžaduje sloveso na konci celé věty.',
        ],
        'Spojuje infinitivní skupinu s jmennou skupinou bez společné stavby.',
        'Členy spojené „und“ nejsou gramaticky rovnocenné; druhou část je třeba doplnit například na „schnell zu antworten“.',
        'odhalení porušeného paralelismu',
      ),
    ],
  }),
];
