import type {
  GrammarChoiceQuestion,
  GrammarFillQuestion,
  GrammarLesson,
  GrammarOrderQuestion,
  GrammarQuestion,
} from './grammar.ts';

type QuestionDraft =
  | Omit<GrammarChoiceQuestion, 'id'>
  | Omit<GrammarFillQuestion, 'id'>
  | Omit<GrammarOrderQuestion, 'id'>;

function choice(
  prompt: string,
  options: string[],
  answer: string,
  explanation: string,
  skill: string,
  instruction = 'Vyber správnou možnost.',
): QuestionDraft {
  return { kind: 'choice', prompt, instruction, options, answer, explanation, skill };
}

function fill(
  prompt: string,
  before: string,
  after: string,
  answers: string[],
  hint: string,
  explanation: string,
  skill: string,
  instruction = 'Doplň chybějící část.',
): QuestionDraft {
  return {
    kind: 'fill',
    prompt,
    instruction,
    before,
    after,
    answers,
    hint,
    explanation,
    skill,
  };
}

function order(
  prompt: string,
  tokens: string[],
  answer: string[],
  translation: string,
  explanation: string,
  skill: string,
  instruction = 'Poskládej větu ve správném pořadí.',
): QuestionDraft {
  return {
    kind: 'order',
    prompt,
    instruction,
    tokens,
    answer,
    translation,
    explanation,
    skill,
  };
}

function lesson(
  definition: Omit<GrammarLesson, 'questions'> & { questions: QuestionDraft[] },
): GrammarLesson {
  const { questions, ...metadata } = definition;
  return {
    ...metadata,
    questions: questions.map(
      (question, index) =>
        ({ ...question, id: `${definition.id}-${index + 1}` }) as GrammarQuestion,
    ),
  };
}

export const additionalGrammarLessons: GrammarLesson[] = [
  lesson({
    id: 'noun-plurals',
    categoryId: 'daily-foundations',
    unit: 86,
    title: 'Množné číslo bez falešné univerzální koncovky',
    shortTitle: 'Tische, Kinder, Autos',
    subtitle: 'Němčina má několik vzorců plurálu; nauč se nový tvar vždy spolu se slovem.',
    cefr: 'A1',
    minutes: 6,
    completionXp: 18,
    concept:
      'Německé množné číslo nemá jedinou koncovku. Časté jsou -e, -er, -(e)n a -s, někdy se přidá přehláska a někdy se tvar nezmění. Člen je v nominativu vždy die.',
    formula: 'der Tisch → die Tische · das Kind → die Kinder · das Auto → die Autos',
    examples: [
      { de: 'Hier stehen drei Tische.', cs: 'Tady stojí tři stoly.' },
      { de: 'Die Kinder spielen draußen.', cs: 'Děti si hrají venku.' },
    ],
    questions: [
      choice(
        'ein Tisch – zwei ___',
        ['Tische', 'Tischen', 'Tischs', 'Tischer'],
        'Tische',
        '„Tisch“ tvoří množné číslo koncovkou -e: „die Tische“.',
        'plurál s -e',
      ),
      fill(
        'Doplň množné číslo.',
        'eine Lampe – zwei ',
        '',
        ['Lampen'],
        'Koncovka -(e)n je častá u ženského rodu.',
        '„Lampe“ dostává v množném čísle koncovku -n: „Lampen“.',
        'plurál ženského podstatného jména',
      ),
      choice(
        'das Kind – die ___',
        ['Kinde', 'Kinds', 'Kindern', 'Kinder'],
        'Kinder',
        'Množné číslo od „das Kind“ je nepravidelné „die Kinder“.',
        'plurál s -er',
      ),
      choice(
        'Které spojení je správně?',
        ['zwei Autos', 'zwei Autoen', 'zwei Auten', 'zwei Auto'],
        'zwei Autos',
        'Přejatá slova zakončená samohláskou často tvoří plurál pomocí -s.',
        'plurál s -s',
      ),
      order(
        'Řekni: Tady jsou tři knihy.',
        ['drei', 'Hier', 'Bücher.', 'sind'],
        ['Hier', 'sind', 'drei', 'Bücher.'],
        'Tady jsou tři knihy.',
        '„Buch“ mění v plurálu samohlásku a přidává -er: „Bücher“; sloveso je „sind“.',
        'nepravidelný plurál ve větě',
      ),
    ],
  }),
  lesson({
    id: 'present-vowel-change',
    categoryId: 'verb-lab',
    unit: 87,
    title: 'Změna samohlásky v přítomném čase',
    shortTitle: 'Du fährst, er liest',
    subtitle: 'Některá silná slovesa mění kmen jen u du a er/sie/es.',
    cefr: 'A1',
    minutes: 6,
    completionXp: 18,
    concept:
      'U části silných sloves se v přítomném čase mění kmenová samohláska: a na ä, e na i nebo ie. Změna nastává pouze u du a er/sie/es, běžné osobní koncovky ale zůstávají.',
    formula: 'fahren → du fährst · lesen → er liest · sprechen → sie spricht',
    examples: [
      { de: 'Du fährst jeden Morgen mit dem Bus.', cs: 'Každé ráno jezdíš autobusem.' },
      { de: 'Meine Schwester liest sehr gern.', cs: 'Moje sestra velmi ráda čte.' },
    ],
    questions: [
      fill(
        'Doplň tvar slovesa fahren.',
        'Du ',
        ' heute nach Berlin.',
        ['fährst'],
        'a → ä u osoby du',
        'U „du“ mění fahren kmen na „fähr-“ a přidává koncovku -st.',
        'změna a na ä',
      ),
      choice(
        'Er ___ jeden Abend ein Buch.',
        ['lest', 'liest', 'lesen', 'leset'],
        'liest',
        '„Lesen“ mění u er/sie/es kmenové e na ie: „er liest“.',
        'změna e na ie',
      ),
      choice(
        'Sprichst du Deutsch? — Ano, tvar „sprichst“ vzniká z…',
        ['sprechen', 'springen', 'schreiben', 'spielen'],
        'sprechen',
        'Silné sloveso „sprechen“ mění u du kmenové e na i.',
        'rozpoznání změněného kmene',
      ),
      choice(
        'Ihr ___ am Wochenende lange.',
        ['schläft', 'schlaft', 'schlafen', 'schläfst'],
        'schlaft',
        'U „ihr“ se kmenová samohláska nemění; správně je „ihr schlaft“.',
        'osoba bez změny kmene',
      ),
      order(
        'Řekni: Můj bratr dnes vidí ten film.',
        ['heute', 'Mein Bruder', 'den Film.', 'sieht'],
        ['Mein Bruder', 'sieht', 'heute', 'den Film.'],
        'Můj bratr dnes vidí ten film.',
        '„Sehen“ mění u třetí osoby e na ie: „sieht“; určité sloveso stojí druhé.',
        'silné sloveso a slovosled',
      ),
    ],
  }),
  lesson({
    id: 'accusative-prepositions',
    categoryId: 'everyday-phrases',
    unit: 88,
    title: 'Předložky, po kterých vždy přijde akuzativ',
    shortTitle: 'Durch, für, gegen, ohne, um',
    subtitle: 'Pět předložek, u kterých nemusíš pád pokaždé znovu hádat.',
    cefr: 'A1',
    minutes: 6,
    completionXp: 19,
    concept:
      'Předložky durch, für, gegen, ohne a um se vždy pojí s akuzativem. Nejvíc je změna vidět u mužského rodu: der se mění na den a ein na einen.',
    formula: 'durch · für · gegen · ohne · um + akuzativ',
    examples: [
      { de: 'Das Geschenk ist für meinen Bruder.', cs: 'Ten dárek je pro mého bratra.' },
      { de: 'Wir gehen durch den Park.', cs: 'Jdeme parkem.' },
    ],
    questions: [
      choice(
        'Das ist für ___ Vater.',
        ['mein', 'meinem', 'meinen', 'meiner'],
        'meinen',
        '„Für“ vyžaduje akuzativ; mužský přivlastňovací člen má tvar „meinen“.',
        'für s mužským akuzativem',
      ),
      fill(
        'Doplň určitý člen v jednotném čísle.',
        'Wir laufen durch ',
        ' Park.',
        ['den'],
        'der Park v akuzativu',
        'Po „durch“ stojí mužský akuzativ „den Park“.',
        'durch s akuzativem',
      ),
      choice(
        'Sie geht nie ohne ___ Regenschirm raus.',
        ['ein', 'einem', 'einen', 'einer'],
        'einen',
        '„Ohne“ se pojí s akuzativem, proto „einen Regenschirm“.',
        'ohne s akuzativem',
      ),
      choice(
        'Která věta používá předložku „um“ se správným pádem?',
        [
          'Der Bus fährt um der Stadt.',
          'Der Bus fährt um die Stadt.',
          'Der Bus fährt um dem Stadt.',
          'Der Bus fährt um den Stadt.',
        ],
        'Der Bus fährt um die Stadt.',
        '„Stadt“ je ženského rodu a po „um“ zůstává v akuzativu člen „die“.',
        'um s ženským akuzativem',
      ),
      order(
        'Řekni: Hraji proti svému kamarádovi.',
        ['meinen Freund.', 'spiele', 'gegen', 'Ich'],
        ['Ich', 'spiele', 'gegen', 'meinen Freund.'],
        'Hraji proti svému kamarádovi.',
        '„Gegen“ vyžaduje akuzativ: „gegen meinen Freund“.',
        'gegen s akuzativem ve větě',
      ),
    ],
  }),
  lesson({
    id: 'dative-prepositions',
    categoryId: 'everyday-phrases',
    unit: 89,
    title: 'Předložky, po kterých vždy přijde dativ',
    shortTitle: 'Aus, bei, mit, nach, seit, von, zu',
    subtitle: 'Nauč se celou skupinu a v běžných větách získáš jistotu v dativu.',
    cefr: 'A1',
    minutes: 7,
    completionXp: 19,
    concept:
      'Předložky aus, bei, mit, nach, seit, von a zu se vždy pojí s dativem. Členy se mění na dem, der a den; bez členu se často používá nach u měst a zemí.',
    formula: 'aus · bei · mit · nach · seit · von · zu + dativ',
    examples: [
      { de: 'Ich fahre mit dem Bus.', cs: 'Jedu autobusem.' },
      { de: 'Sie wohnt seit einem Jahr in Wien.', cs: 'Bydlí rok ve Vídni.' },
    ],
    questions: [
      choice(
        'Wir fahren mit ___ Zug.',
        ['der', 'den', 'dem', 'des'],
        'dem',
        '„Mit“ vyžaduje dativ; mužský člen „der“ se mění na „dem“.',
        'mit s mužským dativem',
      ),
      fill(
        'Doplň přivlastňovací člen mein ve správném pádu.',
        'Ich bin heute bei ',
        ' Tante.',
        ['meiner'],
        'meine Tante v dativu',
        'Po „bei“ stojí dativ; ženský tvar je „meiner Tante“.',
        'bei s ženským dativem',
      ),
      choice(
        'Cíl je Berlín. Morgen fliegen wir ___ Berlin.',
        ['zu', 'nach', 'bei', 'aus'],
        'nach',
        'Před názvem města bez členu vyjadřuje směr předložka „nach“.',
        'nach u města',
      ),
      choice(
        'Ich lerne Deutsch seit ___ Monat.',
        ['ein', 'einen', 'einem', 'eines'],
        'einem',
        '„Seit“ vyžaduje dativ, proto „seit einem Monat“.',
        'seit s dativem',
      ),
      order(
        'Řekni: Jdu z práce domů.',
        ['nach Hause.', 'Ich', 'von der Arbeit', 'gehe'],
        ['Ich', 'gehe', 'von der Arbeit', 'nach Hause.'],
        'Jdu z práce domů.',
        '„Von“ stojí s dativem „der Arbeit“ a ustálený směr domů je „nach Hause“.',
        'dvě dativní předložkové vazby',
      ),
    ],
  }),
  lesson({
    id: 'demonstrative-determiners',
    categoryId: 'reference-and-quantity',
    unit: 90,
    title: 'Dieser, jeder a welcher jako členy',
    shortTitle: 'Dieser Zug, jedes Kind',
    subtitle: 'Ukazuj, zobecňuj a ptej se pomocí stejného systému koncovek.',
    cefr: 'A2',
    minutes: 7,
    completionXp: 21,
    concept:
      'Výrazy dieser, jeder a welcher stojí před podstatným jménem a skloňují se podobně jako určitý člen. Jejich koncovka proto přímo ukazuje rod, číslo a pád.',
    formula: 'dieser/diese/dieses · diesen · diesem/dieser · jeder/jede/jedes',
    examples: [
      { de: 'Dieser Zug fährt nach Hamburg.', cs: 'Tento vlak jede do Hamburku.' },
      { de: 'Mit welcher App lernst du?', cs: 'S jakou aplikací se učíš?' },
    ],
    questions: [
      choice(
        '___ Zug fährt zum Flughafen.',
        ['Diese', 'Dieser', 'Dieses', 'Diesen'],
        'Dieser',
        '„Zug“ je mužský podmět, proto nominativ „dieser“.',
        'mužský nominativ dieser',
      ),
      fill(
        'Doplň tvar dieser.',
        '',
        ' Buch gehört meiner Schwester.',
        ['Dieses'],
        'das Buch v nominativu',
        'Střední nominativ má koncovku -es: „dieses Buch“.',
        'střední nominativ dieser',
      ),
      choice(
        '___ Film möchtest du sehen?',
        ['Welcher', 'Welche', 'Welches', 'Welchen'],
        'Welchen',
        '„Film“ je přímý mužský předmět, proto akuzativ „welchen“.',
        'tázací člen v akuzativu',
      ),
      choice(
        'Ich arbeite gern mit ___ App.',
        ['diese', 'dieser', 'diesem', 'diesen'],
        'dieser',
        'Po „mit“ je dativ; ženský tvar zní „dieser App“.',
        'ženský dativ dieser',
      ),
      order(
        'Řekni: Každý student potřebuje tuto knihu.',
        ['dieses Buch.', 'Jeder', 'braucht', 'Student'],
        ['Jeder', 'Student', 'braucht', 'dieses Buch.'],
        'Každý student potřebuje tuto knihu.',
        'Mužský podmět má „jeder Student“, střední akuzativ má „dieses Buch“.',
        'dva der-výrazy ve větě',
      ),
    ],
  }),
  lesson({
    id: 'connector-adverbs',
    categoryId: 'reference-and-quantity',
    unit: 91,
    title: 'Deshalb a sonst: spojení s inverzí',
    shortTitle: 'Deshalb komme ich',
    subtitle: 'Propoj dvě hlavní věty a po konektoru nezapomeň dát sloveso před podmět.',
    cefr: 'A2',
    minutes: 7,
    completionXp: 21,
    concept:
      'Příslovce deshalb, deswegen a darum odkazují na příčinu v předchozí větě, sonst varuje před jiným následkem. Obsazují první pozici, takže po nich následuje určité sloveso a teprve potom podmět.',
    formula: 'věta. Deshalb/Deswegen/Darum/Sonst + sloveso + podmět + …',
    examples: [
      { de: 'Es regnet. Deshalb bleibe ich zu Hause.', cs: 'Prší. Proto zůstanu doma.' },
      { de: 'Beeil dich, sonst verpasst du den Bus.', cs: 'Pospěš si, jinak zmeškáš autobus.' },
    ],
    questions: [
      choice(
        'Ich bin krank. ___ bleibe ich heute im Bett.',
        ['Deshalb', 'Denn', 'Weil', 'Ob'],
        'Deshalb',
        'Druhá věta vyjadřuje následek; „deshalb“ stojí na první pozici a po něm následuje „bleibe“.',
        'důsledek pomocí deshalb',
      ),
      choice(
        'Která věta má správný slovosled?',
        [
          'Deswegen ich nehme den Zug.',
          'Deswegen nehme ich den Zug.',
          'Deswegen den Zug ich nehme.',
          'Deswegen ich den Zug nehme.',
        ],
        'Deswegen nehme ich den Zug.',
        '„Deswegen“ obsazuje první pozici, proto musí následovat určité sloveso „nehme“.',
        'inverze po spojovacím příslovci',
      ),
      fill(
        'Doplň varování ve významu „jinak“.',
        'Nimm einen Regenschirm mit, ',
        ' wirst du nass.',
        ['sonst'],
        'jinak',
        '„Sonst“ uvádí nežádoucí následek a vyvolává slovosled „sonst wirst du“.',
        'následek pomocí sonst',
      ),
      order(
        'Řekni: Auto je rozbité. Proto jedu autobusem.',
        ['ich', 'Deswegen', 'mit dem Bus.', 'fahre'],
        ['Deswegen', 'fahre', 'ich', 'mit dem Bus.'],
        'Proto jedu autobusem.',
        'Po „deswegen“ následuje časované sloveso „fahre“ a potom podmět „ich“.',
        'důsledková věta s inverzí',
      ),
      choice(
        'Der Laden ist schon geschlossen. ___ kaufen wir morgen ein.',
        ['Darum', 'Oder', 'Dass', 'Weil'],
        'Darum',
        '„Darum“ shrnuje příčinu a uvádí důsledek se slovesem na druhé pozici.',
        'návaznost pomocí darum',
      ),
    ],
  }),
  lesson({
    id: 'adjective-endings-after-ein',
    categoryId: 'purpose-and-complements',
    unit: 92,
    title: 'Přídavné jméno po ein, mein a kein',
    shortTitle: 'Ein guter Plan',
    subtitle: 'Když člen nemá jasnou koncovku, doplní potřebnou informaci přídavné jméno.',
    cefr: 'A2',
    minutes: 8,
    completionXp: 22,
    concept:
      'Po ein, kein a přivlastňovacích členech se používá smíšené skloňování. V nominativu mužského a středního rodu nese rod přídavné jméno; v mužském akuzativu a v dativu bývá koncovka -en.',
    formula: 'ein guter Kaffee · ein frisches Brot · keinen kalten Saft · mit meinem neuen Rad',
    examples: [
      { de: 'Das ist ein guter Vorschlag.', cs: 'To je dobrý návrh.' },
      { de: 'Sie trägt ihre neue Jacke.', cs: 'Má na sobě svou novou bundu.' },
    ],
    questions: [
      choice(
        'Das ist ein ___ Kaffee.',
        ['gute', 'guter', 'guten', 'gutes'],
        'guter',
        '„Ein“ neukazuje v mužském nominativu rod koncovkou, proto ji nese přídavné jméno: „guter“.',
        'mužský nominativ po ein',
      ),
      fill(
        'Doplň koncovku.',
        'Meine neu',
        ' Jacke ist warm.',
        ['e'],
        'ženský nominativ',
        'Po „meine“ má přídavné jméno v ženském nominativu koncovku -e.',
        'ženský nominativ po přivlastnění',
      ),
      choice(
        'Ich trinke keinen ___ Saft.',
        ['kalter', 'kaltes', 'kalte', 'kalten'],
        'kalten',
        'Mužský akuzativ je už označen tvarem „keinen“, přídavné jméno proto končí na -en.',
        'mužský akuzativ po kein',
      ),
      choice(
        'Sie spielt mit ihrem ___ Kind.',
        ['kleine', 'kleines', 'kleinen', 'kleinem'],
        'kleinen',
        'Po přivlastňovacím členu v dativu má přídavné jméno koncovku -en.',
        'dativ po přivlastňovacím členu',
      ),
      order(
        'Řekni: Hledám levný byt.',
        ['eine', 'Ich', 'Wohnung.', 'günstige', 'suche'],
        ['Ich', 'suche', 'eine', 'günstige', 'Wohnung.'],
        'Hledám levný byt.',
        'Ženský akuzativ po „eine“ má na přídavném jménu koncovku -e.',
        'ženský akuzativ po ein',
      ),
    ],
  }),
  lesson({
    id: 'position-and-placement-verbs',
    categoryId: 'purpose-and-complements',
    unit: 93,
    title: 'Liegen, legen, stehen a stellen',
    shortTitle: 'Kde leží, kam pokládám',
    subtitle: 'Rozliš klidovou polohu od změny místa a správný pád přijde přirozeně.',
    cefr: 'A2',
    minutes: 7,
    completionXp: 22,
    concept:
      'Liegen, stehen a sitzen popisují polohu a pojí se s otázkou wo a dativem. Legen, stellen a setzen vyjadřují umístění něčeho někam, proto odpovídají na wohin a používají akuzativ.',
    formula: 'wo? liegen/stehen/sitzen + D · wohin? legen/stellen/setzen + A',
    examples: [
      { de: 'Das Buch liegt auf dem Tisch.', cs: 'Kniha leží na stole.' },
      { de: 'Ich lege das Buch auf den Tisch.', cs: 'Pokládám knihu na stůl.' },
    ],
    questions: [
      choice(
        'Die Schlüssel ___ auf dem Regal.',
        ['legen', 'liegen', 'stellen', 'setzen'],
        'liegen',
        'Klíče už jsou v klidové poloze, proto použijeme „liegen“.',
        'poloha pomocí liegen',
      ),
      fill(
        'Doplň sloveso pro změnu místa.',
        'Ich ',
        ' die Schlüssel auf das Regal.',
        ['lege'],
        'něco položit někam',
        'Podmět aktivně umisťuje klíče, proto „legen“; směr vyžaduje akuzativ „auf das Regal“.',
        'umístění pomocí legen',
      ),
      choice(
        'Die Vase ___ neben dem Fenster.',
        ['steht', 'stellt', 'liegt', 'setzt'],
        'steht',
        'Váza je ve svislé klidové poloze, proto „steht“.',
        'poloha pomocí stehen',
      ),
      choice(
        'Setz dich bitte auf ___ Stuhl.',
        ['der', 'dem', 'den', 'des'],
        'den',
        '„Sich setzen“ vyjadřuje pohyb na cílové místo, proto akuzativ „auf den Stuhl“.',
        'setzen se směrovým akuzativem',
      ),
      order(
        'Řekni: Věším obraz na stěnu.',
        ['an die Wand.', 'das Bild', 'Ich', 'hänge'],
        ['Ich', 'hänge', 'das Bild', 'an die Wand.'],
        'Věším obraz na stěnu.',
        'Jde o změnu umístění, proto otázka wohin a akuzativ „an die Wand“.',
        'směr s akuzativem',
      ),
    ],
  }),
  lesson({
    id: 'temporal-subordinate-clauses',
    categoryId: 'narration-and-time',
    unit: 94,
    title: 'Seitdem, bis, sobald a solange',
    shortTitle: 'Časové hranice děje',
    subtitle: 'Vyjádři začátek, konec, okamžitou návaznost i souběžné trvání.',
    cefr: 'B1',
    minutes: 8,
    completionXp: 24,
    concept:
      'Seitdem označuje děj trvající od minulého bodu, bis jeho koncovou hranici, sobald bezprostřední návaznost a solange dobu souběžného trvání. Ve vedlejší větě stojí určité sloveso na konci.',
    formula: 'seitdem/bis/sobald/solange + podmět + … + sloveso',
    examples: [
      {
        de: 'Seitdem ich hier wohne, fahre ich mit dem Rad.',
        cs: 'Od té doby, co tu bydlím, jezdím na kole.',
      },
      { de: 'Sobald ich angekommen bin, rufe ich dich an.', cs: 'Jakmile dorazím, zavolám ti.' },
    ],
    questions: [
      choice(
        '___ sie in Berlin wohnt, spricht sie täglich Deutsch.',
        ['Bis', 'Seitdem', 'Sobald', 'Bevor'],
        'Seitdem',
        'Mluvení trvá od okamžiku přestěhování až do současnosti, proto „seitdem“.',
        'počáteční hranice se seitdem',
      ),
      fill(
        'Doplň spojku pro koncovou hranici.',
        'Warte hier, ',
        ' ich zurückkomme.',
        ['bis'],
        'až do okamžiku, kdy',
        'Čekání má skončit návratem, proto vedlejší větu uvádí „bis“.',
        'koncová hranice s bis',
      ),
      choice(
        '___ der Bericht fertig ist, schicke ich ihn dir.',
        ['Solange', 'Seitdem', 'Sobald', 'Währenddessen'],
        'Sobald',
        'Odeslání nastane ihned po dokončení zprávy, proto „sobald“.',
        'okamžitá návaznost',
      ),
      choice(
        'Která věta má správný slovosled?',
        [
          'Solange du bist krank, bleib zu Hause.',
          'Solange bist du krank, bleib zu Hause.',
          'Solange du krank bist, bleib zu Hause.',
          'Solange du krank, bist bleib zu Hause.',
        ],
        'Solange du krank bist, bleib zu Hause.',
        'Ve vedlejší větě se „solange“ stojí určité sloveso „bist“ na konci.',
        'slovosled po solange',
      ),
      order(
        'Řekni: Jakmile budu mít čas, ozvu se ti.',
        ['melde', 'Sobald', 'ich', 'ich', 'Zeit habe,', 'mich bei dir.'],
        ['Sobald', 'ich', 'Zeit habe,', 'melde', 'ich', 'mich bei dir.'],
        'Jakmile budu mít čas, ozvu se ti.',
        'Vedlejší větu uzavírá „habe“ a následující hlavní věta začíná inverzí „melde ich“.',
        'časová věta před hlavní větou',
      ),
    ],
  }),
  lesson({
    id: 'brauchen-nicht-zu',
    categoryId: 'narration-and-time',
    unit: 95,
    title: 'Brauchen + nicht zu místo „nemuset“',
    shortTitle: 'Du brauchst nicht zu',
    subtitle: 'Odliš nepřítomnost povinnosti od zákazu a vyhni se častému významovému omylu.',
    cefr: 'B1',
    minutes: 7,
    completionXp: 24,
    concept:
      'Brauchen + nicht/kein + zu + infinitiv znamená, že něco není nutné; zákaz vyjadřuje nicht dürfen. Brauchen lze použít také s omezením nur, erst nebo kaum: Du brauchst nur anzurufen znamená „Stačí zavolat“.',
    formula: 'nicht brauchen zu = nemuset · nur brauchen zu = stačí · nicht dürfen = nesmět',
    examples: [
      { de: 'Du brauchst heute nicht zu arbeiten.', cs: 'Dnes nemusíš pracovat.' },
      { de: 'Du brauchst nur anzurufen.', cs: 'Stačí, když zavoláš.' },
    ],
    questions: [
      choice(
        '„Dnes nemusíš přijít“ znamená…',
        [
          'Du darfst heute nicht kommen.',
          'Du brauchst heute nicht zu kommen.',
          'Du brauchst heute zu kommen.',
          'Du musst heute nicht zu kommen.',
        ],
        'Du brauchst heute nicht zu kommen.',
        '„Nicht brauchen zu“ ruší povinnost; „nicht dürfen“ by znamenalo zákaz.',
        'nemuset proti nesmět',
      ),
      fill(
        'Doplň infinitiv slovesa warten se zu.',
        'Ihr braucht nicht lange ',
        '.',
        ['zu warten'],
        'zu + infinitiv warten',
        'Po záporném „braucht nicht“ následuje infinitiv s „zu“: „zu warten“.',
        'infinitiv po brauchen',
      ),
      choice(
        'Welche Aussage ist ein Verbot?',
        [
          'Hier braucht man nicht zu bezahlen.',
          'Hier darf man nicht parken.',
          'Hier braucht niemand zu warten.',
          'Hier muss man nicht reservieren.',
        ],
        'Hier darf man nicht parken.',
        'Pouze „nicht dürfen“ vyjadřuje, že je něco zakázané.',
        'rozlišení zákazu',
      ),
      choice(
        'Man braucht ___ Angst zu haben.',
        ['nicht', 'keine', 'keinen', 'kein'],
        'keine',
        '„Angst“ je ženského rodu; záporný akuzativní tvar je „keine Angst“.',
        'brauchen s kein',
      ),
      order(
        'Řekni: Nemusíme se rozhodnout hned.',
        ['nicht', 'Wir', 'sofort', 'zu entscheiden.', 'brauchen', 'uns'],
        ['Wir', 'brauchen', 'uns', 'nicht', 'sofort', 'zu entscheiden.'],
        'Nemusíme se rozhodnout hned.',
        '„Brauchen“ stojí na druhé pozici, zápor ve středním poli a infinitiv s „zu“ na konci.',
        'slovosled s brauchen nicht zu',
      ),
    ],
  }),
  lesson({
    id: 'adjective-prepositions',
    categoryId: 'case-system-plus',
    unit: 96,
    title: 'Přídavné jméno a jeho pevná předložka',
    shortTitle: 'Stolz auf, zufrieden mit',
    subtitle: 'Uč se vlastnost společně s vazbou a pádem, který po ní následuje.',
    cefr: 'B1',
    minutes: 7,
    completionXp: 24,
    concept:
      'Řada přídavných jmen vyžaduje pevnou předložku a určitý pád. Vazbu nelze bezpečně odvodit z češtiny, proto je užitečné ukládat ji jako jeden celek s typickým příkladem.',
    formula: 'stolz auf + A · zufrieden mit + D · interessiert an + D · verantwortlich für + A',
    examples: [
      { de: 'Sie ist stolz auf ihre Tochter.', cs: 'Je hrdá na svou dceru.' },
      { de: 'Wir sind mit dem Ergebnis zufrieden.', cs: 'Jsme spokojení s výsledkem.' },
    ],
    questions: [
      choice(
        'Er ist stolz ___ seinen Erfolg.',
        ['an', 'mit', 'auf', 'von'],
        'auf',
        'Ustálená vazba zní „stolz auf + akuzativ“.',
        'vazba stolz auf',
      ),
      fill(
        'Doplň předložku.',
        'Bist du ',
        ' dem Service zufrieden?',
        ['mit'],
        'zufrieden … + dativ',
        '„Zufrieden“ se pojí s „mit + dativ“: „mit dem Service“.',
        'vazba zufrieden mit',
      ),
      choice(
        'Sie ist sehr ___ moderner Kunst interessiert.',
        ['für', 'an', 'über', 'auf'],
        'an',
        'Přídavné jméno „interessiert“ vyžaduje „an + dativ“.',
        'vazba interessiert an',
      ),
      choice(
        'Wer ist ___ die Sicherheit verantwortlich?',
        ['für', 'von', 'bei', 'zu'],
        'für',
        'Vazba „verantwortlich für“ se pojí s akuzativem.',
        'vazba verantwortlich für',
      ),
      order(
        'Řekni: Výsledek závisí na počasí.',
        ['vom Wetter.', 'ist', 'Das Ergebnis', 'abhängig'],
        ['Das Ergebnis', 'ist', 'abhängig', 'vom Wetter.'],
        'Výsledek závisí na počasí.',
        'Přídavné jméno „abhängig“ se pojí s „von + dativ“, zde staženě „vom Wetter“.',
        'vazba abhängig von',
      ),
    ],
  }),
  lesson({
    id: 'nominalized-infinitives',
    categoryId: 'case-system-plus',
    unit: 97,
    title: 'Infinitiv jako podstatné jméno',
    shortTitle: 'Beim Kochen, zum Mitnehmen',
    subtitle: 'Proměň činnost v pojem a využij běžné vazby pro každodenní situace.',
    cefr: 'B1',
    minutes: 7,
    completionXp: 24,
    concept:
      'Každý infinitiv lze zpodstatnit: píše se pak s velkým písmenem, má střední rod a často stojí po stažené předložce beim, zum nebo vorm. Slovesné doplnění může zůstat součástí celého výrazu.',
    formula: 'lesen → das Lesen · bei dem Kochen → beim Kochen · zu dem Mitnehmen → zum Mitnehmen',
    examples: [
      { de: 'Beim Kochen höre ich Musik.', cs: 'Při vaření poslouchám hudbu.' },
      { de: 'Ist der Kaffee zum Mitnehmen?', cs: 'Je ta káva s sebou?' },
    ],
    questions: [
      choice(
        '___ macht mir Spaß.',
        ['Lesen', 'lesen', 'Das lesen', 'Gelesen'],
        'Lesen',
        'Zpodstatněný infinitiv se píše s velkým písmenem; člen lze v této větě vynechat.',
        'velké písmeno u infinitivu',
      ),
      fill(
        'Doplň sloveso kochen jako podstatné jméno.',
        'Beim ',
        ' höre ich einen Podcast.',
        ['Kochen'],
        'kochen jako podstatné jméno',
        'Po staženém „beim“ stojí zpodstatněný infinitiv s velkým písmenem: „Kochen“.',
        'zpodstatnění po beim',
      ),
      choice(
        'Ich hätte gern einen Tee ___.',
        ['zum Mitnehmen', 'zu mitnehmen', 'zum mitnehmen', 'für Mitnehmen'],
        'zum Mitnehmen',
        'Ustálené spojení „zum Mitnehmen“ obsahuje zpodstatněný infinitiv s velkým M.',
        'ustálená vazba zum Mitnehmen',
      ),
      choice(
        'Který nápis je pravopisně správný?',
        ['rauchen verboten', 'Rauchen verboten', 'Das rauchen verboten', 'Rauchend verboten'],
        'Rauchen verboten',
        'Činnost funguje jako podstatné jméno, proto se „Rauchen“ píše s velkým písmenem.',
        'zpodstatněný infinitiv v nápisu',
      ),
      order(
        'Řekni: Před spaním si čtu.',
        ['ich.', 'lese', 'Vor dem', 'Schlafengehen'],
        ['Vor dem', 'Schlafengehen', 'lese', 'ich.'],
        'Před spaním si čtu.',
        'Spojení „vor dem Schlafengehen“ obsahuje zpodstatněný složený infinitiv; po úvodní frázi následuje inverze.',
        'zpodstatněný složený infinitiv',
      ),
    ],
  }),
  lesson({
    id: 'prepositional-relative-clauses',
    categoryId: 'sentence-architecture',
    unit: 98,
    title: 'Vztažná věta s předložkou',
    shortTitle: 'Mit dem, über die',
    subtitle: 'Zachovej slovesnou vazbu a vlož předložku před správný tvar zájmena.',
    cefr: 'B2',
    minutes: 8,
    completionXp: 27,
    concept:
      'Pokud sloveso ve vztažné větě vyžaduje předložku, stojí před vztažným zájmenem. Rod a číslo určuje předchozí podstatné jméno, pád určuje právě předložka.',
    formula: 'jméno, předložka + dem/der/denen/das/die + … + sloveso',
    examples: [
      { de: 'Das ist der Kollege, mit dem ich arbeite.', cs: 'To je kolega, se kterým pracuji.' },
      {
        de: 'Die Frage, über die wir sprechen, ist wichtig.',
        cs: 'Otázka, o které mluvíme, je důležitá.',
      },
    ],
    questions: [
      choice(
        'Der Kollege, mit ___ ich das Büro teile, kommt später.',
        ['der', 'den', 'dem', 'dessen'],
        'dem',
        '„Mit“ vyžaduje dativ a mužský tvar vztažného zájmena je „dem“.',
        'mužský dativ po předložce',
      ),
      fill(
        'Doplň vztažné zájmeno.',
        'Das Thema, über ',
        ' wir diskutieren, ist komplex.',
        ['das'],
        'das Thema + über s akuzativem',
        '„Über“ v této vazbě vyžaduje akuzativ; střední tvar je „das“.',
        'střední akuzativ po předložce',
      ),
      choice(
        'Die Firma, für ___ sie arbeitet, sitzt in Köln.',
        ['der', 'die', 'denen', 'deren'],
        'die',
        '„Für“ vyžaduje akuzativ a ženský akuzativní tvar je „die“.',
        'ženský akuzativ po předložce',
      ),
      choice(
        'Das sind die Gründe, aus ___ wir abgesagt haben.',
        ['den', 'denen', 'die', 'deren'],
        'denen',
        'Po „aus“ stojí dativ; v množném čísle má vztažné zájmeno tvar „denen“.',
        'množný dativ denen',
      ),
      order(
        'Řekni: To je projekt, na kterém pracujeme.',
        ['wir', 'Das', 'an', 'arbeiten.', 'ist', 'dem', 'das Projekt,'],
        ['Das', 'ist', 'das Projekt,', 'an', 'dem', 'wir', 'arbeiten.'],
        'To je projekt, na kterém pracujeme.',
        'Vazba „arbeiten an + dativ“ dává tvar „an dem“ a sloveso uzavírá vztažnou větu.',
        'celá předložková vztažná věta',
      ),
    ],
  }),
  lesson({
    id: 'hypothetical-comparisons',
    categoryId: 'sentence-architecture',
    unit: 99,
    title: 'Hypotetické srovnání s als ob',
    shortTitle: 'Als ob er es wüsste',
    subtitle: 'Popiš dojem, který se tváří jako skutečnost, ale mluvčí ho za skutečný nepovažuje.',
    cefr: 'B2',
    minutes: 8,
    completionXp: 27,
    concept:
      'Po výrazech wirken, aussehen nebo so tun uvádí als ob hypotetické srovnání. Ve vedlejší větě stojí sloveso na konci a často se používá Konjunktiv II; kratší varianta s als začíná přímo slovesem.',
    formula: '…, als ob + … + Konjunktiv II · …, als wäre/hätte + podmět + …',
    examples: [
      { de: 'Er tut so, als ob er alles wüsste.', cs: 'Chová se, jako by všechno věděl.' },
      { de: 'Sie sieht aus, als hätte sie nicht geschlafen.', cs: 'Vypadá, jako by nespala.' },
    ],
    questions: [
      choice(
        'Er spricht, als ob er der Chef ___.',
        ['ist', 'wäre', 'war', 'sein würde hat'],
        'wäre',
        'Neskutečný dojem vyjadřuje Konjunktiv II od „sein“: „wäre“.',
        'als ob se wäre',
      ),
      fill(
        'Doplň hypotetický tvar wissen.',
        'Sie tut so, als ob sie nichts ',
        '.',
        ['wüsste'],
        'Konjunktiv II od wissen',
        'Hypotetické srovnání používá tvar „wüsste“, který stojí na konci vedlejší věty.',
        'Konjunktiv II po als ob',
      ),
      choice(
        'Která zkrácená varianta je správně?',
        [
          'Er wirkt, als er wäre müde.',
          'Er wirkt, als wäre er müde.',
          'Er wirkt, als ob wäre er müde.',
          'Er wirkt, als er müde wäre ob.',
        ],
        'Er wirkt, als wäre er müde.',
        'Po samotném „als“ může následovat sloveso v Konjunktivu II před podmětem: „als wäre er“.',
        'zkrácené hypotetické srovnání',
      ),
      choice(
        'Sie sah mich an, als ___ sie einen Geist gesehen.',
        ['hat', 'hätte', 'würde', 'war'],
        'hätte',
        'Dojem vztahující se k dřívějšímu ději tvoří „hätte … gesehen“.',
        'hypotetická minulost',
      ),
      order(
        'Řekni: Vypadá to, jako by nikdo nepřišel.',
        ['gekommen', 'Es', 'als ob', 'sieht aus,', 'niemand', 'wäre.'],
        ['Es', 'sieht aus,', 'als ob', 'niemand', 'gekommen', 'wäre.'],
        'Vypadá to, jako by nikdo nepřišel.',
        'Ve vedlejší větě s „als ob“ uzavírá hypotetické perfektum dvojice „gekommen wäre“.',
        'als ob v minulé situaci',
      ),
    ],
  }),
  lesson({
    id: 'perfect-infinitive',
    categoryId: 'voice-and-modality',
    unit: 100,
    title: 'Infinitiv perfekta: co už se mělo stát',
    shortTitle: 'Gemacht zu haben',
    subtitle: 'Vyjádři dřívější děj uvnitř infinitivní konstrukce bez další vedlejší věty.',
    cefr: 'B2',
    minutes: 8,
    completionXp: 28,
    concept:
      'Infinitiv perfekta označuje děj, který předchází ději hlavního slovesa. Tvoří se z Partizipa II a infinitivu haben nebo sein; částice zu stojí před závěrečným pomocným infinitivem.',
    formula: 'Partizip II + zu haben / zu sein',
    examples: [
      { de: 'Er behauptet, die E-Mail geschickt zu haben.', cs: 'Tvrdí, že ten e-mail poslal.' },
      { de: 'Sie scheint schon angekommen zu sein.', cs: 'Zdá se, že už dorazila.' },
    ],
    questions: [
      choice(
        'Er behauptet, alles allein ___.',
        ['gemacht zu haben', 'zu gemacht haben', 'gemacht haben zu', 'zu machen gehabt'],
        'gemacht zu haben',
        'Dřívější dokončený děj tvoří „Partizip II + zu haben“.',
        'infinitiv perfekta s haben',
      ),
      fill(
        'Doplň pomocný infinitiv.',
        'Sie scheint früh gegangen zu ',
        '.',
        ['sein'],
        'gehen tvoří Perfekt se sein',
        'Pohybové „gehen“ používá pomocné „sein“, proto „gegangen zu sein“.',
        'infinitiv perfekta se sein',
      ),
      choice(
        'Ich bedaure, so spät ___.',
        ['reagiert zu haben', 'zu reagieren hatte', 'reagieren zu haben', 'reagiert haben zu'],
        'reagiert zu haben',
        'Lítost se vztahuje k už dokončené reakci, proto infinitiv perfekta.',
        'časový vztah infinitivu perfekta',
      ),
      choice(
        'Která věta říká, že vlak už pravděpodobně odjel?',
        [
          'Der Zug scheint schon abgefahren zu sein.',
          'Der Zug scheint schon abzufahren sein.',
          'Der Zug scheint schon abgefahren haben.',
          'Der Zug scheint zu schon abgefahren sein.',
        ],
        'Der Zug scheint schon abgefahren zu sein.',
        '„Abfahren“ tvoří perfektum se „sein“ a celý tvar je „abgefahren zu sein“.',
        'infinitiv perfekta s odlučitelným slovesem',
      ),
      order(
        'Řekni: Přiznala, že zapomněla termín.',
        ['den Termin', 'Sie', 'zu haben.', 'gab zu,', 'vergessen'],
        ['Sie', 'gab zu,', 'den Termin', 'vergessen', 'zu haben.'],
        'Přiznala, že zapomněla termín.',
        'Dřívější zapomenutí vyjadřuje skupina „vergessen zu haben“ na konci infinitivní konstrukce.',
        'infinitiv perfekta po zugeben',
      ),
    ],
  }),
  lesson({
    id: 'clause-correlates',
    categoryId: 'voice-and-modality',
    unit: 101,
    title: 'Darauf, dass a daran, zu jako most k doplnění',
    shortTitle: 'Ich freue mich darauf',
    subtitle: 'Připoj k pevné vazbě celou větu nebo infinitiv a neztrať potřebnou předložku.',
    cefr: 'B2',
    minutes: 8,
    completionXp: 28,
    concept:
      'Když po slovesné vazbě následuje celá věta nebo infinitivní skupina, předložku často zastupuje zájmenné příslovce darauf, daran, damit či davon. Stejný podmět obvykle umožní infinitiv s zu, odlišný podmět vyžaduje dass.',
    formula: 'vazba + da(r)-příslovce, dass … / … zu + infinitiv',
    examples: [
      { de: 'Ich freue mich darauf, dich wiederzusehen.', cs: 'Těším se, že tě znovu uvidím.' },
      {
        de: 'Sie besteht darauf, dass wir pünktlich beginnen.',
        cs: 'Trvá na tom, abychom začali včas.',
      },
    ],
    questions: [
      choice(
        'Ich freue mich ___, dich bald zu sehen.',
        ['daran', 'darauf', 'damit', 'davon'],
        'darauf',
        'Vazba „sich freuen auf“ se před infinitivní skupinou zastupuje tvarem „darauf“.',
        'korelát k vazbě sich freuen auf',
      ),
      fill(
        'Doplň spojku.',
        'Sie besteht darauf, ',
        ' alle ihre Handys ausschalten.',
        ['dass'],
        'následuje věta s vlastním podmětem alle',
        'Protože doplnění má vlastní podmět „alle“, po „darauf“ následuje vedlejší věta s „dass“.',
        'dass po zájmenném příslovci',
      ),
      choice(
        'Wir rechnen ___, dass der Zug später kommt.',
        ['damit', 'darüber', 'davon', 'dazu'],
        'damit',
        'Pevná vazba „mit etwas rechnen“ se před větou mění na „damit rechnen, dass …“.',
        'korelát damit',
      ),
      choice(
        'Která věta správně využívá stejný podmět?',
        [
          'Ich denke daran, morgen anzurufen.',
          'Ich denke daran, dass morgen anzurufen.',
          'Ich denke, daran morgen rufe ich an.',
          'Ich denke daran morgen angerufen.',
        ],
        'Ich denke daran, morgen anzurufen.',
        'Podmět plánovaného volání je opět „ich“, proto stačí infinitivní skupina s „zu“.',
        'infinitiv po korelátu',
      ),
      order(
        'Řekni: Vzpomíná si, že zamkl dveře.',
        ['abgeschlossen', 'Er', 'die Tür', 'zu haben.', 'erinnert sich daran,'],
        ['Er', 'erinnert sich daran,', 'die Tür', 'abgeschlossen', 'zu haben.'],
        'Vzpomíná si, že zamkl dveře.',
        'Vazbu „sich erinnern an“ zastupuje „daran“ a dřívější děj tvoří infinitiv perfekta „abgeschlossen zu haben“.',
        'korelát s infinitivem perfekta',
      ),
    ],
  }),
  lesson({
    id: 'negation-scope',
    categoryId: 'text-cohesion',
    unit: 102,
    title: 'Dosah záporu bez nechtěné změny významu',
    shortTitle: 'Nicht alle ≠ alle nicht',
    subtitle: 'Umísti zápor těsně k tomu, co omezuješ, a formuluj přesně i jemný nesouhlas.',
    cefr: 'C1',
    minutes: 8,
    completionXp: 30,
    concept:
      'Pozice záporného výrazu určuje jeho dosah. Nicht alle znamená „ne všichni“, nicht unbedingt oslabuje nutnost tvrzení a keineswegs ho důrazně odmítá. Přesné umístění brání logické dvojznačnosti.',
    formula: 'nicht + omezený člen · nicht unbedingt · keineswegs · nicht einmal',
    examples: [
      { de: 'Nicht alle Teilnehmenden stimmten zu.', cs: 'Ne všichni účastníci souhlasili.' },
      { de: 'Das ist nicht unbedingt falsch.', cs: 'To nemusí být nutně špatně.' },
    ],
    questions: [
      choice(
        'Co přesně znamená „Nicht alle Gäste sind gegangen“?',
        [
          'Ne všichni hosté odešli.',
          'Žádný host neodešel.',
          'Všichni hosté zůstali.',
          'Hosté nesměli odejít.',
        ],
        'Ne všichni hosté odešli.',
        'Zápor stojí před „alle“ a omezuje pouze úplnost skupiny, nikoli děj u každého jednotlivce.',
        'částečný zápor',
      ),
      choice(
        '„Diese Lösung ist nicht unbedingt besser“ znamená…',
        [
          'Řešení rozhodně není lepší.',
          'Řešení nemusí být nutně lepší.',
          'Řešení je bezpochyby lepší.',
          'Řešení nesmí být lepší.',
        ],
        'Řešení nemusí být nutně lepší.',
        'Spojení „nicht unbedingt“ zpochybňuje nutnost závěru, ale netvrdí jeho přímý opak.',
        'oslabení tvrzení',
      ),
      fill(
        'Doplň výraz pro důrazné „v žádném případě“.',
        'Die Daten sind ',
        ' eindeutig.',
        ['keineswegs'],
        'v žádném případě',
        '„Keineswegs“ důrazně odmítá vlastnost „eindeutig“ a stylisticky se hodí do formálního textu.',
        'důrazný zápor',
      ),
      choice(
        'Která věta říká, že téměř nikdo nereagoval?',
        [
          'Kaum jemand hat reagiert.',
          'Jemand hat kaum reagiert.',
          'Nicht jemand hat reagiert.',
          'Jeder hat kaum nicht reagiert.',
        ],
        'Kaum jemand hat reagiert.',
        '„Kaum jemand“ omezuje počet reagujících téměř k nule.',
        'záporně omezující výraz kaum jemand',
      ),
      order(
        'Řekni: Ani odborníci se neshodli.',
        ['waren', 'Nicht einmal', 'sich', 'die Fachleute', 'einig.'],
        ['Nicht einmal', 'die Fachleute', 'waren', 'sich', 'einig.'],
        'Ani odborníci se neshodli.',
        '„Nicht einmal“ stojí přímo před překvapivě zahrnutou skupinou; určité sloveso zůstává druhým větným členem.',
        'ohnisko záporu s nicht einmal',
      ),
    ],
  }),
  lesson({
    id: 'connective-relative-clauses',
    categoryId: 'text-cohesion',
    unit: 103,
    title: 'Vztažná věta odkazující na celou myšlenku',
    shortTitle: 'Was, wobei, wodurch',
    subtitle: 'Navaž na předchozí výpověď bez neurčitého „a to“ a pojmenuj přesný vztah.',
    cefr: 'C1',
    minutes: 8,
    completionXp: 30,
    concept:
      'Vztažné was může odkazovat na celou předchozí větu. Tvary wobei, wodurch a woraufhin zároveň vyjadřují doprovodnou okolnost, prostředek či následek a okamžitou reakci; určité sloveso stojí na konci.',
    formula: 'výpověď, was/wobei/wodurch/woraufhin + … + sloveso',
    examples: [
      {
        de: 'Er sagte kurzfristig ab, was uns überraschte.',
        cs: 'Na poslední chvíli to zrušil, což nás překvapilo.',
      },
      {
        de: 'Die Frist wurde verlängert, wodurch wir Zeit gewannen.',
        cs: 'Lhůta byla prodloužena, čímž jsme získali čas.',
      },
    ],
    questions: [
      choice(
        'Sie lehnte das Angebot ab, ___ niemand erwartet hatte.',
        ['das', 'was', 'womit', 'worin'],
        'was',
        'Zájmeno odkazuje na celý předchozí děj odmítnutí, proto „was“.',
        'was s odkazem na celou větu',
      ),
      fill(
        'Doplň výraz pro doprovodnou okolnost.',
        'Er erklärte den Ablauf, ',
        ' er mehrere Beispiele nannte.',
        ['wobei'],
        'přičemž',
        '„Wobei“ přidává okolnost, která probíhá současně s vysvětlováním.',
        'doprovodný vztah s wobei',
      ),
      choice(
        'Die Prozesse wurden vereinfacht, ___ die Kosten sanken.',
        ['worüber', 'wobei', 'wodurch', 'woran'],
        'wodurch',
        'Pokles nákladů je důsledkem zjednodušení, proto „wodurch“.',
        'důsledek s wodurch',
      ),
      choice(
        'Er kündigte überraschend, ___ das Team die Aufgaben neu verteilte.',
        ['woraufhin', 'wovon', 'wobei', 'was für'],
        'woraufhin',
        'Nové rozdělení úkolů je bezprostřední reakcí na výpověď, proto „woraufhin“.',
        'návazná reakce s woraufhin',
      ),
      order(
        'Propoj: Server selhal, čímž se zpozdilo zveřejnění.',
        ['sich', 'wodurch', 'Der Server', 'verzögerte.', 'die Veröffentlichung', 'fiel aus,'],
        ['Der Server', 'fiel aus,', 'wodurch', 'sich', 'die Veröffentlichung', 'verzögerte.'],
        'Server selhal, čímž se zpozdilo zveřejnění.',
        '„Wodurch“ odkazuje na celý výpadek, ve vztažné větě stojí zvratné „sich“ před podmětem a sloveso na konci.',
        'kohezní vztažná věta',
      ),
    ],
  }),
  lesson({
    id: 'gerundive-attributes',
    categoryId: 'academic-precision',
    unit: 104,
    title: 'Gerundivum: co je třeba nebo možné udělat',
    shortTitle: 'Die zu lösende Aufgabe',
    subtitle: 'Zhušti pasivní nutnost či možnost do přesného přívlastku před podstatným jménem.',
    cefr: 'C1',
    minutes: 8,
    completionXp: 32,
    concept:
      'Konstrukce zu + Partizip I před podstatným jménem vyjadřuje, že něco má, musí nebo může být provedeno. Celý tvar se skloňuje jako přídavné jméno a u odlučitelných sloves stojí zu mezi předponou a kmenem.',
    formula: 'zu + infinitiv + d + adjektivní koncovka: die zu lösende Aufgabe',
    examples: [
      {
        de: 'Die zu lösende Aufgabe ist komplex.',
        cs: 'Úkol, který je třeba vyřešit, je složitý.',
      },
      {
        de: 'Bitte senden Sie die einzureichenden Unterlagen.',
        cs: 'Zašlete prosím dokumenty, které je třeba odevzdat.',
      },
    ],
    questions: [
      choice(
        '„Úkol, který je třeba vyřešit“ je…',
        [
          'die zu lösende Aufgabe',
          'die gelöste zu Aufgabe',
          'die lösende zu Aufgabe',
          'die zu gelöst Aufgabe',
        ],
        'die zu lösende Aufgabe',
        'Gerundivum vzniká z „zu lösen“ přidáním -d a adjektivní koncovky: „zu lösende“.',
        'základní tvorba gerundiva',
      ),
      fill(
        'Doplň správný tvar.',
        'Das ist ein nicht zu unterschätzend',
        ' Risiko.',
        ['es'],
        'ein + střední nominativ',
        'Po „ein“ nese střední nominativ koncovku -es: „ein nicht zu unterschätzendes Risiko“.',
        'skloňování gerundiva',
      ),
      choice(
        'Die bis Freitag ___ Unterlagen fehlen noch.',
        ['einzureichenden', 'zu einreichenden', 'eingereichten zu', 'einreichende zu'],
        'einzureichenden',
        'U odlučitelného „einreichen“ se „zu“ vkládá dovnitř: „einzureichend-“; po „die“ v plurálu následuje -en.',
        'gerundivum odlučitelného slovesa',
      ),
      choice(
        'Co znamená „die noch zu prüfenden Daten“?',
        [
          'data, která je ještě třeba prověřit',
          'data, která už byla prověřena',
          'data, která právě někoho prověřují',
          'data, která se nesmějí prověřit',
        ],
        'data, která je ještě třeba prověřit',
        'Gerundivum zde vyjadřuje dosud nesplněnou nutnost pasivního děje.',
        'význam gerundiva',
      ),
      order(
        'Řekni: Prověřujeme otázky, které je ještě třeba vyjasnit.',
        ['Fragen.', 'Wir', 'noch', 'prüfen', 'zu klärenden', 'die'],
        ['Wir', 'prüfen', 'die', 'noch', 'zu klärenden', 'Fragen.'],
        'Prověřujeme otázky, které je ještě třeba vyjasnit.',
        'Gerundivum „zu klärend-“ stojí se svými doplněními před podstatným jménem a dostává koncovku -en.',
        'gerundivum v rozvité frázi',
      ),
    ],
  }),
  lesson({
    id: 'nuanced-connectors',
    categoryId: 'academic-precision',
    unit: 105,
    title: 'Jemné logické vztahy v náročném textu',
    shortTitle: 'Zumal, wohingegen, geschweige denn',
    subtitle: 'Rozliš dodatečný důvod, ostrý kontrast, stupňovaný zápor a omezenou platnost.',
    cefr: 'C1',
    minutes: 8,
    completionXp: 32,
    concept:
      'Zumal přidává zvlášť přesvědčivý důvod, wohingegen staví dvě skutečnosti do kontrastu, geschweige denn zesiluje záporné tvrzení a insofern … als přesně omezuje rozsah platnosti výroku.',
    formula: '…, zumal … · …, wohingegen … · nicht X, geschweige denn Y · insofern …, als …',
    examples: [
      {
        de: 'Wir blieben zu Hause, zumal es stark regnete.',
        cs: 'Zůstali jsme doma, zvlášť když silně pršelo.',
      },
      {
        de: 'Ich habe keine Zeit für einen Kaffee, geschweige denn für ein langes Mittagessen.',
        cs: 'Nemám čas na kávu, natož na dlouhý oběd.',
      },
    ],
    questions: [
      choice(
        'Wir sollten warten, ___ noch wichtige Daten fehlen.',
        ['zumal', 'wohingegen', 'geschweige denn', 'insofern'],
        'zumal',
        'Chybějící data jsou dodatečný a zvlášť závažný důvod pro čekání, proto „zumal“.',
        'dodatečný důvod se zumal',
      ),
      fill(
        'Doplň kontrastní spojku.',
        'Lea plant jedes Detail, ',
        ' Tom lieber spontan entscheidet.',
        ['wohingegen'],
        'zatímco oproti tomu',
        '„Wohingegen“ staví dva odlišné způsoby rozhodování do přímého kontrastu.',
        'kontrast s wohingegen',
      ),
      choice(
        'Er kann kaum gehen, ___ einen Marathon laufen.',
        ['zumal', 'insofern', 'wohingegen', 'geschweige denn'],
        'geschweige denn',
        'Druhá možnost je ještě méně představitelná než už záporně omezená první, proto „geschweige denn“.',
        'stupňovaný zápor',
      ),
      choice(
        'Která věta přesně omezuje platnost souhlasu?',
        [
          'Die Aussage stimmt insofern, als sie den allgemeinen Trend beschreibt.',
          'Die Aussage stimmt zumal den allgemeinen Trend.',
          'Insofern die Aussage als stimmt der Trend.',
          'Die Aussage geschweige denn stimmt als Trend.',
        ],
        'Die Aussage stimmt insofern, als sie den allgemeinen Trend beschreibt.',
        'Dvojice „insofern … als“ vymezuje, v jakém přesném ohledu je tvrzení platné.',
        'omezení platnosti pomocí insofern als',
      ),
      order(
        'Řekni: Návrh je užitečný potud, pokud šetří čas.',
        ['Zeit spart.', 'als', 'Der Vorschlag', 'insofern', 'er', 'ist', 'sinnvoll,'],
        ['Der Vorschlag', 'ist', 'insofern', 'sinnvoll,', 'als', 'er', 'Zeit spart.'],
        'Návrh je užitečný potud, pokud šetří čas.',
        '„Insofern“ stojí v hlavní větě, korelační „als“ uvádí vedlejší větu se slovesem na konci.',
        'celá konstrukce insofern als',
      ),
    ],
  }),
];
