import type {
  GrammarCategory,
  GrammarChoiceQuestion,
  GrammarFillQuestion,
  GrammarLesson,
  GrammarOrderQuestion,
} from './grammar.ts';

function choice(
  id: string,
  prompt: string,
  options: string[],
  answer: string,
  explanation: string,
  skill: string,
  instruction = 'Vyber správnou možnost.',
): GrammarChoiceQuestion {
  return { id, kind: 'choice', prompt, instruction, options, answer, explanation, skill };
}

function fill(
  id: string,
  prompt: string,
  before: string,
  after: string,
  answers: string[],
  hint: string,
  explanation: string,
  skill: string,
  instruction = 'Doplň chybějící část.',
): GrammarFillQuestion {
  return {
    id,
    kind: 'fill',
    prompt,
    instruction,
    before,
    after,
    answers,
    hint,
    explanation,
    skill,
  };
}

function order(
  id: string,
  prompt: string,
  tokens: string[],
  answer: string[],
  translation: string,
  explanation: string,
  skill: string,
  instruction = 'Poskládej větu ve správném pořadí.',
): GrammarOrderQuestion {
  return {
    id,
    kind: 'order',
    prompt,
    instruction,
    tokens,
    answer,
    translation,
    explanation,
    skill,
  };
}

export const advancedGrammarCategories: GrammarCategory[] = [
  {
    id: 'connected-thoughts',
    number: '05',
    title: 'Spojené myšlenky',
    description:
      'B1 staví souvětí, hypotézy a pasivum, se kterými už nemusíš mluvit jen v krátkých větách.',
    accent: 'sky',
  },
  {
    id: 'perspective-and-detail',
    number: '06',
    title: 'Vztahy a perspektiva',
    description: 'B2 zpřesňuje čas, podmínky, vztahy mezi ději a tvary uvnitř celé jmenné fráze.',
    accent: 'mint',
  },
  {
    id: 'precision-and-style',
    number: '07',
    title: 'Přesnost a styl',
    description:
      'C1 rozlišuje zdroj informace, míru jistoty a formální styl bez zbytečně těžkopádných vět.',
    accent: 'cobalt',
  },
];

export const advancedGrammarLessons: GrammarLesson[] = [
  {
    id: 'praeteritum-core',
    categoryId: 'connected-thoughts',
    unit: 19,
    title: 'Präteritum pro příběh a vzpomínku',
    shortTitle: 'War, hatte, konnte',
    subtitle: 'Sein, haben a modální slovesa znějí v minulosti přirozeně právě v Präteritu.',
    cefr: 'B1',
    minutes: 7,
    completionXp: 26,
    concept:
      'V běžném vyprávění se sein, haben a modální slovesa často používají v jednoduchém minulém čase: war, hatte, konnte, musste, durfte, wollte a sollte.',
    formula: 'kmen Präterita + osobní koncovka · ich war · wir mussten',
    examples: [
      { de: 'Früher hatte ich mehr Zeit.', cs: 'Dříve jsem měla více času.' },
      { de: 'Wir mussten lange warten.', cs: 'Museli jsme dlouho čekat.' },
    ],
    questions: [
      choice(
        'pret-1',
        'Als Kind ___ ich sehr schüchtern.',
        ['war', 'bin gewesen', 'wäre', 'hatte'],
        'war',
        'U slovesa „sein“ se ve vyprávění běžně používá Präteritum „war“.',
        'Präteritum od sein',
      ),
      fill(
        'pret-2',
        'Vyjádři dřívější schopnost.',
        'Früher ',
        ' ich ohne Pause zehn Kilometer laufen.',
        ['konnte'],
        'Präteritum slovesa können, 1. osoba jednotného čísla.',
        'Tvar „konnte“ označuje schopnost v minulosti; druhý infinitiv „laufen“ zůstává na konci.',
        'Präteritum modálního slovesa',
      ),
      order(
        'pret-3',
        'Včera jsme museli dlouho čekat.',
        ['lange', 'Gestern', 'wir', 'warten', 'mussten'],
        ['Gestern', 'mussten', 'wir', 'lange', 'warten'],
        'Včera jsme museli dlouho čekat.',
        '„Mussten“ stojí po úvodním časovém údaji a infinitiv „warten“ uzavírá větu.',
        'slovosled s modálním slovesem v minulosti',
      ),
      choice(
        'pret-4',
        'Která věta znamená „Neměla žádné peníze, ale chtěla jet s námi“?',
        [
          'Sie hatte kein Geld, aber sie wollte mitfahren.',
          'Sie war kein Geld, aber sie will mitfahren.',
          'Sie hätte kein Geld, aber sie wollte mitgefahren.',
          'Sie hatte nicht Geld, aber sie würde mitfahren wollen.',
        ],
        'Sie hatte kein Geld, aber sie wollte mitfahren.',
        '„Hatte“ je Präteritum od haben a „wollte“ od wollen; po modálním slovese stojí infinitiv.',
        'kombinace hatte a wollte',
      ),
      fill(
        'pret-5',
        'Zeptej se na dovolení v minulosti.',
        '',
        ' du damals allein ausgehen?',
        ['Durftest'],
        'Präteritum od dürfen pro du.',
        'Pro druhou osobu jednotného čísla přidáme k „durft-“ koncovku -est: „durftest“.',
        'časování dürfen v Präteritu',
      ),
    ],
  },
  {
    id: 'konjunktiv-two-present',
    categoryId: 'connected-thoughts',
    unit: 20,
    title: 'Konjunktiv II: přání, možnost, zdvořilost',
    shortTitle: 'Kdyby a mohla bych',
    subtitle: 'Wäre, hätte, könnte a würde oddělí skutečnost od přání i slušné prosby.',
    cefr: 'B1',
    minutes: 8,
    completionXp: 28,
    concept:
      'Konjunktiv II označuje představované nebo nepravděpodobné situace a zjemňuje prosby. U sein, haben a modálních sloves používej vlastní tvary; u mnoha dalších sloves würde + infinitiv.',
    formula: 'wenn + Konjunktiv II …, Konjunktiv II · würde + infinitiv',
    examples: [
      {
        de: 'Wenn ich mehr Zeit hätte, würde ich öfter lesen.',
        cs: 'Kdybych měla více času, četla bych častěji.',
      },
      { de: 'Könnten Sie mir bitte helfen?', cs: 'Mohla byste mi prosím pomoci?' },
    ],
    questions: [
      choice(
        'k2p-1',
        'Wenn ich näher wohnen würde, ___ ich zu Fuß kommen.',
        ['würde', 'werde', 'wäre', 'hatte'],
        'würde',
        'Ve výsledkové větě vyjadřuje představovaný děj konstrukce „würde + kommen“.',
        'würde-konstrukce',
      ),
      fill(
        'k2p-2',
        'Vyjádři přání.',
        'Ich ',
        ' gern mehr Freizeit.',
        ['hätte'],
        'Konjunktiv II od haben.',
        'U „haben“ je přirozený vlastní tvar „hätte“, ne „würde haben“.',
        'Konjunktiv II od haben',
      ),
      order(
        'k2p-3',
        'Mohl bys mi poslat ten odkaz?',
        ['den Link', 'mir', 'schicken', 'Könntest', 'du'],
        ['Könntest', 'du', 'mir', 'den Link', 'schicken'],
        'Mohl bys mi poslat ten odkaz?',
        'Zdvořilá otázka začíná tvarem „Könntest“, infinitiv „schicken“ zůstává na konci.',
        'zdvořilá prosba',
      ),
      choice(
        'k2p-4',
        'Která věta je stylisticky nejpřirozenější?',
        [
          'Wenn ich du wäre, würde ich früher anfangen.',
          'Wenn ich du würde sein, würde ich früher anfangen.',
          'Wenn ich du bin, fange ich früher an.',
          'Wenn ich du hätte, würde ich früher anfangen.',
        ],
        'Wenn ich du wäre, würde ich früher anfangen.',
        'U „sein“ používáme vlastní tvar „wäre“; hlavní věta pak může mít „würde + infinitiv“.',
        'wäre v podmínce',
      ),
      fill(
        'k2p-5',
        'Zjemni žádost v obchodě.',
        'Ich ',
        ' gern zahlen.',
        ['würde'],
        'Zdvořilé würde + infinitiv.',
        '„Ich würde gern zahlen“ vyjadřuje zdvořilé přání; „zahlen“ zůstává v infinitivu.',
        'zdvořilost pomocí würde',
      ),
    ],
  },
  {
    id: 'relative-clauses',
    categoryId: 'connected-thoughts',
    unit: 21,
    title: 'Vztažné věty a správný pád zájmena',
    shortTitle: 'Der, den, dem ve větě',
    subtitle: 'Rod přebíráš z podstatného jména, pád určuje role uvnitř vztažné věty.',
    cefr: 'B1',
    minutes: 8,
    completionXp: 28,
    concept:
      'Vztažné zájmeno se shoduje v rodě a čísle s výrazem před čárkou. Jeho pád ale určuje až sloveso nebo předložka ve vztažné větě.',
    formula: 'jméno, vztažné zájmeno + … + sloveso na konci',
    examples: [
      {
        de: 'Das ist der Mann, den ich gestern getroffen habe.',
        cs: 'To je muž, kterého jsem včera potkala.',
      },
      {
        de: 'Die Kollegin, mit der ich arbeite, kommt aus Wien.',
        cs: 'Kolegyně, se kterou pracuji, pochází z Vídně.',
      },
    ],
    questions: [
      choice(
        'rel-1',
        'Das ist der Schüler, ___ immer gute Fragen stellt.',
        ['der', 'den', 'dem', 'dessen'],
        'der',
        'Zájmeno je podmětem slovesa „stellt“, proto má mužský nominativ „der“.',
        'nominativ vztažného zájmena',
      ),
      choice(
        'rel-2',
        'Kennst du den Film, ___ wir gestern gesehen haben?',
        ['den', 'der', 'dem', 'dessen'],
        'den',
        'Ve vztažné větě je film předmětem slovesa „sehen“, proto použijeme akuzativ „den“.',
        'akuzativ vztažného zájmena',
      ),
      fill(
        'rel-3',
        'Doplň zájmeno po předložce.',
        'Die Freundin, mit ',
        ' ich reise, spricht Spanisch.',
        ['der'],
        'Ženský rod v dativu po mit.',
        'Předložka „mit“ vyžaduje dativ; ženský tvar vztažného zájmena je „der“.',
        'vztažné zájmeno po předložce',
      ),
      order(
        'rel-4',
        'Ta kniha, kterou mi doporučuješ, je vyprodaná.',
        ['ist ausverkauft', 'Das Buch,', 'das', 'du mir empfiehlst,'],
        ['Das Buch,', 'das', 'du mir empfiehlst,', 'ist ausverkauft'],
        'Ta kniha, kterou mi doporučuješ, je vyprodaná.',
        'Vztažná věta je vložená mezi dvě čárky a její určité sloveso „empfiehlst“ stojí na konci.',
        'vložená vztažná věta',
      ),
      choice(
        'rel-5',
        'Ich danke der Lehrerin, ___ mir geholfen hat.',
        ['die', 'der', 'den', 'dem'],
        'die',
        'Pád výrazu „der Lehrerin“ v hlavní větě se nepřenáší. Ve vztažné větě je učitelka podmětem, proto „die“.',
        'pád podle role ve vztažné větě',
      ),
    ],
  },
  {
    id: 'zu-infinitives',
    categoryId: 'connected-thoughts',
    unit: 22,
    title: 'Infinitiv s zu a jeho rozšíření',
    shortTitle: 'Zu, um … zu, ohne … zu',
    subtitle: 'Spoj dva děje se stejným podmětem bez další těžké vedlejší věty.',
    cefr: 'B1',
    minutes: 8,
    completionXp: 28,
    concept:
      'Po řadě sloves a přídavných jmen stojí zu + infinitiv. Um … zu vyjadřuje účel, ohne … zu chybějící doprovodný děj a statt … zu náhradu; u odlučitelných sloves jde zu mezi předponu a kmen.',
    formula: '…, (um/ohne/statt) + … + zu + infinitiv',
    examples: [
      { de: 'Ich versuche, früher aufzustehen.', cs: 'Snažím se vstávat dříve.' },
      {
        de: 'Sie lernt viel, um die Prüfung zu bestehen.',
        cs: 'Hodně se učí, aby zkoušku zvládla.',
      },
    ],
    questions: [
      fill(
        'zu-1',
        'Doplň infinitiv odlučitelného slovesa.',
        'Ich habe vor, morgen früher ',
        '.',
        ['aufzustehen'],
        'aufstehen → auf + zu + stehen',
        'U odlučitelného „aufstehen“ se „zu“ vloží mezi předponu a kmen: „aufzustehen“.',
        'zu u odlučitelného slovesa',
      ),
      choice(
        'zu-2',
        'Sie spart Geld, ___ im Sommer nach Berlin zu fahren.',
        ['um', 'ohne', 'statt', 'dass'],
        'um',
        'Úspora má cíl, proto použijeme účelovou konstrukci „um … zu“.',
        'účel pomocí um zu',
      ),
      order(
        'zu-3',
        'Odešel, aniž se rozloučil.',
        ['ohne', 'Er ging,', 'zu verabschieden', 'sich'],
        ['Er ging,', 'ohne', 'sich', 'zu verabschieden'],
        'Odešel, aniž se rozloučil.',
        '„Ohne … zu“ vyjadřuje děj, který se nestal; zvratné „sich“ stojí před infinitivem.',
        'ohne zu',
      ),
      choice(
        'zu-4',
        'Která věta používá po modálním slovese infinitiv správně bez „zu“?',
        [
          'Du musst heute pünktlich kommen.',
          'Du musst heute pünktlich zu kommen.',
          'Du musst heute pünktlich kommst.',
          'Du zu musst heute pünktlich kommen.',
        ],
        'Du musst heute pünktlich kommen.',
        'Po modálním slovese stojí čistý infinitiv bez „zu“.',
        'infinitiv bez zu po modálním slovese',
      ),
      fill(
        'zu-5',
        'Vyjádři náhradní děj.',
        'Statt zu lernen, ',
        ' er den ganzen Abend Videos.',
        ['schaut', 'sieht'],
        'Hlavní věta potřebuje určité sloveso.',
        'Konstrukce „statt zu lernen“ má stejný podmět jako hlavní věta; v hlavní větě zůstává sloveso na druhé pozici.',
        'statt zu',
      ),
    ],
  },
  {
    id: 'process-passive',
    categoryId: 'connected-thoughts',
    unit: 23,
    title: 'Dějové pasivum: co se právě děje',
    shortTitle: 'Werden + Partizip II',
    subtitle: 'Když je důležitější činnost nebo výsledek než její vykonavatel.',
    cefr: 'B1',
    minutes: 8,
    completionXp: 28,
    concept:
      'Dějové pasivum tvoří časované werden a příčestí II. Původní akuzativní předmět se stává podmětem; původce lze doplnit pomocí von + dativ.',
    formula: 'podmět + werden + … + Partizip II',
    examples: [
      { de: 'Die Straße wird repariert.', cs: 'Silnice se opravuje.' },
      { de: 'Der Brief wurde gestern verschickt.', cs: 'Dopis byl včera odeslán.' },
    ],
    questions: [
      choice(
        'pass-1',
        'Die Ergebnisse ___ morgen veröffentlicht.',
        ['werden', 'sind', 'haben', 'wurden sein'],
        'werden',
        'Přítomné dějové pasivum tvoří „werden + veröffentlicht“.',
        'pasivum v přítomném čase',
      ),
      fill(
        'pass-2',
        'Převeď děj do minulosti.',
        'Die Brücke ',
        ' 1998 gebaut.',
        ['wurde'],
        'Präteritum od werden, 3. osoba jednotného čísla.',
        'Minulé dějové pasivum tvoří „wurde + Partizip II“.',
        'pasivum v Präteritu',
      ),
      order(
        'pass-3',
        'Text kontroluje učitelka.',
        ['von der Lehrerin', 'kontrolliert', 'Der Text', 'wird'],
        ['Der Text', 'wird', 'von der Lehrerin', 'kontrolliert'],
        'Text kontroluje učitelka.',
        'Původce děje se připojí pomocí „von + dativ“ a příčestí stojí na konci.',
        'původce v pasivní větě',
      ),
      choice(
        'pass-4',
        'Která pasivní věta odpovídá „Man verkauft hier regionale Produkte“?',
        [
          'Hier werden regionale Produkte verkauft.',
          'Hier sind regionale Produkte verkaufen.',
          'Hier wird regionale Produkte verkauft.',
          'Hier haben regionale Produkte verkauft.',
        ],
        'Hier werden regionale Produkte verkauft.',
        'Podmět „regionale Produkte“ je v množném čísle, proto „werden“; příčestí je „verkauft“.',
        'shoda v pasivní větě',
      ),
      fill(
        'pass-5',
        'Doplň pasivum ve vedlejší větě.',
        'Ich weiß, dass die Tür jeden Abend ',
        ' wird.',
        ['abgeschlossen'],
        'Partizip II od abschließen.',
        'Ve vedlejší větě stojí příčestí před časovaným „wird“: „abgeschlossen wird“.',
        'pasivum ve vedlejší větě',
      ),
    ],
  },
  {
    id: 'past-sequence',
    categoryId: 'perspective-and-detail',
    unit: 24,
    title: 'Plusquamperfekt a pořadí minulých dějů',
    shortTitle: 'Co se stalo předtím',
    subtitle: 'Jeden minulý děj vytvoří kulisu pro druhý a časová osa zůstane jasná.',
    cefr: 'B2',
    minutes: 8,
    completionXp: 30,
    concept:
      'Plusquamperfekt označuje děj dokončený před jiným bodem v minulosti. Tvoří se pomocí hatte nebo war a příčestí II; často se pojí s nachdem, bevor nebo schon.',
    formula: 'hatte/war + Partizip II → pozdější děj v Präteritu/Perfektu',
    examples: [
      {
        de: 'Nachdem sie gegessen hatte, ging sie spazieren.',
        cs: 'Poté co se najedla, šla na procházku.',
      },
      {
        de: 'Der Zug war schon abgefahren, als wir ankamen.',
        cs: 'Vlak už odjel, když jsme dorazili.',
      },
    ],
    questions: [
      choice(
        'plus-1',
        'Als ich ankam, ___ der Film schon begonnen.',
        ['hatte', 'hat', 'wurde', 'wäre'],
        'hatte',
        'Začátek filmu nastal před příchodem, proto použijeme Plusquamperfekt „hatte begonnen“.',
        'Plusquamperfekt s haben',
      ),
      fill(
        'plus-2',
        'Doplň dřívější pohybový děj.',
        'Bevor der Unterricht begann, ',
        ' alle schon angekommen.',
        ['waren'],
        'Plusquamperfekt s pomocným sein.',
        '„Ankommen“ tvoří složené časy se „sein“; v Plusquamperfektu množného čísla je „waren angekommen“.',
        'Plusquamperfekt se sein',
      ),
      order(
        'plus-3',
        'Poté co dokončila projekt, vzala si volno.',
        ['nahm sie frei', 'sie', 'Nachdem', 'beendet hatte,', 'das Projekt'],
        ['Nachdem', 'sie', 'das Projekt', 'beendet hatte,', 'nahm sie frei'],
        'Poté co dokončila projekt, vzala si volno.',
        'Po „nachdem“ uzavírá vedlejší větu dvojice „beendet hatte“; hlavní věta začíná inverzí „nahm sie“.',
        'nachdem a časová posloupnost',
      ),
      choice(
        'plus-4',
        'Která věta jasně říká, že nejdřív ztratila klíč a potom nemohla otevřít?',
        [
          'Sie konnte nicht öffnen, weil sie den Schlüssel verloren hatte.',
          'Sie konnte nicht öffnen, weil sie den Schlüssel verlor.',
          'Sie hat nicht öffnen können, weil sie den Schlüssel verliert.',
          'Sie würde nicht öffnen, weil sie den Schlüssel verloren hätte.',
        ],
        'Sie konnte nicht öffnen, weil sie den Schlüssel verloren hatte.',
        'Plusquamperfekt „hatte verloren“ označí ztrátu jako dřívější příčinu pozdějšího problému.',
        'dřívější příčina',
      ),
      fill(
        'plus-5',
        'Doplň celé sloveso.',
        'Wir waren müde, weil wir kaum ',
        ' hatten.',
        ['geschlafen'],
        'Partizip II od schlafen.',
        'V Plusquamperfektu s „haben“ stojí příčestí „geschlafen“ před pomocným „hatten“.',
        'Plusquamperfekt ve vedlejší větě',
      ),
    ],
  },
  {
    id: 'past-counterfactual',
    categoryId: 'perspective-and-detail',
    unit: 25,
    title: 'Neskutečná minulost bez záměny',
    shortTitle: 'Kdyby se bývalo stalo',
    subtitle: 'Konjunktiv II minulý pojmenuje podmínku i důsledek, které už změnit nejdou.',
    cefr: 'B2',
    minutes: 8,
    completionXp: 30,
    concept:
      'Pro nereálnou minulost použij hätte nebo wäre v Konjunktivu II a příčestí II. Obě části podmínky mohou mít tento tvar, protože obě popisují neuskutečněnou minulost.',
    formula: 'wenn + hätte/wäre + Partizip II, hätte/wäre + Partizip II',
    examples: [
      {
        de: 'Wenn ich mehr gelernt hätte, hätte ich bestanden.',
        cs: 'Kdybych se bývala víc učila, byla bych uspěla.',
      },
      {
        de: 'Wäre der Zug pünktlich gewesen, hätten wir den Bus erreicht.',
        cs: 'Kdyby byl vlak přijel včas, stihli bychom autobus.',
      },
    ],
    questions: [
      choice(
        'irrealis-1',
        'Wenn du früher losgefahren wärst, ___ du nicht zu spät gekommen.',
        ['wärst', 'bist', 'würdest', 'hättest'],
        'wärst',
        '„Kommen“ tvoří složený čas se „sein“, proto je výsledek „wärst … gekommen“.',
        'nereálná minulost se sein',
      ),
      fill(
        'irrealis-2',
        'Vyjádři neuskutečněnou možnost.',
        'Ohne deine Hilfe ',
        ' ich die Aufgabe nicht geschafft.',
        ['hätte'],
        'Konjunktiv II minulý s haben.',
        'Výsledek v minulosti tvoří „hätte + geschafft“; předložkový výraz nahrazuje podmínku.',
        'hätte v nereálném důsledku',
      ),
      order(
        'irrealis-3',
        'Kdybych to věděla, řekla bych ti to.',
        ['hätte ich', 'Wenn', 'es dir gesagt', 'hätte,', 'ich das gewusst'],
        ['Wenn', 'ich das gewusst', 'hätte,', 'hätte ich', 'es dir gesagt'],
        'Kdybych to věděla, řekla bych ti to.',
        'Vedlejší větu uzavírá „hätte“, po čárce následuje inverze „hätte ich“.',
        'slovosled v minulé podmínce',
      ),
      choice(
        'irrealis-4',
        'Která věta vyjadřuje lítost nad minulostí?',
        [
          'Hätte ich doch besser aufgepasst!',
          'Ich würde jetzt besser aufpassen.',
          'Ich passe besser auf.',
          'Ich hätte morgen besser aufgepasst.',
        ],
        'Hätte ich doch besser aufgepasst!',
        'Samostatná věta s počátečním „Hätte“ a částicí „doch“ vyjadřuje nesplnitelné přání o minulosti.',
        'minulé přání',
      ),
      fill(
        'irrealis-5',
        'Doplň pomocné sloveso.',
        'Wären wir zu Hause geblieben, ',
        ' nichts passiert.',
        ['wäre'],
        'Passieren tvoří složené časy se sein.',
        '„Passieren“ se pojí se „sein“, proto „wäre nichts passiert“.',
        'volba pomocného slovesa',
      ),
    ],
  },
  {
    id: 'complex-connectors',
    categoryId: 'perspective-and-detail',
    unit: 26,
    title: 'Vztah mezi ději: ústupek, způsob, důsledek',
    shortTitle: 'Obwohl, indem, sodass',
    subtitle: 'Spojka neznamená jen čárku — přesně určuje logiku mezi dvěma větami.',
    cefr: 'B2',
    minutes: 8,
    completionXp: 30,
    concept:
      'Obwohl vyjadřuje rozpor s očekáváním, indem způsob, während současnost nebo kontrast a sodass důsledek. Všechny uvádějí vedlejší větu se slovesem na konci.',
    formula: 'hlavní věta, spojka + … + určité sloveso',
    examples: [
      {
        de: 'Obwohl es regnete, gingen wir spazieren.',
        cs: 'Přestože pršelo, šli jsme na procházku.',
      },
      {
        de: 'Sie verbessert ihr Deutsch, indem sie täglich liest.',
        cs: 'Zlepšuje si němčinu tím, že denně čte.',
      },
    ],
    questions: [
      choice(
        'conn-1',
        '___ er wenig Zeit hatte, half er uns.',
        ['Obwohl', 'Indem', 'Sodass', 'Damit'],
        'Obwohl',
        'Pomoc nastala navzdory nedostatku času, proto jde o ústupek s „obwohl“.',
        'ústupkový vztah',
      ),
      fill(
        'conn-2',
        'Vyjádři způsob.',
        'Man lernt neue Wörter, ',
        ' man sie aktiv in Sätzen benutzt.',
        ['indem'],
        'Spojka odpovídá na otázku jakým způsobem.',
        '„Indem“ představuje prostředek nebo postup, kterým se uskuteční děj hlavní věty.',
        'způsob pomocí indem',
      ),
      order(
        'conn-3',
        'Mluvil velmi potichu, takže mu nikdo nerozuměl.',
        ['dass ihn niemand verstand', 'Er sprach', 'so leise,'],
        ['Er sprach', 'so leise,', 'dass ihn niemand verstand'],
        'Mluvil velmi potichu, takže mu nikdo nerozuměl.',
        'Korelace „so …, dass“ vyjadřuje míru a její důsledek; sloveso „verstand“ stojí na konci.',
        'důsledek pomocí so dass',
      ),
      choice(
        'conn-4',
        'Která věta používá „während“ jako kontrast?',
        [
          'Während Lea gern plant, entscheidet Tom spontan.',
          'Während Lea schlief, klingelte das Telefon.',
          'Lea plant, während drei Stunden.',
          'Während des Plans entscheidet Tom spontan.',
        ],
        'Während Lea gern plant, entscheidet Tom spontan.',
        'Věta staví proti sobě dva odlišné způsoby rozhodování; „während“ zde znamená „zatímco“ v kontrastním smyslu.',
        'kontrast pomocí während',
      ),
      fill(
        'conn-5',
        'Doplň důsledek.',
        'Der Zug hatte Verspätung, ',
        ' wir den Anschluss verpassten.',
        ['sodass', 'so dass'],
        'Spojka pro následek.',
        'Zpoždění způsobilo zmeškání spoje, proto použijeme „sodass“; možné je i psaní „so dass“.',
        'důsledek pomocí sodass',
      ),
    ],
  },
  {
    id: 'passive-variants',
    categoryId: 'perspective-and-detail',
    unit: 27,
    title: 'Stavové pasivum a přirozené alternativy',
    shortTitle: 'Ist geöffnet · lässt sich',
    subtitle: 'Rozliš hotový stav, probíhající děj a možnost bez opakování stejného pasiva.',
    cefr: 'B2',
    minutes: 8,
    completionXp: 30,
    concept:
      'Werden + příčestí popisuje děj, sein + příčestí výsledný stav. Konstrukce sich lassen + infinitiv vyjadřuje možnost a sein + zu + infinitiv podle kontextu možnost nebo povinnost.',
    formula: 'wird geöffnet ≠ ist geöffnet · lässt sich öffnen · ist zu öffnen',
    examples: [
      {
        de: 'Die Tür wird geschlossen. / Die Tür ist geschlossen.',
        cs: 'Dveře se zavírají. / Dveře jsou zavřené.',
      },
      { de: 'Die Datei lässt sich leicht öffnen.', cs: 'Soubor lze snadno otevřít.' },
    ],
    questions: [
      choice(
        'pvar-1',
        'Přicházíš a dveře už jsou zamčené. Co řekneš?',
        [
          'Die Tür ist abgeschlossen.',
          'Die Tür wird abgeschlossen.',
          'Die Tür hat abschließen.',
          'Die Tür lässt abschließen.',
        ],
        'Die Tür ist abgeschlossen.',
        'Popisujeme hotový stav, ne probíhající zamykání, proto „sein + abgeschlossen“.',
        'stavové pasivum',
      ),
      fill(
        'pvar-2',
        'Vyjádři možnost.',
        'Das Problem ',
        ' sich schnell lösen.',
        ['lässt'],
        'Konstrukce sich lassen + infinitiv.',
        '„Das Problem lässt sich lösen“ znamená, že problém lze vyřešit.',
        'pasivní alternativa sich lassen',
      ),
      order(
        'pvar-3',
        'Formulář je nutné odevzdat do pátku.',
        ['bis Freitag', 'Das Formular', 'abzugeben', 'ist'],
        ['Das Formular', 'ist', 'bis Freitag', 'abzugeben'],
        'Formulář je nutné odevzdat do pátku.',
        '„Sein + zu + infinitiv“ zde díky termínu vyjadřuje povinnost.',
        'sein zu jako povinnost',
      ),
      choice(
        'pvar-4',
        'Která věta znamená, že se okno právě otevírá?',
        [
          'Das Fenster wird geöffnet.',
          'Das Fenster ist geöffnet.',
          'Das Fenster lässt sich öffnen.',
          'Das Fenster ist zu öffnen.',
        ],
        'Das Fenster wird geöffnet.',
        'Dějové pasivum s „werden“ zachycuje probíhající otevření.',
        'děj proti stavu',
      ),
      fill(
        'pvar-5',
        'Doplň přirozenou pasivní alternativu.',
        'Der Text ',
        ' sich auch ohne Wörterbuch verstehen.',
        ['lässt'],
        'Možnost vyjádřená pomocí sich lassen.',
        '„Lässt sich verstehen“ je běžná alternativa k „kann verstanden werden“.',
        'stylistická obměna pasiva',
      ),
    ],
  },
  {
    id: 'adjective-endings-full',
    categoryId: 'perspective-and-detail',
    unit: 28,
    title: 'Koncovky přídavných jmen: celá logika',
    shortTitle: 'Silné, slabé, smíšené',
    subtitle: 'Koncovku neurčuje seznam, ale to, kolik informace už nese člen.',
    cefr: 'B2',
    minutes: 8,
    completionXp: 30,
    concept:
      'Když člen jasně ukazuje rod, číslo a pád, přídavné jméno mívá slabé -e/-en. Bez členu nese potřebnou informaci samo; po ein, kein a přivlastňovacích výrazech se oba systémy kombinují.',
    formula: 'jasný člen → -e/-en · bez členu → koncovka podobná členu',
    examples: [
      {
        de: 'mit kaltem Wasser / mit dem kalten Wasser',
        cs: 'se studenou vodou / s tou studenou vodou',
      },
      { de: 'ein guter Plan / einen guten Plan', cs: 'dobrý plán / dobrý plán v akuzativu' },
    ],
    questions: [
      choice(
        'adjfull-1',
        'Wir trinken morgens ___ Kaffee.',
        ['frischen', 'frischer', 'frischem', 'frische'],
        'frischen',
        'Bez členu má mužský akuzativ koncovku -en: „frischen Kaffee“.',
        'silné skloňování v akuzativu',
      ),
      fill(
        'adjfull-2',
        'Doplň koncovku bez členu.',
        'Sie wäscht sich mit kalt',
        ' Wasser.',
        ['em'],
        'Střední rod v dativu bez členu.',
        'Bez členu musí přídavné jméno označit dativ středního rodu koncovkou -em.',
        'silné skloňování v dativu',
      ),
      choice(
        'adjfull-3',
        'Trotz ___ Regens gingen wir raus.',
        ['starken', 'starkes', 'starkem', 'starker'],
        'starken',
        'V genitivu mužského rodu bez členu má přídavné jméno běžně -en a podstatné jméno přidává -(e)s.',
        'genitiv bez členu',
      ),
      order(
        'adjfull-4',
        'Nemáme žádné nové informace.',
        ['Informationen', 'keine', 'Wir', 'neuen', 'haben'],
        ['Wir', 'haben', 'keine', 'neuen', 'Informationen'],
        'Nemáme žádné nové informace.',
        'Po „keine“ v množném čísle má přídavné jméno slabou koncovku -en.',
        'množné číslo po kein',
      ),
      fill(
        'adjfull-5',
        'Doplň tvar po ein.',
        'Das ist ein wirklich gut',
        ' Vorschlag.',
        ['er'],
        'Mužský nominativ po ein.',
        '„Ein“ nemá v mužském nominativu koncovku, proto informaci nese přídavné jméno: „guter“.',
        'smíšené skloňování',
      ),
    ],
  },
  {
    id: 'n-declension',
    categoryId: 'perspective-and-detail',
    unit: 29,
    title: 'N-deklinace: mužská jména s druhým tvarem',
    shortTitle: 'Der Student · den Studenten',
    subtitle:
      'U vybrané skupiny mužských jmen přibývá -n nebo -en ve všech pádech kromě nominativu.',
    cefr: 'B2',
    minutes: 7,
    completionXp: 30,
    concept:
      'Slabá mužská podstatná jména jako Student, Kollege, Kunde, Mensch nebo Junge dostávají mimo nominativ jednotného čísla koncovku -n/-en. U Herr se používá tvar Herrn.',
    formula: 'der Student · den/dem/des Studenten',
    examples: [
      { de: 'Ich spreche mit dem neuen Kollegen.', cs: 'Mluvím s novým kolegou.' },
      { de: 'Die Meinung des Experten ist wichtig.', cs: 'Názor odborníka je důležitý.' },
    ],
    questions: [
      choice(
        'ndecl-1',
        'Ich sehe den neuen ___.',
        ['Studenten', 'Student', 'Students', 'Studente'],
        'Studenten',
        'Po „den“ je Student v akuzativu a jako slabé mužské jméno přidává -en.',
        'akuzativ n-deklinace',
      ),
      fill(
        'ndecl-2',
        'Doplň tvar po mit.',
        'Wir arbeiten mit einem erfahrenen ',
        '.',
        ['Experten'],
        'Expert patří k n-deklinaci.',
        'Po dativním „einem“ má „Experte“ tvar „Experten“.',
        'dativ n-deklinace',
      ),
      order(
        'ndecl-3',
        'Znáš názor toho zákazníka?',
        ['des Kunden', 'du', 'Kennst', 'die Meinung'],
        ['Kennst', 'du', 'die Meinung', 'des Kunden'],
        'Znáš názor toho zákazníka?',
        '„Kunde“ dostává v genitivu -n: „des Kunden“.',
        'genitiv n-deklinace',
      ),
      choice(
        'ndecl-4',
        'Která věta má podstatné jméno „Mensch“ správně v nominativu?',
        [
          'Der Mensch braucht Pausen.',
          'Der Menschen braucht Pausen.',
          'Den Mensch braucht Pausen.',
          'Der Mensche braucht Pausen.',
        ],
        'Der Mensch braucht Pausen.',
        'Pouze nominativ jednotného čísla zůstává bez -en: „der Mensch“.',
        'nominativ n-deklinace',
      ),
      fill(
        'ndecl-5',
        'Oslov nepřímo pana Webera.',
        'Ich habe mit Herrn ',
        ' gesprochen.',
        ['Weber'],
        'Po Herrn zůstává příjmení beze změny.',
        '„Herr“ má mimo nominativ zvláštní tvar „Herrn“: „mit Herrn Weber“.',
        'zvláštní tvar Herrn',
      ),
    ],
  },
  {
    id: 'indirect-speech',
    categoryId: 'precision-and-style',
    unit: 30,
    title: 'Konjunktiv I a neutrální nepřímá řeč',
    shortTitle: 'Er sagt, er sei …',
    subtitle: 'Odděl vlastní tvrzení od přesné reprodukce cizí výpovědi.',
    cefr: 'C1',
    minutes: 8,
    completionXp: 32,
    concept:
      'Konjunktiv I označuje, že pouze reprodukuješ cizí výpověď; sám o sobě neříká, zda jí věříš. Pokud se tvar neliší od indikativu, používá se pro zřetelnost často Konjunktiv II.',
    formula: 'říká/tvrdí, + er sei · er habe · er komme · sie hätten',
    examples: [
      {
        de: 'Die Sprecherin sagt, der Termin sei bestätigt.',
        cs: 'Mluvčí říká, že termín je potvrzený.',
      },
      {
        de: 'Die Zeugen erklärten, sie hätten nichts gesehen.',
        cs: 'Svědci uvedli, že nic neviděli.',
      },
    ],
    questions: [
      choice(
        'k1-1',
        'Der Minister erklärt, die Lage ___ stabil.',
        ['sei', 'wäre', 'ist gewesen', 'wird'],
        'sei',
        'Tvar „sei“ je Konjunktiv I od sein a jasně označuje převzaté tvrzení.',
        'Konjunktiv I od sein',
      ),
      fill(
        'k1-2',
        'Převeď minulý výrok do nepřímé řeči.',
        'Sie berichtet, sie ',
        ' den Bericht bereits gelesen.',
        ['habe'],
        'Konjunktiv I od haben.',
        'Minulost v nepřímé řeči tvoří „habe + gelesen“; čas se vztahuje k reprodukovanému výroku.',
        'minulost v nepřímé řeči',
      ),
      choice(
        'k1-3',
        'Die Zeugen sagen, sie ___ nichts bemerkt.',
        ['hätten', 'haben', 'seien', 'würden'],
        'hätten',
        'Konjunktiv I množného „haben“ by vypadal stejně jako indikativ. Konjunktiv II „hätten“ zřetelně označí nepřímou řeč.',
        'náhradní Konjunktiv II',
      ),
      order(
        'k1-4',
        'Mluvčí tvrdí, že se ceny nezvýší.',
        ['nicht steigen', 'die Preise', 'Die Sprecherin behauptet,', 'würden'],
        ['Die Sprecherin behauptet,', 'die Preise', 'würden', 'nicht steigen'],
        'Mluvčí tvrdí, že se ceny nezvýší.',
        'U množného čísla je „würden“ zřetelná náhradní forma tam, kde by Konjunktiv I nebyl rozpoznatelný.',
        'nepřímá řeč v množném čísle',
      ),
      fill(
        'k1-5',
        'Doplň nepřímou otázku.',
        'Er fragte, wann der Zug ',
        '.',
        ['abfahre'],
        'Konjunktiv I od abfahren, 3. osoba jednotného čísla.',
        'Nepřímou otázku uvádí „wann“ a určitý tvar „abfahre“ stojí na konci.',
        'nepřímá otázka v Konjunktivu I',
      ),
    ],
  },
  {
    id: 'epistemic-modals',
    categoryId: 'precision-and-style',
    unit: 31,
    title: 'Modální slovesa jako míra jistoty',
    shortTitle: 'Muss, dürfte, soll, will',
    subtitle: 'Stejná slovesa umějí kromě povinnosti označit závěr, domněnku i cizí tvrzení.',
    cefr: 'C1',
    minutes: 8,
    completionXp: 32,
    concept:
      'V epistemickém významu vyjadřuje müssen silný závěr, dürfte pravděpodobnost a können možnost. Sollen reprodukuje cizí informaci; wollen říká, co o sobě tvrdí sám původce.',
    formula: 'muss/dürfte/soll/will + (Partizip II + haben/sein)',
    examples: [
      { de: 'Sie muss den Zug verpasst haben.', cs: 'Musela zmeškat vlak. (Silný závěr.)' },
      {
        de: 'Der Vertrag soll morgen unterschrieben werden.',
        cs: 'Smlouva má být podle dostupných informací podepsána zítra.',
      },
    ],
    questions: [
      choice(
        'modalep-1',
        'Je zhasnuto a nikdo neodpovídá. „Sie ___ schon gegangen sein.“',
        ['muss', 'will', 'soll', 'darf'],
        'muss',
        '„Muss … gegangen sein“ vyjadřuje silný závěr z dostupných stop, ne povinnost.',
        'silný epistemický závěr',
      ),
      fill(
        'modalep-2',
        'Vyjádři opatrnou pravděpodobnost.',
        'Die Sitzung ',
        ' inzwischen beendet sein.',
        ['dürfte'],
        'Konjunktiv II od dürfen v epistemickém významu.',
        '„Dürfte“ zde znamená „pravděpodobně je“, nikoli dovolení.',
        'pravděpodobnost pomocí dürfte',
      ),
      choice(
        'modalep-3',
        'Která věta znamená „Podle cizích zpráv žije v Berlíně“?',
        [
          'Er soll in Berlin leben.',
          'Er muss in Berlin leben.',
          'Er will in Berlin leben.',
          'Er darf in Berlin leben.',
        ],
        'Er soll in Berlin leben.',
        'Reportativní „soll“ předává informaci z jiného zdroje bez potvrzení mluvčím.',
        'cizí tvrzení pomocí sollen',
      ),
      order(
        'modalep-4',
        'Tvrdí o sobě, že o tom nic nevěděl.',
        ['nichts', 'Er', 'gewusst haben', 'will', 'davon'],
        ['Er', 'will', 'davon', 'nichts', 'gewusst haben'],
        'Tvrdí o sobě, že o tom nic nevěděl.',
        'Reportativní „will“ se vztahuje k tvrzení samotného podmětu; minulost tvoří „gewusst haben“.',
        'vlastní tvrzení pomocí wollen',
      ),
      choice(
        'modalep-5',
        'Das kann nicht stimmen.',
        [
          'Je vyloučeno, aby to byla pravda.',
          'Je povoleno, aby to nebyla pravda.',
          'Někdo tvrdí, že je to pravda.',
          'Určitě to byla pravda.',
        ],
        'Je vyloučeno, aby to byla pravda.',
        '„Kann nicht“ v epistemickém významu označuje, že mluvčí považuje danou možnost za vyloučenou.',
        'nemožnost pomocí können',
      ),
    ],
  },
  {
    id: 'verb-clusters',
    categoryId: 'precision-and-style',
    unit: 32,
    title: 'Perfektum s dvojitým infinitivem',
    shortTitle: 'Hat kommen müssen',
    subtitle:
      'Modální slovesa, hören a sehen mění příčestí na infinitiv a ve vedlejší větě i pořadí.',
    cefr: 'C1',
    minutes: 8,
    completionXp: 32,
    concept:
      'Je-li modální sloveso v perfektu spojeno s dalším infinitivem, nahrazuje se jeho příčestí infinitivem: hat arbeiten müssen. Ve standardní vedlejší větě stojí časované pomocné sloveso před dvojicí infinitivů.',
    formula: 'hat + infinitiv + modal · weil er hat + infinitiv + modal',
    examples: [
      { de: 'Ich habe länger arbeiten müssen.', cs: 'Musela jsem pracovat déle.' },
      {
        de: 'Sie ging, weil sie länger hatte arbeiten müssen.',
        cs: 'Odešla, protože musela déle pracovat.',
      },
    ],
    questions: [
      choice(
        'cluster-1',
        'Která standardní věta je správně?',
        [
          'Er hat früh aufstehen müssen.',
          'Er hat früh aufstehen gemusst.',
          'Er ist früh gemusst aufzustehen.',
          'Er musste früh aufgestanden haben.',
        ],
        'Er hat früh aufstehen müssen.',
        'Při spojení s dalším infinitivem má modální sloveso náhradní infinitiv „müssen“, ne příčestí „gemusst“.',
        'náhradní infinitiv modálního slovesa',
      ),
      fill(
        'cluster-2',
        'Doplň pomocné sloveso ve vedlejší větě.',
        'Sie war müde, weil sie lange ',
        ' warten müssen.',
        ['hatte'],
        'Plusquamperfekt s dvojitým infinitivem.',
        'Ve vedlejší větě stojí časované „hatte“ před dvojicí infinitivů „warten müssen“.',
        'slovosled dvojitého infinitivu',
      ),
      order(
        'cluster-3',
        'Bývala bych mohla přijít dřív.',
        ['kommen', 'früher', 'Ich', 'können', 'hätte'],
        ['Ich', 'hätte', 'früher', 'kommen', 'können'],
        'Bývala bych mohla přijít dřív.',
        'Nereálná minulost s modálním slovesem používá „hätte + infinitiv + modal“.',
        'Konjunktiv II s dvojitým infinitivem',
      ),
      choice(
        'cluster-4',
        'Ich habe sie im Nebenzimmer singen ___.',
        ['hören', 'gehört', 'zu hören', 'hört'],
        'hören',
        'Po slovese vnímání „hören“ může v perfektu při dalším infinitivu stát náhradní infinitiv: „singen hören“.',
        'náhradní infinitiv po hören',
      ),
      fill(
        'cluster-5',
        'Doplň poslední sloveso.',
        'Er sagt, dass er den Termin nicht hat verschieben ',
        '.',
        ['können'],
        'Infinitiv modálního slovesa können.',
        'Časované „hat“ stojí ve vedlejší větě před dvojicí „verschieben können“.',
        'slovesný shluk ve vedlejší větě',
      ),
    ],
  },
  {
    id: 'participial-attributes',
    categoryId: 'precision-and-style',
    unit: 33,
    title: 'Rozvitý participiální přívlastek',
    shortTitle: 'Die gestern veröffentlichte …',
    subtitle: 'Zkrať vztažnou větu, ale zachovej jasný vztah, čas i koncovku.',
    cefr: 'C1',
    minutes: 8,
    completionXp: 32,
    concept:
      'Partizip I vyjadřuje aktivní současný děj, Partizip II zpravidla dokončený nebo pasivní vztah. Celé rozvití stojí před podstatným jménem a participium dostává koncovku jako přídavné jméno.',
    formula: 'člen + rozvití + Partizip I/II + koncovka + jméno',
    examples: [
      { de: 'die seit Jahren in Prag lebende Autorin', cs: 'autorka žijící už léta v Praze' },
      { de: 'die gestern veröffentlichte Studie', cs: 'včera zveřejněná studie' },
    ],
    questions: [
      choice(
        'partattr-1',
        '„Hosté, kteří čekají“ = die ___ Gäste',
        ['wartenden', 'gewarteten', 'wartende', 'zu wartenden'],
        'wartenden',
        'Aktivní současný děj vyjadřuje Partizip I „wartend“; po „die“ v množném čísle dostane -en.',
        'Partizip I jako přívlastek',
      ),
      fill(
        'partattr-2',
        'Doplň správnou koncovku.',
        'Die gestern veröffentlicht',
        ' Studie sorgt für Diskussionen.',
        ['e'],
        'Ženský nominativ po určitém členu.',
        'Partizip II „veröffentlicht“ funguje jako přídavné jméno a po „die“ dostává -e.',
        'skloňování participia',
      ),
      order(
        'partattr-3',
        'student, kterého učitelka podpořila',
        ['unterstützte', 'der', 'Student', 'von der Lehrerin'],
        ['der', 'von der Lehrerin', 'unterstützte', 'Student'],
        'student, kterého učitelka podpořila',
        'Původce s „von“ stojí uvnitř rozvití před Partizipiem II „unterstützte“.',
        'rozvitý pasivní přívlastek',
      ),
      choice(
        'partattr-4',
        'Která konstrukce odpovídá „opatření platné od ledna“?',
        [
          'die seit Januar geltende Regelung',
          'die seit Januar gegoltene Regelung',
          'die geltet seit Januar Regelung',
          'die seit Januar gelten Regelung',
        ],
        'die seit Januar geltende Regelung',
        'Trvající aktivní platnost vyjadřuje Partizip I „geltend“, zde s koncovkou -e.',
        'význam Partizipia I',
      ),
      fill(
        'partattr-5',
        'Zkrať pasivní vztažnou větu.',
        'Die von allen erwartet',
        ' Entscheidung fiel am Freitag.',
        ['e'],
        'Rozhodnutí bylo očekáváno všemi.',
        'Pasivní vztah vyjádří Partizip II „erwartet“; ženský nominativ po „die“ přidává -e.',
        'Partizip II místo vztažné věty',
      ),
    ],
  },
  {
    id: 'nominal-and-verbal-style',
    categoryId: 'precision-and-style',
    unit: 34,
    title: 'Nominalstil a Verbalstil vědomě',
    shortTitle: 'Rozhodnout × učinit rozhodnutí',
    subtitle:
      'Formální text potřebuje přesné vazby; dobrý text ale umí těžkou nominalizaci zase rozbalit.',
    cefr: 'C1',
    minutes: 8,
    completionXp: 32,
    concept:
      'Nominalizace zhušťují odborný text a často tvoří ustálené funkční slovesné vazby. Verbalstil bývá přímější; volba je otázka registru a čitelnosti, ne automaticky vyšší úrovně.',
    formula: 'sloveso ↔ jméno + funkční sloveso · prüfen ↔ eine Prüfung durchführen',
    examples: [
      {
        de: 'Wir untersuchen die Daten. / Wir führen eine Untersuchung der Daten durch.',
        cs: 'Zkoumáme data. / Provádíme zkoumání dat.',
      },
      {
        de: 'Der Vorschlag wurde berücksichtigt. / Der Vorschlag fand Berücksichtigung.',
        cs: 'Návrh byl zohledněn.',
      },
    ],
    questions: [
      choice(
        'nom-1',
        'Která ustálená vazba znamená „podat žádost“?',
        [
          'einen Antrag stellen',
          'einen Antrag machen',
          'einen Antrag geben',
          'einen Antrag setzen',
        ],
        'einen Antrag stellen',
        'Podstatné jméno „Antrag“ se v této funkční slovesné vazbě pojí se „stellen“.',
        'funkční slovesná vazba',
      ),
      fill(
        'nom-2',
        'Doplň formální vazbu.',
        'Die Forschenden ',
        ' eine Untersuchung der Daten durch.',
        ['führen'],
        'durchführen je odlučitelné sloveso.',
        'V hlavní větě se „durchführen“ rozdělí na „führen … durch“.',
        'odlučitelné sloveso ve formální vazbě',
      ),
      choice(
        'nom-3',
        'Která věta je nejpřímější verbalizace „Nach Abschluss der Prüfung erhalten Sie Bescheid“?',
        [
          'Nachdem die Prüfung abgeschlossen ist, erhalten Sie Bescheid.',
          'Bei der Prüfung Abschluss erhalten Sie Bescheid.',
          'Die Prüfung ist Abschluss, dann Bescheid.',
          'Abgeschlossen der Prüfung erhalten Sie Bescheid.',
        ],
        'Nachdem die Prüfung abgeschlossen ist, erhalten Sie Bescheid.',
        'Podstatné jméno „Abschluss“ se rozbalí do vedlejší věty s dějem „abgeschlossen ist“.',
        'převod nominalizace na větu',
      ),
      order(
        'nom-4',
        'Kritiku tohoto postupu vyjádřila komise.',
        ['an diesem Vorgehen', 'Die Kommission', 'übte', 'Kritik'],
        ['Die Kommission', 'übte', 'Kritik', 'an diesem Vorgehen'],
        'Kritiku tohoto postupu vyjádřila komise.',
        'Ustálená vazba je „Kritik an etwas (Dativ) üben“.',
        'rekce funkční vazby',
      ),
      fill(
        'nom-5',
        'Doplň ustálenou vazbu.',
        'Alle relevanten Faktoren müssen in Betracht ',
        ' werden.',
        ['gezogen'],
        'in Betracht ziehen v pasivu.',
        'V pasivu se funkční vazba mění na „in Betracht gezogen werden“.',
        'funkční vazba v pasivu',
      ),
    ],
  },
  {
    id: 'c1-editing-checkpoint',
    categoryId: 'precision-and-style',
    unit: 35,
    title: 'C1 checkpoint: přesnost bez těžkopádnosti',
    shortTitle: 'Redakční checkpoint',
    subtitle:
      'Rozhodni nejen co je gramaticky možné, ale co nejpřesněji vyjadřuje zdroj, čas a vztah.',
    cefr: 'C1',
    minutes: 8,
    completionXp: 36,
    concept:
      'Na C1 se pravidla skládají podle komunikačního cíle. Kontroluj zdroj informace, míru jistoty, časovou osu, slovesný rámec a to, zda zvolený registr větu zpřesňuje.',
    formula: 'význam → perspektiva → slovesný rámec → pád a koncovka → registr',
    examples: [
      {
        de: 'Die Autorin erklärt, die Ergebnisse müssten neu bewertet werden.',
        cs: 'Autorka uvádí, že výsledky je třeba znovu vyhodnotit.',
      },
      {
        de: 'Die bereits mehrfach überarbeitete Fassung lässt sich leichter lesen.',
        cs: 'Již několikrát přepracovaná verze se čte snáze.',
      },
    ],
    questions: [
      choice(
        'c1mix-1',
        'Která věta neutrálně reprodukuje cizí tvrzení?',
        [
          'Der Sprecher sagt, die Daten seien vollständig.',
          'Der Sprecher sagt, die Daten sind bestimmt vollständig.',
          'Der Sprecher sagt: die Daten wären vollständig gewesen sein.',
          'Der Sprecher sagt, die Daten würden vollständig.',
        ],
        'Der Sprecher sagt, die Daten seien vollständig.',
        'Konjunktiv I „seien“ označuje zdroj výpovědi, aniž by mluvčí její obsah vydával za vlastní tvrzení.',
        'nepřímá řeč',
      ),
      order(
        'c1mix-2',
        'Odešla dříve, protože musela pracovat přes noc.',
        ['arbeiten müssen', 'weil sie', 'Sie ging früher,', 'über Nacht', 'hatte'],
        ['Sie ging früher,', 'weil sie', 'über Nacht', 'hatte', 'arbeiten müssen'],
        'Odešla dříve, protože musela pracovat přes noc.',
        'Ve vedlejší větě s dvojitým infinitivem stojí pomocné „hatte“ před „arbeiten müssen“.',
        'slovesný shluk',
      ),
      fill(
        'c1mix-3',
        'Doplň rozvitý přívlastek.',
        'Die von mehreren Teams entwickelt',
        ' Lösung lässt sich leicht anpassen.',
        ['e'],
        'Ženský nominativ po die.',
        'Partizip II „entwickelt“ uzavírá rozvití a jako přídavné jméno dostává koncovku -e.',
        'participiální přívlastek',
      ),
      choice(
        'c1mix-4',
        'Z dostupných stop je závěr téměř jistý. Která věta je nejpřesnější?',
        [
          'Er muss die Nachricht gelesen haben.',
          'Er soll die Nachricht gelesen haben.',
          'Er will die Nachricht gelesen haben.',
          'Er darf die Nachricht gelesen haben.',
        ],
        'Er muss die Nachricht gelesen haben.',
        'Epistemické „muss + infinitiv perfekt“ vyjadřuje silný závěr mluvčího z nepřímých důkazů.',
        'míra jistoty',
      ),
      order(
        'c1mix-5',
        'Již schválený návrh je nutné do pátku zveřejnit.',
        ['bis Freitag', 'Der bereits genehmigte Vorschlag', 'zu veröffentlichen', 'ist'],
        ['Der bereits genehmigte Vorschlag', 'ist', 'bis Freitag', 'zu veröffentlichen'],
        'Již schválený návrh je nutné do pátku zveřejnit.',
        'Participiální přívlastek zhušťuje předchozí děj a „sein + zu“ vyjadřuje povinnost s termínem.',
        'kombinace registru a pasivní alternativy',
      ),
    ],
  },
];
