import type { CefrLevel, LexemeKind, Note } from '../types.ts';
import { normalizeStoryWord, tokenizeStoryText } from './engine.ts';

import type { StoryBookId, StoryGlossaryEntry, StoryPage, StoryTextToken } from './types.ts';

type ReadingSupportDefinition = {
  key: string;
  german: string;
  czech: string;
  cefr: CefrLevel;
  kind?: LexemeKind;
  forms?: string[];
  article?: 'der' | 'die' | 'das';
  plural?: string;
  learningNote?: string;
};

export type StoryReaderToken = StoryTextToken & {
  highlight: boolean;
};

const LEVEL_RANK: Record<CefrLevel, number> = {
  A1: 1,
  A2: 2,
  B1: 3,
  B2: 4,
  C1: 5,
  C2: 6,
};
const knownFormsCache = new WeakMap<Note[], ReadonlySet<string>>();

// Curated help for above-level story words; the reader hides forms the learner already knows.
const readingSupportLexicon: ReadingSupportDefinition[] = [
  {
    key: 'schlafen',
    german: 'schlafen',
    czech: 'spát',
    cefr: 'A2',
    kind: 'verb',
    forms: ['schläft', 'schlief', 'schliefen', 'geschlafen'],
  },
  {
    key: 'schreien',
    german: 'schreien',
    czech: 'křičet',
    cefr: 'A2',
    kind: 'verb',
    forms: ['schreit', 'schrie', 'schrien', 'geschrien'],
  },
  {
    key: 'springen',
    german: 'springen',
    czech: 'skočit, skákat',
    cefr: 'A2',
    kind: 'verb',
    forms: ['springt', 'sprang', 'sprangen', 'gesprungen'],
  },
  {
    key: 'rufen',
    german: 'rufen',
    czech: 'volat, zavolat',
    cefr: 'A2',
    kind: 'verb',
    forms: ['ruft', 'rief', 'riefen', 'gerufen'],
  },
  {
    key: 'traurig',
    german: 'traurig',
    czech: 'smutný',
    cefr: 'A2',
    kind: 'adjective',
    forms: ['traurige', 'traurigen', 'trauriger', 'trauriges'],
  },
  {
    key: 'hungrig',
    german: 'hungrig',
    czech: 'hladový',
    cefr: 'A2',
    kind: 'adjective',
    forms: ['hungrige', 'hungrigen', 'hungriger', 'hungriges'],
  },
  {
    key: 'leise',
    german: 'leise',
    czech: 'tiše, tichý',
    cefr: 'A2',
    kind: 'adjective',
    forms: ['leisem', 'leisen', 'leiser'],
  },
  {
    key: 'ploetzlich',
    german: 'plötzlich',
    czech: 'náhle',
    cefr: 'A2',
    forms: [],
  },
  {
    key: 'endlich',
    german: 'endlich',
    czech: 'konečně',
    cefr: 'A2',
    forms: [],
  },
  {
    key: 'allein',
    german: 'allein',
    czech: 'sám, samotný',
    cefr: 'A2',
    forms: ['alleine'],
  },
  {
    key: 'hinaus',
    german: 'hinaus',
    czech: 'ven, směrem pryč',
    cefr: 'A2',
    forms: [],
    learningNote: '„Hinaus“ vyjadřuje pohyb ven, obvykle směrem od mluvčího.',
  },
  {
    key: 'hinein',
    german: 'hinein',
    czech: 'dovnitř',
    cefr: 'A2',
    forms: [],
  },
  {
    key: 'hinauf',
    german: 'hinauf',
    czech: 'nahoru',
    cefr: 'A2',
    forms: [],
  },
  {
    key: 'hinunter',
    german: 'hinunter',
    czech: 'dolů',
    cefr: 'A2',
    forms: [],
  },
  {
    key: 'folgen',
    german: 'folgen',
    czech: 'následovat',
    cefr: 'A2',
    kind: 'verb',
    forms: ['folgt', 'folgte', 'folgten', 'gefolgt'],
  },
  {
    key: 'erschrecken',
    german: 'erschrecken',
    czech: 'leknout se',
    cefr: 'A2',
    kind: 'verb',
    forms: ['erschrickt', 'erschrak', 'erschraken', 'erschrocken'],
  },
  {
    key: 'fluestern',
    german: 'flüstern',
    czech: 'šeptat',
    cefr: 'A2',
    kind: 'verb',
    forms: ['flüstert', 'flüsterte', 'flüsterten', 'geflüstert'],
  },
  {
    key: 'entdecken',
    german: 'entdecken',
    czech: 'objevit',
    cefr: 'A2',
    kind: 'verb',
    forms: ['entdeckt', 'entdeckte', 'entdeckten'],
  },
  {
    key: 'verschwinden',
    german: 'verschwinden',
    czech: 'zmizet',
    cefr: 'A2',
    kind: 'verb',
    forms: ['verschwindet', 'verschwand', 'verschwanden', 'verschwunden'],
  },
  {
    key: 'sich-verstecken',
    german: 'sich verstecken',
    czech: 'schovat se',
    cefr: 'A2',
    kind: 'phrase',
    forms: ['versteckt', 'versteckte', 'versteckten'],
  },
  {
    key: 'stimme',
    german: 'Stimme',
    czech: 'hlas',
    cefr: 'A2',
    kind: 'noun',
    article: 'die',
    plural: 'Stimmen',
    forms: ['Stimmen', 'Stimme'],
  },
  {
    key: 'gesicht',
    german: 'Gesicht',
    czech: 'obličej, tvář',
    cefr: 'A2',
    kind: 'noun',
    article: 'das',
    plural: 'Gesichter',
    forms: ['Gesichtes', 'Gesichter', 'Gesichtern'],
  },
  {
    key: 'himmel',
    german: 'Himmel',
    czech: 'nebe',
    cefr: 'A2',
    kind: 'noun',
    article: 'der',
    plural: 'Himmel',
    forms: ['Himmels'],
  },
  {
    key: 'bemerken',
    german: 'bemerken',
    czech: 'všimnout si',
    cefr: 'B1',
    kind: 'verb',
    forms: ['bemerkt', 'bemerkte', 'bemerkten'],
  },
  {
    key: 'erscheinen',
    german: 'erscheinen',
    czech: 'objevit se, jevit se',
    cefr: 'B1',
    kind: 'verb',
    forms: ['erscheint', 'erschien', 'erschienen'],
  },
  {
    key: 'erzaehlen',
    german: 'erzählen',
    czech: 'vyprávět',
    cefr: 'B1',
    kind: 'verb',
    forms: ['erzählt', 'erzählte', 'erzählten'],
  },
  {
    key: 'geschehen',
    german: 'geschehen',
    czech: 'stát se, přihodit se',
    cefr: 'B1',
    kind: 'verb',
    forms: ['geschieht', 'geschah', 'geschahen', 'geschehen'],
  },
  {
    key: 'seufzen',
    german: 'seufzen',
    czech: 'povzdechnout si',
    cefr: 'B1',
    kind: 'verb',
    forms: ['seufzt', 'seufzte', 'seufzten'],
  },
  {
    key: 'schleichen',
    german: 'schleichen',
    czech: 'plížit se',
    cefr: 'B1',
    kind: 'verb',
    forms: ['schleicht', 'schlich', 'schlichen', 'geschlichen'],
  },
  {
    key: 'sich-befinden',
    german: 'sich befinden',
    czech: 'nacházet se',
    cefr: 'B1',
    kind: 'phrase',
    forms: ['befindet', 'befand', 'befanden'],
  },
  {
    key: 'allmaehlich',
    german: 'allmählich',
    czech: 'postupně',
    cefr: 'B1',
    forms: [],
  },
  {
    key: 'dennoch',
    german: 'dennoch',
    czech: 'přesto',
    cefr: 'B1',
    forms: [],
  },
  {
    key: 'kaum',
    german: 'kaum',
    czech: 'sotva',
    cefr: 'B1',
    forms: [],
  },
  {
    key: 'sogleich',
    german: 'sogleich',
    czech: 'ihned, vzápětí',
    cefr: 'B1',
    forms: [],
  },
  {
    key: 'heftig',
    german: 'heftig',
    czech: 'prudce, silně',
    cefr: 'B1',
    kind: 'adjective',
    forms: ['heftige', 'heftigen', 'heftiger', 'heftiges'],
  },
  {
    key: 'heimlich',
    german: 'heimlich',
    czech: 'tajně, skrytě',
    cefr: 'B1',
    kind: 'adjective',
    forms: ['heimliche', 'heimlichen', 'heimlicher', 'heimliches'],
  },
  {
    key: 'stumm',
    german: 'stumm',
    czech: 'němý, beze slova',
    cefr: 'B1',
    kind: 'adjective',
    forms: ['stumme', 'stummen', 'stummer', 'stummes'],
  },
  {
    key: 'eilig',
    german: 'eilig',
    czech: 'spěšně, naléhavý',
    cefr: 'B1',
    kind: 'adjective',
    forms: ['eilige', 'eiligen', 'eiliger', 'eiliges'],
  },
  {
    key: 'erstaunt',
    german: 'erstaunt',
    czech: 'překvapený',
    cefr: 'B1',
    kind: 'adjective',
    forms: ['erstaunte', 'erstaunten', 'erstaunter', 'erstauntes'],
  },
  {
    key: 'ahnung',
    german: 'Ahnung',
    czech: 'tušení',
    cefr: 'B1',
    kind: 'noun',
    article: 'die',
    plural: 'Ahnungen',
    forms: ['Ahnungen'],
  },
  {
    key: 'zweifel',
    german: 'Zweifel',
    czech: 'pochybnost',
    cefr: 'B1',
    kind: 'noun',
    article: 'der',
    plural: 'Zweifel',
    forms: ['Zweifels', 'Zweifeln'],
  },
  {
    key: 'absicht',
    german: 'Absicht',
    czech: 'úmysl',
    cefr: 'B1',
    kind: 'noun',
    article: 'die',
    plural: 'Absichten',
    forms: ['Absichten'],
  },
  {
    key: 'entschluss',
    german: 'Entschluss',
    czech: 'rozhodnutí',
    cefr: 'B1',
    kind: 'noun',
    article: 'der',
    plural: 'Entschlüsse',
    forms: ['Entschluß', 'Entschlusses', 'Entschlüsse'],
  },
  {
    key: 'umstand',
    german: 'Umstand',
    czech: 'okolnost',
    cefr: 'B1',
    kind: 'noun',
    article: 'der',
    plural: 'Umstände',
    forms: ['Umstandes', 'Umstände', 'Umständen'],
  },
  {
    key: 'verlangen',
    german: 'Verlangen',
    czech: 'touha, žádost',
    cefr: 'B1',
    kind: 'noun',
    article: 'das',
    plural: '—',
    forms: ['Verlangens'],
  },
  {
    key: 'gegend',
    german: 'Gegend',
    czech: 'kraj, oblast',
    cefr: 'B1',
    kind: 'noun',
    article: 'die',
    plural: 'Gegenden',
    forms: ['Gegenden'],
  },
  {
    key: 'anblick',
    german: 'Anblick',
    czech: 'pohled, podívaná',
    cefr: 'B1',
    kind: 'noun',
    article: 'der',
    plural: 'Anblicke',
    forms: ['Anblicks', 'Anblicke'],
  },
  {
    key: 'augenblick',
    german: 'Augenblick',
    czech: 'okamžik',
    cefr: 'B1',
    kind: 'noun',
    article: 'der',
    plural: 'Augenblicke',
    forms: ['Augenblicks', 'Augenblicke', 'Augenblicken'],
  },
  {
    key: 'blick',
    german: 'Blick',
    czech: 'pohled',
    cefr: 'B1',
    kind: 'noun',
    article: 'der',
    plural: 'Blicke',
    forms: ['Blickes', 'Blicke', 'Blicken'],
  },
  {
    key: 'erwidern',
    german: 'erwidern',
    czech: 'odpovědět, odvětit',
    cefr: 'B2',
    kind: 'verb',
    forms: ['erwidert', 'erwiderte', 'erwiderten'],
  },
  {
    key: 'scheinen',
    german: 'scheinen',
    czech: 'zdát se, svítit',
    cefr: 'B2',
    kind: 'verb',
    forms: ['scheint', 'schien', 'schienen', 'geschienen'],
    learningNote: '„Scheinen“ může podle kontextu znamenat „zdát se“ nebo doslova „svítit“.',
  },
  {
    key: 'vermoegen',
    german: 'vermögen',
    czech: 'dokázat, být schopen',
    cefr: 'B2',
    kind: 'verb',
    forms: ['vermag', 'vermochte', 'vermochten'],
  },
  {
    key: 'vergebens',
    german: 'vergebens',
    czech: 'marně',
    cefr: 'B2',
    forms: [],
  },
  {
    key: 'indessen',
    german: 'indessen',
    czech: 'mezitím; avšak',
    cefr: 'B2',
    forms: ['indes'],
  },
  {
    key: 'freilich',
    german: 'freilich',
    czech: 'ovšem, zajisté',
    cefr: 'B2',
    forms: [],
  },
  {
    key: 'zuweilen',
    german: 'zuweilen',
    czech: 'občas',
    cefr: 'B2',
    forms: [],
  },
  {
    key: 'einstweilen',
    german: 'einstweilen',
    czech: 'prozatím',
    cefr: 'B2',
    forms: [],
  },
  {
    key: 'gleichwohl',
    german: 'gleichwohl',
    czech: 'přesto',
    cefr: 'B2',
    forms: [],
  },
  {
    key: 'unversehens',
    german: 'unversehens',
    czech: 'nečekaně',
    cefr: 'B2',
    forms: [],
  },
  {
    key: 'unwillkuerlich',
    german: 'unwillkürlich',
    czech: 'mimovolně',
    cefr: 'B2',
    forms: [],
  },
  {
    key: 'betraechtlich',
    german: 'beträchtlich',
    czech: 'značný, značně',
    cefr: 'B2',
    kind: 'adjective',
    forms: ['beträchtliche', 'beträchtlichen', 'beträchtlicher', 'beträchtliches'],
  },
  {
    key: 'eigentuemlich',
    german: 'eigentümlich',
    czech: 'zvláštní, svérázný',
    cefr: 'B2',
    kind: 'adjective',
    forms: ['eigentümliche', 'eigentümlichen', 'eigentümlicher', 'eigentümliches'],
  },
  {
    key: 'beharrlich',
    german: 'beharrlich',
    czech: 'vytrvale',
    cefr: 'B2',
    kind: 'adjective',
    forms: ['beharrliche', 'beharrlichen', 'beharrlicher', 'beharrliches'],
  },
  {
    key: 'klaeglich',
    german: 'kläglich',
    czech: 'žalostně',
    cefr: 'B2',
    kind: 'adjective',
    forms: ['klägliche', 'kläglichen', 'kläglicher', 'klägliches'],
  },
  {
    key: 'feierlich',
    german: 'feierlich',
    czech: 'slavnostně, vážně',
    cefr: 'B2',
    kind: 'adjective',
    forms: ['feierliche', 'feierlichen', 'feierlicher', 'feierliches'],
  },
  {
    key: 'verdriesslich',
    german: 'verdrießlich',
    czech: 'mrzutý, nepříjemný',
    cefr: 'B2',
    kind: 'adjective',
    forms: ['verdrießliche', 'verdrießlichen', 'verdrießlicher', 'verdrießliches'],
  },
  {
    key: 'gestalt',
    german: 'Gestalt',
    czech: 'postava, podoba',
    cefr: 'B2',
    kind: 'noun',
    article: 'die',
    plural: 'Gestalten',
    forms: ['Gestalten'],
  },
  {
    key: 'gemuet',
    german: 'Gemüt',
    czech: 'nitro, mysl',
    cefr: 'B2',
    kind: 'noun',
    article: 'das',
    plural: 'Gemüter',
    forms: ['Gemütes', 'Gemütern'],
  },
  {
    key: 'erscheinung',
    german: 'Erscheinung',
    czech: 'zjev, podoba',
    cefr: 'B2',
    kind: 'noun',
    article: 'die',
    plural: 'Erscheinungen',
    forms: ['Erscheinungen'],
  },
  {
    key: 'dergleichen',
    german: 'dergleichen',
    czech: 'něco takového, podobného',
    cefr: 'B2',
    forms: [],
  },
  {
    key: 'unverzueglich',
    german: 'unverzüglich',
    czech: 'neprodleně',
    cefr: 'B2',
    forms: [],
  },
  {
    key: 'keineswegs',
    german: 'keineswegs',
    czech: 'v žádném případě',
    cefr: 'B2',
    forms: [],
  },
  {
    key: 'demnach',
    german: 'demnach',
    czech: 'podle toho, tudíž',
    cefr: 'B2',
    forms: [],
  },
  {
    key: 'antlitz',
    german: 'Antlitz',
    czech: 'tvář, obličej (knižně)',
    cefr: 'C1',
    kind: 'noun',
    article: 'das',
    plural: 'Antlitze',
    forms: ['Antlitzes', 'Antlitze'],
  },
  {
    key: 'mitnichten',
    german: 'mitnichten',
    czech: 'ani zdaleka, vůbec ne',
    cefr: 'C1',
    forms: [],
  },
  {
    key: 'mithin',
    german: 'mithin',
    czech: 'tedy, tudíž',
    cefr: 'C1',
    forms: [],
  },
  {
    key: 'vermittelst',
    german: 'vermittelst',
    czech: 'prostřednictvím',
    cefr: 'C1',
    forms: [],
  },
  {
    key: 'hinlaenglich',
    german: 'hinlänglich',
    czech: 'dostatečně',
    cefr: 'C1',
    forms: [],
  },
  {
    key: 'abermals',
    german: 'abermals',
    czech: 'znovu, opět',
    cefr: 'C1',
    forms: [],
  },
  {
    key: 'sodann',
    german: 'sodann',
    czech: 'poté',
    cefr: 'C1',
    forms: [],
  },
  {
    key: 'schier',
    german: 'schier',
    czech: 'téměř; čirý',
    cefr: 'C1',
    forms: [],
    learningNote: 'Knižní „schier“ znamená podle vazby nejčastěji „téměř“, někdy také „čirý“.',
  },
  {
    key: 'jaeh',
    german: 'jäh',
    czech: 'náhlý, prudký',
    cefr: 'C1',
    kind: 'adjective',
    forms: ['jähes', 'jähe', 'jähen', 'jäher'],
  },
  {
    key: 'ward',
    german: 'ward',
    czech: 'stal se, byl (knižně)',
    cefr: 'C1',
    kind: 'verb',
    forms: ['ward'],
    learningNote:
      '„Ward“ je starší vyprávěcí tvar slovesa „werden“; v moderní němčině stojí zpravidla „wurde“.',
  },
  {
    key: 'derweil',
    german: 'derweil',
    czech: 'zatímco, mezitím',
    cefr: 'C1',
    forms: ['derweilen'],
  },
  {
    key: 'gleichsam',
    german: 'gleichsam',
    czech: 'jakoby, takřka',
    cefr: 'C1',
    forms: [],
  },
  {
    key: 'ungemein',
    german: 'ungemein',
    czech: 'nesmírně, neobyčejně',
    cefr: 'C1',
    forms: [],
  },
  {
    key: 'zugegen',
    german: 'zugegen',
    czech: 'přítomen',
    cefr: 'C1',
    forms: [],
  },
  {
    key: 'obgleich',
    german: 'obgleich',
    czech: 'ačkoli',
    cefr: 'C1',
    forms: [],
  },
  {
    key: 'wiewohl',
    german: 'wiewohl',
    czech: 'ačkoli',
    cefr: 'C1',
    forms: [],
  },
  {
    key: 'ehedem',
    german: 'ehedem',
    czech: 'kdysi, dříve',
    cefr: 'C1',
    forms: [],
  },
  {
    key: 'fortan',
    german: 'fortan',
    czech: 'odteď, nadále',
    cefr: 'C1',
    forms: [],
  },
  {
    key: 'alsbald',
    german: 'alsbald',
    czech: 'vzápětí',
    cefr: 'C1',
    forms: [],
  },
  {
    key: 'bisweilen',
    german: 'bisweilen',
    czech: 'občas',
    cefr: 'C1',
    forms: [],
  },
  {
    key: 'geheimnis',
    german: 'Geheimnis',
    czech: 'tajemství',
    cefr: 'B1',
    kind: 'noun',
    article: 'das',
    plural: 'Geheimnisse',
    forms: ['Geheimnisses', 'Geheimnisse', 'Geheimnissen'],
  },
  {
    key: 'wahrheit',
    german: 'Wahrheit',
    czech: 'pravda',
    cefr: 'B1',
    kind: 'noun',
    article: 'die',
    plural: 'Wahrheiten',
    forms: ['Wahrheiten'],
  },
  {
    key: 'verbrechen',
    german: 'Verbrechen',
    czech: 'zločin',
    cefr: 'B1',
    kind: 'noun',
    article: 'das',
    plural: 'Verbrechen',
    forms: ['Verbrechens'],
  },
  {
    key: 'schweigen',
    german: 'schweigen',
    czech: 'mlčet',
    cefr: 'B1',
    kind: 'verb',
    forms: ['schweigt', 'schwieg', 'schwiegen', 'geschwiegen'],
  },
  {
    key: 'neugierig',
    german: 'neugierig',
    czech: 'zvědavý',
    cefr: 'B1',
    kind: 'adjective',
    forms: ['neugierige', 'neugierigen', 'neugieriger', 'neugieriges', 'neugierigem'],
  },
  {
    key: 'belohnung',
    german: 'Belohnung',
    czech: 'odměna',
    cefr: 'B1',
    kind: 'noun',
    article: 'die',
    plural: 'Belohnungen',
    forms: ['Belohnungen'],
  },
  {
    key: 'gestaendnis',
    german: 'Geständnis',
    czech: 'přiznání',
    cefr: 'B2',
    kind: 'noun',
    article: 'das',
    plural: 'Geständnisse',
    forms: ['Geständnisses', 'Geständnisse'],
  },
  {
    key: 'auseinandersetzung',
    german: 'Auseinandersetzung',
    czech: 'střet, konflikt',
    cefr: 'C1',
    kind: 'noun',
    article: 'die',
    plural: 'Auseinandersetzungen',
    forms: ['Auseinandersetzungen'],
  },
  {
    key: 'wettergegerbt',
    german: 'wettergegerbt',
    czech: 'ošlehaný počasím',
    cefr: 'C1',
    kind: 'adjective',
    forms: ['wettergegerbte', 'wettergegerbter', 'wettergegerbten'],
  },
  {
    key: 'ueberwaeltigen',
    german: 'überwältigen',
    czech: 'přemoci',
    cefr: 'C1',
    kind: 'verb',
    forms: ['überwältigt', 'überwältigte', 'überwältigten'],
  },
  {
    key: 'beruechtigt',
    german: 'berüchtigt',
    czech: 'neblaze proslulý',
    cefr: 'C1',
    kind: 'adjective',
    forms: ['berüchtigte', 'berüchtigten', 'berüchtigter', 'berüchtigtes'],
  },
  {
    key: 'augenblicklich',
    german: 'augenblicklich',
    czech: 'okamžitě; současný',
    cefr: 'C1',
    kind: 'adjective',
    forms: ['augenblickliche', 'augenblicklichen', 'augenblicklicher', 'augenblickliches'],
  },
  {
    key: 'unbegreiflich',
    german: 'unbegreiflich',
    czech: 'nepochopitelný',
    cefr: 'C1',
    kind: 'adjective',
    forms: ['unbegreifliche', 'unbegreiflichen', 'unbegreiflicher', 'unbegreifliches'],
  },
  {
    key: 'gewissensbiss',
    german: 'Gewissensbiss',
    czech: 'výčitka svědomí',
    cefr: 'C1',
    kind: 'noun',
    article: 'der',
    plural: 'Gewissensbisse',
    forms: ['Gewissensbissen', 'Gewissensbisse'],
  },
  {
    key: 'schwindelanfall',
    german: 'Schwindelanfall',
    czech: 'záchvat závrati',
    cefr: 'C1',
    kind: 'noun',
    article: 'der',
    plural: 'Schwindelanfälle',
    forms: ['Schwindelanfalls', 'Schwindelanfälle'],
  },
  {
    key: 'unaufhoerlich',
    german: 'unaufhörlich',
    czech: 'neustále',
    cefr: 'C1',
    kind: 'adjective',
    forms: ['unaufhörliche', 'unaufhörlichen', 'unaufhörlicher', 'unaufhörliches'],
  },
  {
    key: 'gleichgewicht',
    german: 'Gleichgewicht',
    czech: 'rovnováha',
    cefr: 'C1',
    kind: 'noun',
    article: 'das',
    plural: 'Gleichgewichte',
    forms: ['Gleichgewichts', 'Gleichgewichte'],
  },
  {
    key: 'ruecksichtnahme',
    german: 'Rücksichtnahme',
    czech: 'ohleduplnost',
    cefr: 'C1',
    kind: 'noun',
    article: 'die',
    plural: '—',
    forms: [],
  },
  {
    key: 'stillschweigend',
    german: 'stillschweigend',
    czech: 'mlčky, bez výslovné dohody',
    cefr: 'C1',
    forms: [],
  },
  {
    key: 'unentbehrlich',
    german: 'unentbehrlich',
    czech: 'nepostradatelný',
    cefr: 'C1',
    kind: 'adjective',
    forms: ['unentbehrliche', 'unentbehrlichen', 'unentbehrlicher', 'unentbehrliches'],
  },
  {
    key: 'auswanderung',
    german: 'Auswanderung',
    czech: 'vystěhování do ciziny',
    cefr: 'C1',
    kind: 'noun',
    article: 'die',
    plural: 'Auswanderungen',
    forms: ['Auswanderungen'],
  },
  {
    key: 'nachtraeglich',
    german: 'nachträglich',
    czech: 'dodatečně',
    cefr: 'C1',
    kind: 'adjective',
    forms: ['nachträgliche', 'nachträglichen', 'nachträglicher', 'nachträgliches'],
  },
  {
    key: 'merkwuerdigkeit',
    german: 'Merkwürdigkeit',
    czech: 'podivnost',
    cefr: 'C1',
    kind: 'noun',
    article: 'die',
    plural: 'Merkwürdigkeiten',
    forms: ['Merkwürdigkeiten'],
  },
  {
    key: 'missverstaendnis',
    german: 'Missverständnis',
    czech: 'nedorozumění',
    cefr: 'C1',
    kind: 'noun',
    article: 'das',
    plural: 'Missverständnisse',
    forms: ['Mißverständnis', 'Missverständnisses', 'Missverständnisse'],
  },
  {
    key: 'gravitaetisch',
    german: 'gravitätisch',
    czech: 'okázale důstojný',
    cefr: 'C1',
    kind: 'adjective',
    forms: ['gravitätische', 'gravitätischen', 'gravitätischer', 'gravitätisches'],
  },
  {
    key: 'unverschaemt',
    german: 'unverschämt',
    czech: 'nestydatý, drzý',
    cefr: 'C1',
    kind: 'adjective',
    forms: ['unverschämte', 'unverschämten', 'unverschämter', 'unverschämtes'],
  },
  {
    key: 'abscheulich',
    german: 'abscheulich',
    czech: 'odporný',
    cefr: 'C1',
    kind: 'adjective',
    forms: ['abscheuliche', 'abscheulichen', 'abscheulicher', 'abscheuliches'],
  },
  {
    key: 'unvermutet',
    german: 'unvermutet',
    czech: 'nečekaně',
    cefr: 'C1',
    kind: 'adjective',
    forms: ['unvermutete', 'unvermuteten', 'unvermuteter', 'unvermutetes'],
  },
  {
    key: 'ohnfehlbar',
    german: 'ohnfehlbar',
    czech: 'bezpochyby; neomylný (zastarale)',
    cefr: 'C1',
    forms: [],
  },
  {
    key: 'richteramt',
    german: 'Richteramt',
    czech: 'soudcovský úřad',
    cefr: 'C1',
    kind: 'noun',
    article: 'das',
    plural: 'Richterämter',
    forms: ['Richteramts', 'Richterämter'],
  },
  {
    key: 'begebenheit',
    german: 'Begebenheit',
    czech: 'událost, příhoda',
    cefr: 'C1',
    kind: 'noun',
    article: 'die',
    plural: 'Begebenheiten',
    forms: ['Begebenheiten'],
  },
  {
    key: 'geschicklichkeit',
    german: 'Geschicklichkeit',
    czech: 'obratnost',
    cefr: 'C1',
    kind: 'noun',
    article: 'die',
    plural: '—',
    forms: [],
  },
  {
    key: 'annehmlichkeit',
    german: 'Annehmlichkeit',
    czech: 'příjemnost, pohodlí',
    cefr: 'C1',
    kind: 'noun',
    article: 'die',
    plural: 'Annehmlichkeiten',
    forms: ['Annehmlichkeiten'],
  },
  {
    key: 'mannigfaltig',
    german: 'mannigfaltig',
    czech: 'rozmanitý',
    cefr: 'C1',
    kind: 'adjective',
    forms: ['mannigfaltige', 'mannigfaltigen', 'mannigfaltiger', 'mannigfaltiges'],
  },
  {
    key: 'wechselseitig',
    german: 'wechselseitig',
    czech: 'vzájemný',
    cefr: 'C1',
    kind: 'adjective',
    forms: ['wechselseitige', 'wechselseitigen', 'wechselseitiger', 'wechselseitiges'],
  },
  {
    key: 'unueberwindlich',
    german: 'unüberwindlich',
    czech: 'nepřekonatelný',
    cefr: 'C1',
    kind: 'adjective',
    forms: ['unüberwindliche', 'unüberwindlichen', 'unüberwindlicher', 'unüberwindliches'],
  },
  {
    key: 'liebenswuerdig',
    german: 'liebenswürdig',
    czech: 'vlídný, půvabný',
    cefr: 'C1',
    kind: 'adjective',
    forms: ['liebenswürdige', 'liebenswürdigen', 'liebenswürdiger', 'liebenswürdiges'],
  },
  {
    key: 'gewissermassen',
    german: 'gewissermaßen',
    czech: 'do jisté míry, takříkajíc',
    cefr: 'C1',
    forms: ['gewissermassen'],
  },
  {
    key: 'leidenschaftlich',
    german: 'leidenschaftlich',
    czech: 'vášnivý',
    cefr: 'C1',
    kind: 'adjective',
    forms: ['leidenschaftliche', 'leidenschaftlichen', 'leidenschaftlicher', 'leidenschaftliches'],
  },
  {
    key: 'scharfzuengig',
    german: 'scharfzüngig',
    czech: 'jízlivý, s ostrým jazykem',
    cefr: 'C1',
    kind: 'adjective',
    forms: ['scharfzüngige', 'scharfzüngigen', 'scharfzüngiger', 'scharfzüngiges'],
  },
  {
    key: 'oeffentlichkeit',
    german: 'Öffentlichkeit',
    czech: 'veřejnost',
    cefr: 'C1',
    kind: 'noun',
    article: 'die',
    plural: 'Öffentlichkeiten',
    forms: [],
  },
  {
    key: 'bedeutungslos',
    german: 'bedeutungslos',
    czech: 'bezvýznamný',
    cefr: 'C1',
    kind: 'adjective',
    forms: ['bedeutungslose', 'bedeutungslosen', 'bedeutungsloser', 'bedeutungsloses'],
  },
  {
    key: 'unwirklich',
    german: 'unwirklich',
    czech: 'neskutečný',
    cefr: 'C1',
    kind: 'adjective',
    forms: ['unwirkliche', 'unwirklichen', 'unwirklicher', 'unwirkliches'],
  },
  {
    key: 'aesthetisch',
    german: 'ästhetisch',
    czech: 'estetický',
    cefr: 'C1',
    kind: 'adjective',
    forms: ['ästhetische', 'ästhetischen', 'ästhetischer', 'ästhetisches'],
  },
  {
    key: 'bewunderung',
    german: 'Bewunderung',
    czech: 'obdiv',
    cefr: 'C1',
    kind: 'noun',
    article: 'die',
    plural: '—',
    forms: [],
  },
  {
    key: 'verkoerpern',
    german: 'verkörpern',
    czech: 'ztělesňovat',
    cefr: 'C1',
    kind: 'verb',
    forms: ['verkörpert', 'verkörperte', 'verkörperten'],
  },
  {
    key: 'aufrichtig',
    german: 'aufrichtig',
    czech: 'upřímný',
    cefr: 'C1',
    kind: 'adjective',
    forms: ['aufrichtige', 'aufrichtigen', 'aufrichtiger', 'aufrichtiges'],
  },
  {
    key: 'verborgen',
    german: 'verborgen',
    czech: 'skrytý',
    cefr: 'C1',
    kind: 'adjective',
    forms: ['verborgene', 'verborgenen', 'verborgener', 'verborgenes'],
  },
  {
    key: 'schoenheit',
    german: 'Schönheit',
    czech: 'krása',
    cefr: 'C1',
    kind: 'noun',
    article: 'die',
    plural: 'Schönheiten',
    forms: ['Schönheiten'],
  },
  {
    key: 'erfuellung',
    german: 'Erfüllung',
    czech: 'naplnění, splnění',
    cefr: 'C1',
    kind: 'noun',
    article: 'die',
    plural: 'Erfüllungen',
    forms: ['Erfüllungen'],
  },
];

function normalize(value: string): string {
  return value
    .normalize('NFKC')
    .toLocaleLowerCase('de-DE')
    .replace(/^[^\p{L}]+|[^\p{L}]+$/gu, '');
}

function defaultDistractors(kind: LexemeKind | undefined): string[] {
  if (kind === 'verb' || kind === 'phrase') return ['sagen', 'machen'];
  if (kind === 'adjective') return ['ruhig', 'klein'];
  if (kind === 'noun') return ['Weg', 'Haus'];
  return ['heute', 'dort'];
}

function isAboveReaderLevel(entryLevel: CefrLevel, bookLevel: CefrLevel): boolean {
  return LEVEL_RANK[entryLevel] >= LEVEL_RANK[bookLevel];
}

export function enrichStoryGlossary(input: {
  bookId: StoryBookId;
  level: CefrLevel;
  pages: StoryPage[];
  glossary: StoryGlossaryEntry[];
}): StoryGlossaryEntry[] {
  const textWords = new Set(
    input.pages
      .flatMap((page) => page.paragraphs)
      .flatMap((paragraph) => paragraph.match(/\p{L}[\p{L}\p{M}’'-]*/gu) ?? [])
      .map(normalize),
  );
  const represented = new Set(
    input.glossary.flatMap((entry) => [entry.german, ...entry.forms]).map(normalize),
  );
  const additions: StoryGlossaryEntry[] = [];

  for (const definition of readingSupportLexicon) {
    if (!isAboveReaderLevel(definition.cefr, input.level)) continue;
    const forms = [definition.german, ...(definition.forms ?? [])];
    const normalizedForms = forms.filter((form) => !/\s/u.test(form.trim())).map(normalize);
    if (
      normalizedForms.length === 0 ||
      normalizedForms.some((form) => represented.has(form)) ||
      !normalizedForms.some((form) => textWords.has(form))
    ) {
      continue;
    }
    for (const form of normalizedForms) represented.add(form);
    additions.push({
      id: `${input.bookId}-reader-${definition.key}`,
      german: definition.german,
      czech: definition.czech,
      cefr: definition.cefr,
      kind: definition.kind ?? 'other',
      forms: definition.forms ?? [],
      distractors: defaultDistractors(definition.kind),
      article: definition.article,
      plural: definition.plural,
      learningNote:
        definition.learningNote ??
        `V tomto příběhu výraz „${definition.german}“ znamená „${definition.czech}“.`,
    });
  }

  return [...input.glossary, ...additions];
}

export function storySupportTokens(
  page: Pick<StoryPage, 'paragraphs'>,
  glossary: StoryGlossaryEntry[],
  knownForms: ReadonlySet<string>,
): StoryReaderToken[][] {
  const knownEntryIds = new Set(
    glossary
      .filter((entry) =>
        [entry.german, ...entry.forms].some((form) => knownForms.has(normalizeStoryWord(form))),
      )
      .map((entry) => entry.id),
  );
  const highlightedEntries = new Set<string>();
  return page.paragraphs.map((paragraph) =>
    tokenizeStoryText(paragraph, glossary).map((token) => {
      if (!token.glossary || knownEntryIds.has(token.glossary.id)) {
        return { ...token, highlight: false };
      }
      const highlight = !highlightedEntries.has(token.glossary.id);
      highlightedEntries.add(token.glossary.id);
      return { ...token, highlight };
    }),
  );
}

export function storyKnownFormsFromNotes(notes: Note[]): ReadonlySet<string> {
  const cached = knownFormsCache.get(notes);
  if (cached) return cached;
  const values = notes.flatMap((note) => [
    note.german,
    ...note.acceptedGerman,
    note.plural ?? '',
    note.verbForms?.thirdPerson ?? '',
    note.verbForms?.preterite ?? '',
    note.verbForms?.participle ?? '',
  ]);
  const forms = new Set(
    values
      .flatMap((value) => value.match(/\p{L}[\p{L}\p{M}’'-]*/gu) ?? [])
      .map(normalizeStoryWord)
      .filter(Boolean),
  );
  knownFormsCache.set(notes, forms);
  return forms;
}
